### ISSUE TITLE
[Drawer] Add theme configuration

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#1018]
**What problem does this feature solve?** There's no way to configure what a `<Drawer>` looks like when generating a theme from the CLI. I feel like there should be (also, probably for `<Breadcrumb>`).

**What does the proposed API look like?** Just expose the theme configuration!

**Describe alternatives you've considered** Maybe there isn't one there because Drawer just composes other components? To me, I feel like there should still be something there to configure... defaultProps at the very least.

**Additional context** N/A

**Comment by with-heart** [comment]
`Drawer` is `Modal` in disguise 🕵️

This will probably be a constant source of confusion though, you're right. We need to think about how to handle the various components that don't have their own styles and are compositions of other components.

**Comment by segunadebayo** [comment]
I don't see a need to create a configuration for the Drawer component since it's just a modal that slides in.

The only thing worth configuring is the transition duration and timing function. This will only be done through props for now, not from the theme.

I understand your point though, we'll think about ways to compose component themes in the future. For now, let's roll out V1 with this approach.

Thanks

**Comment by cereallarceny** [comment]
Sounds good, I'll close this.
