### ISSUE TITLE
Request to add [Component] resource-list like Shopify-polaris

### ISSUE THREAD

**Issue by vitalijalbu** [chakra-ui/chakra-ui#1025]
**What problem does this feature solve?** Just to make Chakra-Ui the most powerful tool for building admin panels and much  more...

**What does the proposed API look like?** Would be better to have some resource-list like shopify-polaris (https://polaris.shopify.com/components/lists-and-tables/resource-list), this is the best solution instead using tables.

![Schermata 2020-06-29 alle 15 34 09](https://user-images.githubusercontent.com/40239902/86012203-fb3b3200-ba1d-11ea-8698-c6ce7564c552.png)
.

**Describe alternatives you've considered** https://polaris.shopify.com/components/lists-and-tables/resource-list

**Comment by with-heart** [comment]
I will say that this feels like something that's far more complex than what has existed in Chakra up to this point. Typically we've focused on providing the building blocks that you can then use to build complex things like this resource list component.

I'll leave it though because that's quite an impressive component and documentation! You can view each individual state of the component in the docs? That's wild!

It might be a good candidate for a guide or possibly a new examples section of the site where we could show off complex creations.

**Comment by segunadebayo** [comment]
Hi @vitalijalbu,

I don't think we're going to work on this as it's not in our near or future roadmap.

It'll be great if you can make it and open-source the code snippet so others can see and learn from. Once you do, we'll also add it to our component recipes.

Thanks for bringing this up.
