### ISSUE TITLE
[CSSReset] HTML headings don't work as expected

### ISSUE THREAD

**Issue by RikuMantysalo** [chakra-ui/chakra-ui#107]
I noticed an issue when using [react-markdown](https://github.com/rexxars/react-markdown) which uses html tags for rendering markdown.

Apparently, the CSSReset sets `font-size` and `font-weight` for h1-h6 to `inherit`

https://github.com/chakra-ui/chakra-ui/blob/5f15805914ea3c4fc0338228a8a95f657f408bbe/packages/chakra-ui/src/CSSReset/preflight.js#L489-L496

This causes HTML headings to not have the look that one would expect as seen in this sandbox.

https://codesandbox.io/s/rough-violet-84oif

However, if I remove the styling via devtools, they look fine.

<img width="832" alt="Screenshot 2019-09-20 at 17 42 45" src="https://user-images.githubusercontent.com/33690850/65336009-332f6200-dbce-11e9-85a5-6ea7caa98b4e.png">

It also seems that the CSSReset is doing other things as well that affect the look and feel of the site, which would probably fit better inside the default theme, while leaving the actual resets like body margins and such inside the reset.

For example:

https://github.com/chakra-ui/chakra-ui/blob/5f15805914ea3c4fc0338228a8a95f657f408bbe/packages/chakra-ui/src/CSSReset/preflight.js#L440-L443

https://github.com/chakra-ui/chakra-ui/blob/5f15805914ea3c4fc0338228a8a95f657f408bbe/packages/chakra-ui/src/CSSReset/preflight.js#L403-L404

Another thing that I noticed is that without the CSSReset, some styling breaks, such as this `<Textarea>` extending over a `<Flex>`. This might be related to something else though but I managed to fix it with `<Textarea width="initial">`

<img width="618" alt="Screenshot 2019-09-20 at 18 02 42" src="https://user-images.githubusercontent.com/33690850/65337509-f6189f00-dbd0-11e9-9e2b-a922e712dd70.png">

**Comment by segunadebayo** [comment]
Hi @RikuMantysalo,

For now, we recommend that you use `CSSReset` in your apps. We'll find a way to get it to work without the `CSSReset` down the line.

I hope you can find a way to walk around this issue for now, perhaps use CSS to remove the styles within the markdown editor.

Thanks.

**Comment by RikuMantysalo** [comment]
Hey, thanks for the response.

I managed to get it working by forking the CSSReset and removing the styling mentioned in the issue. Didn't seem to outright break anything :smile:

I appreciate your efforts on this library and have been really enjoying using it. Really looking forward to the future development!

**Comment by TiborUdvari** [comment]
Hi, I would just like to add my solution to this would be just passing down the styles with the sx prop. I have some dangerously set HTML that I have rendered so I can pass the styles down like so
```
<Box
                dangerouslySetInnerHTML={{
                __html: post.content
            }}
                sx={{
                "& h1": {
                    fontWeight: "bold"
                }
            }}></Box>
```

**Comment by theboi** [comment]
Hey, I know this is old but seeing that the team hasn't found time to update it I just wanted to share how I worked around it, just to help anyone who has this issue in the future since I took quite some time to fix this... I followed @mantysalo's method kinda by setting `resetCSS={false}` and importing my own global styles copy-pasting the CSS reset from https://github.com/chakra-ui/chakra-ui/blob/266936380ded4e7892c55df3727f5344cf9d2ec4/packages/css-reset/src/css-reset.tsx)

Then I realised that it wasn't only the font size that broke (like margins were also off and I just had to fix that :P). So I tried using (in .scss), basically to prevent applying the CSS reset to elements inside of a .md class:
```scss
:not(.md) > {
  // copy-paste CSS reset
}
```

but realised that things broke even further apparently because adding ".md" increased the specificity of the selector very slightly and broke stuff. My workaround was to wrap the markdown render in custom <md></md> tags (and match `:not(md)` instead). Might just be me but this took me some time to debug because I did not expect the selector specificity to be such a big issue...

Hope it helps anyone in the future!

**Comment by subodhk01** [comment]
Has anyone found the solution for this issue?

**Comment by VR314** [comment]
@subodhk01, this is the solution I found: [chakra-ui-markdown-renderer](https://www.npmjs.com/package/chakra-ui-markdown-renderer).

**Comment by subodhk01** [comment]
@VR314 Thanks, that looks nice. Also, is there any way to disable the chakra css for normal h1, h2... tags

**Comment by VR314** [comment]
@subodhk01 I'm having that same problem, my `h1`s especially are way bigger than I want them to be, even changing the Chakra styling doesn't work, so I'll look around to see if I can find a workaround and I'll let you know if I find anything.

**Comment by PreciousNiphemi** [comment]
> @subodhk01, this is the solution I found: [chakra-ui-markdown-renderer](https://www.npmjs.com/package/chakra-ui-markdown-renderer).

I tried using this. But it doesn't seem to work. I don't know if I am the one doing it wrong or something

**Comment by Nithur-M** [comment]
I am facing this issue right now. Any elegant way to handle this? thanks.

**Comment by SergioArrighi** [comment]
Hello, I am facing this issue too, did anyone find an elegant solution?
Thanks and best regards

**Comment by lee-chance** [comment]
```typescript
<Box
  sx={{
    'h1, h2, h3, h4, h5, h6': {
      'fontSize': 'revert',
      'fontWeight': 'revert'
    },
  }}
>
{/* your component */}
</Box>
```
