### ISSUE TITLE
ThemeProvider in Jest tests

### ISSUE THREAD

**Issue by lallmon** [chakra-ui/chakra-ui#1085]
Apologies if this isn't the right place, but I couldn't find a support channel otherwise.

What is the official pattern of Chakra for including the `<ThemeProvider />` in Jest tests? It seems repetitive and an anti-pattern to wrap every component in a test with the provider, but tests fail because it doesn't have that context.

**Comment by segunadebayo** [comment]
Hi @lallmon,

No worries, you can join our discord server here for further help: https://discord.gg/mm3EXRC

For Jest, here are some helpful links
- https://testing-library.com/docs/react-testing-library/setup#custom-render
- https://github.com/chakra-ui/chakra-ui/blob/master/packages/test-utils/src/test-utils.tsx

The idea is to create a custom `render` function that has the `ThemeProvider` in it and use that instead of React testing library's `render` function. This should help you reduce the repetition.

If you're still stuck, I'd advise you to check out the tests we have in Chakra and also reach out on Discord.

Cheers.
