### ISSUE TITLE
[Stack] Setting margin prop on children of Stack has no affect

### ISSUE THREAD

**Issue by jmiazga** [chakra-ui/chakra-ui#1121]
On Discord, hosmelq reported that adding margin to a child component of the `Stack` component doesn't do anything. This is due to the generated class having a higher precedence.

![image](https://user-images.githubusercontent.com/181441/86490840-dd7c0e80-bd36-11ea-9799-6626ad0dc553.png)

![image](https://user-images.githubusercontent.com/181441/86490843-dfde6880-bd36-11ea-8f8b-1d3ec80dbedc.png)

In the screen shot above, the third box should have been pulled all the way to the right.

This issue can been seeing in the latest 1.0 build.

**Comment by with-heart** [comment]
This is an unfortunate side effect of switching how `Stack` works from previous versions. 

Up until 1.0, we either directly passed `margin` props to `children` or wrapped each child in a `Box` if `shouldWrapChildren` was set. This caused issues if you didn't understand that the margin was set using Chakra's `margin` props and `children` didn't correctly forward them on or use them internally.

Now we're using the lobotomized owl selector, which gives us the benefit of a low specificity in exchange for consistent behavior regardless of how `children` are implemented.

My views on this have gone back and forth. I think it's important that layout components like `Stack` are in charge of laying out their content, and that content components shouldn't be handling their own layout. That's the source of this bug, where the last content component wants control of its own layout via margin.

I've also seen the case made (and am convinced by the argument so far) that layout components should not prevent their content components from having control over themselves, and should not directly modify the content components but should enforce layout by wrapping them.

I'd need to play with these various styles of doing things to really get a feel for what feels best. 

As far as how it works for Chakra, I'm not sure we'll be able to do much for this specific problem. 

`Stack` has a very specific purpose (equal spacing of contained content) and if you don't want that, then perhaps the problem should be solved by other components or methods. For example, the last child can be positioned as expected in this instance using `flexGrow: 1` rather than trying to override `margin`.

**Comment by with-heart** [comment]
I realize that most of that last post is not entirely on topic lol but I think it's important stuff to think about anyway.

**Comment by with-heart** [comment]
> Currently `Stack` uses `*:not(style) ~ *:not(style)` but this selector has more specificity (read more [here](https://css-tricks.com/specifics-on-css-specificity/)) than the class applied by emotion to stack children
> 
> A solution would be to add the `!important` to every margin style applied to child of stack, so we should document that
> 
> A sandbox with an example
> [codesandbox.io/s/upbeat-wind-s45ww?file=/src/App.js](https://codesandbox.io/s/upbeat-wind-s45ww?file=/src/App.js)

_Comment from @remorses in https://github.com/chakra-ui/chakra-ui/issues/1128#issue-650893713_

**Comment by segunadebayo** [comment]
I completely agree @with-heart.

`Stack` should be used for layout purposes to control the spacing between each item. You shouldn't need to control the margin of child items.

If you need to do that, then `Stack` is probably not the best solution. For this scenario, you can combine Stack for the first 2 items and use combination of `Flex` and `justify-content: space-between` to solve this.

@with-heart, let's add a note about this in the Stack docs. Please create a docs issue.
