### ISSUE TITLE
Property '__css' is missing

### ISSUE THREAD

**Issue by arnaudjnn** [chakra-ui/chakra-ui#1127]
I use  ```sx``` props from ```theme-ui``` on ```Accordion``` and works great in dev env but I get the following build error at deploy (Vercel)

````
Property '__css' is missing in type '{ children: Element; allowToggle: true; defaultIndex: number[]; }' but required in type 'Pick<AccordionProps, "boxShadow" | "fontWeight" | "zIndex" | "alignContent" | "alignItems" | "alignSelf" | "appearance" | "backgroundAttachment" | "backgroundBlendMode" | ... 493 more ... | "__css">'.
11:06:06.959  
    37 | 
11:06:06.959  
    38 |   return (
11:06:06.959  
  > 39 |     <Accordion allowToggle defaultIndex={isOpen && [0]}>
11:06:06.959  
       |      ^
11:06:06.959  
    40 |       <AccordionItem sx={{border: 'none'}}>
11:06:06.959  
    41 |         <AccordionButton
11:06:06.959  
    42 |           sx={StyledAccordionButton}>

```

**Comment by segunadebayo** [comment]
Hey @arnaudjnn.

- From the error log (Line 42), I can see you're using `sx` this way `sx={StyledAccordionButton}>`. Ideally `sx` should be used to pass custom theme-aware styles, not components. I'm guessing you meant to use the `as` prop instead of `sx`

- We've fixed the `__css` issue and will push an update shortly.

Cheers.

**Comment by maihungdev** [comment]
Same issue, all component with typescript!

**Comment by with-heart** [comment]
@maihungdev Which Chakra version are you on?

**Comment by sebqq** [comment]
Same issue here. I'm on latest stable version of Chakra-ui.

**Comment by smarthutza** [comment]
@segunadebayo Perhaps you might be able to help? I am trying to use just your accordion component, but I get this: 

`      TS2741: Property '__css' is missing in type '{ children: Element[]; }' but required in type 'Pick<AccordionItemProps, "p" | "slot" | "style" | "title" | "className" | "color" | "height" | "id" | "lang" | "width" | "role" | "tabIndex" | "cursor" | "d" | ... 483 more ... | "isFocusable">'.
`  

I am using:
 "@chakra-ui/accordion": "1.0.0-next.6"
 "@chakra-ui/system":"1.0.0-next.3"

**Comment by ljosberinn** [comment]
please do not mix the versions of chakra packages, they need to be kept in sync. upgrade system to next.6 (generally you probably want to upgrade to `rc5` instead), remove node_modules and lock file and reinstall @smarthutza

**Comment by smarthutza** [comment]
@ljosberinn Thank you for your prompt response!

This has solved my problem:
"@chakra-ui/accordion": "1.0.0-rc.5"
"@chakra-ui/system":"1.0.0-rc.5"

**Comment by smarthutza** [comment]
@ljosberinn @segunadebayo One more thing I'd like to flag please.
Your docs mention `AccordionHeader: The button that toggles the expand/collapse state of the accordion item.`

However, I get this when I try to use it:

```
TS2305: Module '"../../../../../../node_modules/@chakra-ui/accordion/dist/types"' has no exported member 'AccordionHeader'.
ℹ ｢wdm｣: Failed to compile.
```

I have looked at the type definitions and indeed it is missing, so I am now using `AccordionButton` instead of `AccordionHeader`. Not a big deal, but perhaps you can update the docs or rename it. 

Great job! Absolutely love this: **https://openchakra.app/**

**Comment by ljosberinn** [comment]
The docs mention this in the [migration guide](https://next.chakra-ui.com/docs/migration#accordion).

**Comment by smarthutza** [comment]
@ljosberinn Thank you for the link to the migration guide. I hadn't seen it. 

I was mainly looking at this: **https://chakra-ui.com/accordion** where the `AccordionHeader` was still mentioned, which got me confused. 

Thank you for your time!
