### ISSUE TITLE
[General] Cross-browser inconsistencies in media-queries

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#1137]
Opening on behalf of pablo on Discord.

Breakpoints are differently computed, apparently based on browser?

**Expected Behavior** Breakpoints are consistent across browsers.

https://codesandbox.io/s/chakra-ui-media-issue-l1kex?file=/src/index.js

**Steps to Reproduce** 

Open in both Chrome and Firefox.
Chrome works as expected. XL > LG > MD > SM.
Firefox renders:
- MD above 1280px
- SM and LG below 1280px
- SM and XL below 992px
- SM below 768px

**Comment by segunadebayo** [comment]
Thanks for catching this @ljosberinn.

We've reverted most of the implementations to use styled-system's core functions instead. I believe it's more reliable and has been tested to work correctly across all browsers.

I noticed the issue with the `getMediaQuery` function. Thanks for looking into it @jmiazga.

This issue is no longer relevant and I believe this has been fixed.
