### ISSUE TITLE
[aria-hidden="true"] elements contain focusable descendents

### ISSUE THREAD

**Issue by arnaudjnn** [chakra-ui/chakra-ui#1159]
When running Lighthouse audit I get the following error for ```Accordion``` component

Focusable descendents within an `[aria-hidden="true"]` element prevent those interactive elements from being available to users of assistive technologies like screen readers.

[Here is some doc](https://web.dev/aria-hidden-focus/?utm_source=lighthouse&utm_medium=lr)

Is it possible to add a ```display: "none"``` in the next release for the content?

**Comment by segunadebayo** [comment]
Hi @arnaudjnn,

I believe this is coming from `react-animate-height`, the library we use for height animation. It adds `aria-hidden` once the height is collapsed, which I think is a good idea.

Applying `hidden` or `display: none` might make it difficult for the height transition to work correctly. That's why `aria-hidden`, was a better alternative. The goal is to make the content not available to screen readers once the height is collapsed.

I would consider this a design decision in `react-animate-height` not an issue. We've made it possible to disable the height animation and use the normal show/hide behavior which meets this requirement.

Hope this makes sense?

Cheers.

**Comment by arnaudjnn** [comment]
Thanks @segunadebayo 

Yes, it makes sense. Just to let you know that it throws an error in Lighthouse audit.
