### ISSUE TITLE
[Button] Type 'string | undefined' is not assignable to type '"button" | "reset" | "submit" | undefined'.

### ISSUE THREAD

**Issue by supryantowp** [chakra-ui/chakra-ui#1302]
**Description**

when I want to use props with typescript, this kind of problem arises
Type 'string | undefined 'is not assignable to type' "button" | "reset" | "submit" | undefined '.

```typescript
import React from "react";
import { Button } from "@chakra-ui/core";

enum typeButton {
  button,
  reset,
  submit,
}

type myButtonProps = {
  children: string;
  full?: boolean;
  loading?: boolean;
  type: string;
};

const MyButton = (props: myButtonProps) => {
  const { children, full, type } = props;

  return (
    <Button type={type} shadow="sm" my="1rem" isFullWidth={full}>
      {children}
    </Button>
  );
};

export default MyButton;


 ```

**Comment by with-heart** [comment]
Hi @supryantowp!

The reason you're receiving that error is because the `type` prop of `Button` is more _narrow_ than `myButtonProps.type`.

Type of `type` prop for `Button`: `"button" | "reset" | "submit" | undefined`

Since you're using `string`, that means someone could use `<MyButton type="random" />`, but `"random"` is not valid for the `Button` type. 

Instead you could either manually define the type to be the same as `Button`, or you could use `ButtonProps['type']` to grab that specific type: https://codesandbox.io/s/clever-brattain-11mnh?file=/src/MyButton.tsx
