### ISSUE TITLE
CSS props' values typescript autocomplete

### ISSUE THREAD

**Issue by lishine** [chakra-ui/chakra-ui#1360]
Why css props' values are not auto-suggested and are not controlled by typescript ?
Is it because it is impossible to implement it ?
```<Box display: '...' /> // would suggest none, flex, etc.```

**Comment by lishine** [comment]
The `justifyContent` for example - I am typing from scratch every time

**Comment by with-heart** [comment]
This is mostly an upstream dependency issue. [`csstype`](https://github.com/frenic/csstype) gives us types for all of the built-in CSS properties. 

For example, here's our definition for `display`:

https://github.com/chakra-ui/chakra-ui/blob/d5ad2dfdb359148f0a448a22a5cd5747b3ceb73a/packages/styled-system/src/config/layout.ts#L81-L84

`CSS.DisplayProperty` is defined in `csstype` here:

https://github.com/frenic/csstype/blob/e48d1c5c08896a8555829d76ba5ee9f022f7c964/index.d.ts#L1831

The problem really comes about due to `| string`. TypeScript internally reduces string types with literals AND `| string` to `string`, so it has no way to track those string literals and suggest them.

frenic/csstype#8 explains this a little more, but there are a lot of CSS properties that should take an arbitrary `string`. In particular, according to the CSS spec `display` can take a space-separated string value.

frenic/csstype#90 is a more recent issue discussing how to make this work. We'll have to wait for them to modify their types to make this work.

**Comment by with-heart** [comment]
Thanks to @sondh0127, we're now using `csstype@^3.0.0`, so a lot of these properties will now offer autocomplete. I've also opened #1580 to cover Chakra-specific types to make sure we get autocompletion in as many places as possible.
