### ISSUE TITLE
Text component does not have a default fontSize added

### ISSUE THREAD

**Issue by jackblackCH** [chakra-ui/chakra-ui#1361]
Theme:
```
...
  fontSizes: {
    xxs: "8px",
    xs: "11px",
    sm: "12px",
    md: "13px",
    lg: "15px",
  }
...
```
I expect ```<Text>Text</Text>``` to be 13px, since according to ChakraUI the "md" is the default (right?) and should be based on the ChakraUI theme? 

I don't want to add ```<Text fontSize="md">``` everywhere.

If I don't add the fontSize prop, the <Text> component is rendered without any fontSize, which leads into inheriting the browser default, which is 16px, if not adjusted.

I think since <Text> is a ChakraUI component, it should always rely on the defined base settings?

ChakraUI: 0.8.0

**Comment by with-heart** [comment]
Hi @jackblackCH, you can use the `Global` component from `@emotion/core` to set your base `font-size` using your theme values: https://codesandbox.io/s/pedantic-joliot-6jixv?file=/src/App.js

Chakra's default theme doesn't set a font-size and uses `rem` sizing in order to rely on the user's browser font size settings, so you'll have to use that to set your own base font size. 

If you plan on moving to 1.0, you'll be able to use `theme.styles.global` (more info on that [here](https://next.chakra-ui.com/docs/global-styles)).
