### ISSUE TITLE
[Transition] Doesn't support styling all animation states

### ISSUE THREAD

**Issue by skozer** [chakra-ui/chakra-ui#1373]
**Describe the bug** 

Chakra's Transition typings only include a subset of animation states in react-transition-group:
- init
- entered
- exiting

These ones are missing:
- entering
- exited
- unmounted

If I suppress TypeScript errors, styling is applied to the missing animation states as expected.

**Expected Behavior** 

Transition component's types should match the types of the underlying RTG Transition component.

**Link to minimal reproduction** N/A

**Steps to Reproduce**

```js
<Transition
  in={isVisible}
  styles={{
    init: { transform: `translateX(100%) translateZ(1px)`, opacity: 0 },
    // `entering` state below causes TypeScript to complain
    entering: { transform: `translateX(0%) translateZ(1px)`, opacity: 1 },
    entered: { transform: `translateX(0%) translateZ(1px)`, opacity: 1 },
    exiting: { transform: `translateX(100%) translateZ(1px)`, opacity: 0 },
  }}
>
  {(styles) => <Component style={styles} />}
</Transition>

```

**Suggested solution(s)**

Same as expected behavior^

**Desktop (please complete the following information):** N/A

**Additional context** Using Transition component to animate between 2 components, needed to use `entering` state so they animate simultaneously.

**Comment by segunadebayo** [comment]
Hi @skozer,

I'm not sure if you've worked with this `Transition` component from React Transition Group in the past. Passing styles for all the states doesn't work most of the time, RTG has some issues with the timeout.

**Here's a detailed comment:**

Timeout issues adding css animations to enter may be related to
 - https://github.com/reactjs/react-transition-group/issues/189 or
 - https://github.com/reactjs/react-transition-group/issues/22
 
As a result, use enter 0 so that is-open is applied once entered it doesn't matter if we know when the css-animation is done on entering for exiting though, give time for the css-animation to play before removing from the DOM.

I'm not sure if this has been fixed but I believe it's still an issue.

**Comment by skozer** [comment]
Thanks for the detailed reply @segunadebayo!

Your suggestion to use `timeout={{ enter: 0, exit: ... }}` fixed the issue I was having with transition delays.
Also looks cleaner as I don't have to duplicate styles for `entering` and `entered` states.
