### ISSUE TITLE
Add component libraries comparison page

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1421]
Users should be able to understand at-a-glance what the benefits and tradeoffs are to using Chakra over other similar libraries like MUI, AntD, etc..

**Comment by Vynlar** [comment]
When I'm pitching Chakra, my main selling point is that **Chakra makes it easier to customize components to be entirely your own.** MUI has a distinctly "material" look that is difficult to get rid of even if you want to. Chakra strikes a balance of "look nice out of the box" and "can morph into anything".

**Comment by segunadebayo** [comment]
I'd love to see more feedback on how Chakra users pitch or talk about Chakra UI. I believe it'll help get some ideas on how to frame the comparison.

**Comment by ljosberinn** [comment]
That was actually my pitch at work too @Vynlar :) besides the general theming possibility through `ThemeProvider`, overriding just anything is very easily done.

I'd like to make a side by side comparison of ant-d, MUI and chakra in next.js, including static exports, to compare bundle sizes, as mentioned [here](https://www.reddit.com/r/reactjs/comments/i6zqpn/build_a_landing_page_with_chakra_ui_part_1/g11dlwu/).

**Comment by ChasinHues** [comment]
When we were in the process of choosing a component library, like most others that found Chakra, we were looking for something that did a lot of the heavy lifting for us whilst being as unopinionated as possible. This was a big reason that ruled most of the big players out (MUI, Ant). These big players are awesome, don't get me wrong, but because they come with their own design languages, you're kinda stuck with their look.

Then there were a bunch of other medium/small players, such as variations of Bootstrap in React. Among other small issues, these libraries generally don't have large hyper-active communities. 

Then, I found Chakra. 

✅    - A wide range of well-thought components.
✅    - Unopinionated. Chakra gives you the tools to easily make your components look the way you want.
✅    - Built with accessibility in mind! **_You mean I don't have to worry about that anymore!?_**
✅    - **Amazing** community, lead by a great team. ❤️ 

I feel like Chakra is becoming a movement, and I'm excited for it.

**Comment by segunadebayo** [comment]
I've just pushed the first draft for this. We'll improve it as we go.

Cheers.
