### ISSUE TITLE
[Switch] color property only works with predifined theme color. RGB and HEX Code did work.

### ISSUE THREAD

**Issue by motdde** [chakra-ui/chakra-ui#1505]
Colors not defined in the default theme on the switch component doesn't work.

**Comment by with-heart** [comment]
Hi @motdde, can you please provide a codesandbox.io reproduction? It will help us help us.

**Comment by segunadebayo** [comment]
Hi @motdde, this is intentional as we'd like users to keep their interfaces consistent.

I believe you're referring to the `variantColor` prop in Chakra UI`v0.8`. In the next release (v1), we've made it possible to override this component UI and colors directly from the theme.

In the meantime, you can try using the `css` prop from emotion to change the color.

```jsx
/**@jsx jsx*/
import { jsx } from "@emotion/core"

<Switch css={{".selector": { bg: "#hex" } } } />
```
