### ISSUE TITLE
Different sizing unit for different component is a bit confusing.

### ISSUE THREAD

**Issue by coodoo** [chakra-ui/chakra-ui#152]
Take `Box` for example, setting `borderRadius` to `4` (hoping it will match the key in `baseSizes` and value to be converted to `1rem`) is invalid, one has to either specify `10px` or one of the values from `radii` as seen below.

Hence one needs to know which sizing units are available to which component, this is a bit confusing, is there anyway to unify and make sizing units usable across all components?

```js
<Box borderRadius='4' /> ❌
<Box borderRadius='10px' /> ✅
<Box borderRadius='lg' /> ✅

const radii = {
  none: "0",
  sm: "0.125rem",
  md: "0.25rem",
  lg: "0.5rem",
  full: "9999px",
};
```

**Comment by aaronmcadam** [comment]
Try using numbers when you want the 4px sizing scale: https://codesandbox.io/s/chakra-js-starter-t7n8e

**Comment by coodoo** [comment]
Yup, the key issue here is the unit size isn't consistent for all components, sometimes `4` works, sometime it didn't (for the example above, one needs to use `lg` instead of `4`), this is a bit confusing to the users.

**Comment by segunadebayo** [comment]
Hi @coodoo,

We followed the specifications of the Styled-System theme object that's why there's a radii key in the theme which is what you'd use for all `border-radius` properties.

If you want this to work `<Box borderRadius={4} />` and point to the sizes, you might need to extend the theme like this;

```jsx
const newTheme = {
  ...theme,
  radii : {
    ...theme.sizes,
    ...theme.radii
  }
}

<ThemeProvider theme={newTheme}>{/*Your app here*/}</ThemeProvider>
```

I'm not convinced we need to make the borderRadius options match that of sizes, by default. I hope this helps.

**Comment by coodoo** [comment]
Looks good, thanks for pointing that out!
