### ISSUE TITLE
Error in documentation on IconButton

### ISSUE THREAD

**Issue by elektronaut0815** [chakra-ui/chakra-ui#1588]
At the bottom of [the IconBotton doumentation](https://next.chakra-ui.com/docs/components/icon-button), in the 'Props' table, the type of 'icon' is shown as 'string'. This should be ReactComponent.

**Comment by ljosberinn** [comment]
Hi, thanks for filing the issue!

The live docs are currently outdated due to a rework. The actual reference can be found here currently:
https://github.com/chakra-ui/chakra-ui/blob/develop/website/pages/docs/components/icon.mdx#using-an-icon-library - the `icon` prop no longer exists, please use `as={Icon` instead. :)

There's an issue to specifically keep track of the Icon documentation [here](https://github.com/chakra-ui/chakra-ui/issues/998).
