### ISSUE TITLE
[NumberInput] onChange is called on every blur

### ISSUE THREAD

**Issue by dodas** [chakra-ui/chakra-ui#1649]
When number input is not empty, `onChange` callback is fired on each input blur, regardless of whether there was an actual change/input.

Happens both in controlled and uncontrolled mode.

Reproduction: https://codesandbox.io/s/numberinput-onchange-is-called-on-every-blur-1s72h?file=/src/index.js
Version: 1.0.0-rc.2 (does not happen in v0.8.0)

**Comment by ljosberinn** [comment]
Looks like this is because `clampValueOnBlur` [defaults to true](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/number-input/src/use-number-input.ts#L83) and is used in `onBlur` [here](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/number-input/src/use-number-input.ts#L251).

Comparing `next` with `counter.value` [here ](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/number-input/src/use-number-input.ts#L248) should fix that.

@hericlesme wanna look into that? :)

**Comment by dodas** [comment]
Thanks guys!
