### ISSUE TITLE
Using Chakra UI with react-hook-form

### ISSUE THREAD

**Issue by simoncollins** [chakra-ui/chakra-ui#165]
Howdy,

Since Chakra UI has nice support for refs, I was able to convert the Formik example using `FormControl` over to using [react-hook-form](https://react-hook-form.com) very easily - https://codesandbox.io/s/chakra-ui-react-hook-form-v382z

If you think it's worthwhile having a ref+hook-based example of form handling in the docs let me know and I can create a PR.

**Comment by segunadebayo** [comment]
Hi Simon,

Thanks for this. I'll add a "Recipes" to the docs we can include this idea.

If you can create a PR, I'd appreciate that. Here are the steps:
- In `packages/chakra-ui-docs/pages`, create a new file named `recipes.mdx`
- Add this to the recipes with a link to the codesandbox
- Submit a PR

I'd gladly merge your PR once you do this so I can include other recipes.

Thank you.

**Comment by simoncollins** [comment]
Thanks Segun, that sounds great. I'll get you a PR shortly that adds this.

**Comment by mustafawm** [comment]
👍👍

- @segunadebayo I think the recipes.mdx is not very easy to find. It'd be easier to find it if we mention react-hook-form example the same place we mention formik in [usage-with-form-libraries](https://chakra-ui.com/docs/form/form-control#usage-with-form-libraries) section
- If you want @simoncollins , you can update the example so it uses `formState` instead of managing `isSubmitting` using `useState` https://codesandbox.io/s/chakra-ui-react-hook-form-forked-1hwp9?file=/src/HookForm.js

**Comment by simoncollins** [comment]
Sure, @mustafawm, I will update the example shortly.

**Comment by simoncollins** [comment]
@mustafawm, I've updated the example to use `formState` and `isSubmitting` and updated to the latest versions of dependencies. It's always a nice feeling to delete code!
