### ISSUE TITLE
[Refactor] Combine Chakra into one main package

### ISSUE THREAD

**Issue by cereallarceny** [chakra-ui/chakra-ui#1718]
**What problem does this feature solve?**
So, I totally agree that each of the components need to be exported as individual packages, but I'm kinda curious if we need to have some other packages as distinct from the core.

**What does the proposed API look like?**
I feel that we could combine the following packages into the main `core` package:
- `styled-system`
- `system`
- `test-utils`
- `utils`

We should also combine the `theme-tools` into the `theme` package.

**Describe alternatives you've considered**
Honestly, it's a bit of a pain to have no idea where a given function is coming from. This makes development and contributing a bit of a pain. To make this harder, there's no API reference for this either. Rather, we could forego that step and just say that everything is defined in the component itself, the theme package, or the core package... that's it. Plus, we already support tree-shaking, so I'm not aware that there's a particular reason to separate packages as much as we are - it just makes things harder to follow. :)

**Comment by segunadebayo** [comment]
Hi @cereallarceny,

`styled-system` is a framework independent package that we intend to use for both React, Vue and in the future, Svelte. I'd say it's essential to keep it separate.

Here are some ideas:
- Attempt to combine `utils` and `hooks` into a single package
- Attempt to combine `modal`, `alert-dialog`, and `drawer` into a single `modal` package

As for `test-utils`, I think it's important to keep that separate as it's only used in development. Moving them to one package might bloat that package since it might include unneeded `dependencies`.

As a side note, I believe if you take a look at the package name e.g `@chakra-ui/utils`, you'll get a sense of where it's coming from (`packages/utils`). Otherwise, we can improve the source map support to make this easier.

Do you get what I mean?

**Comment by cereallarceny** [comment]
I think I get what you mean. For now, it's just very difficult to understand where various theming related functions exist: `useStyleConfig`, `styleConfig`, `StylesProvider`, `useStyles`, etc.

**Comment by segunadebayo** [comment]
Thanks for raising this issue. We've noted it for future improvements.

**Comment by hutber** [comment]
I'll just throw my bag into the mixer, it would be great to be able to tree shake! :D

**Comment by ljosberinn** [comment]
Everything already treeshakes @hutber

**Comment by hutber** [comment]
Oh, my mistake then.

`import Text from '@charka-ui/react/Text'` 

Doesn't work

**Comment by ljosberinn** [comment]
yeah, because its `import { Text } from '@chakra-ui/react'`, where did you find folderspecific exports?

**Comment by hutber** [comment]
Ye ok perfect. Problem with this is, afaik it imports the entire library. I assumed the other way would only important that single section

**Comment by ljosberinn** [comment]
No, it treeshakes just fine. This is my site in prod for example:

![image](https://user-images.githubusercontent.com/29307652/99274370-8cbf0b00-282a-11eb-886a-6e13c754a0c9.png)

You can see only the components that I'm actually using are imported.
