### ISSUE TITLE
[Image] htmlWidth and htmlHeight are broken

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#1721]
**Describe the bug** A clear and concise description of what the bug is.

The `htmlWidth` and `htmlHeight` attributes have stopped working. The underlying `<img>` element does not get a `width` or `height` attribute set on it.

**Expected Behavior** A clear and concise description of what you expected to
happen.

The underlying `<img>` element should get a `width` or `height` attribute set on it.

**Link to minimal reproduction** Please provide a codesandbox link or GitHub
repo with a minimal reproduction of the issue.

https://codesandbox.io/s/damp-moon-hd1ys

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS latest
- Browser [e.g. chrome, safari] Chrome latest

**Additional context** Add any other context about the problem here, or some
background information of how you ran into this bug.

Chakra 1.0.0 RC2.

**Comment by feross** [comment]
Seems to work in 1.0.0-next.4 and is broken in 1.0.0-next.5. Hope this is helpful!

**Comment by greven** [comment]
Was actually just trying to find out where the issue with the image width and height was.
It looks like the problem lies in the change to the evaluation of the valid props in should forward prop, before .next.5 there was some custom logic but now it is using @emotion/is-valid-prop which doesn't take into account the custom tags htmlWidth and htmlHeight.

This is the previous should-forward-prop: https://github.com/chakra-ui/chakra-ui/blob/gatsby-plugin-chakra-ui%401.0.0-next.4/packages/system/src/should-forward-prop.ts

**Comment by ljosberinn** [comment]
fwiw, until it's resolved, `width` and `height` as regular props worked fine for me both in your sandbox and in another repo

**Comment by segunadebayo** [comment]
Thanks for reporting this @feross. I've just pushed a fix for this.

It'll get released shortly.
