### ISSUE TITLE
[Button] colorScheme white doesn't work as expected

### ISSUE THREAD

**Issue by matteofrana** [chakra-ui/chakra-ui#1801]
**Describe the bug**
I'd to have a white button on a color background: I tried setting `colorScheme="white"`, but the button has no background color (white text in solid variant, black text and border in outline variant)

**Expected Behavior**
For `solid` variant: a solid white button (with black text?)
For `outline` variant: white text and border

**Link to minimal reproduction**
https://codesandbox.io/s/bitter-night-nzzj9?file=/src/App.js

**Suggested solution(s)**
For the solid white button the black text would be arbitrary.
Maybe it's better to have an `inverted` button, so that a blue button becomes white with blue text?

BTW, Thank you for this great library!

**Comment by paulbalogh** [comment]
colorScheme needs a palette of 10 "shades" for each color in order to automatically use color changes on hover, press, and switching to light / dark theme. "White" is defined as just 1 color, so is Black, which means Chakra cannot find the other shades. Workaround: extend the theme with a new "color palette" that contains your "shades of white" as well as the "shades of black". Could be something like: 
```js
    colors: {
      ...theme.colors,
      customWhite: {
        50: '#f5f5f5',
        100: '#ebebeb',
        200: '#d6d6d6',
        300: '#b8b8b8',
        400: '#999999',
        500: '#7a7a7a',
        600: '#5c5c5c',
        700: '#474747',
        800: '#292929',
        900: '#141414',
      },
     customBlack: {...},
}
```

My example above is for some shades of grey, but just replace the 10 shades inside with colors that match what you want. After that use `colorScheme="customWhite"` and everything will be fine.

**Comment by matteofrana** [comment]
Thank you @paulbalogh , now I understand.

I still think it would be great to have an "inverted" variant on buttons to be used on dark backgrounds, which renders:
- a white background with colorScheme text for solid
- a white text, white border for outline

What do you think about it @segunadebayo ?
Should I open a new suggestion issue for this?

Thank you,
Matteo

**Comment by with-heart** [comment]
@matteofrana imo this is probably a better fit for adding as a `variant` inside your own theme. https://next.chakra-ui.com/docs/theming/customize-theme

I'm going to close this for now. If we find more interest in this idea in the future, we'll consider adding it to the project itself.
