### ISSUE TITLE
react-spring in v1

### ISSUE THREAD

**Issue by hc-codersatlas** [chakra-ui/chakra-ui#1804]
Hi, was there any explanation as to why react-spring is being removed in v1? It's not exactly noted as a major change. React-transition-group doesn't have nice animations compared to react-spring and results in loss of functionality. Can this be reconsidered? Thanks.

**Comment by segunadebayo** [comment]
Hi @hc-codersatlas,

I totally understand your concern and agree react-spring has better animation/transition support. We removed it from Chakra UI because we'd like to show users how to use compose animation/transitions using any animation library of choice.

As a sensible default, we use RTG since it has a smaller size and give us a good transition/animation to start.

We'll update our docs to show how to use other animation libraries for Menu, modals, popovers, etc. We'll also add it as part of the major changes. @with-heart please help with this, update the migration guide highlights to include these points.

Hope this helps.
