### ISSUE TITLE
After migration to chakra v1 useColorMode hook does not seem to work properly in production

### ISSUE THREAD

**Issue by nisarhassan12** [chakra-ui/chakra-ui#1984]
Ref: https://github.com/NeonLaw/codebase/issues/776

`useColorMode` hook does not seem to work properly i.e on the initial render the border colour which is applied using it does not work i.e the desired `border-color` is not being applied to the Sections as shown below in the screenshot 

![image](https://user-images.githubusercontent.com/46004116/92321292-2f485a00-f042-11ea-85f1-4a3a03bc5058.png)

same is true for the other elements

![image](https://user-images.githubusercontent.com/46004116/92321373-dcbb6d80-f042-11ea-94bf-be0d8a08e30f.png)

Once the theme is switched via the Theme Switcher the `useColorMode` hook seems to work as expected.

## To Reproduce

visit: https://neonlaw.com

Note: Locally the `useColorMode` hook seems to work fine.

**Comment by ljosberinn** [comment]
#1878 could be related. Regardless, in your case it looks like your CSP policy disallows inline scripts from being ran:
![image](https://user-images.githubusercontent.com/29307652/92414308-f39db500-f153-11ea-8e4f-9deab7f37951.png)

which results in chakras pre-content script:
![image](https://user-images.githubusercontent.com/29307652/92414324-01533a80-f154-11ea-83c6-2a44ed7054bc.png)

not to run which results in no `colorMode` being set:

![image](https://user-images.githubusercontent.com/29307652/92414337-0c0dcf80-f154-11ea-8c6d-23648beaaf3a.png)

Allowing the script to be run would probably fix it.

**Comment by segunadebayo** [comment]
I see this has been fixed in your project @nisarhassan12.

Thanks for checking this @ljosberinn 💖

**Comment by mattiasw** [comment]
I don't use this functionality yet but I may do in the future so I want to add my two cents. The "fix" they did seems to have been to remove the Content Security Policy which is a terrible solution to this issue. Not being able to have a strict CSP will be a deal-breaker for many people (me included). I actually found this thread because of some inline styling that my CSP blocked which meant I had no styling anymore. I don't have time right now to dig into that and formulate an issue, but it definitely looks like a problem (maybe with Emotion though). Chakra is such an awesome project and I know you work hard and can't solve everything. I just wanted to point out that inline styles and scripts should not be added lightly and especially not without having a workaround (if they really have to be inline I guess a hash has to be used, I don't think a nonce will work with statically generated pages).

**Comment by afzaal-ameer** [comment]
This should be reopened. There seems to be no workaround if one wants strict CSP.

**Comment by with-heart** [comment]
I'd prefer if someone opened a new issue with more specific details around what is causing CSP to break.

**Comment by afzaal-ameer** [comment]
Strict CSP does not allow inline scripts or styles, so things like `<ColorModeScript/>` won't work. I have just started using chakra-ui so haven't come across any other failure cases yet.

**Comment by dmasley-hyfen** [comment]
I've been having the same issue except with the useToast method from `@chakra-ui/react`. Not sure how to update the nonce. Has their been any solutions?

**Comment by afzaal-ameer** [comment]
@dmasley-hyfen It looks like it takes nonce as a prop now. https://github.com/chakra-ui/chakra-ui/blob/main/packages/color-mode/src/color-mode-script.tsx

If you're not on the latest version you can modify css variables yourself instead of using `ColorModeScript`.

```js
const root = document.documentElement
root.style.setProperty("--chakra-ui-color-mode", colorMode)
```
