### ISSUE TITLE
Migrate to Theme UI and shadow its components for a better ecosystem

### ISSUE THREAD

**Issue by kripod** [chakra-ui/chakra-ui#199]
As Theme UI Components have [just been released](https://twitter.com/jxnblk/status/1185583086823772161), I realized they could provide a stable foundation for Chakra’s components. The `sx` prop could also come handy in some situations, and accessibility-related improvements could be backported to Theme UI, improving the ecosystem for everyone.

**Comment by segunadebayo** [comment]
I've been thinking about this as well. We're definitely moving to `theme-ui` once we can migrate all components to TS. Then, we'll look into this.

**Comment by cschroeter** [comment]
What is the point of moving to `theme-ui`? I think the main benefit with Chakra is that it brings full TypeSciript to the table where `theme-ui` is written in plain old js with no typings or @types support.

**Comment by fernandobandeira** [comment]
Love this, and it could be adopted progressively since it theoretically isn't a bc, for example, we could use their themeprovider as a start, then start replacing the components with their styled and keep going...

Also, the project has `@types` definitions, its here for now: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/theme-ui

And they plan on moving to ts later on.

**Comment by jondot** [comment]
Funny, I'm starting a migration from `theme-ui` to `chakra-ui` wholesale, after I've built a few components by hand that I see I can replace with better ones from Chakra, the goal is to reduce my own codebase size and replace with something more generic and better looking by default.

Some observations: I really want to keep using the `sx` prop, it _can_ make migration seamless and can provide a nice way to reduce friction. From what I'm seeing using the theme-ui `jsx` function, makes it work:

```jsx
import { jsx } from 'theme-ui'
import { Flex } from '@chakra-ui/core'

const Container = ({ children }) => (
  <Flex
    sx={{
      width: '100%',
      maxWidth: 'container',
      mx: 'auto',
      flexDirection: 'column'
    }}
  >
    {children}
  </Flex>
)
```

I totally didn't expect it, but variables are being fetched properly from the Chakra ThemeProvider and everything works well.

I haven't covered the codebase but this is the way I plan to move forward, Chakra for everything, theme-ui just for the `jsx` function, which when after all is done, I'll try to see how to maybe lift this from `styled-system` if it exists there to build a more isolated dependency tree.

Any thoughts are welcome, please do share :)

**Comment by segunadebayo** [comment]
Hi @jondot, thanks for this detailed feedback.

The `sx` prop is coming to Chakra in the next release so you can do a full migration 😄

**Comment by jondot** [comment]
Perfect!
Meanwhile I’m running side by side. Note that I cannot run two theme providers because they seem to override the same context key.

**Comment by segunadebayo** [comment]
@jondot , I'd suggest you just get the theme from Chakra and add it to Theme UI's ThemeProvider in the meantime.

**Comment by jondot** [comment]
Yup, I tried merging the two themes (my own theme-ui theme and chakra's default) and looks like they are partially compatible but not completely compatible. I think I can probably build something that can merge these together unless the interfaces aren't compatible.

**Comment by jondot** [comment]
Here's one place where the two themes conflict with no good way to resolve, just to leave here for academic purposes. Both themes has a spacing scale, but the concept of the scale is completely different, where I'm guessing in Theme UI it's a linear scale, and in Chakra it's a logical scale.


Theme UI:
```
0: 0
1: 7
2: 14
3: 28
4: 56
5: 112
6: 224
```

Chakra:
```
0: "0"
1: "0.25rem"
2: "0.5rem"
3: "0.75rem"
4: "1rem"
5: "1.25rem"
6: "1.5rem"
8: "2rem"
10: "2.5rem"
12: "3rem"
16: "4rem"
20: "5rem"
24: "6rem"
32: "8rem"
40: "10rem"
48: "12rem"
56: "14rem"
64: "16rem"
px: "1px"
```

**Comment by coodoo** [comment]
@segunadebayo Out of curiosity, what’s the benefit of migrating to theme-ui while chakra with it’s current implementation seemed to work perfectly?

**Comment by segunadebayo** [comment]
@coodoo, we're not exactly migrating to `theme-ui`. I'm only adding support for the `sx` prop and ability to styles components directly from the theme.

**Comment by kristojorg** [comment]
Hey @segunadebayo I'm wondering if the support for `sx` has been completed? I didn't see it in the docs or the changelog, so I'm guessing it's still in the works?

**Comment by jondot** [comment]
@kristojorg seems that as of a couple of weeks ago its not completed:
https://github.com/chakra-ui/chakra-ui/issues/579#issuecomment-609994356

**Comment by arnaudjnn** [comment]
Do you have an example using theme-ui and the new sx props together?

**Comment by clehene** [comment]
> Here's one place where the two themes conflict with no good way to resolve, just to leave here for academic purposes. Both themes has a spacing scale, but the concept of the scale is completely different, where I'm guessing in Theme UI it's a linear scale, and in Chakra it's a logical scale.
> 
> Theme UI:
> 
> ```
> 0: 0
> 1: 7
> 2: 14
> 3: 28
> 4: 56
> 5: 112
> 6: 224
> ```

The theme-ui sizes seem to grow exponentially `7 * 2^(x-1)` which would make the scale (0, 1, 2) logarithmic

> 
> Chakra:
> 
> ```
> 0: "0"
> 1: "0.25rem"
> 2: "0.5rem"
> 3: "0.75rem"
> 4: "1rem"
> 5: "1.25rem"
> 6: "1.5rem"
> 8: "2rem"
> 10: "2.5rem"
> 12: "3rem"
> 16: "4rem"
> 20: "5rem"
> 24: "6rem"
> 32: "8rem"
> 40: "10rem"
> 48: "12rem"
> 56: "14rem"
> 64: "16rem"
> px: "1px"
> ```

Chakra seems to have a series of linear scales `n * .25` followed by `n* .5`,  `n` and `n * 2`
What's a logical scale?

**Comment by joernroeder** [comment]
@jondot same issue here. could you figure out a way how to run both theme-ui and chakra`<ThemeProvider>` in the same app?

**Comment by with-heart** [comment]
@joernroeder Do you mean that the `sx` prop still isn't working?

**Comment by joernroeder** [comment]
@with-heart no, i dont think that the issue. I had some weird issues with `<ThemeProvider>` from `theme-ui` and chakra in the same project. did not get it running, not sure if its an issue with my project setup or nested providers and shared emotion or so. i'll ping you in discord where i've posted some details

**Comment by with-heart** [comment]
@joernroeder Yeah this is most definitely a conflict due to both libraries using `ThemeContext` from `@emotion/core`. The providers for Chakra and `theme-ui` also both have functionality for detecting an outer theme and merging it with their theme, so this would cause crazy overlap. 

Which is the point @jondot made awhile ago, but I didn't notice that until just now. 😆

I'm not sure how to deal with this situation to be honest. They're not compatible with each other in some ways, especially with the difference in scales. There's not a way to easily nest either of them under their own key inside `ThemeContext`.

**Comment by joernroeder** [comment]
@with-heart hm, i have not looked into the implementation yet but this sounds like some singleton bottleneck which would make it impossible to use two independent UI projects like chakra and themeUI as soon as they use an overlapping this usescase is just one example but in theory any lib which uses the themecontext could create this kind of conflict.

> There's not a way to easily nest either of them under their own key inside ThemeContext.

Whats the issue here? Can you elaborate on your findings, thx

**Comment by with-heart** [comment]
> this usescase is just one example but in theory any lib which uses the themecontext could create this kind of conflict.

Yeap, exactly. `theme-ui` in combination with any other library using `ThemeProvider` from emotion using the same theme keys would have the same problems. Considering that most of these systems are imitating `styled-system` in some way, that's going to be a common problem.

> Whats the issue here? Can you elaborate on your findings, thx

Well it's not technically impossible. You could store your themes under `theme.themeUI` and `theme.chakra` so they don't overlap with each other, but there's no way to tell either library to use the corresponding nested object instead of reading `theme` object directly.

**Comment by joernroeder** [comment]
@with-heart wouldnt it be possible to strip the namespace in all low level functions (like `useTheme`) which are interacting with the `ThemeProvider` and other related `emotion/core` objects in a way that lib users do not notice the extra key? for example changing https://github.com/chakra-ui/chakra-ui/blob/master/packages/system/src/providers.tsx#L40 to something like `return theme.__chakra__ ? theme.__chakra__ : theme`
or by adding a similar check after to https://github.com/chakra-ui/chakra-ui/blob/master/packages/system/src/providers.tsx#L77
