### ISSUE TITLE
Context-aware component theming

### ISSUE THREAD

**Issue by hazem3500** [chakra-ui/chakra-ui#2001]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to have the Icon inside the Button component to have a specific `boxSize` depending on the Button `size`, I noticed that the icon has a `width` & `height` of `1em` by default so I can change it by changing the Button's `fontSize` but I want the Icon to be a different size than the Button's `fontSize`.

## Describe the solution you'd like

We can turn the Button component into a multipart component and add the Icon as a part in the theme definition 
```tsx
export const ButtonTheme = {
  parts: ["button", "icon"],
  baseStyle: {
     button: {
       ...
     },
    icon: {
      color: "gray.100"
    }
  },
  sizes: {
    sm: {
      icon: {
        boxSize: 4
      }
    },
    md: {
      icon: {
        boxSize: 6
      }
    },
    lg: {
      icon: {
        boxSize: 8
      }
    }
  },
  defaultProps: {
    size: "md"
  }
};
```

Then we can wrap the passed Icons with `StylesProvider` as so (or add the StylesProvider inside the Icon component somehow)
```tsx
const Button = ({ leftIcon, rightIcon, ...props }) => {
  const styles = useMultiStyleConfig("Button", props);
  return (
    <BaseComponent
      leftIcon={
        leftIcon && <StylesProvider value={styles}>{leftIcon}</StylesProvider>
      }
      rightIcon={
        rightIcon && <StylesProvider value={styles}>{rightIcon}</StylesProvider>
      }
      sx={styles.button}
      {...props}
    />
  );
};
```

Then make the Icon take the styles using `useStyles`
```tsx
const Icon = ({ ...props }) => {
  const styles = useStyles();
  return <BaseComponent sx={styles?.icon} {...props} />;
};
```

But that will make the Icon not work by itself because it will give an error `useStyles: 'styles' is undefined. Seems you forgot to wrap the components in `<StylesProvider />` so we need a way to make `useStyles` return undefined or an empty object when there is no 'StylesProvider'.

We can do the same approach with components that get passed other components in their props

## Describe alternatives you've considered

We could just add `boxSize` to the passed Icon
```tsx
<Button leftIcon={<Icon boxSize={6} />}>Hello</Button>
```
But that doesn't sound like a pragmatic solution

## Additional context
codesandbox example: [link](https://codesandbox.io/s/chakra-ui-context-aware-icons-example-33pg2?file=/src/App.js)
Here is a talk that touches on the point of context-aware component theming: [link](https://youtu.be/EDyiaDJJu-4?t=561)

**Comment by with-heart** [comment]
@hazem3500 Thanks for raising this issue! 

This is something I've thought quite a bit about. I like the idea of certain "generic" components that are automatically styled based on the context they're used in, so that instead of having every potential use case receive a unique component, you can use a generic component in many places and have them automatically styled for that use case. This is definitely one of those situations. I've thought a decent bit about `Heading` and `Text` being context-aware as well, and I'm sure there are a number of other use cases.

I'm not sure how realistic this is for Chakra at this point in time, but it's definitely something I'd like to investigate more in the future. Potential concern for me is making the system too complex, but I think we can alleviate a lot of issues around complexity through good documentation and examples, which is something we're going to be working on a lot the next few months.

Thanks for the details, CodeSandbox example, and the link to the talk!

**Comment by hazem3500** [comment]
@with-heart I've found a way to make this work with the current implementation of chakra.
I've created a `useProvidedStyles` hook that returns the styles only if it is wrapped in a `styleProvider` else it will return null
```ts
import { useStyles } from '@chakra-ui/core';

function useProvidedStyles({ name }: { name: string }) {
    try {
        const styles = useStyles();
        return name ? styles[name] : styles;
    } catch {
        return null;
    }
}

export default useProvidedStyles;
```
then in the `Icon` component for example we can do something like this 
```tsx
import React from "react";
import { Icon as BaseComponent } from "@chakra-ui/core";
import useProvidedStyles from "./useProvidedStyles";

const Icon = ({ ...props }) => {
  const styles = useProvidedStyles({ name: "icon" });
  return <BaseComponent sx={styles} {...props} />;
};

export default Icon;
```
that way the `Icon` can be themed based on the context that it is in.
Here is a codesandbox showing how it works: [link](https://codesandbox.io/s/chakra-ui-context-aware-icons-example-solution-d9h9t?file=/src/Icon.js:0-301)

**Comment by segunadebayo** [comment]
Glad you found a walkaround @hazem3500.
