### ISSUE TITLE
with-chakra-ui with nextjs has very low lighthouse performance.

### ISSUE THREAD

**Issue by lukeyeh** [chakra-ui/chakra-ui#2068]
# Bug report

## Describe the bug

Simply using the `yarn create next-app --example with-chakra-ui with-chakra-ui-app` and not making any changes yields a considerably low lighthouse performance score.

## To reproduce

1. `yarn create next-app --example with-chakra-ui with-chakra-ui-app && cd with-chakra-ui-app`
2. `yarn dev`
3. Go to localhost:3000
3. Go to chrome -> right-click -> inspect element -> lighthouse -> generate report

## Minimal reproduction

Simply do `yarn create next-app --example with-chakra-ui with-chakra-ui-app`

## Expected behavior

I would assume that performance should be higher given that there isn't a lot of javascript on the very basic app.

### Example of getting a score of 30 on a basic Hero index page.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/15702751/93688440-ed80d000-fa93-11ea-8142-051882b26b79.png">

### Unused javascript details.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/15702751/93688460-07221780-fa94-11ea-8cc0-0542509d932a.png">

## System information

- OS: macOS Catalina 10.15.6
- Browser Chrome Version 85.0.4183.102 (Official Build) (64-bit)
- Version of @chakra-ui/core: @chakra-ui/core@0.5.2
- Version of Node.js: v12.18.3

**Comment by with-heart** [comment]
It took me a little while to figure out what this was. It's an official `nextjs` example created by community members: https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui

This example is based on an outdated version of Chakra (latest version of v0 is `0.8.0`, and we're nearing release of v1 which is at `1.0.0-rc.3`). I've created issue #2069 to open a PR to their repo to update the example once we have the time to do so.

Chakra is able to achieve much higher lighthouse scores when using the most recent version and following best practices. For example, the https://next.chakra-ui.com/ scores are:

![image](https://user-images.githubusercontent.com/1954752/93689048-d690ac80-fa98-11ea-9089-1b62e70430da.png)

The lower performance score is due to our use of a CodeSandbox on the homepage which uses passive listeners and somewhat inefficient cache policies and is unfortunately out of our control. Without that, we'd have near perfect scores for our own site.

I'm going to close this as we have a plan in place to resolve this. Thanks a lot for reporting @lukeyeh! Feel free to respond if you have any questions.

**Comment by with-heart** [comment]
Also we have a much more detailed NextJS example here: https://github.com/chakra-ui/chakra-ui/tree/develop/examples/next-js

**Comment by lukeyeh** [comment]
Thanks for figuring out the problem! I currently have a fairly large project that was built on top of using https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui. 

What would be the best way for me to upgrade chakra other than just doing `yarn upgrade yarn upgrade @chakra-ui/core@1.0.0-rc.2` to not mess with current dependencies?

**Comment by tuncpolat** [comment]
If I test the chakra page in incognito mode I see still very poor lighthouse results.
![image](https://user-images.githubusercontent.com/29253137/111384542-ee449880-86a9-11eb-9956-408df03d9034.png)

Has someone a live page build with chakra and nextjs so I can check? 
I am contemplating to build my next app with nextjs and chakra. But not sure if chakra will decrease the performance of the site.

**Comment by s-kris** [comment]
@tuncpolat 

https://github.com/chakra-ui/chakra-ui/discussions/5647#discussion-3894946

**Comment by zumbidoweb** [comment]
Same here, moved to theme-ui , 100% performance easy with next.
It looks an amazing library but can't get  as good ranking with it.
Strange that nobody cares to fix it as it make the library unusable  ...

**Comment by sayshark75** [comment]
With simple plain nextjs with chakraui, when i check lighthouse report for desktop, it is above 90 for each PABS, but when i choose mobile, its performance goes down, shows lots of main thread work
