### ISSUE TITLE
Wrap the Display Name for Easy Debugging

### ISSUE THREAD

**Issue by vuhg** [chakra-ui/chakra-ui#211]
Hey guys,

What do you think about adding `displayName` to chakra-ui's components for easy debugging in React Dev Tools? ([React docs](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging))

Current state:
<img width="945" alt="Screen Shot 2019-10-26 at 17 51 48" src="https://user-images.githubusercontent.com/54054422/67618407-78703080-f819-11e9-8c26-18aca1155827.png">

I used Stack, Text, Box and Image components in the image above. 

Edit: Add https://nqf3w.csb.app/ link.

**Comment by hendrikniemann** [comment]
I just came accross the fact that every component is named _Anonymous_ in the devtools and would love to see this. I'm also happy to make a PR.

**Comment by segunadebayo** [comment]
Yes, this is a good suggestion. If you have some time to look at it  @hendrikniemann, I'll gladly merge your PR.

Thanks

**Comment by yantakus** [comment]
@hendrikniemann, @segunadebayo it would be also very helpful if `chakra-ui` adds component names to CSS classes it generates, like `styled-components` does. So that we can see components names not only in react developer tools, but in Elements panel as well.

ATM it looks like this:
![image](https://user-images.githubusercontent.com/2179726/81039995-11f85900-8eb3-11ea-9995-b783b17ee5bd.png)
and it's very hard to understand anything.

If it's `Flex-css-5vq3nc` or `Box-css-5vq3nc` - it's at least something.

I'm not sure if we can add names of custom components like `styled-components` does this, so that

```
import React from 'react`
import styled from 'styled-components'

const StyledSomething = styled.div`
   display: flex;
`

const CustomComponent = () => <StyledSomething />

export default CustomComponent
```
becomes `CustomComponent-css-5vq3nc`.

If it's possible, it would be super helpful.

**Comment by hendrikniemann** [comment]
@yantakus I think this is a good suggestion that should be discussed. Could you open another issue for this since this issue is closed.
