### ISSUE TITLE
Strip off displayName css classes in production build

### ISSUE THREAD

**Issue by tomdohnal** [chakra-ui/chakra-ui#2229]
# Feature request

## Is your feature request related to a problem? Please describe.
 
Adding the names of Chakra-UI components as classnames (discussed in https://github.com/chakra-ui/chakra-ui/issues/682) to the HTML elements is a very useful feature for easier debugging and development. However, it increases the size of the HTML that gets transfered.

## Describe the solution you'd like

I believe stripping off the classnames in a production bulid could decrease the size of the HTML that gets shipped to the browser.

## Describe alternatives you've considered

An alternative is to keep it as it is now as the decrease is not probably going to be very significant.

**Comment by segunadebayo** [comment]
Hi @tomdohnal,

We plan to leave the classNames as it helps, not just in debugging, but in some cases where you might need to apply custom CSS. That said, I understand the concern about the HTML size, the benefits outweigh the cost though.

Thanks

**Comment by MariuzM** [comment]
I agree with OP we only want to have an option to remove on prod builds

**Comment by nilesh-bamne** [comment]
Any Update on this?

**Comment by caocuong2404** [comment]
Does anyone have other ideas?

**Comment by mdunbavan** [comment]
This is not being actioned from what I can tell and the Chakra team are not budging on it which seems pretty bad considering this is 1 of 2 issues raised about this now. 

The benefits are:

- It helps debug the code
- It is easier to apply custom styles to the components

My thoughts are;

- Debugging should be done without the need to access classes because in react for instance you can access the nodes you are looking at without looking for class names because you will have the component name and that is the same for Vue and Svelte.
- The whole point of this framework is to help streamline how developers build out and prototype UI. What you are suggesting is that we add more bloat to our css and class naming structure for customisation. I'm sure an enterprise dev team using this would be able to figure a way around this without adding more to the bundle size of the application.

I do think this should be looked into more as an option.

If this is a case for you being able to have your brand on all applications through adding class names on everything (which I think is what it is) then give an option to developers to pay to remove the classes from prod build?

@segunadebayo please can you consider the above?
