### ISSUE TITLE
[Theme] Layer Styles

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2231]
# Feature request

On [Discord](https://discordapp.com/channels/660863154703695893/660865137137156146/765545342443323403), the following question came up:
> How can I specify coherent layer styles for light and dark mode?
in regards to [these docs](https://next.chakra-ui.com/docs/features/text-and-layer-styles).

## Is your feature request related to a problem? Please describe.

> This sounds like a great idea, but I'd prefer to not specify "success-light" and "success-dark", and then decide which one I want to use in my client code. 

## Describe the solution you'd like

`layerStyles` should accept a function and be colormode-aware:

```js
layerStyles: (props) => ({
  base: {
    bg: mode('gray.100', 'gray.900')(props),
  }
})
```

## Additional context

[`theme.styles.global`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/styles.ts#L3) do this already.

**Comment by jsefiani** [comment]
@ljosberinn You can assign this one to me ;)

**Comment by dodas** [comment]
I was checking this out and haven't found a way to access the `colorScheme` where the `layerStyle` is resolved:
https://github.com/chakra-ui/chakra-ui/blob/a05204e44d651019434f9f8668280de2e34bb74b/packages/system/src/system.ts#L76

**Comment by ljosberinn** [comment]
I believe that was the issue @jsefiani had too

**Comment by dodas** [comment]
I am talking about actually implementing it, so users can do it in the theme.
I can't see a way to access the `colorScheme` in the `styleResolver ` function, so I could pass it to user's theme.

**Comment by ljosberinn** [comment]
So am I, sorry :) from what I remember he never found a way and thus didn't file a PR. We talked via DM on Discord.

**Comment by dodas** [comment]
Ah, I see.
@segunadebayo could you give us a little hint here?

**Comment by with-heart** [comment]
I think a few people have taken a stab at this and I have given my fair share of terrible advice around this. 😆 

The only function that actually has access to `colorMode` is `useStyleConfig` because component themes aren't computed until render and aren't applied as part of the component creation process via `@emotion/styled` but are applied separately using context and `styles` prop.

I'm not actually sure how feasible this is since `theme` is the only object available at component creation time while `colorMode` is dynamic and sourced from context.

**Comment by segunadebayo** [comment]
Thinking about this. I'd recommend using a className approach to solve this.

We append a `className` to `document.body` and you can leverage that className within the text and layer style. More like this:

```jsx
const theme = {
   layerStyles: {
       base: {
           bg: "red.500",
           ".chakra-ui-dark &": {  bg: "red.300" }
      }
   }
}
```

Over time, we might encourage using this approach rather than the functional approach. I have some ideas around making this work but It might complicate the code a bit and I'd rather avoid it.

**Comment by segunadebayo** [comment]
After much thought, we won't be supporting this API.

Please use the suggested approach above. Thanks

**Comment by AntonioDeCasper** [comment]
Hey, is there a "legal" way to use colorMode in layerStyles?

**Comment by dennemark** [comment]
> ```js
> ".chakra-ui-dark &": {  bg: "red.300" }
> ```

If someone needs this functionality for the DarkMode component, just create a custom component wrapping its children in a div with the beforementioned class:

```
import {ReactNode} from "react"
import {DarkMode as ChakraDarkMode} from "@chakra-ui/react"

export const DarkMode = ({children}:{children: ReactNode})=>{
    return <ChakraDarkMode>
            <div className="chakra-ui-dark">
                {children}
        </div>
    </ChakraDarkMode>
}
```
