### ISSUE TITLE
Unable to set specific styles when extending multipart components (Tabs)

### ISSUE THREAD

**Issue by ryanerras** [chakra-ui/chakra-ui#2289]
# Bug report

## Describe the bug

When trying to extend the theme for Tabs, certain styles aren't being applied for example the selected tab color or the border-bottom on tablist.

## To reproduce

See codesandbox

## Minimal reproduction

[https://codesandbox.io/s/runtime-fire-kgzt1](https://codesandbox.io/s/runtime-fire-kgzt1)

## Expected behavior

All style properties should be applied

## System information

- OS: macOs
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.5
- Version of Node.js: 12.15.0

**Comment by ljosberinn** [comment]
The issue is that [`Tabs` comes with `variants`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/components/tabs.ts#L178). [The default variant is `line`](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/components/tabs.ts#L189), but you're extending `baseStyle`. `baseStyle` is always overwritten by a variants styling. [Here](https://codesandbox.io/s/angry-archimedes-4u282?file=/src/app.js) is a working sandbox.
