### ISSUE TITLE
Popover accessibility

### ISSUE THREAD

**Issue by diegohaz** [chakra-ui/chakra-ui#23]
Hi, amazing work you've done here! Thanks for sharing it with the community and thank you for building it with accessibility in mind! ❤️

While I was testing components, I noticed that `Popover` isn't accessible by default, specially because the content inside the popover isn't perceived by screen reader users when it opens. Even sighted users using only keyboard would have difficulty using it.

I think the issue is basically it not receiving focus when it opens.

Here's an accessible `Popover` I've built that you can use as a reference: https://reakit.io/docs/popover/

**Comment by jimthedev** [comment]
I know they have different goals but if reakit and Chakra can combine forces on the accessibility front that'd be 💯

**Comment by segunadebayo** [comment]
@diegohaz Thank you for your feedback.

I'm aware of the accessibility issues of the Popover component, that's why I marked it as "In Progress".

I've checked through Reakit, and I must say that I'm inspired by the work you put into Reakit. 

I'd appreciate your contribution to help fix this issue, I'll look into it soon as well.

**Comment by segunadebayo** [comment]
@jimthedev , merging Chakra and Reakit sounds like a good idea 💯

**Comment by segunadebayo** [comment]
@diegohaz , I looked through the code of Reakit Popover and it really helped me in rewriting the Popover to make it more accessible and composable.

Thank you 💖. I'll release a patch soon.
