### ISSUE TITLE
Popper throwing error on Chakra Tooltip hover

### ISSUE THREAD

**Issue by ChasinHues** [chakra-ui/chakra-ui#2382]
# Bug report

## Describe the bug
When hovering over a `Tooltip`, a popper error appears in console:
```
Popper: Invalid reference or popper argument provided. They must be either a DOM element or virtual element.
```

## Minimal reproduction

https://codesandbox.io/s/eager-stonebraker-nbxjw?file=/src/App.tsx

## Screenshots

![image](https://user-images.githubusercontent.com/13565648/97661283-aab50d80-1abf-11eb-85a9-1fa832d50419.png)

**Comment by laurensnl** [comment]
Same here. Didn't find a solution yet. From my understanding, Popper might be replaced by something else:

> we are however not content with the general impression popper has made so far so this is ultimately definitely subject to change

**Comment by EllaSharakanski** [comment]
Same here. I just upgraded from `rc.2` to `rc.8` and this error appeared. Before the upgrade, the code worked just fine.

**Comment by with-heart** [comment]
To give some context on what's going on here:

This error is thrown by `popper-core` in two cases, both when the "popper" node doesn't exist:

1. [When the popper is created](https://github.com/popperjs/popper-core/blob/671f71e2b6990765e5ca780daaea7d1f7175beb6/src/createPopper.js#L251-L256)
2. [When `forceUpdate` is called on the popper instance](https://github.com/popperjs/popper-core/blob/master/src/createPopper.js#L174-L179)

In the case of `Tooltip`, the "popper" node is the outer `div` inside the `Portal` that spreads `tooltip.getTooltipWrapperProps`:

https://github.com/chakra-ui/chakra-ui/blob/efd13e63eac03812e6f73575f4f284c8792373c3/packages/tooltip/src/tooltip.tsx#L153-L158

`getTooltipWrapperProps` calls `popper.getPopperProps` passing `_ref`:

https://github.com/chakra-ui/chakra-ui/blob/6e6b39dd9268e56269787ea33eca40d7e21f7b4c/packages/tooltip/src/use-tooltip.ts#L187-L193

`getPopperProps` returns an object where `ref` will call `setPopperNode` to store that object's ref:

https://github.com/chakra-ui/chakra-ui/blob/20be8efc619a1b64d8b4393e9b301a5ec587b917/packages/popper/src/use-popper.ts#L164-L164

So the chain of events is that the wrapper `div` is created and its `ref` is passed through this layer of functions back to `setPopperNode`, where it is stored and passed into our use of the `useBasePopper` hook from `react-popper`:

https://github.com/chakra-ui/chakra-ui/blob/20be8efc619a1b64d8b4393e9b301a5ec587b917/packages/popper/src/use-popper.ts#L127-L131

The issue here appears to be that since the wrapper `div` is conditionally rendered by `tooltip.isOpen`, `popperNode` is a `null` reference whenever the tooltip is not open. I'm not sure what the best course of action would be for fixing this, and I'm also not sure why this suddenly started happening since it seems that this has always been conditionally rendered.

**Comment by PawelJ-PL** [comment]
In version `1.0.0-rc.5` the problem does not occur. It occurs when upgrading to `1.0.0-rc.8`.

**Comment by avaragado** [comment]
I have a hunch that this issue is related to the changes made around transitions. Between rc.5 and rc.8, various components such as `Popover` and I think `Tooltip` moved to use transitions based on `framer-motion`.

I wonder if `popper` and `framer-motion` don't mix? See https://github.com/popperjs/popper-core/issues/376 for example.

I'm using Chakra's `Popover` in my app (as a wrapper for `react-select`), and the `PopoverContent` is now rarely appearing in the right place. It certainly did a few rc versions ago. When `PopoverContent` does appear in the right place, it seems to be because the `Popover` component isn't included in the first render of its owner component (eg because I'm waiting for network data to load before rendering `Popover`). If I render `Popover` on the first render, it's wrongly positioned: usually at the top left of the viewport (I'm using `Portal` around `PopoverContent`). Adding `isLazy` to `Popover` makes no difference.

Resizing the viewport manually ensures the `PopoverContent` is correctly positioned next time `Popover` is open.

Hope that ramble helps...

**Comment by segunadebayo** [comment]
I just pushed a fix for this @ChasinHues. The error was from our custom `react-popper` implementation.

**Comment by Joaoviana** [comment]
@segunadebayo Thanks for getting this fix in! 😄  when are you expecting to release this?

**Comment by nagysandorantal** [comment]
What chakra version has the fix?

**Comment by Smyja** [comment]
> What chakra version has the fix?

any idea yet?

**Comment by Maida90** [comment]
LID_ELEMENT_ERROR = 'Popper: Invalid reference or popper argument provided. They must be either a DOM element or virtual element.';

**Comment by Maida90** [comment]
what is error
