### ISSUE TITLE
Controlled Tabs cannot activate the first tab

### ISSUE THREAD

**Issue by ChiaJune** [chakra-ui/chakra-ui#2384]
# Bug report

## Describe the bug

Controlled Tabs cannot activate the first tab

## To reproduce

1. Go to [https://codesandbox.io/s/tabs-bug-rc8-sh45l?file=/src/App.tsx](https://codesandbox.io/s/tabs-bug-rc8-sh45l?file=/src/App.tsx)
2. Click on 'Teal' or 'Blue' button
3. Then click on 'Red' button
4. The 'Red' button cannot be activated

## Minimal reproduction

[https://codesandbox.io/s/tabs-bug-rc8-sh45l?file=/src/App.tsx](https://codesandbox.io/s/tabs-bug-rc8-sh45l?file=/src/App.tsx)

## Expected behavior

The 'Red' button can be activated

## Screenshots

no.

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of @chakra-ui/core: 1.0.0-rc.8
- Version of Node.js: v12.18.4

## Additional context

no.

**Comment by with-heart** [comment]
Hi @ChiaJune, I've tracked the issue down to the `updateValue` callback inside `useControllable` (which is used by `Tabs` to manage `value`/`defaultValue`/`onChange`:

https://github.com/chakra-ui/chakra-ui/blob/299a82a2c4f290b875ffaced8d671b6fd1953ddd/packages/hooks/src/use-controllable.ts#L95-L99

Since `updateValue` has an empty dependencies array, `onChange` always refers to the first instance of `onChange` passed to it, which in this case is when `tabIndex` is `0`. Updating the dependencies array to `[onChange]` causes this to work correctly. I'll open a PR to suggest that change, as I believe `onChange` should be allowed to update.

In the meantime, you can use a ref that always updates to the value of `tabIndex` and check that in your `handleChange` callback instead: https://codesandbox.io/s/tabs-bug-rc8-forked-sp4d4?file=/src/App.tsx

**Comment by with-heart** [comment]
This should be fixed in the next published version 😄

**Comment by ChiaJune** [comment]
Thank you very much
