### ISSUE TITLE
PropTypes missing

### ISSUE THREAD

**Issue by Zyclotrop-j** [chakra-ui/chakra-ui#2403]
# React PropTypes missing in @next

## Context

propType definitions are not included in the latest (@next) version.
That causes problems when using chakra in js projects (opposed to ts projects).
For one, it doesn't warn, but worse, it crashes existing build which re-compose chakra ui-components and reference their propTypes in doing so. (`MyComponent.propTypes = { foo: PropTypes.bool, ...Grid.propTypes, align: Grid.propTypes.align }`, where Grid is imported from chakra.)

## Possible solutions

I assume the propTypes have been scrapped in favour of typescript.
However, I believe the propTypes could be generated from the typescript definitions, either one-of (e.g. https://github.com/merceyz/typescript-to-proptypes), or continuously at build-time (e.g. https://github.com/milesj/babel-plugin-typescript-to-proptypes).

## Alternatives

I'm currently setting up webpack/babel in such a way that it builds chakra, so I can use the typescript to proptypes conversion on my side. However this is causing a whole range of other problems (need to setup typescript compiler etc) as chakra comes pre-compiled (which is good!).

## Additional context

N.A.

**Comment by with-heart** [comment]
Hi @Zyclotrop-j! I don't think this is something we'll support, for a few reasons:

- We removed `prop-types` from the project in v0.3.2 (September 2019) and so far this is the only request we've had in over a year to add them back
- Our components are generated using `styled-system` as a base. There is the `@styled-system/prop-types` package which allows attaching `prop-types` to components, but as far as I can tell, we would need to completely rebuild our system in order to attach `prop-types` at each step
- We make heavy use of the `as` prop which would make `prop-types` inheritance incredibly complex
- ts-to-prop-types generators are possibly feasible, but are another layer of thing for us to support when we've already have a heavy workload to begin with
- We're a small team and this feels like a large investment of our time for very little return

With that said, I think it's best for us to leave `prop-types` support as a task for individual projects to implement rather than supporting it as part of Chakra. If there's anything we can do to make it easier for you to handle this yourself though, please let us know!

**Comment by Zyclotrop-j** [comment]
Thanks @with-heart for the quick reply and the list of reasons.

From what you're saying, I take it's mostly a return-of-investment problem, and there might be additional architectural challenges. If you don't mind, I'll have a crack at it and see what I can come up with (constrains from your list: no changes to components/architecture + no changes to build + evaluate feasibility of support of `as`-prop); from my first look through the source, it looks feasible and your hint at `@styled-system/prop-types` looks like it might make it easier, too :)
I'll add a comment with how I went whenever I'll have found the time to give it a go!
