### ISSUE TITLE
having colorMode in layerStyles and textStyles

### ISSUE THREAD

**Issue by alexadark** [chakra-ui/chakra-ui#2444]
# Feature request

as layoutStyles and textStyles are reusable styles it would be awesome to be able to define the colors with colorMode instead of having to write it for each component where it's used

**Comment by with-heart** [comment]
To add some context if anyone wants to pick this up:

Most other parts of the theme can be defined as either an object or a function that takes `props` (which includes  `colorMode`). In the case of `layerStyle` and `textStyle`, these can currently only be defined as an object.

We access them from `theme` in `styleResolver`:

https://github.com/chakra-ui/chakra-ui/blob/4c18e327b2a4fa76880b19a6199f3ba90612f2c0/packages/system/src/system.ts#L76-L77

And then add them directly to the `finalStyles` object:

https://github.com/chakra-ui/chakra-ui/blob/4c18e327b2a4fa76880b19a6199f3ba90612f2c0/packages/system/src/system.ts#L104-L114

That function has access to `props`, so we should be able to use `runIfFn` to enable them to be defined as functions.

**Comment by TheThirdRace** [comment]
### Adding to the discussion
I would also add the functionality to everything that is missing it like shadows, colors, borders, etc.

You never know when or how it's gonna be used by others, might as well give them some flexibility.

### When did I run into the problem
I ran into the problem with Shadows. While moving from 1.0.0-rc.5 to 1.0.0-rc.8, a new style (overflow:hidden) was added to Accordion that would block the display of my outline when focused with the keyboard.

After thinking a bit about it, I realized any component that is stuck at the edge of the browser would see its focus outline being cut off at the edge. Same would happen to any component at the edge of a overflow:hidden component.

To solve this, I decided to make the default focus outline inward, since I find it logical that your component doesn't bleed outside it's box model. To achieve this, I couldn't use a function, so I had to import theme from `@chakra/core-ui ` and use string literals to add inset at the end of the outline property. It would have been better to use a function like components, because if I wanted to change the color of the outline, I'd be in trouble... it's also better to have a common way to do these things and the function is already used for components and globals.

Although it did come with the unfortunate problem that inline components with no padding will be partially masked by the outline, like a frame is masking part of a painting. Fortunately, I have very few components that actually are inline with no padding whatsoever, so it was just a matter of removing the `inset` value for the outline in those cases.

The trade-off was definitely worth it for me. With inward outline every component is showing the full outline no matter what. The very few problematic cases can simply be corrected in their theme. At worst, if I forget to fix a problematic case, it's a minor esthetic annoyance as you can still see the component correctly even with the overlapping outline.

**Comment by TheThirdRace** [comment]
I'd like to add to make sure that the function result is merged like with components.

This was added for components and it's really helpful to override base style when both the base and the variant are functions.

**Comment by with-heart** [comment]
@TheThirdRace I feel like I missed something here. The feedback is excellent (I love it when people take the time to provide lots of context and details), but what functionality are you saying you want added to address this?

**Comment by TheThirdRace** [comment]
I did give a bit too much details did I :)

The theme can have functions or object for styling components, here's an example:
```
export const Header: StyleConfig = {
	parts: ['heading', 'subheading'],
	baseStyle: (props: StyleConfigProps): { [part: string]: SystemStyleObject } => {
		return {
			heading: {
				fontSize: '3rem'
			},
			subheading: {
				color: 'blue.300'
			},
		}
	},
	defaultProps: {}
}
```

Globals can also have a function, ex:
```
export const styles: Styles = {
	global: (props) => ({
		html: {
			bg: mode('white', 'black')(props)
		},
		body: {
			fontFamily: 'body',
			color: mode('black', 'whiteAlpha.800')(props),
			bg: mode('white', 'whiteAlpha.50')(props),
			lineHeight: 'base'
		},
		'*::placeholder': {
			color: mode('gray.400', 'whiteAlpha.400')(props)
		},
		'*, *::before, &::after': {
			borderColor: mode('gray.200', 'whiteAlpha.300')(props),
			wordWrap: 'break-word'
		},
		fontFeatureSettings: '"pnum"',
		fontVariantNumeric: 'proportional-nums',
	})
}
```

But `textStyles` and `layerStyles` don't allow function, you need to use an object.

Same goes for other parts of the styles like `shadows`, ex:
```
import { theme } from '@chakra-ui/core'

// Need to use theme directly, can't use function...
export const shadows = {
	...theme.shadows,
	outline: `${theme.shadows.outline} inset`
}
```

It would be nice to have access to the function type to do this instead:
```
export const shadows = (props: StyleConfigProps): SystemStyleObject => ({
	outline: `${props.theme.shadows.outline} inset`
})
```

I got a workaround to do it without a function, but usually it's nice when everything works the same way, not just little parts here and there :)

All this to be able to do this:
```
const overrides = {
	// special config
	config,
	// global styles
	styles,
	// foundation styles
	shadows,
	// component styles
	components: {
		Accordion,
		Button,
		Drawer,
		Heading,
		Icon,
		Link,
		Menu,
		Page,
		Text
	}
}

// eslint-disable-next-line import/no-default-export
export default extendTheme(overrides)
```

I hope it makes more sense now. If not, we can setup a chat on Discord so I can better explain it.

**Comment by ChasinHues** [comment]
@with-heart I wouldn't mind taking a crack at this one if nobody else has started looking into it? 😄

**Comment by ChasinHues** [comment]
@with-heart @segunadebayo how would I get access to colourMode and colourScheme to inject into `runIfFn(...)`?

e.g.
```jsx
  const layerStyleObjectOrFn = get(theme, `layerStyles.${layerStyle}`, {})
  const _layerStyle = runIfFn(layerStyleObjectOrFn, {theme, colorMode, colorScheme})
  
  const textStyleObjectOrFn = get(theme, `textStyles.${textStyle}`, {})
  const _textStyle = runIfFn(textStyleObjectOrFn, {theme, colorMode, colorScheme})
```

**Comment by snesjhon** [comment]
@ChasinHues do you have a branch for this? I'd like to also see how this could work.

**Comment by ChasinHues** [comment]
@snesjhon I didn't get anywhere with this one unfortunately

**Comment by stellarhoof** [comment]
I'd also include `defaultProps` here. Very useful for (ex.) buttons to specify a default colorScheme depending on the color mode.

**Comment by ChasinHues** [comment]
Has this been resolved with the [update to /styled-system](https://github.com/chakra-ui/chakra-ui/pull/3245) in the 1.3.2 release?

**Comment by dannyvaughton** [comment]
This is a feature I am definitely interested in seeing

**Comment by segunadebayo** [comment]
Hey guys, kindly check the recommended approach here #2231.
