### ISSUE TITLE
*:not(style) ~ *:not(style) 

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#2476]
Currently I am having to override most of my `useBreakpointvalue` items with an important to remove this random css rule, but this means I cannot use my number based fontSizes, lineHeights etc.

    const margin = useBreakpointValue({ base: "0 !important", md: space["0.5"] });

So in this situation I cannot use important on my space

What is this style and how can I find out where it is defined?

# Theme

```
const space = {
  "-1": "0rem",
  0: "0.5rem",
  1: "1rem",
  2: "1.5rem",
  5: "2.5rem",
  8: "4rem",
  13: "6.5rem",
  21: "10.5rem",
  35: "16.5rem",
};

```
This is adding the styles from the first image, to all child components of `.chakra-stack.css-gafkgn`
![image](https://user-images.githubusercontent.com/1344898/99070239-c502e700-25a7-11eb-9d7c-ec1913c5c9b1.png)

![image](https://user-images.githubusercontent.com/1344898/99070184-abfa3600-25a7-11eb-9148-f4d96e9cf063.png)

**Comment by RyanPinPB** [comment]
I am also trying to figure out where this rule is coming from. It is not wanted and now I have use an !important css declaration to get around it.

Unwanted style added by something in Chakra:
```
.css-15jzajg>*:not(style)~*:not(style) {
    margin-left: 0.5rem;
}
```

**Comment by rquast** [comment]
Have noticed the same problem as @RyanPinPB  since upgrading from 0.8 to 1.0. Causes a y scrollbar for a right aligned popovers.

**Comment by hutber** [comment]
Was your issue different from mine @rquast or the same as Ryans?

I corrected the issue oddly when I remove this line of code:



```
const space = {	
  0: "0rem",	
  0.5: "0.5rem",	
  1: "1rem",	
  2: "1.5rem",	
  5: "2.5rem",	
  8: "4rem",	
  13: "6.5rem",	
  21: "10.5rem",	
  35: "17.5rem",	
};	
```

And replaced it with and it went away:
```
const space = {
  "-1": "0rem",
  0: "0.5rem",
  1: "1rem",
  2: "1.5rem",
  5: "2.5rem",
  8: "4rem",
  13: "6.5rem",
  21: "10.5rem",
  35: "16.5rem",
};
```
I will try to recreate

**Comment by rquast** [comment]
@hutber sorry, I mean it was the same as Ryan's where it's a seemingly incorrectly applied style. The hidden Popover div inherits this style which causes my issue and I don't know how to get rid of it. If I temporarily disable the style in developer tools, there is no x overflow. I've managed to get around the issue for popovers by adding the placement as "bottom-end" for right-aligned (flush with the far right of the page) popovers. If this should be split into a different issue, I'll create an issue for it and reference this one.

**Comment by RyanPinPB** [comment]
You can see a live example of mine at: https://pearsondigitalmarketing.com/ 

The issue is shown in the social media sidebar (<aside> element) in the **second and third anchor tags holding instagram and twitter**.

It's weird that it's not shown in the first anchor tag. . .

I only saw this after upgrading to the new Chakra v. 1.0.0

`<aside role="group" class="chakra-button__group social-icons css-15jzajg">
<a target="_blank" rel="noopener noreferrer" class="chakra-link css-1bvdrhg" href="https://facebook.com"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="chakra-button social-button css-1g4zwnn" aria-label="Pearson Digital Marketing Facebook" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" style="stroke: unset;"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg></a>

<a target="_blank" rel="noopener noreferrer" class="chakra-link css-1xtj49d" href="https://instagram.com"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="chakra-button css-1ibai6c" aria-label="Pearson Digital Marketing Instagram" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.5" y2="6.5"></line></svg></a>

<a target="_blank" rel="noopener noreferrer" class="chakra-link css-1xtj49d" href="https://twitter.com"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="chakra-button social-button css-1g4zwnn" aria-label="Pearson Digital Marketing Twitter" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" style="stroke: unset;"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg></a></aside>`

**Comment by segunadebayo** [comment]
Hi @hutber ,

I'm not sure I understand this issue. Why do you need to always to override the styles using `useBreakpointValue` instead of passing responsive style props?

Also the title of this issue isn't clear. Could you update that and create a Codesandbox replica of this issue so we can resolve it faster.

When you do I'll re-open this.

**Comment by segunadebayo** [comment]
Also, these styles are coming from the `Stack` component in Chakra UI. Due to the way emotion handles style in SSR, that was the best CSS selector we could use. We could have used. "> * + *" but it doesn't work as expected.

**Comment by hutber** [comment]
https://github.com/chakra-ui/chakra-ui/issues/2578 with correct title and reproducible errors.

**Comment by JakeGinnivan** [comment]
> Also, these styles are coming from the `Stack` component in Chakra UI. Due to the way emotion handles style in SSR, that was the best CSS selector we could use. We could have used. "> * + *" but it doesn't work as expected.

An alternative is to use https://emotion.sh/docs/ssr#advanced-approach

When you do not use the default cache it will not issue that warning. The advanced approach also extracts the styles into a single style tag, so this workaround is not required.

**Comment by RyanPinPB** [comment]
I changed my Chakra component from ButtonGroup to a Flex and the extra styling for .5rem margin went away, solving my problem

**Comment by hutber** [comment]
Ye, the problem is ryan, when you want to use the Flex or YVstack :(, if you see #2578
