### ISSUE TITLE
Customize breakpoint key names and use that keys in component style props

### ISSUE THREAD

**Issue by OFranke** [chakra-ui/chakra-ui#2539]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to customize breakpoint configuration to match the standard of chrome dev tools. I constantly find myself checking which breakpoints I configured in template. Calling breakpoints sm, md, lg, xl is not really descriptive and doesn't really imply which device I am targeting when applying styles inside my components. Right now I need to configure breakpoints like that:
```
const breakpoints = createBreakpoints({
  sm: "320px",
  md: "768px",
  lg: "1024px",
  xl: "1920px",
});
```
## Describe the solution you'd like

I want to configure breakpoints as following:
```
const breakpoints = createBreakpoints({
  mobileS: "320px",
  mobileM: "375px",
  mobileL: "425px",
  tablet: "768px",
  laptop: "1024px",
  laptopL: "1440px",
  "4K": "2560px",
});
```

I guess it would be very comfortable if the key names are customizable in general, so that I could basically maintain the old ones with key names sm, md, lg, xl and update my codebase to new breakpoint names step by step.

That would make it very easy to handle things like fontSize very granular and smooth like so:

```
import { Text, TextProps, useBreakpointValue } from "@chakra-ui/react";
export const DefaultText: React.FC<TextProps> = ({ children, ...props }) => {
  const textSize = useBreakpointValue({
    mobileS: "sm",
    // mobileM: "sm",
    mobileL: "xl",
    // tablet: "xl",
    laptop: "2xl",
    laptopL: "3xl",
    "4K": "4xl",
  });
  return (
    <Text fontSize={textSize} {...props}>
      {children}
    </Text>
  );
};
```

Or I could define things like Default Container components much more descriptive and granular:
```
import {
  Container,
  ContainerProps,
  useBreakpointValue,
} from "@chakra-ui/react";

interface DefaultContainerProps extends ContainerProps {
  size: "s" | "m" | "l" | "xl";
}
export const DefaultContainer: React.FC<DefaultContainerProps> = ({
  size,
  children,
  ...props
}) => {
  const containerSizes = {
    s: {
      mobileS: "100vw",
      mobileL: "400px",
      tablet: "500px",
      laptop: "850px",
      laptopL: "60vw",
    },
    m: {
      mobileS: "100vw",
      mobileL: "500px",
      tablet: "600px",
      laptop: "1050px",
      laptopL: "65vw",
    },
    l: {
      mobileS: "100vw",
      mobileL: "500px",
      tablet: "900px",
      laptop: "1250px",
      laptopL: "70vw",
    },
    xl: {
      mobileS: "100vw",
      mobileL: "500px",
      tablet: "900px",
      laptop: "1400px",
      laptopL: "80vw",
    },
  };

  const containerMaxWidth = useBreakpointValue(containerSizes[size]);

  return (
    <Container
      maxW={containerMaxWidth}
      {...props}
      marginLeft="auto"
      marginRight="auto"
    >
      {children}
    </Container>
  );
};

```

## Describe alternatives you've considered

None, because working around the defaults makes projects much more complicated and prone to bugs. In that case it's better to stick to any defaults.

**Comment by ljosberinn** [comment]
While I agree that `sm` or `xl` might not be as descriptive as `laptop`, I'd still be guessing what dimensions that is then, and `sm` to `xl` are well established standards in css frameworks or ui libraries.

- [Tailwind defaults use `sm` through `xl`](https://tailwindcss.com/docs/breakpoints#app) - it lets you configure it, however
- [Bootstrap uses `sm` through `xl`](https://getbootstrap.com/docs/4.5/layout/overview/#responsive-breakpoints)
- [Mateiral UI uses `sm` through `xl`](https://material-ui.com/customization/breakpoints/#breakpoints) - also configurable
- antd seems to be using `sm` through `xl` too, but can't find anything in the docs except `useBreakpoint`

however, e.g.
- [Bulma uses `mobile`, `desktop` etc.](https://bulma.io/documentation/helpers/typography-helpers/#responsive-alignment)

The underlying issue is here mostly that components use static breakpoints in their configurations ootb, e.g. [here](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/theme/src/components/button.ts#L162).
Once we resolve that, we can look into allowing customizing them entirely like MUI and tailwind do.

**Comment by OFranke** [comment]
I see, thank you for that quick response!

Do you already have a plan how those static breakpoints could be decoupled from the components? With some guidance I might find some time to look into that.

One thing that immediately comes to my mind is to make it mandatory to provide styles for each breakpoint for each component once breakpoints are being customized. But that's probably not very desirable as it would kill maintainability and force a kind of "opt out" from styling updates and fixes.
