### ISSUE TITLE
[Drawer] always receives hard-to-fix "position fixed" from Modal

### ISSUE THREAD

**Issue by ljosberinn** [chakra-ui/chakra-ui#2552]
try to click https://codesandbox.io/s/aged-darkness-9sr8b anything outside of the drawer here

two workarounds included here:
- one in app.js using `extendTheme`
- a hackier one in `App` using `Global`

should change [this](https://github.com/chakra-ui/chakra-ui/blob/1fedbc8d788f193e8be3206296a70a8ca7a9362a/packages/theme/src/components/modal.ts#L69) line to

```js
dialogContainer: {
  ...baseStyleDialogContainer(props),
  position: 'initial',
},

**Comment by segunadebayo** [comment]
I'm not sure this a bug given the main intent of a drawer (which is a dialog).

Based on the WAI-ARIA requirements, you shouldn't be able to click surrounding elements behind a modal dialog. Semantically, this isn't an issue.

There are 2 more walkarounds to still achieve the same:
- Use the `Slide` component which doesn't provide any semantic meaning but just slides content from any direction
- Not recommended 🚨:  I've added support for `containerProps` for `DrawerContent` and `ModalContent` so you can pass this override there, rather than from the theme.
