### ISSUE TITLE
Scrollbar hiding causes page flickering

### ISSUE THREAD

**Issue by viennv1709** [chakra-ui/chakra-ui#2592]
Describe the bug
When opening a drawer with `placement="right"` the scrollbar gets hidden causing the page to flicker (including the drawer itself).

If I use `preserveScrollBarGap`, then the page still display a scrollbar, that's what I don't want to see

Expected Behavior

If the current page has a scrollbar, the scrollbar hidden when opening a drawer with no flickering

**Comment by segunadebayo** [comment]
Hi @viennv1709, what version of Chakra UI are you using?

**Comment by viennv1709** [comment]
I'm using version 1.0. It makes me feel uncomfortable

**Comment by viennv1709** [comment]
@segunadebayo You can play with **basic drawer** https://chakra-ui.com/docs/overlay/drawer
It's causing the page to flicker. You can see it with header in the page

**Comment by with-heart** [comment]
When reporting an issue, please use the provided templates and don't delete their contents. The "Bug Report" template asks questions that provide us with specific context around your issue, like the Chakra version you're using, browser versions, operating system version, etc. I'm assuming this is a Windows problem because I can't reproduce on any browser on a Mac (and scrollbars work differently over here), but if you could please provide more specific information about your system and setup like the template asked for originally, it would really help.
