### ISSUE TITLE
Add react-spring integration guide to the docs

### ISSUE THREAD

**Issue by tomdohnal** [chakra-ui/chakra-ui#2690]
# Feature request

## Is your feature request related to a problem? Please describe.

ChakraUI documents  [integration with Framer Motion](https://chakra-ui.com/guides/integrations/with-framer) but lack a guide on integrating with React Spring

## Describe the solution you'd like

Document usage with React Spring. (It's analogical to the usage with Framer Motion.)

## Describe alternatives you've considered

N/A

## Additional context

N/A

If this is something you'd like to add to the docs I'm happy to do it :)

**Comment by dodas** [comment]
Chakra UI itself depends on Framer Motion, that's why it also documents how you can create custom animations with it.
I would consider including another animation library such as React Spring in your website a bad practice and therefore not promote doing so in the docs.

**Comment by with-heart** [comment]
I'd definitely suggest using `framer-motion` both because it's a direct dependency and because it's an excellent library, but I think it'd still be a good idea to document integration with `react-spring`, especially since `react-spring` is still quite a bit more popular than `framer-motion`: https://www.npmtrends.com/react-spring-vs-framer-motion

> If this is something you'd like to add to the docs I'm happy to do it :)

I'll take you up on that offer!

**Comment by segunadebayo** [comment]
I don't think we should do this. I'd recommend migrating to `framer-motion`, even though I understand that can be painful.

@with-heart, because we chose to go with `framer-motion`, we want to careful not to confuse users when they see a guide for `react-spring` in the docs.

If you want to, you can write-up a blog post about this and we can link to it in the docs resources (working on this), but I don't think it should be in the docs itself as a guide.

Thanks for understanding.

**Comment by kaf-lamed-beyt** [comment]
I wrote a short guide on [how you can use react-spring with Chakra](https://www.meje.dev/blog/using-react-spring-with-chakraui)

Take a look and let me know if it helps.
