### ISSUE TITLE
Getting error in Gatsby while using toast

### ISSUE THREAD

**Issue by creotip** [chakra-ui/chakra-ui#2699]
# Bug report

## Describe the bug
Toast throwing error in gatsby, but the toast itself working fine.
I used a simple, copy-paste example from the chakra website:

```
Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.

Previous: []
Incoming: [function () { return function () { return callback(); }; }]
    in AnimatePresence (created by ToastManager)
    in ul (created by ToastManager)
    in ToastManager
``` 

## To reproduce
Created a simple sandbox :
https://codesandbox.io/s/nervous-hill-ig7zt?file=/src/pages/index.js

## Screenshots
![image](https://user-images.githubusercontent.com/3135968/101180210-f4ab8900-3653-11eb-974a-0da0bd2fbdb8.png)

**Comment by TimKolberger** [comment]
This seems to be related to react-hot-reloader. 
See https://github.com/gaearon/react-hot-loader/blob/6032f4255e0268bb794c1e9b8ae5b436400ffbb5/src/reactHotLoader.js#L33-L38

It has an issue reloading the hook useForceUpdate from framer-motion:
See https://github.com/framer/motion/blob/cfd5098a44f97384d855bb269a23a5fba75ae4f9/src/utils/use-force-update.ts#L11

The error should not be present in a production build.

chakra-ui as a similar hook - but the error is just complaining about framer-motion and the implementation is fine IMO.

I am closing this, because it is not an issue in chakra-ui.
