### ISSUE TITLE
Input border radius not overridable via baseStyle

### ISSUE THREAD

**Issue by loganhuskins** [chakra-ui/chakra-ui#2733]
# 🐛 Bug report

I am unable to override `Input`'s border radius via `theme.compontnts.Input.baseStyle.borderRadius`. However, I am able to override it by passing the `borderRadius` prop to the component itself.

## 💥 Steps to reproduce

1. Create an `Input`.
2. Create a Theme object and pass it to the `Chakra` provider.
3. Assign `Theme.components.Button.baseStyle.borderRadius` to 0.
4. Observe no change
5. Remove the assignment from step 3.
6. Add the `borderRadius` prop to `Button` and pass it 0.
7. Observer change

## 💻 Link to reproduction

https://codesandbox.io/s/blue-dream-bqwon?file=/src/App.js

## 🧐 Expected behavior

I expect to be able to set the `borderRadius` for an `Input` at the theme level.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       1.0.2     |
| Browser          |       Firefox 83     |
| Operating System |       Windows 10     |

## 📝 Additional information

I am able to set `borderRadius` for `Button` in the theme and it works as expected.

**Comment by dodas** [comment]
Hi @loganhuskins.

Each component has different styling needs and therefore structure of their theme varies.
Before writing any code, I recommend checking out the [Chakra's theme source](https://github.com/chakra-ui/chakra-ui/tree/develop/packages/theme/src/components) for any component and you will surely quickly find out how you can override it.

The `Input` component has different border radius set depending on its `size` and because of that, you will need to override the `sizes` object. Also, `Input` has 2 themable parts: `field` and `addon`, so you will need to put your overrides further one level deeper:

```ts
const customTheme = extendTheme({
  components: {
    Input: {
      sizes: {
        md: {
          field: {
            borderRadius: 0,
          },
          addon: {
            borderRadius: 0,
          }
        }
      }
    }
  }
});
```

Example sandbox: https://codesandbox.io/s/elated-noyce-nkyrz?file=/src/theme/index.ts

**Comment by loganhuskins** [comment]
This is great information and solves my problem. Thanks!

**Comment by renchris** [comment]
Hi @dodas. I am trying to do the same except for the bg prop. I'm having difficulty figuring out where/what level to put bg in.

`    Input: {
      baseStyle: {
        field: {
          bg: 'black',
        },
      },
      sizes: {
        md: {
          field: {
            borderRadius: 4,
            bg: 'black',
          },
          addon: {
            bg: 'black',
          },
        },
      },
    },`

**Comment by delanebob** [comment]
@renchris I had a very similar issue to this but with the Checkbox and changing the default border on the checkbox wasn't working. Based on what @dodas mentioned above I went to the [default theme list in GitHub](https://github.com/chakra-ui/chakra-ui/tree/main/packages/theme/src/components) to find the component that I was looking to style.

[Based on this documentation](https://chakra-ui.com/docs/theming/component-style#styling-multipart-components) it advises to add a parts array at the top of your overwrites. This list should be able to be found in each default theme in the link above to see if it's a multipart theme.

So I would advise that you do this and apply the background to all the the parts, and remove one by one to see which it's supposed to be added too. In my case it had to be applied to the `container` part and not the `checkbox`. I don't think the docs on the website doesn't make this clear.

**Comment by JClackett** [comment]
Hi, is there some reason the baseStyle can't override the size variants? I would have thought adding borderRadius to the field baseStyle would set it for all sizes and variants? kind of annoying to have to add default styles to every single size

**Comment by with-heart** [comment]
@JClackett If it worked that'd way, it'd break the whole theming system! I don't think we've documented this very well, but the priority for styles is:

`__css` < `baseStyle` < `variant` < `size` < props < `sx`

This allows for a cascading system of styles, where we use `__css` internally to style components with the lowest priority and then layer the other styles on top.

`baseStyle` has lower priority than `variant`/`size` because if it was higher, then the other two become far less useful as you couldn't customize any of the props they were using. You'd have to manually unset the props from the base and then add your own on top if you wanted them to be different, which imo would be far more frustrating than the current duplication.

The base style essentially just set defaults, and then variants and sizes are customizations on top of that. I can see how that could cause pain in some situations, but not sure how to change that around without breaking the whole model/causing larger pains.

**Comment by JClackett** [comment]
@with-heart Thanks for the response! makes complete sense to me now, thanks for taking the time to explain ❤️
