### ISSUE TITLE
Export Text as Txt to help with automatic imports

### ISSUE THREAD

**Issue by tomhicks** [chakra-ui/chakra-ui#2824]
# 🚀 Feature request

Export `Text` as `Txt` to aid with automatic imports

## 🧱 Problem Statement / Justification

When developing in Chakra with TypeScript, most components automatically import very well. `Text` is the obvious exception, because it is a browser global. This also breaks the TypeScript server's attempts to import all components automatically, as well as various refactoring plugins in VSCode (and I'm sure others).

## ✅ Proposed solution or API

`export const Txt = Text` - just this. Keep the `Text` export but mark it as deprecated.

## ↩️ Alternatives

Somehow getting Chakra to override the browser global types such that TS doesn't think `window.Text` is a thing any more.

## 📝 Additional Information

None, sorry. I bet I'm not the only one with this issue though!

**Comment by segunadebayo** [comment]
I understand and appreciate this, but don't think it's a major issue. I'd prefer if we leave Text as is.

VSCode typically adds the auto-import IntelliSense for `Text` as the second option and I think most users can live with that.

Let's hold off on this for now. If it becomes a pressing issue over time, we'll reconsider it.

Thank you, buddy.

**Comment by tomhicks** [comment]
Thanks for looking at this.

The issue isn't so much the position of the import in the list, but that as it's a browser global it's often ignored as a thing that needs importing.

For instance, "Add all missing imports" never works, and to get Intellisense imports to work you have to explicitly invoke it, whereas the rest of ChakraUI (aside from Image which has the same issue) is automatically picked up.

Try making a file that exports Txt in a local project and compare the DX!!

**Comment by capaj** [comment]
> If it becomes a pressing issue over time, we'll reconsider it.

@segunadebayo obviously this will never become a "pressing issue" because people are kinda ok spending time on just manually writing those imports manually or hunting the import  generation down in the menus.

I think this should be done and the least we can do is to get a wider audience to comment on this. How about posting a twitter poll about this on the official twitter account?
https://twitter.com/chakra_ui

BTW this is the tagline of chakra:
![image](https://user-images.githubusercontent.com/1305378/192213505-ba270b1b-6b99-45b8-829b-a90ac6240f64.png)

Keeping the export as it is goes directly against this, because it introduces a lot of friction for anyone using vscode and typescript.
You know how many times I've seen this in the past few weeks? I forget things easily as I multitask on many projects so it often breaks my flow.
![image](https://user-images.githubusercontent.com/1305378/192214990-cd740b6d-987c-433d-b197-696e753691e1.png)

 I rely on typescript to tell me when something is broken, but ATM typescript cannot detect this as an error unfortunatelly.

Please at least open the poll on twitter, ideally reopen this. Chakra should be about speedy DX. We cannot remove `Text` from the global, so let's avoid it. I know `Txt` looks kinda weird considering all other components are fully worded out, but 

![its a trap](https://media.giphy.com/media/3ornka9rAaKRA2Rkac/giphy.gif).

**Comment by tomhicks** [comment]
It does detect the error but it's still a solid 10 to 30 second drag when this happens.

And it would literally be fixed instantly by `export const Txt = Text`

**Comment by lucasrabiec** [comment]
I also bump this proposal. It is a little bit annoying to import `Text` and `Image` over and over manually. It's just a little thing but exporting `Text` as `Txt` and `Image` as `Img` would be helpful.
