### ISSUE TITLE
Dark Mode not working on Select component with <optgroup>

### ISSUE THREAD

**Issue by remjx** [chakra-ui/chakra-ui#2853]
# 🐛 Bug report

Background and Text of of Select popup is white when using Dark Mode with `Select` `optgroup`
![image](https://user-images.githubusercontent.com/35121685/102798014-80285800-437e-11eb-9d5a-f6ed3a2b8121.png)
![image](https://user-images.githubusercontent.com/35121685/102798137-ad750600-437e-11eb-995e-f45372cc99a3.png)

## 💥 Steps to reproduce

With dark mode enabled,

```
<Select>
      <optgroup label="Group">
          <option value="test1">Test1</option>
          <option value="test2">Test2</option>
      </optgroup>
</Select>
```

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-ui-dark-mode-select-optgroup-issue-8dxbw?file=/src/App.tsx

## 🧐 Expected behavior

Background should be dark, text should be white

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.03      |
| Browser          |     Chrome  87.0.4280.88       |
| Operating System |      Windows 10      |

**Comment by remjx** [comment]
Bumping this so it doesn't get auto-closed

**Comment by remjx** [comment]
bump

**Comment by remjx** [comment]
bumperoo

**Comment by with-heart** [comment]
Hi @remjx, sorry this has taken so long for anyone to address. Glad you put the effort into keeping it open.

Can verify that this is an issue on Chrome with Windows. We specifically include a style for `> option` in the `Select` theme: https://github.com/chakra-ui/chakra-ui/blob/e9e5e3af8f2b4eaa7dd34eaaa8cc1327e0131971/packages/theme/src/components/select.ts#L13-L15

If we also cover `> optgroup` with this style, it will resolve this issue. 

Honestly I wasn't even aware `optgroup` was a thing until I saw this issue, which is kind of blowing my mind a bit because it's quite rare that I run into native elements I don't know at this point.

**Comment by mtergel** [comment]
@with-heart 

issue still exists on Firefox (91.0.1 M1). Tested on the official website
![image](https://user-images.githubusercontent.com/61941297/130409174-ea6f0a05-f018-46a6-8dec-90ed2c6be06b.png)

**Comment by filliph** [comment]
@with-heart could we please get a working fix for this? Thanks!

**Comment by with-heart** [comment]
@filliph Yeah sure! You're welcome to open a PR with a working fix!
