### ISSUE TITLE
Image downloaded two times

### ISSUE THREAD

**Issue by ajitsonlion** [chakra-ui/chakra-ui#2899]
# 🐛 Bug report

I am trying to use Chakra image in project, and I notice that image is being downloaded two times.
When I try to change around images in the chakra docs 
https://chakra-ui.com/docs/data-display/image
there also image is downloaded two times.
![image](https://user-images.githubusercontent.com/7666593/103203280-d81e0c00-48f4-11eb-8663-c90e0042cb1b.png)

## 💥 Steps to reproduce

1. Goto https://chakra-ui.com/docs/data-display/image
2. Use any one of the image examples, change the URL to some new image.
3. In network tab the image is fetch two times. (I have cache disable checked )

Minimal code sandbox example
https://codesandbox.io/s/cocky-kare-9kl5g?file=/src/index.tsx

## 🧐 Expected behavior

Image should be fetched only one time.

## 🧭 Possible Solution

> Not compulsory, but suggesting a fix would be great!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    1.04        |
| Browser          |    Chrome 87   |
| Operating System |        MacOS    |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by jmiazga** [comment]
I am only able to see this in Chrome. It doesn't seem to be an issue in Firefox or Safari.

**Comment by vamshi9666** [comment]
i am seeing this only when i use exact code in docs. Could you post a snippet with a absolute image url. (from any cdn preferably).

**Comment by vamshi9666** [comment]
i think example code in docs is not a reliable one, caz its using bit.ly as redirection.

**Comment by ajitsonlion** [comment]
Hello
The one in codesandbox example is not bit.ly
https://codesandbox.io/s/cocky-kare-9kl5g?file=/src/index.tsx
![image](https://user-images.githubusercontent.com/7666593/103465823-8c79c100-4d3f-11eb-9993-a1f8c080e7bf.png)

**Comment by with-heart** [comment]
I don't think is actually an issue. 

Working from this CodeSandbox: https://codesandbox.io/s/affectionate-sammet-otcl9?file=/src/App.tsx

If we open the direct URL for that sandbox (https://otcl9.csb.app/) and use the network tools, we can see what's happening with this image:

![image](https://user-images.githubusercontent.com/1954752/105611630-68c8fa00-5d84-11eb-9f49-bb0ade6fa433.png)

The first 4 entries are the first render initiated by `use-image.js`, where it follows the redirect chain until it reaches the `200` entry which contains the actual image binary, and the last 4 entries initiated by `react-dom.development.js`. This happens twice because `StrictMode`—which is enabled in `development` by `create-react-app`—invokes certain things twice, as explained on the [Strict Mode docs page](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects):

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:
>
> - Class component constructor, render, and shouldComponentUpdate methods
> - Class component static getDerivedStateFromProps method
> - Function component bodies
> - State updater functions (the first argument to setState)
> - Functions passed to useState, useMemo, or useReducer

Looking at the production docs page for `Image`, we can see that this series of redirects only occurs once: 
![image](https://user-images.githubusercontent.com/1954752/105611716-e0972480-5d84-11eb-85c0-6a2b312b2981.png)

**Comment by OmarZeidan** [comment]
So you guys still insisting that this is not an issue :) 

@with-heart checking the url you provided, its actually coming 4 times, love to check? here you go

![image](https://user-images.githubusercontent.com/3344403/117045397-c075ea80-ad0f-11eb-9185-866c218bddb2.png)

**Comment by OmarZeidan** [comment]
So you guys insisting that its not an issue 👍🏼 

@with-heart using the link your provided, its being fetched more than 2 times now. Love to see, here you go

And twice from the codesanbox; check it out.
<img width="1434" alt="Screenshot 2021-05-04 at 19 38 16" src="https://user-images.githubusercontent.com/3344403/117045930-5f9ae200-ad10-11eb-8869-7323232b65bb.png">

**Comment by with-heart** [comment]
Yes, that's expected. Read my last post which explains why.

**Comment by OmarZeidan** [comment]
I did, @with-heart but I also removed the strict mode and actually one of my projects not using create-react-app at all.

But still, these are extra HTTP request(s) which means money sometimes when a lot of users visiting your website.

Thanks 🌹

**Comment by mislavmiocevic** [comment]
@with-heart I created this issue because for me it is happening with the fallback prop.
https://github.com/chakra-ui/chakra-ui/issues/5285
