### ISSUE TITLE
Request to add AppBar component

### ISSUE THREAD

**Issue by lednhatkhanh** [chakra-ui/chakra-ui#291]
**Is your feature request related to a problem? Please describe.**

An Appbar is a commonly used components in webapp and it would be great if chakra-ui can provide that component

**Describe the solution you'd like**

Maybe something like [tailwind header example](https://tailwindcss.com/components/navigation/#responsive-header)?

**Comment by jeanbauer** [comment]
Hey @lednhatkhanh and @segunadebayo 

I'm currently working exactly on that right now. This is how it looks:

<img width="1280" alt="header" src="https://user-images.githubusercontent.com/4689228/70672327-29724380-1c7f-11ea-8692-5d6c4ad2232e.png">

I made it using a Box + Flex approach.
The style is the same as Tailwind's Header just following the current theme running on Chakra.

If you think that could be a PR let me know and I'll be happy to make it. :)

**Comment by lednhatkhanh** [comment]
Wow, that's really nice, it would be great if you can make a PR for that.

**Comment by jeanbauer** [comment]
The problem with adding a Header component to Chakra is that most Headers doesn't have the same structure. Think about the Avatar component for example:

![Screen Shot 2019-12-12 at 09 22 25](https://user-images.githubusercontent.com/4689228/70695013-1a13ea00-1cc1-11ea-9cd6-e2f94dc5c2a9.png)

Most of the websites and libraries design the same component, it is a common thing, right?
Now try to find a Header component in all the popular UI libraries, kinda hard. 

Probably because headers can have lots of variations. Have to deal with all these variations from the library side would take a lot of effort, let's see how we could design the API for this example of mine:

```
import { header } from '@chakra-ui/core'

<Header
   <LeftsideItems aling='start'>
      <YourLinkComponent to={...}>LogoSVG<YourLinkComponent/>
      <YourLinkComponent to={...}>Docs<YourLinkComponent/>
      <YourLinkComponent to={...}>Example<YourLinkComponent/>
      <YourLinkComponent to={...}>Blog<YourLinkComponent/>
   <LeftsideItems/>
   <RightsideItems align='end'>
       <YourButtonComponent onClick={...}>Download<YourButtonComponent/>
   <RightsideItems/>
 /> 
```

not that good, right? because you would still have to write your own **separator** component, such as this _LeftsideItems_.

I think we still have to answer some questions to implement this. 
- Do we want to be as flexible as possible? 
- What would be the cost of it? 
- How developers wants to use the "Header" API?

But in the meantime, I'll upload this Header of mine in some gist. :)

**Comment by segunadebayo** [comment]
I agree @jeanbauer. There are so many variations of this Header API and I don't think we'll add it to the library.

This feels like something we can add to docs as "Common Recipes" or "Component Showcase" so other users can just copy the code and use it.

**Comment by jeanbauer** [comment]
Perfect @segunadebayo! Once I have this finished I'll add there. Thanks :)

**Comment by jeanbauer** [comment]
PR: https://github.com/chakra-ui/chakra-ui/pull/293

**Comment by utkarshdubey** [comment]
Has this already been added to the Common Recipes section or something?

**Comment by utkarshdubey** [comment]
@jeanbauer

**Comment by jeanbauer** [comment]
@utkarshdubey yes

https://chakra-ui.com/recipes#responsive-header-with-chakra-ui
updated source: https://codesandbox.io/s/chakra-ui-header-sbsh5?fontsize=14&hidenavigation=1&theme=dark&file=/src/header.js

_note: this is just some example code, could be better :D_

**Comment by utkarshdubey** [comment]
Nice work.

**Comment by daveamol** [comment]
Somehow the old link doesn't work and it needs latest react and react-dom to work. Here is it with changes
https://codesandbox.io/s/chakra-ui-header-forked-ckfb60?file=/src/header.js

Also any idea why the recipes does not have this example anymore ?
