### ISSUE TITLE
[Button] baseStyle _hover background property is not working

### ISSUE THREAD

**Issue by bawahakim** [chakra-ui/chakra-ui#2958]
Thanks for the wonderful library @segunadebayo, probably one of the most flexible, plug & play library I've ever used :)

# 🐛 Bug report

When adding baseStyle to the `Button` component, the `_hover`, `_focus` and `_active` properties are not handling `background` or `bg`. What I would like, is to pass my own function to calculate the background color for different states.

## 💥 Steps to reproduce
```
const theme = extendTheme({
  components: {
    Button: {
      variants: {
        blue: {
          _hover: {
            bg: 'blue.500',
          },
          _active: { bg: 'blue.700' },
        },
      },
      baseStyle: {
        _hover: { background: 'blue.500' },
        _active: { background: 'blue.700', textDecoration: 'underline' },
        w: '15rem',
        h: '2.5rem',
      },
    },
  },
});
```
Moreover, the `textDecoration` property works, and the `_hover` using a variant works. I also do not see any `hover` style with the inspector for a button without a variant.

## 🧐 Expected behavior

A default button should use the `background` property when hovered.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     latest       |
| Browser          |       Firefox@latest     |
| Operating System |       Mac Os      |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by dodas** [comment]
Hey @bawahakim.

Background of the `Button` varies depending on the `variant` used.
You need to override the `bg` / `background`  property on the `variant` you are using.
[The default `variant` for `Button` is `solid` and color scheme is `gray`.](https://github.com/chakra-ui/chakra-ui/blob/2df55388076f92b0c06a7d169f55052c9475c331/packages/theme/src/components/button.ts#L188)

So you can override it like this:
```ts
const theme = extendTheme({
    components: {
      Button: {
        variants: {
          solid({ colorScheme }) {
            return {
              _hover: {
                bg: `${colorScheme}.500`,
              },
              _active: { bg: `${colorScheme}.700` },
            }
          },
        },
      },
    },
});
```

If you want always `blue`, you could use an object literal instead of a function, but this way you have it responsive to all color schemes.

Hope that helps. Cheers!

**Comment by bawahakim** [comment]
Thanks @dodas ! So the `solid` variant default `_hover` properties are overriding the `baseStyle` ones.
