### ISSUE TITLE
[Editable] does not work with conditional rendering

### ISSUE THREAD

**Issue by HadiSDev** [chakra-ui/chakra-ui#2975]
# 🐛 Bug report

> Conditional rendering does not work for editable input

## 💻 Link to reproduction

https://codesandbox.io/s/sparkling-violet-k276d?file=/src/App.tsx

## 🧐 Expected behavior

It should show the firstname "Chakra" and not "N/A"

**Comment by santialbo** [comment]
This has nothing to do with Editable nor Chakra, the same happens with vanilla react. See this codesandbox.
https://codesandbox.io/s/funny-rain-ft81k

The problem is in your react logic with `setState` and `useEffect`.
By setting the defaultValue you are setting the initial value for the input which is already set once the useEffect runs.
