### ISSUE TITLE
useBreakpointValue does not work with `px` values

### ISSUE THREAD

**Issue by kkatsuba** [chakra-ui/chakra-ui#3042]
# 🐛 Bug report

`useBreakpointValue` totally not working 

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/blissful-mayer-3kwdq?file=/src/index.ts
2. Resize result view a bit.
3. As you can see it is blinking and console full with errors.
```log
index.js:27 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at Herna (https://3kwdq.codesandbox.io/src/App.tsx:33:74)
    at div
    at Styled(div) (https://3kwdq.csb.app/node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:87:44)
    at ColorModeProvider (https://3kwdq.csb.app/node_modules/@chakra-ui/color-mode/dist/esm/color-mode-provider.js:41:15)
    at ThemeProvider (https://3kwdq.csb.app/node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:114:42)
    at ChakraProvider (https://3kwdq.csb.app/node_modules/@chakra-ui/react/dist/esm/chakra-provider.js:15:18)
    at App
```

## 🧐 Expected behavior

IMO it should not make such things. But it just my opinion 

## 🌍 System information

| Software         | Version(s) |
| ---------------  | ---------- |
| Chakra UI        |      1.1.4    |

## 📝 Additional information

Also I found a `"fix"` https://github.com/chakra-ui/chakra-ui/issues/2990
but in version 1.1.2 `useBreakpointValue`  works fine (1.1.3. totally not working because it has wrong dependencies)

**Comment by cschroeter** [comment]
#2990 was fixed 6 days ago and is part of 1.14

**Comment by kkatsuba** [comment]
@cschroeter as u can see `Additional information` from description it is noticed and it broke useBreakpointValue

**Comment by cschroeter** [comment]
After looking into the issue I noticed that this bug only occures when using `px` values.
If you are using relative units like `em` or `rem` it just works fine.

**Comment by ivanyeoh** [comment]
Another workaround for using `px`: specifying all the breakpoints.
i.e. `const breakpoints = createBreakpoints({
  sm: "320px",
  md: "768px",
  lg: "960px",
  xl: "1200px",
  "2xl": "1200px",
})`

Because if we don't specify e.g. 2xl, the value will be the default 96em and be `parseInt` and cause the incorrect sorting order https://github.com/chakra-ui/chakra-ui/commit/5db7d9a31bd5c91c617f48a2e31cf602fd2cdd5b#diff-5ace375c5eeadc6f170d8314834a1ddbc0dca440c3c97ee900fb60e95edd6024R9

**Comment by dodas** [comment]
I think the root of the problem here is that `extendTheme` merges default breakpoints with user provided breakpoints. Regardless of what units you use, the breakpoints will be merged.
In the docs we explicitly note that you should not mix units:
<img width="759" alt="Screenshot 2021-02-11 at 00 39 41" src="https://user-images.githubusercontent.com/14360171/107587758-a93cca80-6c02-11eb-9f4b-b7eae79b3673.png">

..But we do so in our own utility. I consider this a bug.

The question is whether we can fix this without considering it a breaking change.

cc @chakra-ui/react-team
