### ISSUE TITLE
Modal with size="full" breaks the overflow behavior

### ISSUE THREAD

**Issue by neilnahid** [chakra-ui/chakra-ui#3062]
# 🐛 Bug report
Modal component's overflow-y behavior breaks if size is set to "full"

## 💥 Steps to reproduce

> Clear and concise reproduction steps are important for us to be able to triage
> your issue in a timely manner

1. use the Modal component with the standard layout(ModalContent,Body,Footer)
2. set size="full"
3. render a very long content inside <ModalBody>
4. Add overlay
4. See error/bug

## 💻 Link to reproduction
https://codesandbox.io/s/floral-brook-hh3dc?file=/src/App.js
## 🧐 Expected behavior

Overflow-y should work properly with background color properly covering all content inside <Modal>

## 🧭 Possible Solution

set the modalcontent's height to height:min-content instead of height:100vh when size prop is set to "full"

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.1.2         |
| Browser          |      chrome      |
| Operating System |     Ubuntu 20.10       |

## 📝 Additional information

- Screenshots or code
- Notes or link to ideas

**Comment by henryboisdequin** [comment]
When I run it, I get no errors

**Comment by Barrod-code** [comment]
I've stumbled upon the same issue. @neilnahid 's codesandbox already has his fix applied. [Here](https://codesandbox.io/s/sharp-resonance-efe3n?file=/src/App.js)'s one without it and some testing options. Current default settings with height:100vh work for scrollingBeaviour="inside". If instead you set scrollBeahviour="outside" (Chakra-UI default), the modal box with height:100vh is too small for the long content, which is fixed by @neilnahid modification.

As far as I can see, height=min-content works with both scroll behaviours, while height=100vh is broken for outside scrolling.
