### ISSUE TITLE
Tooltip does not show in correct position

### ISSUE THREAD

**Issue by mingbackmountain** [chakra-ui/chakra-ui#3063]
I recently tried to use a tooltip, however when using it seem to produce incorrect style and position

like this
<img width="685" alt="Screen Shot 2564-01-15 at 12 35 28" src="https://user-images.githubusercontent.com/25886138/104685830-8bc52f80-572e-11eb-9e43-fd71d1d9f49c.png">

Here is my current code 
<img width="900" alt="Screen Shot 2564-01-15 at 12 38 47" src="https://user-images.githubusercontent.com/25886138/104685927-bca56480-572e-11eb-854d-f8ca3ddcb777.png">

**Comment by santialbo** [comment]
It's very difficult to help without a codesandbox where the issue is isolated and can be reproduced.
This issue is likely to be caused by something outside of the code snippet you just pasted (as an image).

**Comment by with-heart** [comment]
If the icons you're using are from `react-icons`, there's a known issue where they don't forward refs, which breaks our `Tooltip` implementation. Try wrapping the icons in `Box`.

**Comment by seangenabe** [comment]
Nice catch @with-heart, that fixed it for me. Although I also needed to use `shouldWrapChildren` on the other tooltips that didn't have the react-icons.

Is there somewhere I can go to find out more about this issue?

**Comment by with-heart** [comment]
@seangenabe You would need `shouldWrapChildren` for anything that doesn't forward refs. Not sure how your other icons are built, but if they're not wrapped in `forwardRef` or created using Chakra's `createIcon`, there's a good chance that's the issue.

Going to close this since we haven't heard back from the original poster, but feel free to reply if you have more questions!

**Comment by brixbimboavengoza** [comment]
You can just wrap it inside <Flex>
