### ISSUE TITLE
Menu does not work with nextjs => preact

### ISSUE THREAD

**Issue by approached** [chakra-ui/chakra-ui#3099]
# 🐛 Bug report

The Menu does not work with nextjs => preact.
After i load the page, the browser is just freezing. And app does not work. I must kill the tab in my browser.

## 💥 Steps to reproduce

I just copied the first example https://chakra-ui.com/docs/overlay/menu#import and put it on my app.

## 💻 Link to reproduction

Nextjs / Preact Template: https://github.com/vercel/next.js/tree/canary/examples/using-preact

**Comment by wbercx** [comment]
Popover also goes into infinite loop using Preact. I was playing around with it in [this sandbox](https://codesandbox.io/s/affectionate-dream-yw6ql).

I think it's any component that uses Popper for positioning, but I have yet to figure out why despite several attempts.  I really struggle with the stacktraces that are minified for non-humans.

If I recall correctly half of the stacktrace just bounces between `$` and `m` repeatedly, and always ends up in the `usePopper` hook provided by this lib, I just can't work out know _why_. I really struggle to work out the triggers of renders in React and likeminded libs sometimes.

@marvinhagemeister Sorry for dropping you in here, but do you by chance have any tips for debugging a scenario where Preact goes into an infinite loop?

**Comment by marvinhagemeister** [comment]
@wbercx In general infinite loops are caused by circular state updates. These are caused by a Child updating a Parent, which updates the Child again, which causes the Child to update the Parent again and thereby completing the loop.

```txt
          render
  Parent --------> Child
    |                |
    ^----------------|
        schedules
         update
```
       
React has some built in mechanics to hide that from the developer and try to repeatedly render until state references remain stable or a threshold has been reached. When the threshold is reached it will print a warning. Since we don't see a warning here, but there are multiple updates of the same component, it seems that it works out just fine.

I spent a bit of time to check what is causing the loop it in `chakra-ui` but rather than a single source it seems to be caused by many things playing together. I'm seeing some places where `refs` on HTML elements are used to trigger state updates and there are some places where `useEffect` is called without any dependency arguments and calls some sort of `forceUpdate` on the provider. Those should be a good place to start looking.

**Comment by wbercx** [comment]
@marvinhagemeister Thanks for taking the time! I will have another look at it.

**Comment by wbercx** [comment]
Still an issue. See also #3384

**Comment by segunadebayo** [comment]
Is this still an issue with the latest release @approached?

**Comment by approached** [comment]
I tested with the version: `1.4.1`. It works fine.

Thank you.
