### ISSUE TITLE
Expose change log in the website

### ISSUE THREAD

**Issue by bartekczyz** [chakra-ui/chakra-ui#3143]
First of all, thank you `chakra-ui` community for this awesome library! 🤝 

# 🚀 Feature request

Combine change logs from all packages and present them in the website

## 🧱 Problem Statement / Justification

Currently to see what actually had changed, you have to click through multiple "releases" pages on GitHub. Most of the releases are "dependency update" which makes reading the actual changes quite frustrating.

## ✅ Proposed solution or API

It would be great to have a "changelog" section on the website to quickly see what were the lates changes in the components

**Comment by DecliningLotus** [comment]
Currently, the best changelog is via the announcements tab within the Discord server imo. I think crossposting what's already there onsite would reach a lot more users.

The [blog](https://chakra-ui.com/blog) section isn't really being used and I'm not sure what other purposes you guys have in store for that - especially when there is a guides and resources section that competes with it. Perhaps that would be the best place to post updates since the infrastructure is already setup and built?

**Comment by with-heart** [comment]
I've been doing some work for #2739 which will lead to a PR for [`changesets`](https://github.com/atlassian/changesets) which will allow us condense and customize our changelog and what's posted to our Releases page.

**Comment by DecliningLotus** [comment]
@with-heart, personally I find the PR updates less readable since it has all the "update dependencies" commits.

It might be useful if it were talking about external dependencies. But otherwise, it feels like a lot of noise and bloat that makes it harder to find the changes that _actually_ matter.

**Comment by with-heart** [comment]
Definitely agree, which is why the global changelog work is being done to produce something more customized that's both useful for and friendly towards users.
