### ISSUE TITLE
Checkbox and Switch setValue broken with React Hook Form

### ISSUE THREAD

**Issue by jcognard-actinvision** [chakra-ui/chakra-ui#3190]
# 🐛 Bug report

Boolean inputs (like Checkbox and Switch) used with React Hook Form don't update when setValue is called.

## 💻 Link to reproduction

[CodeSandbox example](https://codesandbox.io/s/chakra-ui-react-hook-form-forked-93b42?file=/src/HookForm.js)

> `name` field updates whereas `subscribe` checkbox doesn’t.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        | 1.1.6           |
| React Hook Form        | 6.14.2           |
| Browser          | Chrome 88.0.4324.104           |
| Operating System | Windows 10           |

**Comment by TimKolberger** [comment]
The components Checkbox and Switch control the state of the DOM Element (like the NumberInput). 

Kindly follow the [react-hook-form docs on integrating it with component libraries](https://react-hook-form.com/get-started#IntegratingwithUIlibraries)

**Comment by jcognard-actinvision** [comment]
Hi @TimKolberger and thanks for your answer.
I’m sorry but while I understand the way NumberInput works I can’t figure out what’s the problem with my previous codesandbox.

When I set `defaultValues` on form initialization it works with Checkbox (see https://codesandbox.io/s/chakra-ui-react-hook-form-forked-b74q1?file=/src/HookForm.js:425-452) but not when i call `setValue("subscribe", true)`

**Comment by with-heart** [comment]
Without `defaultValue` or `value`, Chakra assumes the components are uncontrolled and gives them a default value. Since they're uncontrolled, this also means changing the `value` doesn't do anything.

You'd need to either use the `defaultValue` prop to set the default value if you're using uncontrolled components: https://codesandbox.io/s/chakra-ui-react-hook-form-forked-bmyir

Or you'd need to use `Controller` as shown in the docs Tim linked to in order to pass `value` and `onChange` to them if you want to use them as controlled components that you can manipulate using `setValue`.

See https://reactjs.org/docs/uncontrolled-components.html for more information about controlled vs. uncontrolled.
