### ISSUE TITLE
Changing order of tabs causes selected tab to not match the rendered TabPanel

### ISSUE THREAD

**Issue by stefanbugge** [chakra-ui/chakra-ui#3320]
Thank you for a wonderful library!

# 🐛 Bug report

I am using a controlled Tabs component where I loop over an array to render the individual `Tab` components. The tabs array is ordered based on some property of the array items and the order may change. When the array changes due to a reordering the selected `Tab` is no longer in sync with the selected `TabPanel`.

## 💥 Steps to reproduce

1. Create a controlled Tabs component 
2. Model tabs as an array and render in a loop
3. Change order of the items in the array
4. See selected `Tab` and `TabPanel` out of sync.

## 💻 Link to reproduction

https://codesandbox.io/s/controlled-tabs--ordered-tabs-ompqp?file=/src/App.tsx

## 🧐 Expected behavior

Selected `Tab` and `TabPanel` are in sync.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.3.2         |
| Browser          |   88         |
| Operating System |    macOS 11.2        |

**Comment by with-heart** [comment]
Oh boy. I likely just built something at work that suffers from this same issue 😬 

Appears to be caused by a disconnect between `index` coming from `useDescendant` and the `index` coming from `validChildren.map` inside `useTabPanels`. https://github.com/chakra-ui/chakra-ui/blob/500b1eea0876909b670c103ffa354b2b77ff024f/packages/tabs/src/use-tabs.ts#L361-L363

These `index` values don't correspond once the order of items changes.

**Comment by stefanbugge** [comment]
Replying in order to keep issue open.

**Comment by mamoyko** [comment]
is it resolve? mine not woking

**Comment by lifejuggler** [comment]
neither is mine :(
