### ISSUE TITLE
Request for smaller bundle size, or ability to import components piecemeal

### ISSUE THREAD

**Issue by jfhector** [chakra-ui/chakra-ui#338]
First, well done on Chakra UI. I haven't tested it thoroughly yet, but it looks darn good! (Looking at it with the eyes of a web accessibility specialist).

**Is your feature request related to a problem? Please describe.**
I was about to recommend using Chakra UI to my colleagues. Then I checked the bundle size. It looks like the chakra-ui/core needs to be important, which is [100kb of gzipped](https://bundlephobia.com/result?p=@chakra-ui/core@0.5.2). (I imagine that most of it is JavaScript, so real performance implications). Then there's an additional 12kb worth of dependencies.

**Describe the solution you'd like**
Would it be possible to either:
* Reduce the size of the core
* Let developers npm install components piecemeal? (It's unlikely I'll use Chakra UI for all my components; but I'd be tempted to use it for some of them, if the bundle wasn't so big).

**Comment by jfhector** [comment]
I imagine that tree shacking would reduce the sizes quite a lot. But how much?

It'd be good to have a sense of the performance cost of using Chakra-UI for just some components.

**Comment by egoist** [comment]
> I imagine that tree shacking would reduce the sizes quite a lot. But how much?

See https://bundlephobia.com/result?p=@chakra-ui/core@0.5.2

**Comment by segunadebayo** [comment]
Hi @jfhector,

Thanks for bringing this up.

We're already looking into this for the next release. Each component will be its own package and core will still remain as is (mostly re-export all components).

**Comment by ianstormtaylor** [comment]
@segunadebayo do you know when the next release will be? Just curious as I'm evaluating Chakra right now and it seems like the next release will contain a lot of nice improvements, but not sure how long it will take.

**Comment by segunadebayo** [comment]
I'm currently looking at the mid-February for the next release

**Comment by fr3fou** [comment]
any news?

**Comment by tioluwani94** [comment]
Hi @fr3fou, we are working on this and we'll have this with the next major release in March

**Comment by pspeter3** [comment]
Is it possible to also reduce the depth of the output tree? I wonder if using hooks would reduce the number of context consumers.

**Comment by fr3fou** [comment]
was this released?

**Comment by mhinostroza** [comment]
was this released?

**Comment by samwightt** [comment]
Has this been released yet?

**Comment by with-heart** [comment]
Hi all. We're on `1.0.0-rc.0`, getting very close to the full `1.0.0` release. See https://next.chakra-ui.com/ for more info!

**Comment by fimbault** [comment]
Not sure how this relates to v1.0, but is there more information on bundle size for production environments? Thanks.

**Comment by ljosberinn** [comment]
@fimbault since everything treeshakes, its dependant on what you use

**Comment by fimbault** [comment]
@ljosberinn ok makes sense, nice. An update in the documentation would be great.

**Comment by redbar0n** [comment]
@fimbault For individual component gzip sizes, see the Exports Analysis at the bottom of [https://bundlephobia.com/result?p=@chakra-ui/react@1.0.3](https://bundlephobia.com/result?p=@chakra-ui/react@1.0.3).

I'm still a bit baffled how the single gzipped **Drawer** component here is listed as **27.4 kB**?
Considering, for comparison, that the entire **Relay** library takes [**36.4 kB**](https://bundlephobia.com/result?p=react-relay@10.1.1), and **Apollo Client** is now down to only [**15.6 kB**](https://bundlephobia.com/result?p=apollo-client@2.6.10). I was considering dropping either of those libraries in favor of **React Query** since it is only [**7.2 kB**](https://bundlephobia.com/result?p=react-query@2.26.4). To decrease the overall download time on mobile, to care for emerging/underprivileged markets, as well as decrease bounce time. Downloading 27.4 kB over emerging 3G (50 kB/s) would add 548ms just in itself. The rest comes on top. That makes me concerned about the initial page load.

Is it something I'm not understanding here? It seems that **chakra-ui/drawer** comes in at only [**16.2 kB**](https://bundlephobia.com/result?p=@chakra-ui/drawer@1.0.0-next.3), so I don't know which one to rely on (that one, or the Exports Analysis of chakra-ui/react). If anyone could clarify, that would be much appreciated.

**Comment by redbar0n** [comment]
Exports Analysis seems to have a bug which makes it report incorrect sizes for exports/components: https://github.com/pastelsky/bundlephobia/issues/364

So it seems it is the bundle size of [chakra-ui/drawer](https://bundlephobia.com/result?p=@chakra-ui/drawer@1.0.0-next.3) of **16.2 kB** which is reliable to be correct. It is still quite large for a single component...

**Comment by oliviermtl** [comment]
Even 16kB for a drawer is excessive, Menu items were also very heavy. I love chakra-ui, but i am not using menu and drawer for this reason.

**Comment by with-heart** [comment]
@oliviermtl It's a great time to get involved in open source! PRs and proposals are more than welcome.
