### ISSUE TITLE
Checkbox not getting isInvalid prop from FormControl

### ISSUE THREAD

**Issue by la55u** [chakra-ui/chakra-ui#3419]
# 🐛 Bug report

Checbox should be able to get the isInvalid prop from FormControl if it is set, just like the Input component.

## 💥 Steps to reproduce

See the link below.

## 💻 Link to reproduction

https://codesandbox.io/s/confident-shape-ngdej?file=/src/App.js

## 🧐 Expected behavior

The first checkbox in the example should be red.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.3.3         |
| Browser          |     Firefox       |
| Operating System |    Fedora        |

**Comment by segunadebayo** [comment]
Hi @la55u,

The Checkbox was initially designed to work with CheckboxGroup and it'll get more complex on our side to handle these use cases.

- Single Checkbox should read from FormControlContext. In this case, it should read isInvalid
- CheckboxGroup should not read from FormControl's Context since it doesn't make sense for all checkboxes to be isInvalid

Here's what a working code could look like:
https://codesandbox.io/s/checkbox-invalid-form-control-oi0gn?file=/src/App.js

Hope you find this helpful!
