### ISSUE TITLE
Unable to clear Radio Buttons

### ISSUE THREAD

**Issue by Patrick-Ullrich** [chakra-ui/chakra-ui#3549]
# 🐛 Bug report

Once a value is set in a RadioGroup, I am unable to clear the selection.

## 💥 Steps to reproduce

https://codesandbox.io/s/purple-fog-oyb5h?file=/src/App.js

1. Select a Radio Button
2. Press Clear
3. Nothing happens

## 💻 Link to reproduction

https://codesandbox.io/s/purple-fog-oyb5h?file=/src/App.js

## 🧐 Expected behavior

Radio buttons should represent state correctly, and have nothing selected

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    1.3.4        |
| Browser          |      Chrome 89.0.4389.82       |
| Operating System |    w10       |

**Comment by Patrick-Ullrich** [comment]
After some further investigation - things work as expected using `useRadioGroup`, seems like an issue specifically to <RadioGroup> implementation

**Comment by segunadebayo** [comment]
Thanks @Patrick-Ullrich,

I just pushed a fix for this.

**Comment by xveganxxxedgex** [comment]
What ended up being the fix for this? I'm using a `RadioGroup`, but I can't seem to figure out how to unset values. I even tried intercepting the click event on the `Radio` to prevent default/stop propagation and override the value to undefined or null, but the change either doesn't persist, or it reverts back to a previously selected value. Thanks for any info or help!
