### ISSUE TITLE
Tabs isLazy behavior

### ISSUE THREAD

**Issue by stellarhoof** [chakra-ui/chakra-ui#3683]
# 🚀 Feature request

Possibly change isLazy behavior to mount on first select and never unmount. If we want to keep the current behavior, consider adding a new prop.

## 🧱 Problem Statement / Justification

I read through https://github.com/chakra-ui/chakra-ui/issues/1384 to understand the problem `isLazy` is trying to solve. There are two distinct features asked for in that issue:

- Do not mount all tabs at once, since they might do data loading.
- Mark individual tab panels as lazy. This was a later feature request, not added in the linked PR.

The solution to the problem above was to mount on select and unmount on a different tab being selected. I think this can be improved to further reduce data loading.

Currently a lazy tab will unmount whenever it's unselected, causing it to load data on being selected again. A true lazy tab will only mount once, on first selection. This mount-on-first-selection behavior makes the second feature request above unnecessary.

## ✅ Proposed solution or API

Pretty simple. Each tab panel has an internal flag (useRef) to keep track of whether it has _ever_ been selected.
- If it has not been selected and it's not active, render `null`
- Otherwise set the flag to true and render its children as normal.

## ↩️ Alternatives

If we don't want to change the `isLazy` behavior, we could add a new prop.

Can anyone think of a use case where the current behavior is preferred over the one I'm suggesting?

## 📝 Additional Information

N/A

**Comment by stellarhoof** [comment]
I can take this up if a maintainer thinks it's an improvement.

**Comment by segunadebayo** [comment]
I really like the thought behind this @stellarhoof, and I think you're correct.

The way we handle the `isLazy` behavior isn't ideal and your solution looks like a good one.

Feel free to create a PR for this.

**Comment by with-heart** [comment]
This was actually a breaking change. If tabs were built with the expectation that they would be unmounted when no longer selected, but they are now not unmounted, it could lead to unexpected results. 

Imagine a tab hitting an API on an interval. The previous expectation that it would be unmounted means the interval stops when the tab isn't displayed, but now the interval will never stop once started. 

We've decided that we're going to revert the `isLazy` behavior back to its pre-`1.3.2` behavior and add a new `unmountHiddenPanels` prop to `Tabs` that allows you to turn off the unmounting behavior. This prop defaults to `true` so that the behavior of `isLazy` is the old behavior by default, meaning this will no longer be a breaking change.

**Comment by stellarhoof** [comment]
@with-heart That's a good point. Thanks for catching that.

**Comment by Hazem-Gamall** [comment]
has the unmountHiddenPanels prop made it to the latest version?  I can't seem to find it on version 2.8.1
