### ISSUE TITLE
Input inside MenuList not working

### ISSUE THREAD

**Issue by hazem3500** [chakra-ui/chakra-ui#3697]
# 🐛 Bug report

I Can't type in an `Input` which is inside a `MenuList`
```jsx
<Menu>
  <MenuButton as={Button}>
    Button
  </MenuButton>
  <MenuList>
    <Input/>
  </MenuList>
</Menu>
```

## 💥 Steps to reproduce

1. Open dropdown
2. Try to type in input

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/nostalgic-galois-3hg23?file=/src/App.js

## 🧐 Expected behavior

I should be able to type inside the `Input` if it exists inside `MenuList`

## 🧭 Possible Solution

I can use the [`Popover`](https://chakra-ui.com/docs/overlay/popover) component but shouldn't it also work in `Dropdown`?

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |    1.3.3   |
| Browser          |   Chrome   |
| Operating System |   Windows  |

## 📝 Additional information

What I am trying to do is create an "AutoComplete popover".
 something like this
![image](https://user-images.githubusercontent.com/22430645/112973856-0b6d7280-9152-11eb-987b-ad8f74cbb62e.png)

**Comment by jon424** [comment]
This is great - but when I go to the CodeSandbox, it won't run unless I reel back the framer-motion version to 4.1.0. I'm just going to leave that here for anyone who may be trying.

I do have a question! Is there a way to make it so that the input doesn't close the <Menu> on click? Currently, if I click inside the <Input />,  the menu just closes. I have the same setup as the original poster. I've tried playing around with "closeOnSelect="false"" and that didn't seem to work. Any advice would be greatly appreciated.

**Comment by jon424** [comment]
Okay, nevermind.  Adding 
`onClick={e => e.O()} `
to `<Input/>` did the trick.

**Comment by mamiabudat** [comment]
codesandbox doesn't works
