### ISSUE TITLE
Popovers/Menus rendering things "outside of view" (reintroduced in 1.4.0)

### ISSUE THREAD

**Issue by santialbo** [chakra-ui/chakra-ui#3814]
# 🐛 Bug report

1.4.0 reintroduced a previously fixed bug #2586, #3201 but I was unable to reproduced on codesandbox back then (there were some issues that seem to be fixed now).

## 💥 Steps to reproduce
It's a bit hard to explain, check the reproduction.
Add a Popover inside an overflowed element. When the popover is closed it still renders something that causes the body to be larger than necessary adding an unnecessary scrollbar to the window.
<img width="529" alt="Screenshot 2021-04-14 at 12 20 12" src="https://user-images.githubusercontent.com/1557563/114702575-84f58b00-9d24-11eb-975a-609cc5451598.png">

## 💻 Link to reproduction

**Attention**: If you are on a mac make sure to enable this setting in order to see scrollbars (like in Windows for example)
<img width="672" alt="104043516-3b088080-51dc-11eb-9e74-c81ed9630224" src="https://user-images.githubusercontent.com/1557563/114701124-ace3ef00-9d22-11eb-9dce-ea23750a8d8d.png">
CodeSandbox reproduction: https://codesandbox.io/s/condescending-burnell-zpe36?file=/src/App.tsx

## 🧐 Expected behavior
I would expect that when the popover is closed nothing is rendered like in 1.3.4.
Here's a working codesandbox using Chakra 1.3.4 https://codesandbox.io/s/infallible-bartik-192kc

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.4.0         |

**Comment by kogovsekm** [comment]
Having the same issue with Chakra UI "1.6.0" (on macOS 11.2.3). When rendering a popup inside the table row, the second scrollbar appears (not the table scrollbar, but the page scrollbar) and page is extremely long event though table is smaller than viewport.

**Comment by lannik** [comment]
Facing the same issue

**Comment by lannik** [comment]
Fixed the issue by setting the _overflow_ property to _hidden_ in my case.

**Comment by santialbo** [comment]
> Fixed the issue by setting the _overflow_ property of _body_ to _hidden_ in my case.

Thats' the nuclear solution but it might not work in all scenarios, you might want the body to be able to scroll.

**Comment by Jiiieeef** [comment]
I am having the same issue when upgrading Chakra to 1.6.0. 
Funny thing is that the bug is also visible here https://chakra-ui.com/docs/components/portal 😅

**Comment by santialbo** [comment]
Hi @dodas, is it possible that you fixed this issue with the release of 1.6.3? I'm not able to reproduce it with that version.

**Comment by feross** [comment]
I'm still seeing this issue in Chakra 1.6.3, but it appears fixed in 1.6.4. It was causing an unnecessary horizontal scroll on the entire webpage.

You can see it here: 

<img width="1176" alt="Screen Shot 2021-06-18 at 4 42 27 PM" src="https://user-images.githubusercontent.com/121766/122625091-2c11de00-d058-11eb-91a6-dec6fe63139d.png">

Inspector confirms that it's the `visibility: hidden` popover that's causing the issue.

<img width="1178" alt="Screen Shot 2021-06-18 at 4 42 21 PM" src="https://user-images.githubusercontent.com/121766/122625093-2d430b00-d058-11eb-98c1-ecc4b2910653.png">

One workaround seems to be adding `strategy='fixed'` to the Popover. Or just update to 1.6.4.

**Comment by jeffn12** [comment]
I found a workaround that 'solved' this issue for me in Chakra 1.5.0:

I accessed the `isOpen` state of the `<Menu />` , and used it to set the `display` prop on the `<MenuList />`.  When `isOpen = true`, I set the display to block, and when `isOpen = false`, I set the display to none.

```js
<Menu closeOnBlur offset={[-6, -38]}>
      {({ isOpen }) => (
        <>
          <MenuButton>
            <Icon
              as={FaHome}
              lineHeight="inherit"
              marginRight={1}
              marginBottom={1}
            />
            Home <Icon as={FiChevronDown} />
          </MenuButton>
          <MenuList zIndex={500} display={isOpen ? "block" : "none"}>
               <MenuItem>
                         ...
                         ...
          </MenuList>
        </>
    )}
</Menu>
```

This still applies animations/transitions when opening and closing the menu, which had been discussed in #2586

**Comment by codetheweb** [comment]
I'm still seeing this in 1.6.4 rendering `<MenuList/>` in a Portal.

**Comment by codetheweb** [comment]
Still relevant.

**Comment by primos63** [comment]
I tried the CodeSandbox provided. I no longer saw the issue starting with v1.6.12. If there are others experiencing this issue with v1.6.12 or later, please provide a CSB with the issue otherwise this issue should be considered closed.

**Comment by santialbo** [comment]
@primos63 You are right, this is not happening anymore. Thanks for the heads up!

**Comment by Chukwuamaka** [comment]
This issue persists in Chakra v2.3.6. 

I am building a dashboard with a sidebar and topbar menu, both of which don't scroll with the rest of the body. Hence, the parent container of the rest of the body has overflowY set to 'auto' or 'scroll'. In this scrollable region, I am rendering a table with a popover in one of its columns to show the menu options for each row of data. The popovers for the first three rows of data do not trigger the behaviour that this issue addresses and I think it's because the popovers for these rows render within a 100vh of the body (_just a hypothesis_), but for the remaining rows of data, this issue comes up.

Setting the position of the parent container of the scrollable region to 'relative' (as suggested in [this comment](https://github.com/chakra-ui/chakra-ui/issues/2760#issuecomment-1310873134) on a duplicate issue) and rendering the popover outside of a portal solved the problem for me.

**Comment by DedaDev** [comment]
```
display={isOpen ? "block" : "none"}
```
works well for me, thanks @jeffn12 for the idea

**Comment by isBatak** [comment]
Setting `display:none` breaks the accessibility feature.
https://css-tricks.com/places-its-tempting-to-use-display-none-but-dont/

Problem is in `position:relative;` in some of the parent.

Solution is enabling `computePositionOnMount` or remove `position:relative;` form all the parents in the DOM three.
![image](https://user-images.githubusercontent.com/4128883/212885465-6fb39275-8d1f-4459-ad47-642c8889e7af.png)

**Comment by leognmotta** [comment]
> display={isOpen ? "block" : "none"}

Thanks, that was the one right answer, I made my paraent position dynamic based on state.

**Comment by wuwb** [comment]
persists in Chakra 2.4.4
