### ISSUE TITLE
First checkbox is checked by default in checkbox group when used with react-hook-form

### ISSUE THREAD

**Issue by TomasB** [chakra-ui/chakra-ui#3847]
# 🐛 Bug report

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/reac-hook-form-with-chakra-ui-checkbox-selects-first-element-9sg7d?file=/src/App.tsx
2. event though defaultValues doesn't mention"aaa" value, checkbox is checked anyway, 

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/reac-hook-form-with-chakra-ui-checkbox-selects-first-element-9sg7d?file=/src/App.tsx

## 🧐 Expected behavior

2nd and 4th checkbox selected only (values "bbb" and "ddd"

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.5.1       |
| Browser          |     Chrome       |
| Operating System |  Windows and MacOS           |

**Comment by with-heart** [comment]
Hi @TomasB! I don't know why `"aaa"` is checked by default because I don't know much about `react-hook-form`, but I can tell you that your use of `Checkbox` doesn't follow the component's API, so I recommend [checking out the `Checkbox` docs page](https://chakra-ui.com/docs/form/checkbox). 

Here's an example using `Controller` and `CheckboxGroup` to accomplish what you were attempting: https://codesandbox.io/s/reac-hook-form-with-chakra-ui-checkbox-selects-first-element-forked-f7qh9?file=/src/App.tsx
