### ISSUE TITLE
`mx` propery provides margin-inline-xxx

### ISSUE THREAD

**Issue by SoshiHomma** [chakra-ui/chakra-ui#3874]
# 🐛 Bug report

`mx` provides CSS Properties: `margin-inline-start` and `margin-inline-end`, not as like the doc said:
![image](https://user-images.githubusercontent.com/52709206/115554175-2793a800-a2e9-11eb-87d0-b0c23589dc09.png)

## 💥 Steps to reproduce

1. Write mx for any component like: `<Stack mx={32}>`
2. That's it.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/bold-tesla-d97s1

## 🧐 Expected behavior

`mx` provides `margin-right` and `margin-left`

## 🧭 Possible Solution

Use `mr` and `ml` instead of `mx`

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.3.3       |
| Browser          | Firefox 88.0        |
| Operating System |  Server: Fedora 31, Client: Windows 10 Pro  |

^ This means I'm running Node server on Fedora, but I'm using proxy to show the render result on Firefox in Windows.

**Comment by segunadebayo** [comment]
Hi @SoshiHomma,

This is by design to enable us to support RTL by default. margin-inline-start and margin-inline-end are exactly identical when your writing mode is ltr so there should be no issues.

We'll update the docs to reflect this, instead.

@estheragbaje please update the docs to show that `mx` and `px` map to `margin-inline-X` and `padding-inline-X`

Cheers.

**Comment by SoshiHomma** [comment]
HI @segunadebayo,
I understand that is the design for RTL, thank you for spending your time!
