### ISSUE TITLE
useMediaQuery alternative for server side rendering

### ISSUE THREAD

**Issue by Sharvin26** [chakra-ui/chakra-ui#3958]
Hello first of all thank you for developing such a great UI library. 

We are using Chakra UI in lot of our projects and I have became a big fan of the library.

# 🚀 Feature request

> Alternative to useMediaQuery for server side rendering

## 🧱 Problem Statement / Justification

We developed a web application using **ReactJS** and Chakra UI.  We used the `useMediaQuery` hook at lot of places. 

Now we want to migrate the web application to **NextJS**. In this [Github issue](https://github.com/chakra-ui/chakra-ui/issues/2827#issuecomment-753596709) I found that `useMediaQuery` hook works only on the client side rendering.

The problem with using `sx` or `css` prop is that we render some different components based on the `useMediaQuery`. This behaviour is not possible with `sx` or `css` ( Please correct me if I am wrong )
 
## ✅ Proposed solution or API

 Some kind of hook similar to `useMediaQuery` for server side rendering would be great if possible. 

If not then what can be used for achieving the conditional rendering of components based on sizes for Chakra UI?

Again thanks for such a great work.

Keep it up!

**Comment by segunadebayo** [comment]
Hi @Sharvin26,

You could consider using responsive style props instead of `useMediaQuery`. There's no way to read the window dimensions on the server-side, the best bet is to try to read the `user-agent` and there's not an elegant solution.

You could defer rendering the component or showing a spinner/skeleton until the component loads on the client-side.

Using responsive values for `display` css property is still the SSR-safe way I'd recommend. In other words, rely on CSS instead of JS for that.

Hope you find this useful.

**Comment by stevenWang0917** [comment]
You could try JS native method, const mqList = window.matchMedia('(max-width: 767px)'); The link is https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia
