### ISSUE TITLE
Stop Click Propagation on Blur with Popovers

### ISSUE THREAD

**Issue by kentongray** [chakra-ui/chakra-ui#4010]
# 🚀 Feature request

When a popover is open stop propagation of clicks "behind" the popover to mimic native behavior.

## 🧱 Problem Statement / Justification

When working with busy pages and popovers users have to carefully click an area to close. This is not the normal experience with popovers in native OS. A contrived example below comparing right click popover to Chakra UI popover.

https://user-images.githubusercontent.com/100857/118195127-411f9f80-b410-11eb-8b0e-f11abb551991.mov

> Please provide code snippets, gists, or links to the ideal design or API
Our basic strategy is to include this in the portal to handle this with useDisclosure

```
 {ctrl.isOpen && (
            <Flex
              w={'100vw'}
              h={'100vh'}
              position={'fixed'}
              top={0}
              left={0}
              onClick={ctrl.onClose}
            />
```

Ideally this behavior could be built in IMO by default and potentially a toggle option to hide it. Also when originally investigating I saw how the <ModalOverlay> works and that would be acceptable as well (if not a little verbose)

## ↩️ Alternatives

As mentioned the current workaround feels a little hacky and ends up with us having some repetitive code that we can't easily abstract

## 📝 Additional Information

I love Chakra!

> What resources (links, screenshots, etc.) do you have to assist this effort?

Happy to submit a PR if the team agrees this is a worthwhile effort!

**Comment by segunadebayo** [comment]
Hi @kentongray,

This is by design. The example you showed in the video is for a "modal, context menu". Usually, when showing a modal menu or a context menu, you want to block scroll and disable all body pointer events.

It's different for a popover. Because it's not modal, we don't block pointer events that happen outside the popover. The current logic reads like this:

- If the user blurs outside and the target is a focusable element, let the click proceed and activate that element
- If it's not a focusable element, prevent and return focus to the popover trigger.

In the future, we might provide a way to opt out of this decision.
