### ISSUE TITLE
After version 1.6.2, the ring style will appear when the button blur

### ISSUE THREAD

**Issue by firede** [chakra-ui/chakra-ui#4041]
# 🐛 Bug report

After version `1.6.2`, the ring style (outline) will appear when the button blur (Chrome browser, used [`focus-visible`](https://chakra-ui.com/docs/migration#css-reset) package).

<img src="https://user-images.githubusercontent.com/157338/118852336-46478780-b905-11eb-8d14-a24b15a7a9cd.gif" width="400" />

## 💥 Steps to reproduce

1. Go to [CodeSandbox](https://codesandbox.io/s/chakra-ui-button-blur-jnvfh?file=/src/App.tsx)
2. Click the button
3. Click anywhere except the button

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-ui-button-blur-jnvfh?file=/src/App.tsx

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |1.6.2|
|`focus-visible`| 5.2.0 |
| Browser          |Chrome 90.0.4430.212 |
| Operating System |macOS 11.3.1 |

**Comment by with-heart** [comment]
Looks like it's caused by `transition: all 250ms` + `outline: 2px solid transparent` attached to `Button`. When I toggle the `outline` rule on and off, I see the same effect. If I disable the `transition` rule or add `transition: outline none`, it stops happening. Not sure which solution would be preferable @segunadebayo

**Comment by segunadebayo** [comment]
I'd recommend narrowing the scope of the transition to `colors` and `box-shadow`
