### ISSUE TITLE
Popover add unwanted scroll because of PopoverContent position

### ISSUE THREAD

**Issue by Jiiieeef** [chakra-ui/chakra-ui#4109]
# 🐛 Bug report

Hello,

I am currently working with `Popover` and I found a bug.

When a `Popover` has not been opened yet, the `PopoverContent` is misplaced and can cause unwanted horizontal scroll.
Once it has been opened, the `PopoverContent` is placed correctly and everything is normal.

## 💥 Steps to reproduce

Use a `Popover` at the right of the window and a scroll will happen.

## 💻 Link to reproduction

See https://codesandbox.io/s/vigorous-dijkstra-d1s2k, the red block is the `PopoverContent` and as you can see, I've set the `Popover` placement in left but even so, the content is in bottom-end. 
Hover the button and the content will be placed correctly.

## 🧐 Expected behavior

PopoverContent should have the correct position event when it's not been opened.

## 🧭 Possible Solution

I found a workaround by setting `isLazy` to the `Popover` or by setting the `PopoverContent` in a `Portal` but I feel like it's a hacky fix 🤔 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.6.3      |
| Browser          |      Chrome and Firefox (at least)      |
| Operating System |        Mac OS Big Sur    |

**Comment by dlindenkreuz** [comment]
I have the same issue, but with the `<Menu>` component.

Is this related to this PR? https://github.com/chakra-ui/chakra-ui/pull/4026

**Comment by dlindenkreuz** [comment]
Another workaround: https://codesandbox.io/s/floral-mountain-cvoku?file=/src/App.js

```jsx
<PopoverContent rootProps={{style: {right: 0}}}>
// or
<MenuList rootProps={{style: {right: 0}}}>
```

This overrides the absolute position so it doesn't overflow `<body>`.

As soon as the Popover or Menu is opened, the override gets overridden again 😜 and everything works as usual.

**Comment by beni69** [comment]
> Another workaround: https://codesandbox.io/s/floral-mountain-cvoku?file=/src/App.js
> 
> ```js
> <PopoverContent rootProps={{style: {right: 0}}}>
> // or
> <MenuList rootProps={{style: {right: 0}}}>
> ```
> 
> This overrides the absolute position so it doesn't overflow `<body>`.
> 
> As soon as the Popover or Menu is opened, the override gets overridden again 😜 and everything works as usual.

I have this problem too, with the MenuList component.
I've been bashing my head into my desk for 30mins, and this finally solved it. Thanks 🎉

**Comment by Jiiieeef** [comment]
> I have the same issue, but with the `<Menu>` component.
> 
> Is this related to this PR? #4026

I am not sure, it jas beed released with 1.6.3 but the problem is still present.

I like your solution too :) Looks like there is a lot of workaround

**Comment by anubra266** [comment]
Hey @Jiiieeef This is what I get from your codesandbox. Is that what you expect?
 
![Peek 2021-05-29 12-23](https://user-images.githubusercontent.com/30869823/120068497-e4abb980-c078-11eb-9245-87a91ff16d4f.gif)

**Comment by with-heart** [comment]
![Kapture 2021-05-29 at 09 19 23](https://user-images.githubusercontent.com/1954752/120071847-faac8080-c05e-11eb-81ec-907b9589862f.gif)

I don't know enough about our `Popover` implementation to understand the implications of changing this, but I don't think `visibility: hidden` can work here since any `PopoverContent` near the edge of the page would cause an overflow.

**Comment by anubra266** [comment]
I think Popper could change the position of the popover once it causes an overflow.

**Comment by Jiiieeef** [comment]
There is modifiers which allow to automatically change the position of the popover to prevent overflow (https://popper.js.org/docs/v2/modifiers/flip/).

The problem here is that the container is misplaced before the first display and the modifiers doesn't seems to handle this case. Maybe this is issue from popper.js ?

**Comment by microbit-matt-hillsdon** [comment]
I've seen what I think is the same change in behaviour here in 1.6.3 which I think is caused by deferring creating the popper.js instance as noted in the release note. So for me, the initial placement caused overflow of a 100vh body height but the placement in 1.6.2 and after interacting with the menu did not.

An example of different behaviour: https://codesandbox.io/s/upbeat-solomon-6vttf

**Comment by with-heart** [comment]
@microbit-matt-hillsdon Thanks for the excellent reproduction! Perfect example + explanations to clearly demonstrate the difference in behavior between 1.6.2 and 1.6.3. If there was an issue reproduction hall of fame, I would put this in there!

**Comment by TheThirdRace** [comment]
As posted in this issue https://github.com/chakra-ui/chakra-ui/issues/4186

---

After a bit of testing on my side, I've located the problem within `popper.js`.

Here's a comparative of positioning before/after updating Chakra:

| Chakra | Popper.js | CSS positioning |
|:--|:--|:--|
| 1.6.2 | 2.1.2 | position: absolute; left: 0px |
| 1.6.3 | 2.2.0 | position: absolute; ~left: 0px~ |

I simply added `left: 0` to `listRoot` part within the theme to fix my problem.

With Popper 2.2.0, the `listRoot` doesn't have any positioning on first render. Once you click on the button to open the menu, the styling kicks in and Popper use `inset` to position the `listRoot`.

My guess is that Popper moved to `inset` instead of `left` in version 2.2.0, but forgot to add the correct positioning on the first render.

If your `<MenuButton>` is located too far right, the positioning will be too far right and poke out of the viewport, which then cause the overflow horizontally and the scrollbar being displayed.

**Comment by santialbo** [comment]
It's not ideal but with `Portal` and `isLazy`, the issue goes away

https://codesandbox.io/s/icy-meadow-q09vl?file=/src/App.js

**Comment by ianfelix** [comment]
> > Another workaround: https://codesandbox.io/s/floral-mountain-cvoku?file=/src/App.js
> > ```js
> > <PopoverContent rootProps={{style: {right: 0}}}>
> > // or
> > <MenuList rootProps={{style: {right: 0}}}>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This overrides the absolute position so it doesn't overflow `<body>`.
> > As soon as the Popover or Menu is opened, the override gets overridden again 😜 and everything works as usual.
> 
> I have this problem too, with the MenuList component.
> I've been bashing my head into my desk for 30mins, and this finally solved it. Thanks 🎉

Thanks man. I had the same problem, this solution solved.

**Comment by Enfield-Li** [comment]
> Another workaround: https://codesandbox.io/s/floral-mountain-cvoku?file=/src/App.js
> 
> ```js
> <PopoverContent rootProps={{style: {right: 0}}}>
> // or
> <MenuList rootProps={{style: {right: 0}}}>
> ```
> 
> This overrides the absolute position so it doesn't overflow `<body>`.
> 
> As soon as the Popover or Menu is opened, the override gets overridden again 😜 and everything works as usual.

This doesn't work in my case, but found an alternative by adding `overflow: "auto"` and `position="relative"` to the main component, something like this:
```
export default function App() {
  return (
    <Flex overflow="hidden" height="100vh" position="relative">
          // ...
    </Flex>
  );
}
```
[Sandbox link](https://codesandbox.io/s/hungry-leaf-ow7rrl)

**Comment by MaksymBer** [comment]
> > Another workaround: https://codesandbox.io/s/floral-mountain-cvoku?file=/src/App.js
> > ```js
> > <PopoverContent rootProps={{style: {right: 0}}}>
> > // or
> > <MenuList rootProps={{style: {right: 0}}}>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This overrides the absolute position so it doesn't overflow `<body>`.
> > As soon as the Popover or Menu is opened, the override gets overridden again 😜 and everything works as usual.
> 
> This doesn't work in my case, but I found an alternative by adding `overflow: "hidden"` and `position="relative"` to the main component, something like this:
> 
> ```
> export default function App() {
>   return (
>     <Flex height="100vh" overflow="hidden" position="relative">
>           // ...
>     </Flex>
>   );
> }
> ```
> 
> See [Sandbox link](https://codesandbox.io/s/hungry-leaf-ow7rrl)

As previous workarounds do not work anymore, another workaround would be to use `transform: scale(0)`.
The code below worked for me, `transform` is being overwritten when you open the menu, so it doesn't break the layout.
```
<MenuList rootProps={{ style: { transform: 'scale(0)' } }}>
```
