### ISSUE TITLE
Variant styles in Table component are always the most important

### ISSUE THREAD

**Issue by pszafer** [chakra-ui/chakra-ui#4122]
# 🐛 Bug report

Hi,
I think I found 2 issues with Table component styling. I think both issues might be related so I created one report.
I'm creating custom variant for my table eg.
```
<Table variant="myvariant" colorScheme="gray" size="sm">
```
1. If I use sx prop in any of inline jsx then it won't get applied as it is loaded sooner than variant.
2. If I create table inside table, second table uses different variant then only first variant is applied.

### First issue
1. Go to https://codesandbox.io/s/variant-override-forked-odxpd 
2. See tfoot, it is supposed to be green but it is red as defined in variant.

### Second issue

1. Go to https://codesandbox.io/s/variant-override-forked-of5bx
2. See `SubCol` table
3. It should have yellow background

## 💻 Link to reproduction

CodeSandbox reproduction:
- https://codesandbox.io/s/variant-override-forked-odxpd , 
- https://codesandbox.io/s/variant-override-forked-of5bx

## 🧐 Expected behavior

If I style with sx then sx should be more important than variant.
If I put table inside table, then second variant should be more important.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.6.3      |
| Browser          |    Chromium 91        |
| Operating System |    Arch Linux        |

**Comment by TimKolberger** [comment]
Hi @pszafer,
Thanks for taking the time to create two reproductions for this issue!

I can see your point that the styles you provided are not showing up.
All provided styles, those via `variant` (red background) and via `sx` (green background) are applied, but the `variant` creates a selector with a higher specificity than the `sx` prop, which override your intended styles.

![image](https://user-images.githubusercontent.com/16899513/120378089-49d40900-c31e-11eb-8e45-04d5a235e29e.png)

This means that this is an issue with the cascading nature of CSS. From a chakra point of view this works as expected.

But lets focus on possible solutions for you:

## Issue 1 `sx`

We need to create a selector with a higher specificity than the one from the variant. This is done with the `&&` selector. 
emotion replaces every `&` with its generated class name (= `.emotion-class.emotion-class`), and because there are two of them, the specificity is higher than the nested selector. This is kind of a hack, but judge for yourself.

```tsx
<Td
  sx={{
    "&&": {
      backgroundColor: "green.500",
    },
  }}
>
  tfoot1
</Td>
```

We cannot change this behaviour in v1 of chakra-ui.

## Issue 2 nested tables

You could use the `parent > element` selector to target only those elements with a specific parent to be able to nest tables:

```tsx
const myvariant = {
  tbody: {
    '> tr': { // <-- note the `>`
      "&:nth-of-type(odd)": {
        backgroundColor: "green.200"
      }
    }
  }
};

const secondVariant = {
  tbody: {
    '> tr': { // <-- note the `>`
      backgroundColor: "yellow.200"
    }
  }
};
```

This could be backported into the chakra default theme to make this work out of the box.

**Comment by with-heart** [comment]
@TimKolberger I suppose we should probably document the solution to issue 1 on the table page. It's the only use of `&:X` in the `theme`, so I think it's a problem unique to tables.

**Comment by pszafer** [comment]
both solutions works. Thank you!
I think both solutions should be somehow documented in table docs.
