### ISSUE TITLE
Unable to use Drawer from @chakra-ui/drawer

### ISSUE THREAD

**Issue by samuelcastro** [chakra-ui/chakra-ui#4156]
# 🐛 Bug report

To avoid import all components at once I want to use specific packages for specific needs. I'm trying to use the Drawer component from `@chakra-ui/drawer`, however it's not working.

## 💥 Steps to reproduce

Follow documentation: https://chakra-ui.com/docs/overlay/drawer

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/wizardly-star-tl3nf

## 🧐 Expected behavior

Be able to use drawer accordingly.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      latest      |
| Browser          |    chrome        |
| Operating System |   mac         |

**Comment by with-heart** [comment]
Hi @samuelcastro! `Drawer` is a part of the `@chakra-ui/modal` package, so it works if you import it from there: https://codesandbox.io/s/quirky-stallman-3lcek?file=/src/index.tsx

We used to have a separate `@chakra-ui/drawer` package, but haven't since the end of the v1 beta.

I'd also recommend just using `@chakra-ui/react` unless you have very specific needs. Modern systems will tree-shake Chakra imports, so you likely wouldn't see a difference between importing from `@chakra-ui/react` and `@chakra-ui/modal`.

**Comment by samuelcastro** [comment]
Interesting @with-heart, I thought I'd need to import directly to minimize bundle size similarly to https://material-ui.com/guides/minimizing-bundle-size.

Do you have some links to share about how the tree-shake would prevent unnecessary imports?

Thank you.

Sam

**Comment by samuelcastro** [comment]
Never mind, the link I shared even explain the tree-shaking, more here for reference: https://webpack.js.org/guides/tree-shaking/
