### ISSUE TITLE
Menu closeOnSelect prop won't work with MenuOptionGroup

### ISSUE THREAD

**Issue by delucca** [chakra-ui/chakra-ui#4165]
# 🐛 Bug report

While using a `MenuOptionGroup` with type radio the `closeOnSelect` property of the `Menu` won't work always. Sometimes it closes the menu, sometimes it won't.

## 💥 Steps to reproduce

1. Go to Chakra Menu page at the Menu Option Group section using [this link](https://chakra-ui.com/docs/overlay/menu#menu-option-groups)
2. Change the `closeOnSelect={false}` of the `Menu` component to `closeOnSelect={true}`
3. Opens the rendered menu and try to select an option. You should try a few times. After a few attempts it would close, but not as expected (on the first attempt)

## 💻 Link to reproduction

https://chakra-ui.com/docs/overlay/menu#menu-option-groups

## 🧐 Expected behavior

After clicking on a given item, it should close the menu

## 🧭 Possible Solution

No idea =/

## 📝 Additional information

The `closeOnSelect` works on `MenuGroup` (but not MenuOptionGroup)

**Comment by samageloff** [comment]
Replicated here as well: https://codesandbox.io/s/chakra-menu-list-close-on-select-zg6nz?file=/src/index.js

**Comment by Sqvall** [comment]
https://github.com/chakra-ui/chakra-ui/blob/cbf8bbdf02eff45a57a28307ec9c3137ce845420/packages/menu/src/use-menu.ts#L337-L341
Problem in this place.
Menu item option - it button contains 2 span (icon and text).
![Screenshot from 2021-06-05 22-21-16](https://user-images.githubusercontent.com/47914396/120903117-f11dac80-c64c-11eb-8a02-9a362f660cfb.png)
When we click on text or icon - isTargetMenuItem called with span or svg element in event.target ant event not propagation to the button.
Because of this, the condition does not pass:
```js 
!!target.getAttribute("role")?.startsWith("menuitem")
```
We cannot attach to the parent for this event targets because its broke for icon or if children include another DOM elements.

May be somebody can fix it?
Or give me a hint what would be the best option to fix it correctly.

**Comment by segunadebayo** [comment]
Good investigation @Sqvall.

Let me check this and see if I can propose a fix for it.

**Comment by segunadebayo** [comment]
Pushed a fix for this, thanks to your help @Sqvall 💖.

We'll release an update shortly.

**Comment by Sqvall** [comment]
No problem, I was glad to help.
