### ISSUE TITLE
Prevent Menu dropdown from overflowing and causing a scrollbar on bottom

### ISSUE THREAD

**Issue by gurkang** [chakra-ui/chakra-ui#4186]
# 🐛 Bug report

When using a dropdown menu in a nav element and pushing it to the right with a `<Spacer/>` the dropdown menu causes overflow and forces a scrollbar to appear on the bottom of the page.
This goes away after pressing the Menu and having the dropdown menu actually render.

## 💥 Steps to reproduce

1. Go to sandbox
2. see scrollbar on bottom
3. press the avatar on top right
4. see scrollbar disappear after dropdown renders

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/competent-chaum-ds0pw?file=/src/index.js

## 🧐 Expected behavior

I expect the dropdown menu not to overflow and cause a scrollbar

## 🧭 Possible Solution

No idea to be honest.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |        1.6.3    |
| Browser          |        chrome    |
| Operating System |      windows 10      |

**Comment by TheThirdRace** [comment]
I use a `<Menu>` within a `nav` element and I experience the exact same thing without any `<Spacer/>`.

In my case, I simply styled my menu to take the whole viewport width when opened.

In Chakra 1.6.2, this problem didn't happen.

The problem happens just as well in Firefox and Edge (chromium)

**Comment by TheThirdRace** [comment]
After a bit of testing on my side, I've located the problem within `popper.js`.

Here's a comparative of positioning before/after updating Chakra:

| Chakra | Popper.js | CSS positioning |
|:--|:--|:--|
| 1.6.2 | 2.1.2 | position: absolute; left: 0px |
| 1.6.3 | 2.2.0 | position: absolute; ~left: 0px~ |

I simply added `left: 0` to `listRoot` part within the theme to fix my problem.

With Popper 2.2.0, the `listRoot` doesn't have any positioning on first render. Once you click on the button to open the menu, the styling kicks in and Popper use `inset` to position the `listRoot`.

My guess is that Popper moved to `inset` instead of `left` in version 2.2.0, but forgot to add the correct positioning on the first render.

If your `<MenuButton>` is located too far right, the positioning will be too far right and poke out of the viewport, which then cause the overflow horizontally and the scrollbar being displayed.

**Comment by aspectiscool** [comment]
Could you please give a more in-depth explanation of how you fixed this issue?

**Comment by asimplify** [comment]
The issue still persists but was able to find a workaround, just need to add a condition in menuList:
`  <MenuList display={isOpen ? "block" : "none"}>`

**Comment by nelsieborja** [comment]
Another fix would be to use the strategy "fixed" when using the usePopper hook
