### ISSUE TITLE
Select dropdown has white bars above and below the list of options

### ISSUE THREAD

**Issue by mah51** [chakra-ui/chakra-ui#4194]
# 🐛 Bug report

On the select drop down in dark mode there are white bars above and below the options, this is not seen in lightmode as its white. (doesn't happen in chrome, but does in firefox). It is also worth nothing that chrome does not have gaps above and below the list of options like firefox does. I also am having trouble inspecting element as the dropdown closes every time i try to select that element.

## 💥 Steps to reproduce

Visit the [docs](https://chakra-ui.com/docs/form/select)

## 🧐 Expected behavior

Bars to be the same colour as the rest of the background or remove bars like it is on chrome.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       latest     |
| Browser          |        firefox    |
| Operating System |      windows 10      |

## 📝 Additional information

![image](https://user-images.githubusercontent.com/47287285/121208883-4f77a480-c872-11eb-8dff-f1e70daa78c5.png)

![image](https://user-images.githubusercontent.com/47287285/121209220-949bd680-c872-11eb-914b-a97b90d54706.png)

**Comment by mah51** [comment]
I forgot to add what it looks like on chrome, the attached above photos are firefox and below is chrome:

![image](https://user-images.githubusercontent.com/47287285/121209579-d9c00880-c872-11eb-92ec-277b1c5dad3d.png)

**Comment by anubra266** [comment]
I use firefox, but can't seem to reproduce this. 
![image](https://user-images.githubusercontent.com/30869823/121443892-4b3cab80-c986-11eb-9350-b4659d235056.png)

**Comment by mah51** [comment]
It looks like you are on mac to me, and it doesn't replicate the behaviour on mac, only on my windows desktop.

Here is mac chrome:
<img width="780" alt="CleanShot 2021-06-10 at 01 26 33@2x" src="https://user-images.githubusercontent.com/47287285/121446290-141cc900-c98b-11eb-8042-12405b5afb3e.png">

and mac firefox:
<img width="800" alt="CleanShot 2021-06-10 at 01 28 05@2x" src="https://user-images.githubusercontent.com/47287285/121446305-1e3ec780-c98b-11eb-956d-d56545a0eabf.png">

**Comment by anubra266** [comment]
I'm on ubuntu. I just customized it.😃 
It's a native windows problem then.

**Comment by jigz** [comment]
Just noticed this myself, firefox on windows 10
![12](https://user-images.githubusercontent.com/31827190/121670087-a635e600-cadf-11eb-91a6-1a8cf549770c.png)

**Comment by Dacker15** [comment]
I have the same problem to on Firefox in Windows 10

![Bug Chakra](https://user-images.githubusercontent.com/47461361/122818026-f7608980-d2d8-11eb-8b64-075ae2fc2aca.jpg)

**Comment by JTBrinkmann** [comment]
## Workarounds

on the Select, either
- set (text) color to `black` (`#000`) or `white` (`#FFF`)
- set a non-transparent background color
- set `variant="solid"`

You can also set this in your theme, but make sure the variant(s) you are using don't override it. Also you could set the body text color to `white` (instead of `whiteAlpha.900`) in dark mode.


## Explanation

On Windows (10?), Firefox generally colors the select dropdown white. When Firefox uses a dark browser theme **and** the Select's `color` is black or white, it colors the dropdown with a dark background. In either case, Firefox applies the Select's background color on top. Examples: on top of white `bg="red"` results in red, `bg="blackAlpha.100"` results in light gray, no bg results in white.

The default Firefox theme switches between Light and Dark depending on the system's color mode. With non-default themes, the system's color mode has no effect on this bug.


## Possible fixes in the Chakra repo

One solution on Chakra's end would be to add `_dark: { color: "white" }` to the theme. This is not too far off from `whiteAlpha.900` that's inherited from body, but it breaks color inheritance. Changing the body color could also be considered, but that's a (slightly) visible change for **every** Chakra user.

I can see that the theme [already has a `bg` in the baseStyle](https://github.com/chakra-ui/chakra-ui/blob/e7a732/packages/theme/src/components/select.ts#L14), but that's mostly useless because it gets overriden by the variants.

The only proper long-term solution would be, to not use the browser's select at all, but to replicate it. To quote [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#styling_with_css):

> The `<select>` element is notoriously difficult to style productively with CSS. You can affect certain aspects [...]
> 
> However, these properties don't produce a consistent result across browsers, [...] you should consider using a library with good facilities for styling form widgets, or try rolling your own dropdown menu using non-semantic elements, JavaScript, and WAI-ARIA to provide semantics.
