### ISSUE TITLE
IconButton border radius

### ISSUE THREAD

**Issue by Mzaien** [chakra-ui/chakra-ui#4255]
# 🐛 Bug report

The border radius of Iconbutton is gone it is a sharp box button 
<img width="57" alt="CleanShot 2021-06-19 at 03 26 19@2x" src="https://user-images.githubusercontent.com/43112535/122625508-221aca00-d0ae-11eb-8fd7-bc5d728d0622.png">

## 💥 Steps to reproduce

1 - Update to latest chakra version 
2 - run your website

## 💻 Link to reproduction

The doc site is having the problem so i did not make a reproduction
https://chakra-ui.com/docs/form/icon-button#button-variants

## 🧐 Expected behavior

icon Buttons should be somewhat rounded

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.6.4       |
| Browser          |     Chrome       |
| Operating System |      MacOs      |

## 📝 Additional information

<img width="672" alt="CleanShot 2021-06-19 at 03 29 05@2x" src="https://user-images.githubusercontent.com/43112535/122625564-8b024200-d0ae-11eb-8247-040876d40651.png">

**Comment by Mattinton** [comment]
This bug is caused by my MR from a couple days ago https://github.com/chakra-ui/chakra-ui/pull/4245. Turns out providing `undefined` as a prop doesn't return the styling to it's default, unsure if this is a problem with how the Button component does it's styling or if its to do with how chakra styling works all together.
