### ISSUE TITLE
[IconButton] How to add hover, focus, disabled styles?

### ISSUE THREAD

**Issue by gopinav** [chakra-ui/chakra-ui#426]
**Describe the bug**
There is no mention in the docs on how to style IconButton for pseudo selectors and PseudoBox doesn't seem to work with as='IconButton'.

**Expected Behavior**
Documentation or make PseudoBox work with IconButton.

**Comment by segunadebayo** [comment]
Hi @gopinav,

Sorry for the late response. I believe you can pass all props of PseudoBox to the IconButton.

I mean

```jsx
<IconButton _hover={hoverStyles} _focus={focusStyles} />
```

Hope this helps.

**Comment by annisamalik** [comment]
Hi, may I ask if we can't change the icon in IconButton? I try to change the icon when the link is active. however, the icon doesn't change, here is what I try. I use iconify

```
_activeLink={{ icon: `${<Icon icon={outlineSpeakerNotes} />}` }}
```

**Comment by keeeeith** [comment]
> Hi @gopinav,
> 
> Sorry for the late response. I believe you can pass all props of PseudoBox to the IconButton.
> 
> I mean
> 
> ```js-jsx
> <IconButton _hover={hoverStyles} _focus={focusStyles} />
> ```
> 
> Hope this helps.

@segunadebayo I'm having an issue where `_hover` styles are over-riding `_focus` and `_active`. This is causing some weird effects. For example, the "focus" outline will appear on a button only after I've moved my mouse off of it. If I hover my mouse over it while the focus outline is visible, the outline will hide, because I have a different shadow set to show on hover. Any idea how to fix this? I'd like focus styles to have priority over hover styles.
```
<Button
    _hover={{ ...hoverStyles, boxShadow: "md" }}
    _focus={{ ...hoverStyles, boxShadow: "outline" }}
  />
```

**Comment by nikosolihin** [comment]
@keeeeith On the same boat, what did you end up doing?

**Comment by artokun** [comment]
@keeeeith did you ever find a solution to this?

**Comment by keeeeith** [comment]
@nikosolihin & @artokun I did not.

**Comment by artokun** [comment]
Well one hopeful attempt that seems to work is to use `_focusWithin`
