### ISSUE TITLE
Chakra components not honoring __css

### ISSUE THREAD

**Issue by trumpet2012** [chakra-ui/chakra-ui#4269]
# 🐛 Bug report

I've been attempting to wrap several Chakra components into a single custom component that is styled from the base theme. From reading the docs, it seems like the correct way to do this is to use the __css prop. However it doesn't seem like the provided Chakra components honor the __css that gets passed to them.

Using the `sx` prop instead of `__css` leads to the desired results. 

Here is the sample component I am trying to create (codesandbox link below):
```
// Style the custom form wrapper using __css and multi style config
export const FormControlThemed = (props) => {
  const [value, setValue] = useState("");
  const { variant } = props;
  const styles = useMultiStyleConfig("CustomForm", {
    variant
  });

  return (
    <FormControl __css={styles.wrapper} className="anvil-form-control">
      <Input
        variant="unstyled"
        __css={styles.input}
        value={value}
        onChange={(event) => setValue(event.target.value)}
      />
      <FormLabel __css={styles.label}>Label</FormLabel>
    </FormControl>
  );
};
```

## 💥 Steps to reproduce

1. Pass in styles using the `__css` prop to a provided Chakra component, like `FormControl`, `Input` and `FormLabel`.
2. Observe that styles don't take affect.

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-theme-custom-form-wrapper-g1gge?file=/src/index.js

## 🧐 Expected behavior

I would expect the Chakra components to use the provided `__css` prop to extend the `__css` rules that get created on them internally.

## 🧭 Possible Solution

It seems like there are inconsistencies about how they handle the props that get passed to the components. Some components like FormControl don't handle passing the `__css` prop down at all, https://github.com/chakra-ui/chakra-ui/blob/main/packages/form-control/src/form-control.tsx#L235. 

Other components like `FormLabel` appear to pass the `__css` prop down but it gets overwritten by it's own `__css` prop, https://github.com/chakra-ui/chakra-ui/blob/main/packages/form-control/src/form-label.tsx#L50. 

Box handles it a different way and adds the `__css` after it's internal `__css` rules, https://github.com/chakra-ui/chakra-ui/blob/main/packages/layout/src/box.tsx#L57. 

A possible solution could be to merge a provided `__css` with the one that gets added internally.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.6.4       |
| Browser          |      Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)      |
| Operating System |        MacOS Big Sur    |

**Comment by joshburer** [comment]
I'm running into the same issue on Chakra's Button component. Trying to extend it with some theming causes all of Chakra's Button styles to be cleared when the `__css` prop is used, but not `sx`. 

It seems like the Button component internally uses the `__css` prop, and providing this prop just overwrites it instead of extending. 

Here's a CodeSandbox to demonstrate the behavior for the Button component:
https://codesandbox.io/s/chakra-theming-with-css-prop-sqtlu

**Comment by ahrbil** [comment]
Hello @joshburer and @trumpet2012,  I have the same issue as well, `__css` wipes all the styles but `sx` prop works, but you can't override the styles via props anymore.
is there any workaround for this?
Thank you 🙏

**Comment by adhanji8** [comment]
Also having the same issue. Any workaround?

**Comment by segunadebayo** [comment]
This is happening because the Chakra components are already connected to the theming system and already consume the `__css` prop.

An alternative would be to spread the styles unto the component (as style props), this will effectively override the styles as needed.

If you need to build your own component and theming system, please create your own primitives using `chakra.<element>` syntax.

We're trying to reduce the API surface and not increase the level of flexibility of the system. It's a difficult problem to solve but I think we've provided enough primitives for you to build on top of.

Thanks for understanding.
