### ISSUE TITLE
Can't add custom variant to FormControl component

### ISSUE THREAD

**Issue by trumpet2012** [chakra-ui/chakra-ui#4270]
# 🐛 Bug report

When trying to add a custom variant to the `FormControl` component, it doesn't seem to work. I originally tried adding the variant under the `FormControl` component key. Looking at the `FormControl` component however it is actually in the theme as `Form` instead, https://github.com/chakra-ui/chakra-ui/blob/main/packages/form-control/src/form-control.tsx#L220 and https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/form.ts.

## 💥 Steps to reproduce

1. Extend the Chakra theme and add a custom variant for `Form`
2. Add the variant prop to the FormControl component
3. See styles not take affect

## 💻 Link to reproduction

https://codesandbox.io/s/chakra-theme-form-control-50btm?file=/src/input.js
CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🧐 Expected behavior

I expected the `FormControl` component to honor the variant styles defined in the theme.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.6.4       |
| Browser          |      Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)      |
| Operating System |       MacOS Big Sur     |

**Comment by ahrbil** [comment]
Hello @trumpet2012, any updates about this?

**Comment by bhishp** [comment]
Whilst I'm here, it also feels like the naming & documentation is confusing here. The docs only ever show a **single field** being wrapped by a FormControl component, but the docs say, "FormControl provides context... to form element**s**" (plural), in addition, the theming key is "Form", which sounds like it should relate to a `<form>` element. However, the context props probably make more sense on a field-level (you would want to mark particular fields as required, rather than the entire form in most cases I'd say). From looking at the underlying code it feels like FormControl is meant to be used on a per-field basis as opposed to a replacement for `form`, not sure if anyone else also finds it confusing?

Maybe we could benefit by renaming the theming key and making it clearer in the docs as well?

**Comment by bhishp** [comment]
First time contributing but here's a PR that should address this bug: https://github.com/chakra-ui/chakra-ui/pull/4317
