### ISSUE TITLE
Checkbox & Radio style props are not applied consistently

### ISSUE THREAD

**Issue by simontaisne** [chakra-ui/chakra-ui#4295]
### Description

When styling `Checkbox` & `Radio` components using the same style props, I expected a similar visual appearance but it's currently not the case.

### Link to Reproduction

https://codesandbox.io/s/eloquent-hoover-g4s8f

### Steps to reproduce

By adding the `background` or `borderColor` props to the `Checkbox` & `Radio` components.

### Chakra UI Version

1.6.4

### Browser

Chrome 91

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

### Additional Information

In the case of `Checkbox`, the style props are properly applied to the `container` part of the component. While with `Radio`, styles are applied to the `control` directly.

<img src="https://user-images.githubusercontent.com/233639/123562532-4137ec80-d77d-11eb-80af-fbaedf12b568.png">

**Comment by seaerchin** [comment]
i can take a look at this! just to be sure i'm understanding you correctly, you'd expect the container for the `radio` to also have css styling applied to it right? (i.e, looks identical to checkbox)

**Comment by seaerchin** [comment]
@segunadebayo just double checking - does it make sense to allow for users of chakra-ui to style the radio or is this by design?

**Comment by seaerchin** [comment]
@simontaisne while we wait for a reply, there's a reason why this happens. The style props put onto the `radio` component is selectively being applied onto the input element rather than the chakra div as you've pointed out.

for now, what could be done is to use either 

1. the custom `useRadio` that chakra exports to build your own custom radio component or
2. use a wrapper component (ilke a `Box`) and apply the desired styling there while setting `width = 'fit-content'` like so: 
```ts
export const StyledRadio = () => <Box background="yellow.100"
  border="1px"
  borderColor="yellow.300"
  width='fit-content'
><Radio>
    Radio
  </Radio>
</Box>
```

**Comment by simontaisne** [comment]
Hey @seaerchin! Thanks for looking into this issue.

Yeah, I'd expect both the `Radio` & `Checkbox` style props to behave the same. I'm unsure which component should be considered correct, but It seems to me that allowing the `container` to be customized is more useful than the `control` 🤷

> use a wrapper component (ilke a Box) and apply the desired styling there while

The issue here is that clicking the `Box` won't update the state of the `Radio`. You can take a look at https://codesandbox.io/s/amazing-bhaskara-tohwg and notice the difference with `Checkbox`.

**Comment by seaerchin** [comment]
@simontaisne the docs have [an example](https://chakra-ui.com/docs/form/radio#custom-radio-buttons) on creating your own custom radio component!

> The issue here is that clicking the Box won't update the state of the Radio

i think this could be remedied by setting `height = 'fit-content'` as well so that the `Box` is exactly the size of the checkbox component + label and then clicking on the `Box` should update the state of the radio! (see [here](https://codesandbox.io/s/epic-architecture-ztxv2)) I do have to say that this behaviour (using `Box` as a workaround) is less than ideal though :/

i think that this issue should be addressed primarily by bringing the component styling in line with what checkbox does (assuming that it's not an issue to do so) and depending on the follow up, a follow up PR to bring radio/checkbox behaviour to be identical.

**Comment by simontaisne** [comment]
> the docs have an example on creating your own custom radio component!

Right, but as you can see there's no way to get the visual radio `control` via this hook.

> i think this could be remedied by setting height = 'fit-content'

Interesting, I wasn't aware of that property. CSS Support is pretty limited atm though.

>  I do have to say that this behaviour (using Box as a workaround) is less than ideal though :/

Right, especially since it works out of the box with `Checkbox`.

> i think that this issue should be addressed primarily by bringing the component styling in line with what checkbox does

💯

**Comment by simontaisne** [comment]
Being addressed by @seaerchin 👍

**Comment by simontaisne** [comment]
Still waiting for a review on this one.

**Comment by simontaisne** [comment]
Still there!

**Comment by simontaisne** [comment]
😅 There's a pending fix..

**Comment by TheXienator** [comment]
I saw the PR linked to this has been closed, but there is no resolution for this issue is the pending fix still something that is being worked on?

**Comment by segunadebayo** [comment]
This is a flaw in Chakra v2. We'll fix this in v3 since this will lead to a significant breaking change for others.
