### ISSUE TITLE
How to overwrite Tailwind colors when using Chakra's dark mode

### ISSUE THREAD

**Issue by MarcLongJoyride** [chakra-ui/chakra-ui#4306]
### Subject

How to overwrite Tailwind colors when using Chakra's dark mode

### Description

When using Tailwind's bg-white, Chakra's dark mode is not overwriting that value to something like gray.800. It would be great if the main site had documentation on how to achieve this goal because I have not been able to solve this yet,

**Comment by aboveyunhai** [comment]
As far as how I understand the Tailwind CSS, you can treat it as any inline CSS styles.
So it takes precedence and will always override the current chakra `color` style. 

You have to manually do something like 
```js
const { colorMode, toggleColorMode } = useColorMode();

className={colorMode === "dark" ? "bg-gray" : "bg-white" }
```
Note that `bg-gray` and Chakra `gray.800` might be different. So you may need to define your own CSS style here.
unless `Chakra-UI` has some de-coupled CSS magic allows it to integrate with other CSS library seamlessly in the future.

**Comment by segunadebayo** [comment]
Thanks for chiming in @aboveyunhai. 

@MarcLongJoyride I don't have experience with Tailwind to suggest a better solution. Feel free to use `useColorModeValue` or even Tailwind's dark mode classes.

I'll close this out for now. If you need more ideas, please create a reproduction of the issue.

Thank you.

**Comment by nick-delirium** [comment]
I know its a very old and closed issue, but I'm adding this for folks who will have this exact question as well :) 

if you want to use `dark:` from tailwind with chakra-ui dark mode, add 

`darkMode: ["selector", ".chakra-ui-dark"],`

to your `tailwind.config.js` and voila, tailwind will use dark theme when it detects this class in DOM tree rather than detecting user settings from browser!
