### ISSUE TITLE
Toast is not centered when width exceeds 560px

### ISSUE THREAD

**Issue by nauynix** [chakra-ui/chakra-ui#4387]
### Description

When width exceeds 560px, I expect the toast it to still be centered. However, it seems to be aligned off-centered, regardless of width.

### Link to Reproduction

Easier to demonstrate in Chakra docs

### Steps to reproduce

1. Go to https://chakra-ui.com/docs/feedback/toast#custom-component, scroll down to `Custom Component`
2. Change the code to 
```
function CustomToastExample() {
  const toast = useToast({duration: 50000000})
  return (
    <Button
      onClick={() =>
        toast({
          position: "top",
          render: () => (
            <Box color="white" p={3} w="560px" bg="blue.500">
              Hello World
            </Box>
          ),
        })
      }
    >
      Show Toast
    </Button>
  )
}
```
3. Play around with the width that is originally set to `560px`
<img width="920" alt="image" src="https://user-images.githubusercontent.com/20250559/125771287-20052a6c-786b-463d-aaed-e03adc41ec68.png">

### Chakra UI Version

1.6.4

### Browser

Firefox, Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by seaerchin** [comment]
Hi, for clarification, you mean that the toast rendered is not displayed in the middle of the screen right?

**Comment by kb-ally** [comment]
Looks there was parent div
<div class="chakra-toast__inner" data-reach-alert="true" style="pointer-events: auto;max-width: 560px;min-width: 300px;margin: 0.5rem;">

which adds max-width: 560px, causes this behaviour

overriding max-width of chakra-toast__inner can solve. Is there any better ways to solve it ?

**Comment by seaerchin** [comment]
i'm taking a stab at this!

**Comment by seaerchin** [comment]
ok so the reason that this happens is pretty simple - as @kb-ally pointed out, there's a `max-width` property being set.

chakra's `useToast` hook is fairly intricate, and what happens with a custom render function is that `render` is being called within a provider with a few props (the interface being exposed is `UseToastOptions`) together with a few defaults. 

This, however, is being wrapped by `toast.class` (which is, in turn, wrapped by `toast-manager`). the point of `toast.class` , as far as i can tell, is to just mount the toast correctly at the appropriate location by means of a `portal`. `toast-manager` is the one that actually provides the methods (it binds to `toast.class` through passing `this.bindFunctions` (from `toast.class`) to the `notify` prop (of `toast-manager`). 

in `toast-manager`, the stateful logic is then encapsulated (eg: where to position the toast relative to the _previous_ toast). The `toast-manager` then calls another toast component, `toast.tsx`, which handles the animation of the `toast`. This component is the final wrapper around our actual `render` function and is the one causing the trouble.

From what i can tell, the problem stems from the `render` function we pass in having a greater max width than the `ReactAlert`'s max width inside `toast.tsx`. The invisible animation component which wraps the visible toast is then centered correctly but the actual toast we pass into it overflows. 

Hence, there could be 2 possible fixes - either we make the animation comaponent aware of the props passed in (specifically, only the `maxWidth` prop) or we just adjust the `maxW` in the animation component itself.

i'm opposed to the sceond solution because of [modal styling concerns](https://css-tricks.com/considerations-styling-modal/#dealing-with-width) and i'll be implementing the first one! 

let me know if you guys have any thoughts
