### ISSUE TITLE
[Modal Dialog] ModalCloseButton overlaps ModalHeader

### ISSUE THREAD

**Issue by Hagendorn** [chakra-ui/chakra-ui#4395]
### Description

As you can see with my example, the ModalCloseButton overlaps the ModalHeader. This leads to the problem, that a long text is not readable. 

### Link to Reproduction

https://codesandbox.io/s/happy-cloud-1z5tr?file=/src/index.tsx

### Steps to reproduce

1. Click 'Open Modal'

Maybe you have to adapt the browser window to see that the close button overlaps the text.

### Chakra UI Version

1.6.5

### Browser

Google Chrome 91

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information
Screen shot from my example:
![Screen Shot 2021-07-16 at 11 44 14](https://user-images.githubusercontent.com/200940/125928488-955edc13-1f42-4770-9c84-bde28e44039e.png)

Screen shot from the chakra-ui docs, when manipulation the text:
![Screen Shot 2021-07-16 at 11 29 35](https://user-images.githubusercontent.com/200940/125929404-d53adc79-64a5-4cf7-bb3c-5df0ddc727b7.png)

**Comment by anubra266** [comment]
Just add a margin to the `ModalHeader` component. `mr="6"`. Adding that to the repo is unnecessary complexity, because it would be a not needed push for modals, that don't use the close button. Chakra would have to detect if a close button is present. Meanwhile just one prop solves this on we users' end.

**Comment by Hagendorn** [comment]
Not sure if this is a good idea to move the problem to the users' end, because now I have to know when Chakra changes some  layout styles for `ModalHeader` or `ModalCloseButton`. I have then to check that applied margin still works.

**Comment by anubra266** [comment]
So how do you propose this works internally.

**Comment by Hagendorn** [comment]
I don't know how this should be solved. I mean me as user I would like to avoid to know that I have to apply some margin to the `ModalHeader` which I don't know how long `6` is the correct one.

Maybe there are other solutions instead of `ModalHeader` should try to detect if there is a `ModalCloseButton` rendered. Maybe `ModalHeader` will get a new boolean property which is responsible to use more space for the right padding to ensure that the `ModalCloseButton` has enough space not to overlap the text. But this feel to me that this is not a good solution.

Or set a higher right padding to the `ModalHeader` independent if there exists a `ModalCloseButton`. Sure this has the side effect that if no close button is used. The header could use more space for text, but I think this is a good tradeoff.

**Comment by anubra266** [comment]
@with-heart I'm taking a stab at this, but I have two ways in mind, and would love your input on which approach is better for Chakra UI.
1. Programmatically detect if A `CloseButton` exists, using it's `displayName` then add the necessary margin to the `Header`
2. The `Header` uses a flex display, and the `CloseButton` has to be it's child with `ml` set to `"auto"`

I think 1 is more complexity we might want to avoid. But worse, 2 is likely a breaking change, though it'll be simpler to achieve since we're only changing styles.

**Comment by segunadebayo** [comment]
Thanks for chiming in @anubra266 .

@Hagendorn. I really think this should be handled in the userland for a start. Any change to this might trigger a breaking change to other consumers of Chakra. Let's not maintain more code than necessary.

I'd recommend adding a margin or reducing the length of the heading content in your app.
