### ISSUE TITLE
Drawer doesn't support transitions other than Slide, contrary to documentation

### ISSUE THREAD

**Issue by pianomansam** [chakra-ui/chakra-ui#4423]
### Description

When I change the motionPreset property on a Drawer, I expect a different transition. According to [the documentation](https://chakra-ui.com/docs/overlay/drawer#drawer-props), the motionPreset property is supposed to change the animation style. But it's clear in the source code that only the slide animation is implemented:

https://github.com/chakra-ui/chakra-ui/blob/main/packages/modal/src/drawer.tsx#L114

### Link to Reproduction

https://codesandbox.io/s/angry-easley-bgnjq?file=/pages/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/angry-easley-bgnjq?file=/pages/index.js
2. Click on "Toggle"
3. Observe that though the motionPreset property is set to "slideInBottom", the Drawer still slides in from the side.

### Chakra UI Version

1.6.5

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by seaerchin** [comment]
from looking at the source, it should be using `ModalTransition` instead of `Slide` to animate. i could try looking into this!

**Comment by seaerchin** [comment]
@pianomansam i actually think the more appropriate solution is to update the typings and remove the `motionPreset` prop. 

i'm not sure adding `motionPreset` makes sense; if we were to consider the `Slide` animation only, we'd need to account for whether it makes sense to have different `placement` and slide direction. for example, we place the drawer at the top and have it slide in from left/bottom/right. 

this seems to be counter-intuitive and now exposes additional complexity to the developer when using the `Drawer` rather than having it automatically generated by chakra itself. as idt many people will have different `placement`/slide direction, this seems to be an unneeded change which encumbers the majority of usecases for little marginal benefit/customizability. 

wrt the `Scale` animation, i'm not too sure it makes sense for a `Drawer` component, regardless of where the `Drawer` is located. 

If you do desire to have your own Drawer which has special animation, you could do it through consuming Chakra's transition components [here](https://chakra-ui.com/docs/components/transitions) and just applying simple styling. for what it's worth, the `DrawerContent` is the one that consumes the styling so it'd be possible to only swap out the `DrawerContent` and still have a working `Drawer`

i'd love to hear any thoughts you might have on this!

**Comment by pianomansam** [comment]
I agree that Slide is probably the only animation that makes sense. However, unless I'm missing something, it's not currently possible to have it simply show and hide. That's what originally let me do this discovery... I simply wanted to disable the animation with `motionPreset="none"` and it had no effect.

**Comment by seaerchin** [comment]
could you share more on this? my main concern is that a prop like `isAnimated` might lead to more cruft and a cluttered api. would you apply additional animation styling onto the drawer or would it be just a simple show/hide?

**Comment by seaerchin** [comment]
i think what could happen here is that we extract transition related component and props into a separate component (something like `DrawerTransition`), which allows the users to apply transition styling. 

then, we preserve display related props/the actual content showing on screen on `DrawerContent`. This allows us to have an API like so:
```tsx
<DrawerTransition {...transitionProps}>
  <DrawerContent {..displayProps}>
    {children}
  </DrawerContent>
</DrawerTransition>
```

in this case, users like yourself who wish for no transition could simply omit the `DrawerTransition` component whereas those who wish for additional transition styling could apply them on `DrawerTransition`. (while still preserving the `placement` prop) 

wdyt about this solution?

**Comment by pianomansam** [comment]
I agree that unless there's already a precedent like `isAnimated` elsewhere, it would lead to clutter. I like the idea of `<DrawerTransition>` as it matches the pattern already used in Drawer, but the compound components of Drawer already seem like a lot. I'm not entirely sure what the best approach is best, but I'd lean towards DrawerTransition.

**Comment by seaerchin** [comment]
> I agree that unless there's already a precedent like `isAnimated` elsewhere, it would lead to clutter. I like the idea of `<DrawerTransition>` as it matches the pattern already used in Drawer, but the compound components of Drawer already seem like a lot - so many components to create a "simple" element. I'm not entirely sure which best approach is best, but I'd lean towards DrawerTransition.

sure, i can do this! however, i'm relatively inexperienced wrt frontend code and i wanted to confirm 2 things with the chakra maintainers @with-heart @segunadebayo 

1. should we adopt the compoujnd components pattern for this component? this seems to make sense and i see this happen with other components as well (most notably `ModalTransition` which isn't publicly stated in the documentation) 
2. that `getDialogProps` is mostly just for accessibility/behaviour reasons and it should be set on the element that contains the content, not the animation component

**Comment by segunadebayo** [comment]
The point of the Drawer using only the `Slide` transition is by design. The prop table used in the docs is automatically inferred from the typings. There should be no `motionPreset` prop in the `Drawer` documentation.

I've updated the types to reflect this.

Re: @seaerchin We're looking to implement the compound component pattern for all transitions in the next major. Changing that right now might be considered breaking.
