### ISSUE TITLE
<Stack /> renders children with key={index}, even if children have a key (when using shouldWrapChildren or divider)

### ISSUE THREAD

**Issue by jamesopti** [chakra-ui/chakra-ui#4447]
### Description

When the children of a <Stack> change, they are re-rendered if their index changes.  (when using shouldWrapChildren or divider)

### Link to Reproduction

https://codesandbox.io/s/boring-euler-kq2jn?file=/src/index.tsx

### Steps to reproduce

1. Go to the codesandbox above
2. Click on the button to remove the last fruit in the list. None of the other `<Fruit>` are destroyed. Only the last one is.
3. Click on the button to remove the first fruit in the list. All of the `<Fruit>` are destroyed and recreated.

The root cause of this is the usage of array indexes for the keys: https://github.com/chakra-ui/chakra-ui/blob/752910bb1f4604213134fc8ea9f547bccd6a2f09/packages/layout/src/stack.tsx#L136-L149

A fix would be to prefer `child.key` if it exists, falling back to index.

### Chakra UI Version

1.6.4

### Browser

Chrome Version 91.0.4472.164 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

When generating the child clones, this would prefer the child key:

```ts
validChildren.map((child, index) => {
  const key = child.key || index;
  const isLast = index + 1 === validChildren.length
  const wrappedChild = <StackItem key={key}>{child}</StackItem>
  const _child = shouldWrapChildren ? wrappedChild : child

  ...

  return (
    <React.Fragment key={key}>
  ...
```

**Comment by abhishekmg** [comment]
As per the above codesandbox , I did the following steps which fixes the toast message when first Fruit is removed .



- Comment out the toast useEffect in `Fruit` component 
- Added the toast in the `onRemove` func call , where we are mapping the `Fruit` . 

toast fix : https://codesandbox.io/s/loving-zhukovsky-ul945?file=/src/index.tsx 

The reason why we get all those toast messages when the first Fruit is removed , is due to re-render like @jamesopti mentioned . 

Also replacing the `Stack` which a normal div also fixes the issue , this must be due to `usage of array indexes for the keys` in Stack component . 

But is there any specific issue that might arise because of this re-render ?
