### ISSUE TITLE
NumberInput problem with position sticky

### ISSUE THREAD

**Issue by gustavochavarria** [chakra-ui/chakra-ui#4470]
### Description

NumberInput and Input has z-index that collapses with position sticky

### Link to Reproduction

https://codesandbox.io/s/romantic-violet-sdj2f?file=/src/index.js

### Steps to reproduce

The green box is sticky. Please scroll down and see that NumberInput get over exposed

### Chakra UI Version

1.6.5

### Browser

Chrome 92

### Operating System

- [X] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/37227357/127076801-e1c600ac-bf50-4df0-9276-33b6e8e49b18.png)

![image](https://user-images.githubusercontent.com/37227357/127076870-96a49af4-911d-45d7-bf0c-c7a7099ab399.png)

![image](https://user-images.githubusercontent.com/37227357/127077498-29d5b5d4-d902-4ff0-8208-66683715eb72.png)

**Comment by gustavochavarria** [comment]
I fixed it with this:

`  position: sticky;
  z-index: 1000;
  transform: translateZ(0); 
`

https://axe369.medium.com/chrome-position-sticky-with-z-index-problem-4b57bb80816e

**Comment by segunadebayo** [comment]
Hi @gustavochavarria,

This was a design decision, not exactly a bug.

**Input:** we needed to add those to get Input working with InputElements and InputAddons
**NumberInput:** because it extends Input styles, it gets inherited.

I recommend adding `zIndex:1` to the position sticky element to resolve this on your end. Removing the zIndex values from the component might be a breaking visual change.
