### ISSUE TITLE
Scoped global styles - `<Global sx={{ body: {} }} />`

### ISSUE THREAD

**Issue by mayteio** [chakra-ui/chakra-ui#4472]
### Description

A component that lets you define global styles from anywhere in your component tree, rather than in your theme.

### Problem Statement/Justification

Occasionally you need to apply global styles for a specific page/component only. Consider changing the `body` `background-image` from a `Login` component that's nested in a `Layout` component:

```
<ChakraProvider>
   <Layout> // applies padding/layout changes
    <Login />
  </Layout>
</ChakraProvider>
```

There's no current way, to my understanding, to modify `body` styles from within the `<Login />` component.

### Proposed Solution or API

`<Global sx={{ body: { bg: 'red' } }} />`

This would override the `body` component's background to be the color `red` from anywhere within your app.

Alternatively, have a special `global` prop in `sx`:

`<Box sx={{ global: { body: { background: "red" } } }}>`

### Alternatives

Use emotion's `<Global />` component, though it isn't theme aware out of the box.

### Additional Information

- [emotion's `Global` component](https://emotion.sh/docs/globals)
- [styled-components `createGlobalStyle` API](https://styled-components.com/docs/api#createglobalstyle)

**Comment by primos63** [comment]
The use case seems very narrow to me. The problem is even described starting with the word 'occasionally' -

So if one changes the global style from a component, assuming that is what is meant by local scope, it won't just be for that page/component as it's a global style. That means you need a way to reset the global style to it's original setting, possibly using useEffect, but I'm thinking Chakra doesn't know when you navigate to another page. Your solution only accounts for changing and not resetting. It also doesn't take into account dark mode.

**There's no current way, to my understanding, to modify body styles from within the <Login /> component.**
Using a component like `Box` as-is, correct. However, you could modify the body styles. Take a look at the ChakraProvider, `packages/react/src/chakra-provider.tsx` code. It uses a ThemeProvider and GlobalStyles provider, `packages/system/src/providers.tsx`. The GlobalStyles provider uses Emotion's <Global />.

Here's what I've come up with in my [CodeSandbox](https://codesandbox.io/s/chakra-ui-theme-extension-w5u2n).

My opinion: I just don't think this is something that is needed in Chakra. The use case is very specific and doesn't present itself often. It's easy enough to add something like what I have in my CodeSandbox example if one needs it. Again that's just my opinion.

**Comment by anubra266** [comment]
@mayteio you can use the `Global` component from emotion. As it's a dependency of Chakra UI

**Comment by mayteio** [comment]
Nice, that's what I was after. Thank you.

**Comment by verekia** [comment]
If all you need is a rare one-off, you can also use `<style>` without relying on any library:
```jsx
<style dangerouslySetInnerHTML={{ __html: 'body { color: red }' }} />
```
