### ISSUE TITLE
The onClick of the switch is invalid.I need stopPropagation in a Table.

### ISSUE THREAD

**Issue by linxianxi** [chakra-ui/chakra-ui#4494]
### Description

I need onClick in a Table.

### Link to Reproduction

https://codesandbox.io/s/headless-tree-kzv34?file=/src/App.js

### Steps to reproduce

1. click the switch,the row click event for the table is triggered.

### Chakra UI Version

lastest

### Browser

google

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Clicking on a row of a table to jump to a page is a common requirement

**Comment by primos63** [comment]
This isn't  an issue with Chakra's code for `Switch`. Perhaps this should be explicitly documented for the component?

As it is based on `Checkbox`, `Switch` does not have an `onClick` event. It has `onChanged` and `onBlur`. Changing the event handler from `onClick` to `onChange` will cause the `stopPropagation` function to execute.

```jsx
        <Switch
          onChange={(e) => {
            e.stopPropagation();
            console.log("click switch");
          }}
        />
```

Then second example works because the event on `Switch` is propagated to its parent `span` which supports `onClick`.

**Comment by linxianxi** [comment]
> This isn't an issue with Chakra's code for `Switch`. Perhaps this should be explicitly documented for the component?
> 
> As it is based on `Checkbox`, `Switch` does not have an `onClick` event. It has `onChanged` and `onBlur`. Changing the event handler from `onClick` to `onChange` will cause the `stopPropagation` function to execute.
> 
> ```js
>         <Switch
>           onChange={(e) => {
>             e.stopPropagation();
>             console.log("click switch");
>           }}
>         />
> ```
> 
> Then second example works because the event on `Switch` is propagated to its parent `span` which supports `onClick`.
StopPropagation of onChange is useless

**Comment by linxianxi** [comment]
> This isn't an issue with Chakra's code for `Switch`. Perhaps this should be explicitly documented for the component?
> 
> As it is based on `Checkbox`, `Switch` does not have an `onClick` event. It has `onChanged` and `onBlur`. Changing the event handler from `onClick` to `onChange` will cause the `stopPropagation` function to execute.
> 
> ```js
>         <Switch
>           onChange={(e) => {
>             e.stopPropagation();
>             console.log("click switch");
>           }}
>         />
> ```
> 
> Then second example works because the event on `Switch` is propagated to its parent `span` which supports `onClick`.

StopPropagation of onChange is useless

**Comment by primos63** [comment]
For the way you have your example setup, absolutely it is! Your example said the first Switch didn't work and I explained why. 

The CodeSandox you provided does not contain a Chakra Table. If it did then it would have `<Td>` tag in which `<Switch />` would reside. So like your second "row" which contains a `<span>` tag and stops the propagation of the click event from the `Switch`, you would put the `onClick` event handler on the `<Td>` and stop the click propagation.

If you're making your own table from `<Box>` tags and want a `Switch`, then your best bet is to wrap your switch with `<Box as="span">` and attach an `onClick` handler which will stop the propagation.

This isn't an issue with Switch, Checkbox or Radio which would all have the same behavior. Even if you used `<input type="checkbox" or type="radio" />`, the onChange handler would be triggered and a `click` event propagated. The behavior of Switch, Checkbox and Radio is consistent with the standard HTML tag `input` with a type of checkbox or radio.

[Here's a modified CodeSandbox](https://codesandbox.io/s/determined-wildflower-i6i92) showing use of the standard `input` tag, using Chakra Table and your example.

For me this isn't an issue with the Chakra component, but I don't make that decision. The core team members do. They can review the issue and make the appropriate decision.

**Comment by linxianxi** [comment]
> For the way you have your example setup, absolutely it is! Your example said the first Switch didn't work and I explained why.
> 
> The CodeSandox you provided does not contain a Chakra Table. If it did then it would have `<Td>` tag in which `<Switch />` would reside. So like your second "row" which contains a `<span>` tag and stops the propagation of the click event from the `Switch`, you would put the `onClick` event handler on the `<Td>` and stop the click propagation.
> 
> If you're making your own table from `<Box>` tags and want a `Switch`, then your best bet is to wrap your switch with `<Box as="span">` and attach an `onClick` handler which will stop the propagation.
> 
> This isn't an issue with Switch, Checkbox or Radio which would all have the same behavior. Even if you used `<input type="checkbox" or type="radio" />`, the onChange handler would be triggered and a `click` event propagated. The behavior of Switch, Checkbox and Radio is consistent with the standard HTML tag `input` with a type of checkbox or radio.
> 
> [Here's a modified CodeSandbox](https://codesandbox.io/s/determined-wildflower-i6i92) showing use of the standard `input` tag, using Chakra Table and your example.
> 
> For me this isn't an issue with the Chakra component, but I don't make that decision. The core team members do. They can review the issue and make the appropriate decision.

https://codesandbox.io/s/elegant-dream-u3ywf.   It works if you write onClick on input,onClick should be passed to input. Like this: https://ant.design/components/switch/#API

**Comment by primos63** [comment]
The only point of having an `onClick` for some components would be to stop the propagation of the event. The handler is otherwise, pointless.

`Switch` has 3 parts, input, track and thumb. Depending on which part of the switch you activate, track or thumb, you will receive 2 click events. This could be handled by adding a new property to the `Switch` component, like `stopClickPropagation: boolean` and using the existing wrapping tag to execute a `stopPropagation` for the click event. 

Whether it is changed in Chakra or you apply it to your code, the solution comes down to wrapping. It took less than 25 lines to create the higher order functional component to accomplish this ([see CodeSandbox](https://codesandbox.io/s/elated-matsumoto-vggc0)). 

If you feel strongly about the issue, you could apply the necessary code changes, tests and docs for a PR. The change may also need to be applied to both `Checkbox` and `Radio` as they seem to exhibit similar behavior. As for me, I'd like to hear what thoughts the core team has about it.

**Comment by segunadebayo** [comment]
From the look of this issue, I think this has more to do with how you're orchestrating the Switch and Table components @linxianxi.

I'd recommend you share a CodeSandbox that represents the exact issue you're facing so we can really surface the issue.

Given that I might be wrong, if you feel strongly about it, feel free to open a PR that demonstrates the fix (before/after) and I'll take a look.
