### ISSUE TITLE
Breadcrumb separator does not work when item is returned by another component

### ISSUE THREAD

**Issue by samedii** [chakra-ui/chakra-ui#4496]
### Description

When returning a BreacrumbItem from a custom component I expected chakra to see that this is still a BreadcrumbItem and create separators as usual

### Link to Reproduction

https://codesandbox.io/s/intelligent-mountain-czecb?file=/src/index.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/intelligent-mountain-czecb?file=/src/index.js
2. There is no separator between A and B as there would be if the item was not returned by a custom component.

### Chakra UI Version

1.6.5

### Browser

Google Chrome 91

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by primos63** [comment]
I don't believe this is an issue with Chakra's code. Perhaps this behavior should be documented.

The Failure function should be
```jsx
function Failure(props) {
  return (
    <BreadcrumbItem {...props}>
      <Text>A</Text>
    </BreadcrumbItem>
  );
}
```
Breadcrumb processes all of its children and if valid adds the separator property to the child. `<Failure />` is a valid React component, but it's not rendered at the time Breadcrumb is processing its children. Failure gets modifed and contains the separator, but because those props are not passed to Failure, the separator is undefined and does not appear on the screen.

**Comment by samedii** [comment]
Thank you! That is a nice solution. However, is this also what you are meant to do when you have multiple BreadcrumbItems in a Fragment? (This is my actual use case)

Example:
https://codesandbox.io/s/confident-worker-gswlu

**Comment by primos63** [comment]
Yes, you'd need to pass the props for each item. It doesn't work without it. You can put the creation of those breadcrumb items in a loop so {...props} is only written once.

**Comment by samedii** [comment]
Okay thanks :+1: , I'll close this then
