### ISSUE TITLE
Tabs: defaultIndex does not fully support SSR

### ISSUE THREAD

**Issue by mjnaderi** [chakra-ui/chakra-ui#4506]
### Description

I have a `Tabs` component and one tab is selected initially (using defaultIndex). When page is rendered at server side, the tab does not seem selected (no blue border), and it becomes selected after JavaScript loads on client side.

### Link to Reproduction

https://codesandbox.io/s/cool-jang-xt0jz?file=/pages/index.tsx

### Steps to reproduce

1. Go to https://xt0jz.sse.codesandbox.io/
2. Open Chrome DevTools, Open Settings. In "Debugger" section click on "Disable JavaScript".
3. Reload the page.
4. The second tab does not seem active (has no colored underline).

### Chakra UI Version

1.6.5

### Browser

Any Browser

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Server-rendered output:

![image](https://user-images.githubusercontent.com/2115303/127970898-e8fafa50-2a27-428b-9cc6-429543239cdd.png)

Expected output:

![image](https://user-images.githubusercontent.com/2115303/127970951-6452ec2e-357b-4f30-9fa6-0949451e02e2.png)

Potentially related issue: #4483

**Comment by segunadebayo** [comment]
This is a known problem with how we manage the index of components. We can't compute the index of components in an SSR  environment that's why it's set to `-1` by default, on the client-side, we try to get the index as quickly as possible.

We intend to move away from `index` and `descendants` in the next major release and use `value` instead. That way, we don't need to rely on index and it'll work in SSR as well.

**Comment by hems** [comment]
> We intend to move away from `index` and `descendants` in the next major release and use `value` instead. That way, we don't need to rely on index and it'll work in SSR as well.

is there an estimate date for solving this problem and/or next major release?

SSR is pretty much a requirement these days so would be good what sort of timeframe you have in mind otherwise we might have to work around this issue in a more "manual" way.

**Comment by LucasSolares** [comment]
Hello! If you happen to get here is because you love Chakra UI so much that you do not want to change it just because of defaultIndex error, until we wait for a solution here we can do the next that works for me, install this package
`@uidotdev/usehooks`

There you can use the hook `useIsClient()`

And do something like this

```
const [accordionIndex, setAccordionIndex] = useState<number>(); // Notice that I leave this as undefined if you put any value here it will fail.

const isClient = useIsClient();
 
 useEffect(() => {
    if (isClient) setAccordionIndex(0); // You can do any modification on the index here with your values, and will be applied.
  }, [isClient]);

  const handleChange = (index: number) => setAccordionIndex(index);
  
  <Accordion index={accordionIndex} onChange={handleChange} >
      // rest...
    </Accordion>
```

Hope this helps somebody and I hope we can have this change soon.
