### ISSUE TITLE
If the popover trigger does not set tabIndex,click the trigger will not close the content

### ISSUE THREAD

**Issue by linxianxi** [chakra-ui/chakra-ui#4529]
### Description

If the popover trigger does not set tabIndex,click the trigger will not close the content

### Link to Reproduction

https://codesandbox.io/s/headless-tree-kzv34?file=/src/App.js

### Steps to reproduce

1. click on trigger to open it
2. click on trigger to close it
3. example 1 close failed, but example 2 worked.

### Chakra UI Version

lastest

### Browser

chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by takethefake** [comment]
Hej @linxianxi thanks for your report!

In general: `a11y`-wise it is best to use the `Button` component as a trigger to open the popover. 

In reference to your issue: as stated in the docs(https://chakra-ui-8rj8qc1pt-chakra-ui.vercel.app/docs/overlay/popover#basic-usage) you have to make sure that the component inside `PopoverTrigger` is focusable.

If you try to close the popover with a non-focusable Element as a trigger. `use-focus-on-hide` inside `use-popover` tries to focus the element inside `PopoverTrigger` which does not work.

I didn't understand fully why the modal reopens if it can't focus the element in `PopoverTrigger` but since having a focusable element in `PopoverTrigger` is mandatory there shouldn't be any adjustments on chakras side.
