### ISSUE TITLE
[ButtonGroup] Use negative spacing to hide extra border

### ISSUE THREAD

**Issue by nelsieborja** [chakra-ui/chakra-ui#4531]
### Description

Use ButtonGroup's `spacing` instead of Button's `mr` to set the negative value once.

### Problem Statement/Justification

Currently, you will have to repeat the code on every button (except for the last one) and on every button group. Moving this logic to the parent element would seem to provide easier customisation and lesser code.

### Proposed Solution or API

So instead of doing this:
```
<ButtonGroup isAttached>
    <Button mr="-px">Day</Button>
    <Button mr="-px">Week</Button>
    <Button>Month</Button>
  </ButtonGroup>
```

do this:
```
<ButtonGroup isAttached spacing="-px">
    <Button>Day</Button>
    <Button>Week</Button>
    <Button>Month</Button>
  </ButtonGroup>
```

### Alternatives

Or why not just remove the extra borders automatically when `isAttached` is passed?

**Comment by takethefake** [comment]
Hej @nelsieborja thanks for your feedback!

Unfortunately, I didn't get what you are trying to achieve. What is the goal that you want to achieve by adding `margin-right` to your buttons and how does this affect the borders from `ButtonGroup`?

**Comment by alkamin** [comment]
@takethefake here is a sandbox that describes the problem: https://codesandbox.io/s/young-sound-l8x0z?file=/src/index.tsx

The goal is to eliminate the double-wide border that results when using `variant="outline"` and `isAttached` on the same button group. Currently, each button is required to have a `mr="-1px"` or some equivalent in order to eliminate the double-wide border. It would be convenient to still apply the `spacing` prop to the buttons within a `ButtonGroup` event even if `isAttached` is present.

Hopefully we can get this one re-opened. I found the current behavior surprising.

**Comment by novascreen** [comment]
I think `ButtonGroup` should handle the negative margin whenever `isAttached` is `true`, anything else is unintuitive and unnecessarily repetitive
