### ISSUE TITLE
<Select> cannot be made inline

### ISSUE THREAD

**Issue by bard** [chakra-ui/chakra-ui#4549]
### Description

When I added `display="inline"` to `Select`, I expected it to become inline, but it didn't.

### Link to Reproduction

https://codesandbox.io/s/magical-ives-r7q7d

### Steps to reproduce

1. Open sandbox.

### Chakra UI Version

1.6.5

### Browser

Google Chrome 92

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

It seems to be related to the fact that `Select` generates a wrapper `div`, and that properties passed to `Select` go to the underlying `select`, not the `div`.

Related: 

- https://github.com/chakra-ui/chakra-ui/issues/241
- https://github.com/chakra-ui/chakra-ui/issues/989 (suggests a workaround, but doesn't appear to work)

**Comment by takethefake** [comment]
Hej @bard! :)

The `Select` Component has a `display:inline` but it also has `width:100%` you need to adjust the width to fit inside your container so no breaks happen. Since `widths` are ignore if you set a component `inline` you need to go with `display:inline-block` and `width:initial` to fit the content of your select box.

https://codesandbox.io/s/agitated-maxwell-tzisc?file=/src/index.js

**Comment by bard** [comment]
@takethefake I see! Apologies for the false alarm then, and thank you for the explanation and solution!

**Comment by wspringer** [comment]
Using the latest version. It doesn't work. The wrapper is still getting generated with display:block.
