### ISSUE TITLE
[Core] V0.6.1 cant start/build with Next.js

### ISSUE THREAD

**Issue by JClackett** [chakra-ui/chakra-ui#458]
**Describe the bug**
Upgrading to the latest version of chakra breaks my site using Next.js

**Expected Behavior**
Works as expected.

**To Reproduce**
Upgrade and start next.js server

**Suggested solution(s)**
Not sure yet, looks like an issue in the CSSReset component, but might me due to emotion

```
TypeError: Cannot read property 'body' of undefined
    at tailwindPreflight (<path>/node_modules/@chakra-ui/core/dist/CSSReset/preflight.js:23:56)
    at styles (<path>/node_modules/@chakra-ui/core/dist/CSSReset/index.js:64:56)
    at Object.children (<path>/node_modules/@emotion/core/dist/core.cjs.dev.js:239:51)

```

**Comment by segunadebayo** [comment]
Hi @JClackett,

Thanks for this issue.

Quick questions:
- Is CSSReset insider the ThemeProvider? If not, kindly move it inside the ThemeProvider
- If it is, do you have a `theme.fonts.body` field in your theme, I think might also be the problem.

If it's none of these, please send me a CodeSandbox replica of this issue and I'll fix it right away.

**Comment by JClackett** [comment]
Hi @segunadebayo 

It is inside a ThemeProvider and im not using theme.fonts.body :(

I will keep investigating and try to make a replica!

**Comment by JClackett** [comment]
Okay, so im using heroku to host my next site, and i just cleared the cache and it seems to be working again.. not sure what happened there? 

thanks for the quick response though

**Comment by jeremyadavis** [comment]
Not sure if this helps as I haven't been able to debug this thoroughly yet, but last night I started upgrading some deps and I hit a similar issue and it seems to be with @emotion/core going from 10.0.27 to 10.0.28.

I was able to upgrade chakra-ui/core from 0.5.2 to 0.6.1 by itself without issue, but as soon I bump @emotion/core, I get major freakout errors.

**Comment by jeremyadavis** [comment]
Unfortunately I couldn't reproduce this with a simple Code Sandbox. 
https://codesandbox.io/s/chakra-ui-sandbox-7sgjw?fontsize=14&hidenavigation=1&theme=dark

My ChakraUI setup doesn't use create-react-app, it's a 'ui' package that uses Storybook to view the components so maybe it's related to some storybook conflict.

**Comment by jeremyadavis** [comment]
Just a followup to my earlier comment. Turns out another package in my monorepo had @emotion/core as a dep so when I upgraded my storybook/chakra package's dep of it, something went haywire with the ThemeContext.
All's good now.

**Comment by geocine** [comment]
@jeremyadavis how did you solve this, I am experiencing the same issue but now with Gatsby

**Comment by jeremyadavis** [comment]
@geocine For the most part, my issue presented itself like the component didn't have proper access to the ThemProvider context, so just double check that all that is in order with ThemeProvider and CSSReset.
My setup wasn't a Gatsby one so I'm uncertain how that setup might be different.

My actual setup is a monorepo where I have my app in its own package, then a separate UI package that centralize all my app's UI components, a majority of them being ChakraUI pass through.

My issue was that my original app had used ChakraUI directly and it's dependencies, so when I migrated ChakraUI out of my app package and into my 'ui' package, I forgot to migrate the @emotion dependencies along with @chakra-ui/core. When I went about upgrading the 'ui' package dependencies I got my very odd error due to having two @emotion/core versions in the monorepo dependencies.
Luckily, I just had to remove the one from the app package and everything was happy again, so I didn't have to figure out how to make them coexist.
