### ISSUE TITLE
Chakra UI Accordion large number creates performance bottleneck

### ISSUE THREAD

**Issue by domingasp** [chakra-ui/chakra-ui#4598]
Here's a sandbox with 250 [accordion panels](https://codesandbox.io/s/y4vs4), quickly sent it through the profiler and found that all 250 panels are re-rendered because of `AccordianContext.Provider` changed (because of hooks, the classic case with useContext.) 

![image](https://user-images.githubusercontent.com/7134153/129209590-d84b4d9e-b6a3-49a1-b606-3d25603cc96a.png)

Since it is not anything that we the users can control, I believe it has to be looked further by chakra team.

_Originally posted by @payapula in https://github.com/chakra-ui/chakra-ui/discussions/4554#discussioncomment-1163805_

**Comment by segunadebayo** [comment]
Hi @domingasp.

This is largely caused by our use of `index` to determine the open/closed state of the accordion. From a UX perspective, it's recommended not to use too many accordions on the same page.

From a performance perspective, we intend to move away from `index` for most components in the next major release. The `index` approach requires us to read the state of the DOM, check the relative index of accordion, and sync that with the component state. This also makes the SSR output inconsistent with the Client output since we need to read the DOM.

We have ideas to drastically simplify this in the next major release.

Thanks for understanding.

**Comment by natBizitza** [comment]
This causes another issue. Whenever I reorder items the selected item is determined by the index (by position not by  _the real_ ID of the item). Hence, the wrong item is selected.

**Comment by CEOSiyris** [comment]
> Hi @domingasp.
> 
> This is largely caused by our use of `index` to determine the open/closed state of the accordion. From a UX perspective, it's recommended not to use too many accordions on the same page.
> 
> From a performance perspective, we intend to move away from `index` for most components in the next major release. The `index` approach requires us to read the state of the DOM, check the relative index of accordion, and sync that with the component state. This also makes the SSR output inconsistent with the Client output since we need to read the DOM.
> 
> We have ideas to drastically simplify this in the next major release.
> 
> Thanks for understanding.

Any update on this?

**Comment by natBizitza** [comment]
I had great hopes for this PR #6935. However, it says that the strategy has changed. I am not sure what that means and what to expect.
