### ISSUE TITLE
[Image] No native "src" property on server side rendered page

### ISSUE THREAD

**Issue by harshzalavadiya** [chakra-ui/chakra-ui#462]
**Describe the bug**
Currently while checking image component rendered on server side (in my case using next.js) there's no `src` in server side rendered native `<image />` tag
is this intentionally designed like this? or is there any way to configure this

because this might be a huge impact on SEO as no image will have `src`

PFB codesandbox describing minimal nextjs sample
[![Edit fast-bush-2nsvz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fast-bush-2nsvz?fontsize=14&hidenavigation=1&theme=dark)

**Expected Behavior**
have `src` property on native `<image/>`

**To Reproduce**
no reproduction required just use component with src

**Suggested solution(s)**
NA

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] All
 - Browser [e.g. chrome, safari] All
 - Version [e.g. 22] All

**Additional context**
If lazy loading images was the purpose then `loading=lazy` tag might be useful
https://caniuse.com/#feat=loading-lazy-attr

**Comment by jun-nguyen-goldenowl** [comment]
Any solution for this? :D

**Comment by harshzalavadiya** [comment]
https://www.npmjs.com/package/react-cool-img Somethung like this might help, best of both worlds

**Comment by jun-nguyen-goldenowl** [comment]
Thanks @harshzalavadiya! Btw, I found that this issue will occur when `src` value is provided by require an image with `.webp` extension.

**Comment by jun-nguyen-goldenowl** [comment]
Could you help me understand why this issue occurred?

**Comment by harshzalavadiya** [comment]
@jun-nguyen-goldenowl 
I guess issue can reproduced with other image formats as well because in issue template codesandbox link it was easily reproduced with `jpeg` as well from, Might be something else then I think

**Comment by fastengineer** [comment]
I solved the issue using fallbackSrc. But it is a bug I think.

**Comment by DevAlien** [comment]
I have the same issue with a jpeg image

**Comment by jmcruzmanalo** [comment]
The solution of @fastengineer worked.

I went through the `useImage` hook that is used by the `Image` component.

Seems like `src` isn't getting set in this [line](https://github.com/chakra-ui/chakra-ui/blob/master/packages/image/src/use-image.ts#L66).

For our team's case, we don't need `fallbackSrc` since we aim to render a base64 lqip server side. The `Image` component accepts an `ignoreFallback` prop and when set to true makes the `useImage` hook return the `loaded` state. If the state isn't `loaded` the component passes `fallbackSrc` to the native `img` tag instead of `src`. [See this file](https://github.com/chakra-ui/chakra-ui/blob/master/packages/image/src/image.tsx#L77)

**Comment by harshzalavadiya** [comment]
Thanks @jmcruzmanalo,
using `ignoreFallback` might be optimal solution
