### ISSUE TITLE
Popover + Portal inside Modal isn't clickable

### ISSUE THREAD

**Issue by gmathieu** [chakra-ui/chakra-ui#4620]
### Description

Rendering [popover in a Portal](https://chakra-ui.com/docs/overlay/popover#rendering-the-popover-in-a-portal) inside a Modal prevents users from interacting with the Popover. Portals are usually needed when using `<Modal scrollBehavior="inside">`.

### Link to Reproduction

https://codesandbox.io/s/chakra-modal-popover-portal-lfeep?file=/src/index.tsx

### Steps to reproduce

1. Visit codesandbox
2. Click on "Open w/ inline popover" to see expected behavior
3. Click on "Open w/ Portal popover" to see issue

### Chakra UI Version

1.6.6

### Browser

Chrome 92

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Couple workarounds:
- to display the Popover over the ModalOverlay, you can set `<ChakraProvider portalZIndex={5000}>`
- to enable interaction of the Popover inside the Portal, you can set `<Modal focusTrap={false}>`

Here's what it looks like in our app:
![image](https://user-images.githubusercontent.com/7855/130673559-2cbaeac2-2e47-4d6f-9d37-1aaf63c34f11.png)

**Comment by linxianxi** [comment]
same

**Comment by anubra266** [comment]
not stale

**Comment by primos63** [comment]
Add `trapFocus={false}` to your `Modal`
```jsx
<Modal trapFocus={false} {...disclosure} scrollBehavior="inside">
```

**Comment by gmathieu** [comment]
@primos63 that's the workaround I'm currently using (and listed in the description) but it isn't a proper solution. Trapping focus is important for accessibility (part of what makes this library so great).

**Comment by primos63** [comment]
Reopened and labelled bug not sure it's really a bug though. It could be a feature. This is now the third such request - two from Github and one from the Discord community for something I'd consider an edge case. Perhaps that's why it wasn't included with `Popover`.

Triage:
When you open a `Popover` in a `Portal` from a `Modal` and `trapFocus` is true, focus is kept within the modal making selection of any fields in the `Popover` impossible. Chakra uses [react-focus-lock](https://github.com/theKashey/react-focus-lock) to trap the focus. The library does support [Portals](https://github.com/theKashey/react-focus-lock#portals), but that feature is not included within Chakra. In order to allow access to the Popover, one of the three ways provided in the React Focus Lock library needs to be implemented with Chakra.

This [CodeSandbox](https://codesandbox.io/s/modal-portal-popover-oh-my-kbymn) has a rough solution using `group`.  I'd have to look into the `group` prop more to fully understand what it is doing.

**Comment by lbdremy** [comment]
nice @primos63  ! do you know if the react-focus-lock group feature planned to be integrated in chakra-ui ?
It would be really helpful as I'm hitting this use case you're describing.

**Comment by benjamincharity** [comment]
Not stale

**Comment by WasiqK14** [comment]
Not stale
