### ISSUE TITLE
An Error while deploying a next js app due to `InputLeftElement`

### ISSUE THREAD

**Issue by Prash2002** [chakra-ui/chakra-ui#4644]
### Description

When I used InputLeftElement and passed in the props as "children" as mentioned in the docs, it worked perfectly fine in my localhost. But when I tried to deploy it, I got an error as follows: "Do not pass children as props. Instead, nest children between the opening and closing tags.  react/no-children-prop"

### Link to Reproduction

https://codesandbox.io/s/twilight-silence-v59qc?file=/pages/index.tsx

### Steps to reproduce

1. Go to 'pages/index.tsx'
2. run the command `npm run build`
3. The error: _Do not pass children as props. Instead, nest children between the opening and closing tags.  react/no-children-prop_

### Chakra UI Version

1.6.6

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

My solution/ suggestion:

1. either change the props name to something else other than children or
2.  pass in the content as children as shown:

`  <InputLeftAddon> +91 </InputLeftAddon>`

the second method works completely fine! it would be cool if the docs over [here](https://chakra-ui.com/docs/form/input#left-and-right-addons) could be updated too

Thanking you!

**Comment by takethefake** [comment]
Hej @Prash2002 thanks for reaching out!

AFAIK: Your described error should only happen because of your local linting configuration regarding the [`react/no-children-prop`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md) and there for shouldn't be chakra-related. Setting the content via the `children`-props should therefore work if your linting ruleset approves it.

**Comment by Prash2002** [comment]
Hi @takethefake ,

Got it, thank you so much for responding 😄
