### ISSUE TITLE
Support dot notation components to decrease the amount of imports

### ISSUE THREAD

**Issue by codebuzzco** [chakra-ui/chakra-ui#4717]
### Description

Support dot notation components to decrease the amount of imports needed when using e.g. modal or table.

![image](https://user-images.githubusercontent.com/90099080/133524491-5ff9ff35-dffe-493a-90e9-9d540ba6968b.png)

### Problem Statement/Justification

Less imports makes the code cleaner.

### Proposed Solution or API

![image](https://user-images.githubusercontent.com/90099080/133524579-3490d06f-e764-4481-a3b8-96091155b6ca.png)

### Additional Information

https://reactjs.org/docs/jsx-in-depth.html#using-dot-notation-for-jsx-type

**Comment by primos63** [comment]
I think the problem with this is that your ability to do tree-shaking is lost. You have to bring all of the components in because they are part of an object.
Here's an [example](https://rollupjs.org/repl/?version=0.43.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCU3QiUyMFNoYXBlcyUyMCU3RCUyMGZyb20lMjAnLiUyRm1hdGhzLmpzJyUzQiU1Q24lNUNuY29uc29sZS5sb2coJTIwU2hhcGVzLmN1YmUoJTIwNSUyMCklMjApJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwbWF0aHMuanMlNUNuZXhwb3J0JTIwY29uc3QlMjByZWN0YW5nbGUlMjAlM0QlMjAoeCUyQyUyMHkpJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHklNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFNoYXBlcyUyMCUzRCUyMCU3QiU1Q24lMjAlMjBzcXVhcmUlM0ElMjBmdW5jdGlvbiUyMHNxdWFyZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0JTVDdHJldHVybiUyMHglMjAqJTIweCUzQiU1Q24lNUN0JTdEJTJDJTVDbiUyMCUyMGN1YmUlM0ElMjBmdW5jdGlvbiUyMGN1YmUlMjAoJTIweCUyMCklMjAlN0IlNUNuJTIwJTIwJTVDdHJldHVybiUyMHglMjAqJTIweCUyMColMjB4JTNCJTVDbiU1Q3QlN0QlNUNuJTdEJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) using the Rollup.js repl. The `rectangle` function is removed as it is never used, but the `square` function stays as it's part of the Shapes object.

**Comment by stefee** [comment]
I think what @primos63 said is correct.

If you could import this way then it would work better for tree-shaking in theory:

```js
import * as Modal from “@chakra-ui/modal”
import * as NumberInput from “@chakra-ui/number-input”
```

(I’m not sure if this example works - would need to try it and find out!)

This means importing each namespace separately, but it ultimately equates to the same lines of code as your example which looked like this:

```js 
import {
  Modal,
  NumberInput,
} from “@chakra-ui/react”
```

**Comment by codebuzzco** [comment]
Ah interesting. Hmm I wonder how other libraries such as react-bootstrap handle this since they do support dot notation components. 🤔

The code certainly looks cleaner supporting this but I wouldn't want to end up importing the entire library if I'm just using a few components.

Just out of curiosity; do you import all of your chakra components from '@chakra-ui/react'? or if you e.g. import button do you import it from '@chakra-ui/button'?

**Comment by primos63** [comment]
React-Bootstrap is not tree-shakable. See this [Github issue](https://github.com/react-bootstrap/react-bootstrap/issues/5990).
Here's the import & export for Modal.tsx
```javascript
import ModalBody from './ModalBody';
import ModalContext from './ModalContext';
import ModalDialog from './ModalDialog';
import ModalFooter from './ModalFooter';
import ModalHeader from './ModalHeader';
import ModalTitle from './ModalTitle';

export default Object.assign(Modal, {
  Body: ModalBody,
  Header: ModalHeader,
  Title: ModalTitle,
  Footer: ModalFooter,
  Dialog: ModalDialog,
  TRANSITION_DURATION: 300,
  BACKDROP_TRANSITION_DURATION: 150,
});
```
Everything is imported and put into the Modal object. You may not need a `Footer`, but that won't matter because the library will have it.
