### ISSUE TITLE
StyledOptions doesn't have themeKey in ChakraFactory

### ISSUE THREAD

**Issue by akasuv** [chakra-ui/chakra-ui#4727]
### Description

When I was trying to custom Tab like introduced in the doc, TS compiler gave a warning that `themeKey` doesn't exist on StyledOptions

### Link to Reproduction

https://codesandbox.io/s/young-frog-6qk9g?file=/src/App.tsx

### Steps to reproduce

1. Go to App.tsx
2. Hover on where the red warning shows
3. See TS error

### Chakra UI Version

1.6.7

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @akasuv,

This is because `themeKey` isn't supported in `StyledOption`. You may have been misled by the README in `packages/system`, please ignore that (I'll update it shortly).

Kindly follow the spec here to learn how to use the theme key to style components: https://chakra-ui.com/docs/theming/component-style

Thanks for understanding.
