### ISSUE TITLE
<Select> Passing some props to parent component

### ISSUE THREAD

**Issue by brenoos** [chakra-ui/chakra-ui#4746]
### Description

Apparently, some props used goes to the parent wrapper and other ones goes to the 'select'. In the codesandbox example, you can see that "top, left, pt" goes to the root wrapper, and "fontSize, w and bg" goes to the 'select' itself

### Link to Reproduction

https://codesandbox.io/s/gracious-johnson-jl5je

### Steps to reproduce

Just pass props to `<Select>`

### Chakra UI Version

1.6.6

### Browser

Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

If this is really a bug, can someone help me to pass a padding and other props to the select?

**Comment by primos63** [comment]
This should have been a discussion rather than an issue as it's not a bug. 
You can use the `sx` prop to set the padding on the `select` element.

**Comment by brenoos** [comment]
Sorry for my mistake opening this as a bug, could you change it? I'm not able to do that

This is why I think this is not right:
1 - There is a prop called `rootProps` to forward to the root `div` element, in this case, makes more sense to me that only the props on this be set on the wrapper.
2 - Some props going to an element and other props going to another element without anything telling that, does not seems right for me

@primos63 Thanks for the suggestion on the `sx` prop, worked

**Comment by primos63** [comment]
The point of mentioning that was just to point out that there is a discussion board for such questions. If something is a bug there is a button in the discussion to create an issue. Sorry, but I don't have that ability either. I think you should have the ability to mark this as closed when you are ready.

Why are props okay? In my opinion, they are okay because this is a component which acts as a single element. One passes props to the component not to elements which make up the component. I'm pretty sure most other libraries are like that. For the most part, the underlying implementation shouldn't be a concern to the user. When it is a concern the authors have provided the user the theme source so one can extend their theme and the `sx` prop which has precedence other styling options including props passed to the component.

Glad the you resolved your issue.

**Comment by brenoos** [comment]
Thanks @primos63, will close this and open a discussion. Thanks!
