### ISSUE TITLE
styled: No custom props TS

### ISSUE THREAD

**Issue by RadovanPelka** [chakra-ui/chakra-ui#4772]
### Description

Bad types

### Link to Reproduction

https://codesandbox.io/s/compassionate-breeze-swx2k

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

All

### Browser

All

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Should be: props: StyleResolverProps & T

![image](https://user-images.githubusercontent.com/29738200/135416303-c18bc744-19a0-4c5f-ab18-75b513d83411.png)

![image](https://user-images.githubusercontent.com/29738200/135416592-bbaaa1e4-623b-4580-87b1-af2f37d2e07e.png)
![image](https://user-images.githubusercontent.com/29738200/135416612-47ecffc6-8913-4d13-8107-0778716c5d15.png)

cc @segunadebayo

**Comment by aboveyunhai** [comment]
I felt like you are looking for something like this discussion.
https://chakra-ui.com/docs/theming/customize-theme
https://github.com/chakra-ui/chakra-ui/discussions/3435#discussioncomment-416056

First, even though `styled` function appears in `Chakra`, it's used internally. so it probably means Chakra will not fully support everything like you expect.
Second, because you are directly inserting `test` (in your example), you will likely to get a console warning that `test` does not exist in component from my past experience.

**Comment by RadovanPelka** [comment]
Interesting... no console warning 😄

**Comment by aboveyunhai** [comment]
> Interesting... no console warning 😄 
> 

if you check your code snippet, there is one.

**Comment by RadovanPelka** [comment]
> > Interesting... no console warning 😄
> 
> if you check your code snippet, there is one.

Yes TypeScript...

**Comment by aboveyunhai** [comment]
> > > Interesting... no console warning 😄
> > 
> > 
> > if you check your code snippet, there is one.
> 
> Yes TypeScript...

No, it's a console warning from `react` when you try to direct insert prop to Chakra Component.
```
Warning: Received `true` for a non-boolean attribute `test`.
If you want to write it to the DOM, pass a string instead: test="true" or test={value.toString()}.
```
