### ISSUE TITLE
When to use css over sx?

### ISSUE THREAD

**Issue by TKDev7** [chakra-ui/chakra-ui#4839]
### Subject

styled-system

### Description

I pretty much exclusively use the sx prop. Is there a use case for the css prop? They both seem to do the same thing

**Comment by takethefake** [comment]
You may expect a very little computation overhead when using the `sx`-prop since we're resolving the tokens there - but I personally prefer using the `sx`-prop in general

**Comment by primos63** [comment]
@ludwignagelhus I had asked Sage about `css` while working on an issue. It's a hold over from v0. I suggested it be deprecated since `sx` is available. `sx` should be the highest order prop, but because of the `css` it is not. I agree with the previous comment that the preference should be to use the `sx` prop.

Order precedence should be 

1. `__css` prop { styles defined in the component itself }
2. theme styles
3. apply, textStyle, layerStyle props
4. style props { those passed to the component such as bg='blue.400' }
5. `sx` prop

Currently if the `css` prop is used, then it is combined with the other computed properties. So it has the highest precedence and can override something defined in `sx`. It can also produce unexpected results because the computed properties take into account responsive styles. If you use `css`, that's on you.

**Comment by ParallelUniv3rse** [comment]
> @ludwignagelhus I had asked Sage about `css` while working on an issue. It's a hold over from v0. I suggested it be deprecated since `sx` is available. `sx` should be the highest order prop, but because of the `css` it is not. I agree with the previous comment that the preference should be to use the `sx` prop.
> 
> Order precedence should be
> 
> 1. `__css` prop { styles defined in the component itself }
> 2. theme styles
> 3. apply, textStyle, layerStyle props
> 4. style props { those passed to the component such as bg='blue.400' }
> 5. `sx` prop
> 
> Currently if the `css` prop is used, then it is combined with the other computed properties. So it has the highest precedence and can override something defined in `sx`. It can also produce unexpected results because the computed properties take into account responsive styles. If you use `css`, that's on you.

This should be part of the docs somewhere, especially referenced around the `useMultiStyleConfig` hook. Thanks for the insight.

**Comment by afatoga** [comment]
Using css prop gives you an ability to use scss for basic HTML elements, see an example [here](https://stackoverflow.com/a/78126683/6679040)
