### ISSUE TITLE
Heading component fontSize overrides: Works using array but not using breakpoints object

### ISSUE THREAD

**Issue by zeta22** [chakra-ui/chakra-ui#4886]
### Description

When we override Heading fontSize using object breakpoints syntax, it's not taking the values

### Link to Reproduction

https://codesandbox.io/s/zeta-heading-size-issue-890dg?file=/src/index.js

### Steps to reproduce

_**Link to codesandbox attached.**_

Heading size overrides for a custom variant works when
- we provide an array of sizes by media breakpoint
- we provide a single size

It's not working when I provide a sizes by using an OBJECT with media query breakpoints.

Example code here:
**_Heading 2 it's taking default values._** and ignoring the overrides

```js
import React from "react";
import ReactDOM from "react-dom";
import { Box, ChakraProvider, extendTheme, Heading } from "@chakra-ui/react";

const theme = extendTheme({
  components: {
    Heading: {
      variants: {
        arrayBreakpoints: {
          fontSize: ["10px", "20px", "30px"]
        },
        objectBreakpoints: {
          fontSize: { base: "10px", sm: "20px", md: "30px", lg: "40px" }
        },
        fixedSize: {
          fontSize: "10px"
        }
      }
    }
  }
});

function App() {
  return (
    <ChakraProvider theme={theme}>
      <Box padding={4}>
        <Heading variant={"arrayBreakpoints"}>Heading 1</Heading>
        <Heading variant={"objectBreakpoints"}>Heading 2</Heading>
        <Heading variant={"fixedSize"}>Heading 3</Heading>
      </Box>
    </ChakraProvider>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

### Chakra UI Version

1.6.7

### Operating System

- [X] macOS
- [X] Windows
- [x] Linux

**Comment by takethefake** [comment]
I've checked into this and the problem here is caused by how we extend our theme currently.

the initial fontSize is: `['3xl',null,'4xl']` because our `merge`-function doesn't take into account what the previous or next value is based on type we mix things together and end up with the following case: https://codesandbox.io/s/zeta-heading-size-issue-forked-p41sj?file=/src/index.js (check browser dev tools since codesandbox doesn't support `console.dir`)

there we see that the merged object contains the following:

```
Array(3)
0: "3xl"
1: null
2: "4xl"
base: "10px"
lg: "40px"
md: "30px"
sm: "20px"
length: 3
```

what we need to do to fix this is to adjust our `mergeThemeCustomizer` in `extendTheme` https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/extend-theme.ts#L109:L126

if we want to allow the user to pass in an object here we need to also take the users defined breakpoints into consideration.
