### ISSUE TITLE
Reduce theme bundle size

### ISSUE THREAD

**Issue by hiroppy** [chakra-ui/chakra-ui#4975]
### Description

Hi, I'm @hiroppy from webpack team. First, thank you for creating a wonderful library and I am satisfied with it other than one thing which is the huge bundle size. I want to discuss you have a plan to re-architecture the code structure or not. The bundle size is so important to improve performance and chakra-ui has many unnecessary variables even if bundled.

### Problem Statement/Justification

The code of chakra-ui isn't friendly with dead code elimination so the bundle size will be huge. I created [a loader of webpack](https://github.com/hiroppy/chakra-ui-optimization-loader) to improve chakra-ui's bundle size and it can reduce bundle size, but I know it's a bad practice because I won't realize breaking changes of charka-ui.

e.g. an example of just importing the chakra-ui

You can see all themes exist in a chunk **even if you don't use a component**, this is because of importing all themes as an object field. See https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/index.ts#L17

<img width="1304" alt="w-o-loader" src="https://user-images.githubusercontent.com/3367801/139788628-45ea300a-04bc-4a75-9abb-dde3a77ebb3b.png">

Also, even if you don't use css variables of Twitter, Facebook, and so on, the chunk has them. See https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/foundations/colors.ts#L9-L248

I think we don't need many tokens on production...

When ignore 'Alert', 'Table', 'Tabs', 'Slider'

<img width="1345" alt="w-loader" src="https://user-images.githubusercontent.com/3367801/139789266-8b900585-ecb9-431b-8269-20a6549a3741.png">

the bundle size is down over 10kb

From now on, chakra will introduce many components and the bundle will be bigger than now so I want to discuss preventing this situation.

### Proposed Solution or API

I think we have many ideas.

- provide a config file like tailwind to tell information to bundlers, not runtime config(extendTheme)
- each theme should be in each component, don't add it to a global object, should be as on-demand 
- do you have others...?

### Additional Information

Our company uses the chakra-ui on production but I have this issue. The article is [here](https://engineering.mercari.com/blog/entry/20210823-a57631d32e/) written in Japanese.

**Comment by hiroppy** [comment]
oh, sorry I didn't read [this issue](https://github.com/chakra-ui/chakra-ui/issues/4972), maybe "Core (Styled System)" is similar to this issue🙂

**Comment by segunadebayo** [comment]
Hey @hiroppy,

This is great! and I'd love to have you help us improve the bundling of Chakra UI components. We're happy to do a major release if we have a system that works pretty well.

The webpack loader you created sounds very interesting. Another approach I had in mind is to have the theme only include the foundations (colors, fonts, etc.) and let the user import the theme for the components they use.

```jsx
import sliderTheme from "@chakra-ui/theme/slider"
import accordionTheme from "@chakra-ui/theme/accordion"
import { extendTheme } from "@chakra-ui/react"

const theme = extendTheme({
 components: { Slider: sliderTheme, Accordion: accordionTheme }
})
```

Each component style will have entry points the user can import from. We can also eliminate unnecessary colors from the theme and move them to entry points instead.

What do you think?

PS: Please fill out the form in #4972. I'd love to work with you on this.

**Comment by hiroppy** [comment]
Hey @segunadebayo, thank you for your reply! 

> Another approach I had in mind is to have the theme only include the foundations (colors, fonts, etc.) and let the user import the theme for the components they use.

That suggestion is easy to reduce bundle sizes, but users might face a situation that occurs a gap between components and styles since if users forget to import buttonTheme, the Button component won't have the style.

I think one of the good points of chakra-ui is that users don't need to consider many things which are tokens, themes, etc so I want to seek how to reduce the bundle size but keep DX by not increasing the settings.

> PS: Please fill out the form in #4972. I'd love to work with you on this.

yep, I submitted!

**Comment by MrHBS** [comment]
@hiroppy Have you had any chance working at this?

**Comment by pedronasser** [comment]
Any intention on working on this in the future?
I do think this needs more attention.
I would be willing to contribute on this, but I would like a position from Chakra's main contributors first.

**Comment by Ploppy3** [comment]
@segunadebayo please consider the request above.

**Comment by ekrokowski** [comment]
this should have much higher priority 😢

**Comment by sauldeleon** [comment]
Hi!

regarding this, is there any way of importing `extendTheme` without exporting the whole bundle?

Thanks in advance!

**Comment by isaachinman** [comment]
@takethefake @segunadebayo @TimKolberger We have contributors ready to help on this. Can we please get an official response?

**Comment by noobinthisgame** [comment]
This is a topic we want to adress! Priority has been on v2 lately. Feel free to submit PRs if you want to work on this :) 
Some possible solutions have been discussed in this issue.

**Comment by isaachinman** [comment]
@noobinthisgame New to this project. Will these namespace import and theme organisation issues affecting bundle size be resolved with v2? If so, what is the timeline? If not, why not?

**Comment by TimKolberger** [comment]
v2 is only focused on React 18 support. We try to keep the breaking changes to a minimum to provide a smooth upgrade experience.

Improved theme APIs are next up. We organize the epics in this Github project if you are curious: https://github.com/orgs/chakra-ui/projects/3

I can't communicate a timeline - everyone involved here does this in their free time.
From my perspective there are no major obstacles in our way for the v2 release.

**Comment by isaachinman** [comment]
Thanks @TimKolberger. I'm also an OSS maintainer and understand the process. Just trying to get a sense of impact for the work proposed here. It sounds like it would carry on to future versions and be quite an important improvement for the lib.

**Comment by isaachinman** [comment]
Not stale.

**Comment by riolly** [comment]
> Hey @hiroppy,
> 
> This is great! and I'd love to have you help us improve the bundling of Chakra UI components. We're happy to do a major release if we have a system that works pretty well.
> 
> The webpack loader you created sounds very interesting. Another approach I had in mind is to have the theme only include the foundations (colors, fonts, etc.) and let the user import the theme for the components they use.
> 
> ```js
> import sliderTheme from "@chakra-ui/theme/slider"
> import accordionTheme from "@chakra-ui/theme/accordion"
> import { extendTheme } from "@chakra-ui/react"
> 
> const theme = extendTheme({
>  components: { Slider: sliderTheme, Accordion: accordionTheme }
> })
> ```
> 
> Each component style will have entry points the user can import from. We can also eliminate unnecessary colors from the theme and move them to entry points instead.
> 
> What do you think?
> 
> PS: Please fill out the form in #4972. I'd love to work with you on this.

Is there a way to optimize it and reduce the bundle size on v2?
This way is no longer working.

**Comment by Patrick-Ullrich** [comment]
Starting a new project I noticed that the bundle size immediately ballooned. After spending some time withit, I think we can drastically reduce the bundle size but never using `"@chakra-ui/react"`. I'll see if I can put together a smaller code sandbox, but just from some quick testing. Using vite (rollup):

### Step 1
Using @chakra-ui/react
![image](https://user-images.githubusercontent.com/6193042/176272929-39f762f1-18d9-4298-8085-ce32aa229b17.png)

### Step 2
Using 
import { ChakraProvider } from "@chakra-ui/provider";
instead of
import { ChakraProvider } from "@chakra-ui/react";
![image](https://user-images.githubusercontent.com/6193042/176272955-c3e6ec33-e03e-45d1-9d02-759615836885.png)

### Step 3
Removing `extendTheme` the only thing I noticed in the minimal repo that had to come from @chakra-ui/react.
![image](https://user-images.githubusercontent.com/6193042/176273142-41bce9c5-f8fa-45ec-a87f-ec041dd46029.png)


If this turns out to be pretty fruitful then I think documentation should update to always import from packages directly instead of @chakra-ui/react.

**Comment by klujanrosas** [comment]
@Patrick-Ullrich 


While the name **ChakraProvider** might cause one to think the one exposed by `@chakra-ui/react` and `@chakra-ui/provider` are one and the same, that would be incorrect.

Even though they share a name, they are different:

- **ChakraProvider** from **@chakra-ui/provider** is the default, standalone, themeless provider.

- **ChakraProvider** from **@chakra-ui/react** uses _@chakra-ui/provider_ and _@chakra-ui/theme_ under the hood to build a full provider, with the default theme applied.

Hence the size difference.

**Comment by TheThirdRace** [comment]
As long as components are included in the `theme`, tree-shaking will be inefficient.

When I load a page with an `<Accordion>`, I only need the variant I'm using in the theme.

When I load a page *** without *** an `<Accordion>`, there should be no `<Accordion>` styles in the theme.

Unfortunately, I don't think it's doable with the current API:

- Having `components` as part of the theme is not tree-shakeable
- Having only the components you use in the theme is still not tree-shakable enough (different pages, different variants, etc.)
- We have not much controls on the default styles, which are also not tree-shakeable

The only solution I see is:

- to have every `base`, `variant` and `size` be an entry point (we will need to import them)
- use composition (instead of Chakra doing it for us, we'll have to do it ourselves)
- use the `sx` prop because this is the only way I can think of to pass those tree-shaked styles to the component effectively

If you want to reuse components between projects, the styles needs to be separated from the components **COMPLETELY**.  Such approach has many advantages, such as:

- perfect tree-shakeability
- complete freedom for composition (ever tried to compose 2 variants together? which is much more frequent than you might think)
- great separation of concerns, the best example would be [CSS Garden](http://www.csszengarden.com/) which completely change their website appearance by only adjusting the CSS without ever thouching a line of structure, aka HTML or JS (appearance vs structure)
- easily reuse components between projects

The only disadvantage is that it's a bit more boilerplate.

The ironic part in all this is that the solution to all those problems is the total opposite of what Chakra's team has been pushing since the launch. To get all those benefits, all you need to do is to avoid at all cost the inline styling props and start using the `sx` prop. All we're really missing at the moment is to have every `base`, `variant` and `size` be an entry point and we're good to go.

It's always nice to be able to prototype stuff with inline styling props, but if you use this method beyond a prototype, be ready to start every new project from scratch. There was a reason for having the CSS behind classes instead of inline styling...

**Comment by RichiCoder1** [comment]
It wouldn't be nearly as simple as it'd require interoping with bundlers, but Tailwind-like experience where it was smart enough to build the theme and inject the theme based on components used is about the only way you'll get a lower boilerplate but bundle-size-efficient solution.

**Comment by segunadebayo** [comment]
I discussed with @nikolovlazar today how we can achieve this. We'll start a refactoring spree to solve this problem with the theme. I appreciate all the thoughts and ideas here

**Comment by minhchu** [comment]
From this discussion https://github.com/chakra-ui/chakra-ui/discussions/5277 , should we remove `framer-motion` from the core ?

**Comment by brandonLyonMM** [comment]
Are there any progress or status updates on this?

**Comment by TheThirdRace** [comment]
@brandonLyonMM 
I'm not a contributor, but there has been some progress lately.

In version [2.4.2`](https://github.com/chakra-ui/chakra-ui/blob/main/.changelog/v2.4.2.mdx#chakra-uireact242), they introduced `<ChakraBaseProvider >` and `extendBaseTheme` to only include the components you need in the theme.

For the first time ever, when I upgraded Chakra my bundle size was reduced!!! Ok, only 5KB, but that's better than the increase of 3KB every couple release 🎉

There's still work to do, but seeing PR #6929 replace framer-motion in a component is giving me hope we'll eventually be rid of framer-motion.

**Comment by minhchu** [comment]
From the discord channel (in roadmap), Sage said that the team was evaluating Zero-runtime js options. So chakra is definitely moving away from runtime css-in-js

**Comment by TheThirdRace** [comment]
> From the discord channel (in roadmap), Sage said that the team was evaluating Zero-runtime js options. So chakra will be likely moving away from runtime css-in-js

They were talking about switching to zero-runtime CSS-in-JS solution more than 2 years ago... I'll believe it when I see it 😒

**Comment by segunadebayo** [comment]
Hi all,

The best we can do now is to provide a minimal provider that doesn’t include the component themes.

We’ve added a `ChakraBaseProvider` and `extendBaseTheme`, which only supply the theme tokens and ignore components.

Please refer to the changelog here regarding how to do this:
https://chakra-ui.com/changelog/2.4.2#react-242

It might not be the smoothest experience, but it will help us achieve the desired outcome without investing too much effort (aka, webpack, babel, vite plugins).

If someone can create a sample plugin, I’m more than happy to reconsider this. We can publish it as a recipe for those who want all components but remove unused themes.

> As explained in the 3.0 roadmap, we plan to remove the dependency on framer-motion, further reducing the size.

Thanks for understanding.
