### ISSUE TITLE
[Stack] Spacing overrides margin values given directly to children

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [chakra-ui/chakra-ui#5108]
### Description

Duplicate of this issue: https://github.com/chakra-ui/chakra-ui/issues/207
But I think `Flex` with `flexDirection="column"` is not an alternative, at least not a good one. Say I have 10 elements within `Flex`, most of them using the same spacing, but few of them are using another spacing. It'd be convenient for me to use `VStack` with spacing that is used by most elements, and to set spacing for other elements manually.
With `Flex` on the other hand I have to manually set desirable margins on all of them.

### Problem Statement/Justification

Managing spacing of large amount of elements is tedious. A solution that does it all in one place with an option to tweak some things individually would be awesome. 

### Proposed Solution or API

As @segunadebayo suggested in linked issue, 
> We'll have to check if `child.props.mr || child.props.marginRight` exists and use that instead of `spacing` value.

### Alternatives

You can use `%ur_spacing% !important` on individual elements, but that's not really chakra way (I hope)

### Additional Information

https://github.com/chakra-ui/chakra-ui/issues/207

I'm not english native so please don't beat me to death for mistakes.

**Comment by segunadebayo** [comment]
Hi @b-novikov-ipersonality,

This is by design and I would recommend:
- Using flex and the `gap` property as a way to solve this since it's supported natively.
```jsx
<Flex sx={{ gap: "24px" }} />
```
- Consider wrapping the elements you want to exclude in `<StackItem/>` element and then apply margin to that element

```jsx
<StackItem>...</StackItem>
```

> I'm not english native so please don't beat me to death for mistakes.

Haha. I totally get your explanation. No worries about not being a native speaker, we're a caring community 💖 not a group of angry mobs 😆
