### ISSUE TITLE
SkeletonText causes jitter due to hard-coded defaultNoOfLines

### ISSUE THREAD

**Issue by kfranqueiro** [chakra-ui/chakra-ui#5134]
### Description

When I use SkeletonText for specifically-sized placeholders in a component, I expect them to honor the noOfLines value I give them, but they initially render 3 lines unconditionally for one frame.

### Link to Reproduction

https://codesandbox.io/s/cranky-murdock-o7pus?file=/src/index.tsx

### Steps to reproduce

1. Go to linked codesandbox
2. Watch closely as you click on the Toggle button - you'll see it very briefly jump

### Chakra UI Version

1.6.4 and 1.7.2

### Browser

Chrome 95 and Firefox 94

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I'm not sure how common use cases are for breakpoint-dependent `noOfLines` for `SkeletonText`, but `useBreakpointValue` is what's causing this - particularly the fact that it's using an internally hard-coded default which can't be changed.

This can be fixed for non-breakpoint-dependent cases like the one in the codesandbox with the following change to `skeleton.ts`, to use the single passed `noOfLines` value as the default as well:

```ts
  const noOfLinesValue =
    useBreakpointValue(
      typeof noOfLines === "number" ? [noOfLines] : noOfLines,
    ) || (typeof noOfLines === "number" ? noOfLines : defaultNoOfLines)
```

We might want to consider exposing `defaultNoOfLines` as a prop for the breakpoint-dependent case as well.

**Comment by dgrcode** [comment]
I'm having this bug as well. After looking at the code, I also don't understand why `useBreakpointValue` is used to get the number of lines. I imagine that adds some delay until the hook gets the screen width, and the `defaultNoOfLines` is shown in the meantime.

I vote the `useBreakpointValue` is removed. We can just remove `noOfLinesValue` and just use `noOfLines` since we already have this extraction from the props:
```ts
 const {
    noOfLines = defaultNoOfLines,
    // other props
  } = props
```

If people want to have different amount of lines for different screen sizes they can always use `useBreakpointValue` and send the result as the prop.

Happy to open a PR if someone from the team agrees with the solution.

**Comment by kfranqueiro** [comment]
It looks like this became unreproducible in 1.7.4, probably due to this:

> useBreakpointValue returns the correct value on first tick, if matchMedia is available

**Comment by dgrcode** [comment]
Awesome, thanks for the heads up!
