### ISSUE TITLE
[NumberInput] precision prop has no effect when using it as a controlled component

### ISSUE THREAD

**Issue by aaronmcadam** [chakra-ui/chakra-ui#516]
**Describe the bug**

I would like to give the affordance that my input accepts decimal numbers by displaying the default value as `0.0`.

**Expected Behavior**

I expect that if I set `precision`, it should format the default value like it does in uncontrolled components.

**To Reproduce**

1. Go to https://codesandbox.io/s/chakra-ts-starter-ui31u
2. See that the default values are all integers

**Additional context**

Please let me know if there's another way to use this component or access its state without using it as a controlled component.

**Comment by segunadebayo** [comment]
Hi @aaronmcadam,

I'll most likely update the docs to include this but, the `precision` prop doesn't work with Numeric state values, you'll have to convert it to a string.

Here's what happens with the demo setup:
- You passed precision as `2` and step of `0.1`, and click the increment button
- The onChange handler returns `'2.10'` has the next value (as string)
- but because you're converting to a number, it's cast back to `2.1` float number

If you really need the precision prop, I'd recommend you use the state as a string.

Here's an example CodeSandbox: https://codesandbox.io/s/chakra-ts-starter-gdkwj

I hope you find this useful

**Comment by aaronmcadam** [comment]
That makes sense, thanks!

**Comment by adamsmasher** [comment]
Is there a reason why Chakra can't convert the numeric value to a string of the appropriate precision before rendering?
