### ISSUE TITLE
Request to add RTL support

### ISSUE THREAD

**Issue by M074554N** [chakra-ui/chakra-ui#517]
Hello @segunadebayo, it's a beautiful UI library and I used it in a project and it requires RTL support, I was wondering if you have it in plan? and what should I do if I want to contribute to the RTL support of the library?

Thanks

**Comment by segunadebayo** [comment]
Hi @MohamedHassanWD, 

Thanks for the amazing feedback about Chakra UI. 

At the moment, we're not looking to support RTL but it's something Chakra UI will definitely solve down the line. I have some ideas around and would like to share with you if you're interested in contributing to this effort.

Let's have a chat here: https://discord.gg/dQHfcWF

**Comment by omarkhatibco** [comment]
@MohamedHassanWD  
I used it in an RTL Project, almost everything works fine, I did just small amount of changes.

**Comment by Abdulla97** [comment]
@omarkhatibco 

how did you approach it? what was your solution ?

**Comment by Abdulla97** [comment]
The solution suggested from Chakra discord channel was helpful,  
I will take the Alert component as an example we have 2 steps one for icon position to the right and text to the right, 
for text wrap them in a <Box> with setting dir="rtl" and width, then the icon position="absolute" right="8px" as shown in the example below  

![RTL-chakra-1](https://user-images.githubusercontent.com/29528930/89230387-da04cd00-d5eb-11ea-8112-e07d9547c15d.png)

**Comment by omarkhatibco** [comment]
Hi @Abdulla97,

usually flexbox and grid are aware of RTL so for everything in layouts I just used them.

for other components like `toast`, 'alert' & inputs with Icons, I just rewrote them and revert 'left' to 'right', 'mr' to 'ml'.

but I recommend that you use `direction: rtl;` on html element so the whole website revert to RTL.

a better approach I recommend  (but still not available in Chakra just in css attribute) to use [CSS Logical Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Propertiesurl) here you could make everything works perfectly in both LTR & RTL.

I could provide you with my RTL repo to check it if you want.

**Comment by Abdulla97** [comment]
Hello @omarkhatibco, 
yes that the best workaround currently. yes, please if you can provide repo that will be awesome 
thank you

**Comment by omarkhatibco** [comment]
@Abdulla97 
[https://github.com/omarkhatibco/faris-group.com](here is the repo) it's based on `v0.8`

I'm doing another project with the `v1` version, I could send you the link once it's public

**Comment by Abdulla97** [comment]
@omarkhatibco 
that will be helpful since my plan to start with v1 from now 
thanks

**Comment by nimerfarahty** [comment]
great ui thax for all contributors

**Comment by hazem3500** [comment]
Hey guys,

I was thinking of making a PR using [CSS Logical Properties & values](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) as @omarkhatibco suggested and noticed that not all logical properties have browser support yet, so since chakra-UI uses **emotion** I've thought about using a **stylis** plugin that will let us use logical properties like this plugin [postcss-logical](https://github.com/csstools/postcss-logical) for PostCSS but didn't find anyone that works with **stylis** so I've made one called [styled-plugin-logical](https://github.com/hazem3500/stylis-plugin-logical).

To use it we can do one of two things
1. use **styled-plugin-logical** internally
2. add `stylisPlugin` prop to `ChakraProvider` to allow users to provide there own stylisPlugin

If we go with option 1 we will need to refactor the components theme to use logical properties instead of physical properties and we'll also need to add styled props for logical properties (`paddingInlineStart`, `border-block`, etc.).
It will also be better to rename some of the props to be more friendly to RTL users, such as `rightIcon` and `leftIcon`, it would be better if they were `startIcon` and `endIcon` since in RTL `rightIcon` will appear on the left.

Am willing to make a PR but I need to know which direction we want to take with adding RTL support.

**Comment by omarkhatibco** [comment]
@hazem3500, 

after another RTL Project, Chakra is about 90% RTL friendly.

in some cases there were margin-left or margin-right on some components, I had to use the global style like this 

```js
'[lang=ar] ': {
  '& body': {
    direction: 'rtl',
  },
  '& h1, h2, h3, h4, h5, h6': {
    letterSpacing: '-0.6px',
  },
  '& .chakra-form__label': {
    textAlign: 'right',
  },
  '& .chakra-select': {
    paddingLeft: 8,
    paddingRight: 3,
  },
}
```
or direct in the component like so: 

```js
<AboutUsFirstBg
  position='absolute'
  width={{ base: 9.5 / 10, md: 1 / 2, xl: 1 / 3 }}
  sx={{
    left: 0,
    '[lang=ar] &': {
      transform: 'scale3d(-1,1,1)',
      left: 'auto',
      right: 0,
      },
    }}
  bottom={{ base: '-30%', md: '-40%', lg: '-70%' }}
/>
```

but try to avoid `Stack`, `VStack`, `HStack` & `Wrap`

**Comment by with-heart** [comment]
I am happy to announce that RTL support is being prioritized in our upcoming work!

**Comment by omarkhatibco** [comment]
@with-heart 
That would be great, also I'm Happy to help you with this.

**Comment by hazem3500** [comment]
@with-heart I would like to help with the RTL support, is there an open discussion other than this issue on supporting RTL?

**Comment by with-heart** [comment]
This is work @segunadebayo is taking on. Feel free to discuss here and I'll make sure he checks this issue!

**Comment by ehsanbigzad** [comment]
I would like to contribute to RTL support if needed, thanks

**Comment by segunadebayo** [comment]
I'm writing a guide for this at the moment. In the meantime, feel free to check this blog post:
https://dev.to/ugbechike/setup-an-internationalization-i18n-routing-web-app-with-nextjs-and-chakra-ui-39f1

**Comment by omarkhatibco** [comment]
Hi @segunadebayo,

Should I list RTL bugs here or in a single new issue ?

**Comment by with-heart** [comment]
@segunadebayo recently implemented a lot of functionality around RTL which is [documented on the RTL Support page](https://chakra-ui.com/docs/features/rtl-support). I'm going to close this issue as we've achieved official RTL Support.

@omarkhatibco Please open new issues for any related bugs you find.
