### ISSUE TITLE
Editable in LinkBox is not clickable

### ISSUE THREAD

**Issue by baptisteArno** [chakra-ui/chakra-ui#5198]
### Description

`EditablePreview` isn't clickable in a `LinkBox` component

### Link to Reproduction

https://codesandbox.io/s/currying-sea-202r1?file=/src/App.tsx

### Chakra UI Version

1.7.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Alfxjx** [comment]
seems the LinkOverlay cover the editable component

**Comment by segunadebayo** [comment]
Hi @baptisteArno,

The LinkBox component by design shouldn't contain more interactive components. As stated in the docs, it was made to use as a layout primitive for websites and blogs for displaying articles.

After giving it some thought, this sounds similar to putting an `<input>` (editable) element within an `<a>` (link-box) element.

Kindly consider building a wrapper yourself to get this working.

Thanks for understanding.
