### ISSUE TITLE
Allow Input Group width to be configurable

### ISSUE THREAD

**Issue by hpersson** [chakra-ui/chakra-ui#5252]
### Description

We have overridden the default `width: 100%` property for Input and Select in our project using our custom Chakra theme. 

However, we are unable to configure the default width of InputGroups via the theme object - https://github.com/chakra-ui/chakra-ui/blob/main/packages/input/src/input-group.tsx#L72

We wrap the Chakra InputGroup component and pass styles to provide a uniform experience when building forms. But it would be nice if this could be configured like the other properties.

### Problem Statement/Justification

Without being able to configure InputGroup's width from 100%, it is hard to use Chakra directly with inputs of a fixed width.

Other components allow you to configure "container" components - e.g. FormControl can be configured to not have `width: 100%`

### Proposed Solution or API

Add a "container" or "group" part to the theme for inputs

**Comment by primos63** [comment]
> However, we are unable to configure the default width of InputGroups via the theme object 

Yes, because there is no theme for `InputGroup`. 

> We wrap the Chakra InputGroup component and pass styles to provide a uniform experience when building forms.

I assume you have a simple wrapper that passes a `width` prop to the `InputGroup` which is valid.

I cannot see the use case for this. Every form you have with `InputGroup`s are always the same width? I would expect that the children of `InputGroup` would always take up 100% of the parent's width. If your form's container had a width of 300px, I would expect your inputs to also have that width.

If you could please provide a CodeSandbox example of what you are trying to do, it would be appreciated.

**Comment by hpersson** [comment]
> I cannot see the use case for this. Every form you have with InputGroups are always the same width?  If your form's container had a width of 300px, I would expect your inputs to also have that width.

All of our Inputs have the same width. Technically, though, the override I would like to make to the InputGroup width is to set it to "fit-content".

While I can understand the choice to have Inputs and InputGroups take up 100%, I don't think this is necessarily the only obvious case. In fact, I don't think Chakra itself has always assumed this, given that Input has [deprecated props](https://chakra-ui.com/docs/form/input) for `isFullWidth` which makes me think that these components behaved differently, or were able to be configured to behave differently, at some point.

I filed this as a feature request and not a bug because I fully acknowledge that I can have a wrapper that passed width to the InputGroup, so I'm not blocked/missing any functionality. But, it is not clear to me why I need a wrapper component for an InputGroup when most other customization of this variety I have been able to configure through theme.

Here's an example:
https://codesandbox.io/s/unruffled-flower-o5t82?file=/src/index.tsx
It demonstrates 1) why we would prefer fixed width inputs (having a uniform input width when each row has a varying number of inputs) and 2) how input groups cannot be used with fixed-width inputs, without also overriding their width property.

**Comment by primos63** [comment]
Thanks for the CodeSandbox. Yes, I understand you are requesting a feature. I've updated the app [here](https://codesandbox.io/s/inputgroup-theme-yfp1z) There are about 10 lines of code that can be added to a project to produce the feature you desire. I think this is fine for someone to include in their project. I'm not sure of its inclusion in Chakra.

Where's the stopping point for properties on `InputGroup`? You'll see in my example that I have a `_hover` on two of the input groups. One works the other doesn't due to the color set on the Input itself. And so would come all the misunderstandings and issues.

> While I can understand the choice to have Inputs and InputGroups take up 100%, I don't think this is necessarily the only obvious case. In fact, I don't think Chakra itself has always assumed this, given that Input has deprecated props for isFullWidth which makes me think that these components behaved differently, or were able to be configured to behave differently, at some point.

No it's not the only case, but I believe it's the most common case. I haven't heard other requests for other cases until now. The deprecated props are from the v0 version of the product. Obviously when you have a major version release there will be things which are deprecated.

I would much rather this be in control of the user than of the project, but that is simply my opinion.

**Comment by hpersson** [comment]
Thanks for the updated example. It sounds like once a component has a baseStyle etc available in the theme object, the concern is it would open the door for people to apply other css properties that do not work as expected w/ InputGroup's interactions with Inputs.

I think that makes sense to me, we can probably close this issue. Thanks for taking the time!
