### ISSUE TITLE
_css prop in Heading and Text component not having any effect 

### ISSUE THREAD

**Issue by leonelmeque** [chakra-ui/chakra-ui#5519]
### Description

When I try to create styles with _css prop with the Heading and Text components no change happens 

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-issue-3exwx

### Steps to reproduce

1. Add a Heading or Text Component
2. Use the __css prop and add styles
3. Check the UI for changes

Thanks in advance

### Chakra UI Version

1.7.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by with-heart** [comment]
The `__css` prop is typically used internally by Chakra to set low priority styles for components. In the case of `Text` and `Heading` (and probably other components), the `__css` prop is ignored entirely.

Instead of using `__css`, Chakra supports the [`sx` prop](https://chakra-ui.com/docs/features/the-sx-prop) which allows you to set specific styles on each component.

You can see a fork of your CodeSandbox demonstrating the `sx` prop here: https://codesandbox.io/s/chakra-ui-issue-forked-hve9w?file=/src/App.js

**Comment by leonelmeque** [comment]
> The `__css` prop is typically used internally by Chakra to set low priority styles for components. In the case of `Text` and `Heading` (and probably other components), the `__css` prop is ignored entirely.
> 
> Instead of using `__css`, Chakra supports the [`sx` prop](https://chakra-ui.com/docs/features/the-sx-prop) which allows you to set specific styles on each component.
> 
> You can see a fork of your CodeSandbox demonstrating the `sx` prop here: https://codesandbox.io/s/chakra-ui-issue-forked-hve9w?file=/src/App.js

Thanks for the quick response, I have probably missed this in the docs.
