### ISSUE TITLE
onChange in Chakra Tabs component triggers twice on tag change

### ISSUE THREAD

**Issue by soulchainer** [chakra-ui/chakra-ui#5552]
### Description

When clicking in a non active tab inside Tabs component, I expected an onChange event to be triggered, but two are triggered instead.

### Link to Reproduction

https://codesandbox.io/s/billowing-smoke-4fs7q?file=/src/App.test.js

### Steps to reproduce

1. Go to 'codesandbox «tests» tab'
2. Wait for the tests to run or click on 'Run all tests' button to re-run it later
4. See test error

Also, in the «Browser» tab:
- Go to «console» tab in the codesandbox
- Click in the other tab
- Check how 2 onChange events are triggered

### Chakra UI Version

1.8.3

### Browser

Chromium 97.0.4692.99, Firefox Developer 97.0b7, Microsoft Edge 98.0.1108.43 (Windows)

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

I'm currently doing a great upgrade of all the Chakra related packages in the project I work, from a bit outdated version.
This was working before (@chakra-ui/react@1.1.4, covered by unit tests) and it's breaking after the upgrade.
There was not a «breaking changes» or similar note about this change in the [changelog](https://github.com/chakra-ui/chakra-ui/blob/main/CHANGELOG.md). And, in any case, it doesn't sound like a «feature».

**Comment by takethefake** [comment]
hej @soulchainer thanks for reaching out!

I've taken a look into it and can confirm your described behaviour.

Currently, the `onChange`-Handler is fired because of the `click`-event as well as on the `focus`-event. This happens because of a11y-reasons. 

One way to make it only call once is by setting the `isManual`-Flag which will only trigger a of `onChange` on `enter` after `focus` and `onClick`. 

Tried to find a way to only trigger `onChange` in `onFocus` when `onFocus` was triggered by a `keyboard`-event but haven't found a good solution for this.

**Comment by soulchainer** [comment]
@takethefake Hi, Daniel!

Thank you for the swift response!

I have tried and it solves my problem :).

As I only need it for unit testing, is just fine to add the call in such tests in my case, for now.
Thanks again, this behavior was driving me crazy :þ.

Closing :).
