### ISSUE TITLE
top={80} renders element at unexpected location 

### ISSUE THREAD

**Issue by godfreyyeung** [chakra-ui/chakra-ui#5563]
### Description

When I absolutely position an element at top={80}, I expect it to be linearly positioned from the top, but it jumps the element further down the screen

### Link to Reproduction

https://codesandbox.io/s/sharp-roentgen-e209v?file=/src/index.js

### Steps to reproduce

1. Go to the codesandbox link
2. See that there are `Box`s are positioned at top={79}, top={80}, top={81}
4. See that the box positioned at top={80} is not in between 79 and 81 as it should be

<img width="254" alt="image" src="https://user-images.githubusercontent.com/3311663/153669028-9c4c6a7d-ec37-4ae5-9367-329d402cc1b4.png">

```
<ChakraProvider>
      <Box position="relative" padding={4}>
        <Box position="absolute" top={50} height="40px">
          ----- 50
        </Box>
        <Box position="absolute" top={79} height="40px">
          ----- 79
        </Box>
        <Box position="absolute" top={80} height="40px">
          ----- 80
        </Box>
        <Box position="absolute" top={81} height="40px">
          --------------- 81
        </Box>
        <Box position="absolute" top={100} height="40px">
          --------------- 100
        </Box>
      </Box>
    </ChakraProvider>
```

### Chakra UI Version

@chakra-ui/react ^1.6.12

### Browser

Google Chrome 98.0.4758.80

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Perhaps it has to do with the Chakra variable `--chakra-space-80`?

**Comment by takethefake** [comment]
Hej @godfreyyeung thanks for your question!

you're right! it happens because you ran into the `80`-value from `--chakra-space-80`!

`top` is defined here:

https://github.com/chakra-ui/chakra-ui/blob/main/packages/styled-system/src/config/position.ts#L14

and `spaceT` uses either a `space`-token and otherwise falls back to `px` value

https://github.com/chakra-ui/chakra-ui/blob/main/packages/styled-system/src/utils/index.ts#L17


so to ensure you use `80px` write `top="80px"` and therefor avoid getting caught by defined spacing variables.
