### ISSUE TITLE
It's currently not possible to add a focus effect (like box-shadow) to a link

### ISSUE THREAD

**Issue by tomhicks** [chakra-ui/chakra-ui#5575]
### Description

When I add a _focus style including a shadow to a link, I expect that style to be applied

### Link to Reproduction

https://codesandbox.io/s/dazzling-haibt-vnr6u?file=/src/index.tsx

### Steps to reproduce

1. Add a link with a shadow
2. Add the shadow to the _focus styles, too
2. Click the link but make sure the link stays on page (this happens a lot in a Next.js app)
3. The shadow disappears, and there is no way to keep it

### Chakra UI Version

1.8.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Add `:not(.always-show-focus)` or something to the CSS reset and this is fixed immediately! Document the ability to do this, too. Perhaps generally the focus ring should be documented separately? I'm happy to write that if you want.

**Comment by m4x3d** [comment]
Thanks for reporting this!

Found out that it is a global Chakra UI css overwrite in the [CSSReset](https://github.com/chakra-ui/chakra-ui/blob/main/packages/css-reset/src/css-reset.tsx#L276). I guess you could remove that by passing this `resetCSS` prop with `false` in the [ChakraProvider](https://github.com/chakra-ui/chakra-ui/blob/main/packages/provider/src/chakra-provider.tsx#L36). Maybe you need to create your own CSSReset without that boxShadow line.

Since I'm not deep enough in that whole 'reset browser styles' thing and it seems to be a breaking change maybe someone can give me a hint if we need that [boxShadow](https://github.com/chakra-ui/chakra-ui/blob/main/packages/css-reset/src/css-reset.tsx#L276) line in general. Otherwise I think it is better to remove it that users are more flexible with their boxShadows.

**Comment by m4x3d** [comment]
Ok, got it. Cant test it out this morning by myself tbh.\
And yes that re-adding of the CSS reset was more or less meant like a quick and dirty approach for your current problem until it possibly get fixed.

Will have a deeper look during the day. Got a similar problem few days ago thats why I want to have that overwritable too.

**Comment by tomhicks** [comment]
I'm going to create a PR I think - it's an easy fix and should be perfectly backwards compatible.
