### ISSUE TITLE
Allow for properties of a component to be overriden via props

### ISSUE THREAD

**Issue by kkhan01** [chakra-ui/chakra-ui#5587]
### Description

If I pass in a prop to a chakra component, I expect my props to have a higher priority than the default props. 

### Problem Statement/Justification

As applications develop, there are likely different uses that lead to the need to have finer control over props on a component. Or else we'd need to compose our own components.

Recently, I wanted to add an aria label to `TagCloseButton` because `close` wasn't as descriptive as I'd like. However, I was unable to because the component's defaults have a higher priority.

I'm not sure how many other props in other components have this issue. Maybe this should be scoped down to aria labels and different issues for other properties should be brought up accordingly(?)

### Proposed Solution or API

In the case of `TagCloseButton` at least, the props could be reordered here:
https://github.com/chakra-ui/chakra-ui/blob/ead2bd65978fdaa84c14fd3d60d15c3ec4285d87/packages/tag/src/tag.tsx#L111-L119

to be:
```js
    <chakra.button
      type="button"
      aria-label="close"
      disabled={isDisabled}
      __css={btnStyles}
      {...rest}
    >
      {children || <TagCloseIcon />}
    </chakra.button>
```

**Comment by m4x3d** [comment]
Hi, thanks for reporting this. Im totally on your side regarding the aria-label prop.

But in my opinion you should not be able to overwrite all properties without any restrictions. So in this case I would prefer this solution:

```
<chakra.button
  aria-label="close"
  {...rest}
  type="button"
  disabled={isDisabled}
  __css={btnStyles}
>
  {children || <TagCloseIcon />}
</chakra.button>
```

Because Im not that deep into the code it would be nice if someone who is deep into it would give me an thumb up or just assign me to this issue and I will fix it directly afterwards. :smiley:

**Comment by kkhan01** [comment]
Interesting take. Out of curiosity, why shouldn't devs always get the final say in what a property should be? Sure some properties are no brainers and just make _sense_, eg `type="button"` on a button component, but there's nothing lost by letting user props have the highest priority.

The way I see it: devs would just be able to customize whatever they need to at a fine grain level, and the defaults still exist so it's really just an _option_ to override rather than need to define properties.

**Comment by m4x3d** [comment]
Let it me specify it a bit more:
In the first instance Im totally with you. Devs should be able to overwrite properties if needed.

But after I viewed all 90 `{...rest}` spreads I recognized that there are sometimes classes and also default `__css` styles from Chakra UI specfified. I guess in that scope you don't want to give all devs the full control over that because it is a complete breakout of Chakra UI. Lets take the Avatar as an example:
https://github.com/chakra-ui/chakra-ui/blob/ead2bd65978fdaa84c14fd3d60d15c3ec4285d87/packages/avatar/src/avatar.tsx#L213-L218

**Comment by takethefake** [comment]
@kkhan01 @m4x3d regarding `arial-label` i'm on your side, we should adjust this so it can be overwritten.

Giving the user the power to override all properties is kind of a double-edged sword. 

- on the one hand, experienced users can take a look into the implementation of a component understand how it works and adjust props accordingly which gives a lot of power to the user, which is in general not a bad thing
- on the other hand, inexperienced users may run into unexpected behaviour leaving them behind frustrated.

In my opinion in general `chakra-ui` is opinionated in ways how certain components should work. Complete control would be nice in certain scenarios but may lead to redirecting chakra's opinion into your opinion which might be better solved with a custom component that uses some of `chakras` features e.g. component hooks than trying to overwrite certain props to manipulate how a component work.
