### ISSUE TITLE
textUnderlineOffset doesn't have a numerical type

### ISSUE THREAD

**Issue by JackHumphries9** [chakra-ui/chakra-ui#5592]
### Description

When using the textUnderlineOffset property, I have discovered that you can use numerical values. However, Typescript doesn't allow you to use a numerical value. Using a string does not work either.

### Link to Reproduction

https://codesandbox.io/s/cocky-nobel-h0l7gu?file=/pages/index.tsx

### Steps to reproduce

1. See that you can use the property.
2. Run `yarn build` to check the types.
3. See the error in the terminal. `Type error: Type '6' is not assignable to type 'ResponsiveValue<TextUnderlineOffset<0 | (string & {})>>'.`

### Chakra UI Version

1.8.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I did a bit of digging and I don't know if it's maybe an issue with the [csstype](https://www.npmjs.com/package/csstype) package. But I am not sure how Chakra uses this package.

**Comment by MrBirb** [comment]
You cannot use a numerical value though? I just checked the syntax and it only accepts <length> or <percentage>

**Comment by JackHumphries9** [comment]
I'm unsure of what value to use because a string that contains the number (ie `textUnderlineOffset="6"`) seems to have no effect but a number (ie `textUnderlineOffset={6}`) works.

**Comment by TimKolberger** [comment]
The number value works because emotion is converting it to a px value.
Using "6px" as a value should work as well.

We are supporting number values for most <length> CSS values and I think we could add support for this property too.

This file in which this change would need to happen is here: https://github.com/chakra-ui/chakra-ui/blob/main/packages/styled-system/src/config/text-decoration.ts

Kindly file a PR to address this if you like 😊

**Comment by ardnahcivar** [comment]
@TimKolberger raised PR for this

**Comment by mrcaidev** [comment]
Can we add support for `textUnderlineOffset="6"` too? Currently it won't work and we have to specify `textUnderlineOffset="6px"`. I think it would be great if we can omit that "px", just like `p`, `m` do.
