### ISSUE TITLE
[Menu/MenuButton] MenuButton with no text and only rightIcon has odd shape

### ISSUE THREAD

**Issue by jdiamond** [chakra-ui/chakra-ui#560]
I'm trying to use the Menu and MenuButton components with no text in the MenuButton and only a rightIcon and the button has an unexpected shape. I tried using `as={IconButton}` instead of `as={Button}`. The shape now looks correct, but the icon isn't visible.

Screenshot:

![image](https://user-images.githubusercontent.com/110538/78311363-79fafe80-7505-11ea-8ff0-641957df3265.png)

CodeSandbox:

https://codesandbox.io/s/determined-https-p3zi1

**Comment by segunadebayo** [comment]
Hi @jdiamond,

Thanks for this issue. I don't think this is a bug because you're passing `rightIcon` prop to the `MenuButton` which comes with a default left margin.

Here's what you can do:

```jsx
<MenuButton as={Button}>
    <Icon name="chevron-down"/>
</MenuButton>
```

and if you want to use IconButton, you should pass props that are valid to IconButton. `rightIcon` isn't a valid prop.

Here's what you can do:

```jsx
<MenuButton as={IconButton} icon={MdMoreHoriz} />
```

Hope this helps.
