### ISSUE TITLE
Button focus, consider border

### ISSUE THREAD

**Issue by nappalm** [chakra-ui/chakra-ui#5600]
### Description

They should prefer the inactive border, to avoid that when clicking this happened.
![image](https://user-images.githubusercontent.com/35016608/154374816-bceb986e-3982-4b6f-b839-604e97893066.png)

### Problem Statement/Justification

Do I have to put a margin, to avoid this? should generally be considered.

### Proposed Solution or API

Consider the border when the focus is active

**Comment by TimKolberger** [comment]
Hi @nappalm 

The image looks like the element with focus is in a container element which applies `overflow: hidden`. This removes the overflowing pixels from our `box-shadow`. 
To fix this you can apply a margin to the element with focus or a padding to the container.

The browser default for focus style is [outline](https://developer.mozilla.org/en-US/docs/Web/CSS/outline), and we use box-shadow to make it look prettier.

If we would use `border` as focus style, element could loose their own border styles on focus, which are more common than `box-shadow` and they may change their width/height, because we are using `box-sizing: border-box` as the default [box model](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model#border_area).

Closing this because it is not an issue within chakra.
