### ISSUE TITLE
Can't set defaultProps for variant and colorScheme together

### ISSUE THREAD

**Issue by unimonkiez** [chakra-ui/chakra-ui#5715]
### Description

When I added default variant and default colorScheme, I expected it to have both, but instead only variant takes effect

### Link to Reproduction

https://codesandbox.io/s/youthful-frog-l1t1to?file=/src/index.tsx:0-683

### Steps to reproduce

1. Go to sandbox link and expect to see red save button, instead it's gray (try commenting out `variant` on line 11 and see the color showing).

### Chakra UI Version

1.8.6

### Browser

Version 99.0.4844.51 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by omerman** [comment]
It would be nice to be able to have the ability to define default props that are not just variant & size

**Comment by segunadebayo** [comment]
Hi @unimonkiez,

I'm not sure what your expectation is here. The color scheme is closely tied to the "variant" or "visual style" that's why it doesn't work in your example.

If you meant to make the button a specific color or extend an existing variant, that's a different conversation. Please refer to the implementation of the button variants [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/button.ts)

@omerman The lack of that functionality is intentional. You can always use the classic react format for setting components' default props.

```jsx
Button.defaultProps = {{ }}
```

**Comment by unimonkiez** [comment]
Thank you 🙏
