### ISSUE TITLE
It would be nice if i could use color variants (colorName.500, colorName.200) in colorScheme. 

### ISSUE THREAD

**Issue by ramizqazi** [chakra-ui/chakra-ui#5716]
### Description

It would be nice if I could use color variants (colorName.500, colorName.200) in colorScheme please add this feature. 

### Problem Statement/Justification

It is a really useful feature. I like the color scheme property It makes the work much easier but when I need a different color than the default red, blue, green I can't do much the color scheme property only accepts its default color, and that does not fit my needs.

Please Ignore Bad English I Am Learning! 

### Proposed Solution or API

Make ColorSheme property to accept any given color hex code.

**Comment by TylerAPfledderer** [comment]
Hey @ramizqazi!

There is a discussion going in the Chakra Doc issues regarding adding documentation for themes to each component, and this might be something to also consider.

You can, however, use a custom colors by name in the `colorScheme` prop! You just have to know how the color scheme is used in the components' default theming.

For example, take a look at the theme for the `Button` component: https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/button.ts

I'm looking at lines 108 - 111 under the `variantSolid` properties, as this is the default set of properties used.

`colorScheme` is passed in as `c`. And you can see for `bg` it's looking for the 500 shade of the color name from the theme. Then  `hoverBg` looking for the 600 shade. And so on.

So you can extend the theming with a new color name and provide custom colors set to 500, 600, and 700. Then you can pass this color name to the `colorScheme`.

Check out this sandbox example for a possible use, using the `Button` component: https://codesandbox.io/s/distracted-satoshi-0hc0lr?file=/src/index.js

Is this what you had in mind?

**Comment by Patrick-Ullrich** [comment]
Not sure if that goes with @ramizqazi thoughts, but colorScheme has become essentially useless outside of prototyping because of the set `hues` (hardcoded c.500, c.800 etc). I wonder if adding another property like `colorSchemeHue` would make this better. 

I think making it overwriteable is easy, the question is more on what the API should look like to indicate what number to use for which action. e.g. 

colorSchemeHue={{
  _hover: 200,
  default: 800
}}

seems a bit cumbersome.

**Comment by veloware** [comment]
I too am running into similar cumbersome issues.  I love Chakra so far, but small complexities like this cropping up are making me thing twice about using the library unfortunately.  Im looking to use the `Tabs`, `TabList` and `Tab` components to build a simple tabbed content switcher, pretty simple stuff, and I am looking to match the colour with my teams designers have came up with,  but because the design system's 'palette' of colours don't align with the _hue_ of the colour that the component is looking for - 

```
const variantSoftRounded: PartsStyleFunction<typeof parts> = (props) => {
  const { colorScheme: c, theme } = props
  return {
    tab: {
      borderRadius: "full",
      fontWeight: "semibold",
      color: "gray.600",
      _selected: {
        color: getColor(theme, `${c}.700`),
        bg: getColor(theme, `${c}.100`),
      },
    },
  }
}
``` 

in this case `c.100`,  I don't see a way to easily style the tabs as per the designs on my project other than to re-export the component and pass different props? 

```
import { Tab as ChakraTab } from '@chakra-ui/react';
export const Tab = ChakraTab;

Tab.defaultProps = {
   _selected: {
      color: '#ff0000' <-- or whatever hex colour I need to match the designs
   }
}
```

then usage - 

```
import { Tab } from '@my-component-lib'
...
<Tab>My tab</Tab>
```

I've also noticed that various components that use a colorScheme will using differing hue levels as the base,  e.g. compare the above Tabs config with the Button config below - 

```
return {
    bg: background,
    color: mode(color, `gray.800`)(props),
    _hover: {
      bg: mode(hoverBg, `${c}.300`)(props),
      _disabled: {
        bg: background,
      },
    },
    _active: { bg: mode(activeBg, `${c}.400`)(props) },
  }
```

Tabs uses color - gray.600 for the `color` style, whereas the Button uses `gray.800`, and so on

**Comment by Manyu-Vll** [comment]
I also like the colorScheme property, but I would like more flexibility on choosing what hue is chosen (as for hover etc...).
@Patrick-Ullrich proposal seems what would fix this.

**Comment by Patrick-Ullrich** [comment]
I have put up a Draft PR - open for feedback. It just uses the ideas brought forward here and actually implements them.

Personally, I am torn. I wonder if it adds too much overhead and ends up being not that great of a solution. On the other hand, I currently just ignore colorScheme all together or have a custom implementation on top of it.

**Comment by svrakata** [comment]
In Mantine there is primaryShade property that defines what level from the pallete should be used to color the components. I find that useful and kind of way to solve the problem. Hover and other state colors should be based on the primaryShade (lighten up etc.).

**Comment by sushanyadav** [comment]
any alternative to getColor? since it is deprecated.
