### ISSUE TITLE
Border not working when set props in different order

### ISSUE THREAD

**Issue by itta611** [chakra-ui/chakra-ui#5761]
### Description

When I set `borderColor` prop before `border`, border color set with default color `gray.800`.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-border-bug-38mugc

### Steps to reproduce

1. Set `borderColor` prop before `border`.
2. You can check it `borderColor` is not applyed.

### Chakra UI Version

latest (1.8.6)

### Browser

Google Chrome 99

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I checked how the `border-color` property is set in the developer tools, and while this property looks to be applied correctly, but the `border-top-color`, `border-right-color`, `border-bottom-color` and `border-left-color` were not set to any value.

<img width="380" alt="スクリーンショット 2022-03-22 18 46 54" src="https://user-images.githubusercontent.com/86896657/159452891-b1cff7a6-0b2d-482a-8bdc-b65e84b2a22f.png">

**Comment by segunadebayo** [comment]
Hi @itta611,

This isn't a bug in Chakra but how CSS styles work. The `border` declaration you've put sets the value for the border width, style and color together. I see you passed just the width, which is the issue here.

Even though you passed a prior `borderColor`, it won't take effect because you pass `border:1px` which means `border: 1px inherit inherit` and ends up being the root border-color.

To fix this, you should use `borderWidth: 1px` instead.

**Comment by TimKolberger** [comment]
border is a CSS shorthand property which overrides the properties border-width, border-style and border-color. [See MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/border)

If chakra deviates from the CSS spec, it is is hard to anticipate its behavior. This will have a negative effect on the developer experience.

Does using the borderWidth, borderStyle and borderColor props solve your stated issue?
