### ISSUE TITLE
`alignItems` does not work on `Wrap` component but `align` does

### ISSUE THREAD

**Issue by Ploppy3** [chakra-ui/chakra-ui#5765]
### Description

`alignItems` does not work on `Wrap` component but `align` does

### Link to Reproduction

https://codesandbox.io/s/magical-estrela-fd4d8g?file=/src/index.js

### Chakra UI Version

1.8.6

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @Ploppy3,

This is because of the structure of the HTML and how we handle the props internally. In [the code](https://github.com/chakra-ui/chakra-ui/blob/main/packages/layout/src/wrap.tsx), you can see that `align` is added to the `ul` element while other props are passed to the root `div` element.

Therefore `align` is a custom prop we designed for the wrap component, not a generic prop that's interchangeable with the flex-box `alignItems`.
