### ISSUE TITLE
Multipart theming not working for PinInput

### ISSUE THREAD

**Issue by nvmnghia** [chakra-ui/chakra-ui#5826]
### Description

I can't use `extendTheme()` to theme `PinInput` and `PinInputField`.

### Link to Reproduction

https://codesandbox.io/s/nervous-antonelli-0n60d6?file=/src/index.js

### Steps to reproduce

The `borderColor` attribute doesn't apply to `PinInputField`, although it does to `Input`.

### Chakra UI Version

1.8.7

### Browser

Chrome 100

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @nvmnghia,

We'll take the blame for this one and try to improve the documentation around the component theming.

`PinInput` isn't a multipart component so you don't need to nest it inside `field` property. Here's a working solution.

https://codesandbox.io/s/bold-wilson-jj4z92?file=/src/index.js

**Comment by Chukwuamaka** [comment]
Hello @segunadebayo.

I ran into this same issue trying to set a background color to the filled variant of the component and I struggled for some hours trying to figure out a solution both from the docs and my knowledge of component theming. From playing around with it, I figured that the issue was from the theme not being applied to the individual PinInputField components and that bg is not even a valid prop for the PinInput component, hence I thought this was a multipart component since it didn't state otherwise in the docs. I had already resorted to repeatedly passing the bg prop on each PinInputField component before I found this issue and followed your recommendation.

Sadly, it's been more than a year since the initial issue was reported but the docs hasn't been updated yet. Is this something I can fix so that others don't experience this?
