### ISSUE TITLE
popover and menu matchWidth property does not constrain content longer than width

### ISSUE THREAD

**Issue by baileywall** [chakra-ui/chakra-ui#5865]
### Description

When setting the matchWidth property on a Popover or Menu component, I expect the width of the dropdown to match the width of the trigger but if the content is larger than the trigger width the dropdown expands beyond the trigger width to attempt to fit the content.

### Link to Reproduction

https://codesandbox.io/s/headless-framework-xgppe4

### Steps to reproduce

1. Click on "Fit Content" and see that the width of the popover / menu content fits the content (matchWidth is not set).
2. Click on "Short Content" and see that the width of the popover / menu content expands to match the trigger's width (because matchWidth is set).
3. Click on "Long Content" and see that the width of the popover / menu content expands to attempt to fit the content (matchWidth is set).

### Chakra UI Version

1.8.8

### Browser

firefox 99.0, chrome 100.0.4896.75 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Thanks, chakra is awesome!

**Comment by segunadebayo** [comment]
I can confirm this is an issue. The issue might be from the `packages/popper` package because we're setting ` minWidth: "max-content",` in the styles.

**Comment by Bob-On-Github** [comment]
[I hope it's the correct place to mention that]
I tend to think the original behaviour was correct and that the proposed solution in fact broke it. To my understanding, `matchWidth` attribute was trying to match the width of the popover popper/content with the width of the popover trigger. Considering this, when the content is wider than the trigger, it may be wider **but** it is expected to follow any other constraint that may have been applied to it (placement, etc.)

Since removing `min-width: max-content` in 6b969b41dad850fa061613b3d50f50b8a15265a7, when the content is wider than the trigger (as in "with a predefined width that you cannot squeeze enough to fit the trigger's width"), it is still wider **AND** it is breaking other constraints such as placement...

This can be reproduced on Chakra docs:
* Navigate to [v1 docs for Popover basic usage](https://v1.chakra-ui.com/docs/components/overlay/popover#basic-usage) and [v2 docs for Popover basic usage](https://chakra-ui.com/docs/components/popover/usage#basic-usage)
* Add a `matchWidth` attribute to the Popover components
* Notice how the default `bottom` placement is ignored in v2

v1
![image](https://user-images.githubusercontent.com/26261763/231242295-81b0651a-daa1-4a43-a6c2-51eabc45c9d8.png)

v2
![image](https://user-images.githubusercontent.com/26261763/231242400-9889e1a7-4c84-40b8-96a3-d6500bd40a09.png)

This is detrimental for any select or date-picker input that was built with Chakra UI, as it cannot be placed on the edge of the window anymore

**Comment by kaf-lamed-beyt** [comment]
Incase anyone runs into this in the future again. You can modify the menu component to fit your need by using the anatomy config. 

Here's how I modified mine to ensure the with fits the content of menu. 

```ts
import { menuAnatomy } from "@chakra-ui/anatomy";
import { createMultiStyleConfigHelpers } from "@chakra-ui/react";

const { definePartsStyle, defineMultiStyleConfig } =
  createMultiStyleConfigHelpers(menuAnatomy.keys);

const baseStyle = definePartsStyle({
  list: {
    minWidth: "fit-content",
  },
});

export const menuTheme = defineMultiStyleConfig({ baseStyle });

import { extendTheme } from "@chakra-ui/react";
import { menuTheme } from "./menu";

const theme = extendTheme({
  components: {
    Menu: menuTheme,
  },
});

export default theme;
```
Then in the provider, import your theme 

```
import {theme} from "theme.ts"

<ChakraProvider theme={theme}> content</ChakraProvider>
```
