### ISSUE TITLE
[Theming] Styled Components Theme

### ISSUE THREAD

**Issue by zandoh** [chakra-ui/chakra-ui#59]
When using chakra-ui and styled-components the theme prop is not passed into the styled-component

Reproduction CodeSandbox below
https://codesandbox.io/s/modest-bogdan-fnc0q

**Comment by segunadebayo** [comment]
Hi @zandoh ,

Chakra was built using `emotion` not `styled-components`. The `ThemeProvider` comes from `emotion-theming` that's why it's not working.

We'll think of a way to support `styled-components` soon. Making the switch from styled-components to emotion is quite seamless, so you can consider that.

If you switch the `styled` to come from `@emotion/styled`, it should work.

**Comment by segunadebayo** [comment]
I going to close this issue.

As I explained earlier, if you switch `import styled from styled-components` to `import styled from @emotion/styled`, it resolves this issue.
