### ISSUE TITLE
Not possible to change role to Menu component.

### ISSUE THREAD

**Issue by zygimantastalech** [chakra-ui/chakra-ui#5902]
### Description

I want to be able to change role to `MenuList` and `MenuItem` components.

I can see in the chakra codebase that it's definitely not possible, because adding `role` end of item properties, after spreading other rest component props (attached screenshots).

### Problem Statement/Justification

I want to add a role of `listbox` to the `MenuList` component and add a role of `option` to `MenuItem` component, but it keeps overriding it to be `menu` and `menuitem`.

It's required for `a11y` issue to solve `Voice Over` reading problems.

### Proposed Solution or API

![image](https://user-images.githubusercontent.com/50610012/164166935-349b0c57-e2c4-476d-add7-dc48e63a5c9c.png)
![image](https://user-images.githubusercontent.com/50610012/164167123-6d6db751-1552-477b-9ba4-b0b18428d68a.png)

**Comment by segunadebayo** [comment]
Hi @zygimantastalech,

This is by design. The `Menu` component was built to mirror the menu ARIA pattern. Trying to use the `Menu` to create a Listbox seems like the wrong pattern. I don't recommend it.

The Listbox pattern goes beyond being able to navigate the options and selecting an option to close.

For example, based on [Listbox example](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-scrollable.html):
- there needs to be `aria-selected` attached to the selected option
- there needs to be `aria-activedescendant` on the Listbox (and Listbox should have DOM focus)

These are patterns that are not built into the Menu component. From a design standpoint, I'd consider this a feature request to create a Listbox component. We'll look into that in the future.

If you still want to go ahead with your idea, feel free to use the `useMenu` and `useMenuItem` hooks instead. So you can override the parts as needed. Again, I don't recommend this approach.

Thanks for understanding.
