### ISSUE TITLE
Input doesn't work with <DarkMode>

### ISSUE THREAD

**Issue by dufia** [chakra-ui/chakra-ui#5966]
### Description

Input stays in light mode even if wrapped in <DarkMode>

### Link to Reproduction

https://codesandbox.io/s/crazy-hellman-4f2xn3?file=/src/index.tsx

### Steps to reproduce

1. Open the codesandbox

### Chakra UI Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TylerAPfledderer** [comment]
Hey @dufia! It appears that your CSB example is working as expected. Could you clarify which styling is not changing?

Also, by latest version, do you mean `v1.8.8` or did you bump to `2.0.0-next3`?

**Comment by dufia** [comment]
@TylerAPfledderer 

Input on the top is the same as input on the bottom, even though the one is wrapped in <DarkMode>. The button is correctly dark.
<img width="266" alt="Screenshot 2022-05-05 at 13 52 09" src="https://user-images.githubusercontent.com/5569649/166917679-de92bb00-36f6-4a51-b426-8ec31c944a6b.png">

If toggled to dark mode globally, it changes state. 
<img width="285" alt="Screenshot 2022-05-05 at 13 52 16" src="https://user-images.githubusercontent.com/5569649/166917681-c496e17d-ae17-4b48-a018-7a4e28d506f8.png">

It's `1.8.8`

**Comment by TylerAPfledderer** [comment]
Ah I understand. 🤦🏼‍♂️

**Comment by TylerAPfledderer** [comment]
So the default variant is `outline` which does not have any styles that are directly affected by toggling dark mode except for the border style on hover. This is working as intended if you remove the `bg` color from the `Box` to allow the whole preview box to change color, and then hover over the input when "Light" mode is toggled.

The input's `border-color` not on hover is inherited by any immediate parent or ancestor whose `border-color` is affected by the toggle. In this case, it's the global styling:
```
*, ::before, ::after {
  border-color: var(--chakra-colors-gray-200);
  word-wrap: break-word;
}
```

The `bg` prop also has the value `inherited`.

I change the `variant` to "filled" and that is working! 😄 

The only good solution I see is to not have inherited values in the "outline" variant. But was it intentional to allow a parent to affect this styling?

**Comment by dufia** [comment]
@TylerAPfledderer thanks for investigating it :+1:

**Comment by TylerAPfledderer** [comment]
Closing this issue, as the `outline` variant uses `inherit` to apply global styling in dark mode. The best solution is to add the 'borderColor' and 'color' props to the component to force the color value to render no matter the color mode. 

Otherwise, create a new variant if used in multiple places.
