### ISSUE TITLE
Formik: Expression produces a union type that is too complex to represent. 

### ISSUE THREAD

**Issue by unclerom** [chakra-ui/chakra-ui#6023]
### Description

When following the documentation for advanced integration of formik into chakra I encounter the following typescript error
```
Expression produces a union type that is too complex to represent.ts(2590)
```

The issue is also visible in the docs code sandbox
<img width="613" alt="image" src="https://user-images.githubusercontent.com/29046942/168393572-a536f24c-bca9-483b-987b-078363becdb3.png">

### Link to Reproduction

https://codesandbox.io/s/6qcl2r?file=/input.tsx&from-sandpack=true

### Steps to reproduce

1. Follow documentation for advanced formik integration
2. run `tsc`
3. see compilation error

### Chakra UI Version

1.9.1

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @unclerom,

This is a TypeScript issue you need to resolve, not a Chakra UI issue. See the type definition in formik is defined as 

```ts
export declare type GenericFieldHTMLAttributes = JSX.IntrinsicElements['input'] | JSX.IntrinsicElements['select'] | JSX.IntrinsicElements['textarea'];
```

The compiler can't possibly understand how to merge this with `InputProps`. Consider omitting `FieldHookConfig<"input">;` since the properties already exists in `InputProps`
