### ISSUE TITLE
CLI gets stuck after generating tokens

### ISSUE THREAD

**Issue by wladiston** [chakra-ui/chakra-ui#6177]
### Description

When I run `chakra-cli tokens --strict-component-types`, I expected it to exit code after generating types but it gets stuck making it not viable to keep on `postinstall` script 

### Link to Reproduction

https://github.com/wladiston/chakra-cli-isse

### Steps to reproduce

1. run `yarn install`
2. see the error

### Chakra UI Version

1.9.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="471" alt="Screen Shot 2022-06-09 at 11 45 01 AM" src="https://user-images.githubusercontent.com/1843792/172877219-70e67871-8c95-4511-9d38-fe4074f36b1a.png">

$ node -v
v16.15.0
$ yarn -v
1.22.15

**Comment by YosefBlandin** [comment]
Hi @wladiston I've cloned your repository in order to replicate the issue but it works fine here, I set the node and yarn version as you have.

![1](https://user-images.githubusercontent.com/65220054/173482709-c1390b86-d168-41c2-bebe-4503dbe65cfa.png)

**Comment by YosefBlandin** [comment]
Hi @wladiston I've cloned your repository in order to replicate the issue but it works fine here, I set the node and yarn version as you have. If someone has the same issue, please let us know

![1](https://user-images.githubusercontent.com/65220054/173482709-c1390b86-d168-41c2-bebe-4503dbe65cfa.png)


![1](https://user-images.githubusercontent.com/65220054/173483605-31681404-c0af-40c6-a1fe-d893679a0998.png)

**Comment by YosefBlandin** [comment]
![1](https://user-images.githubusercontent.com/65220054/173484050-5c267f28-810f-4201-b62a-c3580afb77e0.png)

**Comment by joernroeder** [comment]
I have the same issue

**Comment by wladiston** [comment]
It seems to be working fine for some unknown reasons
