### ISSUE TITLE
Make a ToastProvider component so Toasts are usable within React Classes

### ISSUE THREAD

**Issue by davidli3100** [chakra-ui/chakra-ui#618]
Currently, Chakra UI toasts are only usable within a functional component, thus, they are not generally backwards compatible with other class components (even though hooks and functional components are now generally the norm).

Ideally there would be a `ToastProvider` of some sort similar to that of other libraries to provide compatibility.

**Comment by segunadebayo** [comment]
Hi @davidli3100,

I think you can make this work with Class components as well. You simply need to mount the toast function from `useToast` on a provider then consume that.

```jsx
// create toast context
const ToastContext = React.createContext(() => {});

// create provider
function ToastProvider({ children }) {
  const toast = useToast();
  return (
    <ToastContext.Provider value={toast}>{children}</ToastContext.Provider>
  );
}

// use in class components
class Example extends React.Component {
  render() {
    return (
      <ToastContext.Consumer>
        { toast => (
          <button onClick={() => toast({ title: "Chakra is the best!" })}>
            Click me
          </button>
        )}
      </ToastContext.Consumer>
    );
  }
}
```

Hope this helps

**Comment by Sofianio** [comment]
This is not a clean way to do it

**Comment by jsonMartin** [comment]
> 
> 
> This is not a clean way to do it

I agree...

**Comment by femi-Zedev** [comment]
What i'm going to share may not exactly fit for Class Component (I hope it can help tho) but it be can helpfull for other usecases. 
The idea is to create a provider just as @segunadebayo did but to expose the function triggered by the button so that we can fire that function from anywhere in our app. Here what the provider could look like:
`'use client'; // for people using NextJs
import { Box, useToast } from '@chakra-ui/react'
import React, { ReactNode, createContext, useContext, useState } from 'react'

interface ToastStateType {
	showToast(body: ReactNode): void; // you could add more paramaters such as the toast position and so on ...
}

const defaultAuthState: ToastStateType = {
  showToast: (body) => { },
};

const ToastContext = createContext(defaultAuthState);

export const useNotify = () => useContext(ToastContext);

export default function ToastProvider({ children }: { children: ReactNode }) {

  const toast = useToast()



  function showToast(body: ReactNode) {
    toast({
      position: 'bottom-right',
      render: () => (
        <Box color='white' p={3} bg='blue.500'>
          {body}
        </Box>
      ),
    })
  }

  return (
    <ToastContext.Provider
			value={{
        showToast: (body) => showToast(body),
      }}>
			{children}
		</ToastContext.Provider>
  )
}
`
