### ISSUE TITLE
portalZIndex causes toasts to appear under modals

### ISSUE THREAD

**Issue by anilanar** [chakra-ui/chakra-ui#6276]
### Description

When I use a toast while a modal is open, I expect the toast to always appear at the top of the stack.

### Link to Reproduction

https://codesandbox.io/s/homepage-forked-tiouzc

### Steps to reproduce

1. Go to https://codesandbox.io/s/homepage-forked-tiouzc
2. Click on 'Toggle'
3. Click on 'Toast' multiple times
4. See that toasts are rendered below the modal.

### Chakra UI Version

2.2.1

### Browser

All

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by anilanar** [comment]
Not stale.

**Comment by wjpg** [comment]
+1 👍

**Comment by austinbradshaw** [comment]
+1 👍

**Comment by austinbradshaw** [comment]
What's interesting is that the theme's z-index vars put toasts > modals

![image](https://user-images.githubusercontent.com/66370533/197243147-39d89432-ec9b-40e3-a78e-5ca82e646e40.png)

**Comment by matusca96** [comment]
Not by a long shot the best solution, but if you fell here because you're using a modal with another modal or drawer above and also need to display a toast above everything you can try this:

Let's suppose you put the property `portalZIndex` to be equals `5`, in this case you need to increase the z-index from the toast portal in 1, which you could reach by adding this css content:

index.css
```
@supports selector(:has(*)) {
  .chakra-portal-zIndex:has(#chakra-toast-manager-top) {
    z-index: 6 !important;
  }
}
```

Then you just need to import this css file in the root file of your project:

main.tsx/index.tsx/...
```
import './index.css'
```

I know that there is not enough support for the `has` selector, and maybe could be better ways to increase this z-index only for the toast portal, but is a way out for someone that is stuck in this annoying issue.

**Comment by anilanar** [comment]
@ParriauxMaxime The downside of that workaround is that it will now render things such as menus, popovers and all usages of portals behind toasts. Maybe worth making a note of it for people who might copy/paste your code.

**Comment by selrond** [comment]
Has anybody found out why setting `portalZIndex` causes this?

**Comment by codebutler** [comment]
I am noticing that the behavior is inconsistent based on the order things happen. If a modal is displayed immediately when the page loads, toasts will appear above the overlay. Otherwise they show up below. This is happening because of the order that the portal containers are added to the DOM. See example:
https://replit.com/@codebutler/ChakraPortalZIndexProblem#src/App.tsx

| below | above
|--|-----
| <img width="1732" alt="Screenshot 2023-04-22 at 9 28 29 AM" src="https://user-images.githubusercontent.com/3827/233796010-549fd264-0a4b-4c17-aab7-49bd286ce744.png"> | <img width="1732" alt="Screenshot 2023-04-22 at 9 30 35 AM" src="https://user-images.githubusercontent.com/3827/233796013-af034b70-f206-487d-a944-dee32bab8f08.png">


Is it possible to solve this problem with only a single global `portalZIndex`? The theme system defines a constant for toast z-index, but I don't think this is used anywhere?
https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/theme/src/foundations/z-index.ts#L13

Adding a toast container (as suggested above) with an explicit z-index solves the problem in either scenario
```tsx
<Box ref={toastContainerRef} zIndex="toast" />
```

@anilanar I'm curious, what's a scenario where you don't want a toast to be on top of everything (menus/popovers/etc)?

**Comment by anilanar** [comment]
@codebutler I agree, it's an extreme and most likely an ignoreable edge case. But I would expect a menu to appear above everything else when I click it. Let's say, if there's a toast at the same spot where I'm interacting with the menu with and when I click it, if menu appears below the toast, I'd possibly consider that a bug. Especially when toast has long duration or if it requires dismissing with a click.

**Comment by GabriPires** [comment]
Same issue here

**Comment by leadream** [comment]
Same here.

**Comment by vincent-vdl** [comment]
Same here

**Comment by haneefneef** [comment]
Same issue here

**Comment by segunadebayo** [comment]
This is a design flaw in v2.

Please set the `--toast-z-index` variable in a global style to get this working consistently

```tsx
const theme = {
   styles: { body: { "--toast-z-index": "zIndices.toast" } }
}
```

**Comment by firstpersoncode** [comment]
> This is a design flaw in v2.
> 
> Please set the `--toast-z-index` variable in a global style to get this working consistently
> 
> ```tsx
> const theme = {
>    styles: { body: { "--toast-z-index": "zIndices.toast" } }
> }
> ```

I did add that and still have the issue

**Comment by kubk** [comment]
Solved this by switching to `notistack` with this hack: https://github.com/iamhosseindhv/notistack/issues/231#issuecomment-1509515003

The approach suggested above with `"--toast-z-index": "zIndices.toast"` also didn't work for me. It seems like `theme` doesn't even accept `styles`: 



<img width="612" alt="Screenshot 2024-10-09 at 15 03 58" src="https://github.com/user-attachments/assets/51f2a94d-387a-4ff9-874b-210c1f652dac">

**Comment by coddingtonbear** [comment]
@firstpersoncode -- I'm afraid the proposed solution does work if you happen to have a z-index set under that name. You can confirm that it's that problem by changing where you see  `zIndices.toast` to instead be something like `9999`.
