### ISSUE TITLE
Slider doesn't render when using a custom theme

### ISSUE THREAD

**Issue by KolbySisk** [chakra-ui/chakra-ui#6298]
### Description

When I try to use a Slider, nothing renders, but only when using a custom theme

### Link to Reproduction

https://codesandbox.io/s/affectionate-microservice-rfsdhe?file=/pages/index.tsx

### Steps to reproduce

See it here: https://codesandbox.io/s/affectionate-microservice-rfsdhe?file=/pages/index.tsx

If you remove the theme from the provider, it works fine. 
If you inline the theme instead of breaking it into modules, it seems to work.

### Chakra UI Version

@chakra-ui/react": "2.2.1"

### Browser

FireFox 102.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @KolbySisk,

This is happening because of this Syntax `import * as components from 'components'`. That imports the components as a namespaced module, not exactly an object.

My recommendation is to properly export a components object, as shown here: https://codesandbox.io/s/nice-dubinsky-nx734f?file=/theme/components/index.ts

Cheers
