### ISSUE TITLE
referrerPolicy not work in NextJS (<Avatar/>)

### ISSUE THREAD

**Issue by nasatome** [chakra-ui/chakra-ui#6327]
### Description

When I want to use the referer policy in NextJS, it is implemented inside a `<span>` tag (In the Avatar component)

### Link to Reproduction

https://codesandbox.io/s/dazzling-thunder-v5ucno

### Steps to reproduce

1.- Inspect the Avatar generated html
expected result:
![image](https://user-images.githubusercontent.com/18271791/179078478-9f8ced8b-df70-4f0f-a671-2291045973d9.png)

Obtained:
![image](https://user-images.githubusercontent.com/18271791/179078247-61c2ea0e-f0b7-4d21-a518-bbc75c60ebdb.png)

### Chakra UI Version

2.2.4

### Browser

Chromium v101

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Related: https://github.com/chakra-ui/chakra-ui/issues/5909

**Comment by wub** [comment]
I've been struggling with this too. It looks like the referrer-policy doesn't actually get passed through to `useImage` (see [here](https://github.com/chakra-ui/chakra-ui/blob/19e1532ec5a03b3b14a605f8a602d3a4e835db48/packages/image/src/use-image.ts)), which loads the image in the background and then swaps the element over. The initial load fails because it's missing the param.

I assume your expected result is `referrerPolicy="no-referrer"`, not `no-referrer="no-referrer"`.

(Pinging @jaqas because he took care of #6057 😄)

**Comment by nasatome** [comment]
> 
> I assume your expected result is `referrerPolicy="no-referrer"`, not `no-referrer="no-referrer"`.
> 


That's right, I had a problem copying and pasting, sorry.

**Comment by nogenem** [comment]
Having the same problem ;/

**Comment by ItamarShDev** [comment]
you can use https://nextjs.org/docs/advanced-features/security-headers

**Comment by segunadebayo** [comment]
This has already been fixed in one of the recent PRs. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.
