### ISSUE TITLE
Multiple toast when using multiple react roots

### ISSUE THREAD

**Issue by mabey01** [chakra-ui/chakra-ui#6328]
### Description

When a page has multiple react roots, showing a toast causes multiple toasts to be rendered.

### Link to Reproduction

https://stackblitz.com/edit/react-ts-2ja3cn?file=index.tsx

### Steps to reproduce

1. Go to [demo](https://stackblitz.com/edit/react-ts-2ja3cn?file=index.tsx)
2. Click on "Show toast"
3. Click on "Update" to update the count of toast rendered.
4. See that it's more than the visual toasts seen on screen.

When downgrading to chakra v1.8.8 and react v17, this issue does not happen. There is just 1 toast rendered.

### Chakra UI Version

2.2.4

### Browser

Chrome 103

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jonathanwilke** [comment]
I am having the same issue. On a "normal" page I only get one toast. But when I am on a page where I have a shadow root element included, I get a second toast.

**Comment by itkrt2y** [comment]
[Workaround] Use `ChakraProvider` of `@chakra-ui/provider` instead of `@chakra-ui/react` for the second and subsequent ones.

```tsx
// Example

import { ChakraProvider } from '@chakra-ui/react';
import { ChakraProvider as RawProvider } from '@chakra-ui/provider';
import React, { ComponentType } from 'react';
import * as ReactDOM from 'react-dom/client';

let initialized = false;

function initializeRoot(Root: ComponentType, containerId: string) {
  let Provider: typeof ChakraProvider;
  if (initialized) {
    Provider = RawProvider;
  } else {
    Provider = ChakraProvider;
    initialized = true;
  }

  const root = document.getElementById(containerId);
  ReactDOM.createRoot(root).render(
    <Provider>
      <Root />
    </Provider>
  );
}
```

The `ChakraProvider` in `@chakra-ui/react` contains the `<ToastProvider>`, but the `@chakra-ui/provider` does not.
https://github.com/chakra-ui/chakra-ui/blob/88e812c3a6d99554965b54856382916b6fbf6774/packages/react/src/chakra-provider.tsx#L16-L25
https://github.com/chakra-ui/chakra-ui/blob/88e812c3a6d99554965b54856382916b6fbf6774/packages/provider/src/chakra-provider.tsx#L63-L96
You can prevent multiple toasts by not using `<ToastProvider>` multiple times.
