### ISSUE TITLE
Focusable Icon not focusing 

### ISSUE THREAD

**Issue by ariel-serruya** [chakra-ui/chakra-ui#6359]
### Description

When I pass an `Icon` component the focusable prop, I expect it to focus on keyboard tabbing.

### Link to Reproduction

https://codesandbox.io/s/morning-dawn-z07os7?file=/src/index.js

### Steps to reproduce

1. Create an `Icon` component 
2. Pass it `focusable={true}`
3. Try tabbing to that icon 

### Chakra UI Version

Latest

### Browser

Google Chrome Latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Perhaps I'm misunderstanding what the `focusable` prop is meant to do, but I imagine it would enable a user to tab focus to that icon. I'd like to have tooltips for Help/Info icons appear on tab focus without relying on IconButtons.

**Comment by aboveyunhai** [comment]
@ariel-serruya in order to make it work,  you need to provide a `tabIndex`， for example `tabIndex={0}` to the icon.

https://allyjs.io/tutorials/focusing-in-svg.html
Technically it's a `<svg />` question, you might want to do your own google search for the specification of each attribute.
https://allyjs.io/tutorials/focusing-in-svg.html

**Comment by segunadebayo** [comment]
Closing based on @aboveyunhai's comment.
