### ISSUE TITLE
Preview build of CodeSandbox is broken

### ISSUE THREAD

**Issue by yukukotani** [chakra-ui/chakra-ui#6397]
### Description

When I've submitted a PR and open CodeSandbox preview, an error has been occurred regardless of the content of PR.

### Link to Reproduction

https://codesandbox.io/s/create-react-app-ts-x2jy8c

### Steps to reproduce

1. Submit PR
2. Create CodeSandbox with preview build hosted on `pkg.csb.dev`.
3. The error `React.createContext is not a function` has been occurred

### Chakra UI Version

v2.2.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Maybe #6356 is the cause.

**Comment by itkrt2y** [comment]
This is essentially a CodeSandbox bug. (ref: https://github.com/codesandbox/codesandbox-client/issues/6160)

ChakraUI exports esm files with `.mjs` for esm environments since #6356 and CodeSandbox uses these `.mjs` files.
However, in CodeSandbox, mjs files incorrectly import cjs packages when using `import * as React from "react"`.

[minimal reproduction](https://codesandbox.io/s/react-with-mjs-error-ebrp93?file=/src/App.mjs)

To fix this, we should use `import React from "react"` or named imports like `import { useState } from "react"` instead of `import * as React from "react`.

**Comment by yukukotani** [comment]
@itkrt2y Somehow your reproduction works without errors on the latest master branch of codesandbox-client hosted on my local computer. Maybe the bug will be fixed in the next release?

**Comment by yukukotani** [comment]
I found that `import React, { createContext } from "react"` is also broken.

repro: https://codesandbox.io/s/react-with-mjs-error-forked-f2wv3u
