### ISSUE TITLE
An empty span tag injected by ChakraProvider becomes visible when a modal is rendered inside a stack

### ISSUE THREAD

**Issue by ehynds** [chakra-ui/chakra-ui#6420]
### Description

An empty `span` tag injected by `ChakraProvider` becomes visible when a modal is rendered inside a stack. I haven't been able to reproduce the issue when the stack is removed.

### Link to Reproduction

https://codesandbox.io/s/black-cherry-54whdz?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/black-cherry-54whdz?file=/src/App.tsx. This sandbox includes a DOM structure with a button that triggers a modal, both of which are inside a stack.
2. Click on the `Open modal` button
3. You may not see it on the first click, but eventually you'll see a flash of red content when the modal opens. This is caused by an injection of an empty `<span />` tag by `ChakraProvider` somehow becoming visible while the modal opens. I've given this `span` a width, height, and a red background so you can see the visual jank it causes when the modal opens.

### Chakra UI Version

2.2.4

### Browser

Chrome latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

* This issue is not present in `v2.2.1`
* https://github.com/chakra-ui/chakra-ui/issues/6374 also complains about the `span` tag causing issues

**Comment by clement-v8** [comment]
Hi @ehynds 
I just checked the codebase. the span is generated in `EnvironmentProvider`. the purpose is it needs to provide an environment context.

https://github.com/chakra-ui/chakra-ui/blob/main/packages/env/src/env.tsx#L59

So I think we can suggest that we should wrap the children in a `div` like wrapper instead of creating a separate `span` tag.

wait for more from the authors!
