### ISSUE TITLE
Popover not closing when initialFocusRef is set

### ISSUE THREAD

**Issue by florianmartens** [chakra-ui/chakra-ui#6510]
### Description

When the Popover component received the initialFocusRef the closing functionality does not work as expected.

### Link to Reproduction

https://codesandbox.io/s/suspicious-meitner-54jnnz?file=/src/CustomPopover.tsx

### Chakra UI Version

2.2.8

### Browser

Chrome 98

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

When the initialFocusRef is set, the Popover does not close. 

Might be related to: #6326

**Comment by NickVishwamitra** [comment]
This is happening because you're forgetting an `href` property on your LinkOverlay element.  [Chakra UI (and HTML) requires a link element to be focusable.](https://github.com/chakra-ui/chakra-ui/blob/e111fa229227a90c8caf541b2e51cf6c80229e6e/packages/utils/src/tabbable.ts#L66)

https://codesandbox.io/s/peaceful-bush-qx85ej
