### ISSUE TITLE
Change focusBorderColor globaly

### ISSUE THREAD

**Issue by Bulletninja** [chakra-ui/chakra-ui#663]
I've seen here i can customize input borders with the `focusBorderColor`.
 
https://github.com/chakra-ui/chakra-ui/blob/24b9df8b73c45735579f4a9e5a16e71b3703f432/packages/chakra-ui-docs/pages/input.mdx

Is there a place in `theme.js` that i should use to change these for every input instance instead of having to pass that param for each one?

**Comment by segunadebayo** [comment]
Hi @Bulletninja,

At the moment, there's no place in the theme object to do this.

Why not consider creating a wrapper component that applies your focus border-color and just use that instead of importing from Chakra.

I understand it might be a bit painful but we've resolved this in the next release, consider this suggestion a walkaround for now.

Thanks.

**Comment by PierreAndreis** [comment]
> [...] we've resolved this in the next release

How can this be accomplished on 1.0?

**Comment by with-heart** [comment]
@PierreAndreis Check out the v1 theming docs: https://next.chakra-ui.com/docs/theming/overview

**Comment by PierreAndreis** [comment]
@with-heart my question is more if we can have an object key to configure the focus border color on input and textarea instead of taking hardcoded `blue.300 `
https://github.com/chakra-ui/chakra-ui/blob/34e96629689707a8940a95c04c030718153d27dd/packages/theme/src/components/input.ts#L3-L9

similar to how buttons/tabs/anything focusable share a variable on box-shadow called "outline"
https://github.com/chakra-ui/chakra-ui/blob/34e96629689707a8940a95c04c030718153d27dd/packages/theme/src/components/button.ts#L92-L94

The problem here is that if we change the `outline` color from the buttons to our branding color, to accomplish the same for `input` and `textarea` we have to make our own input and Textarea style configs. All we want to do is just change the focus outline color on it.

**Comment by with-heart** [comment]
I'll re-open so we can consider this.

**Comment by with-heart** [comment]
The team has currently prioritized other work and as part of our issues backlog cleanup, I'm going to close this issue. We can potentially revisit in the future if it remains an issue for users.

**Comment by tomaszgil** [comment]
Stumbled upon this issue as well - I wanted to tweak focus color for inputs. Using `defaultProps` worked for me well here.

```javascript
const Input = {
  baseStyle: {
    field: {
      background: 'pink',
      color: 'gray.700',
    },
  },
  defaultProps: {
    focusBorderColor: 'brand.700',
  },
}
```

With that there's not need to create custom wrapper components. Hope it helps.

**Comment by sohhamm** [comment]
Please allow us to override global _focus property

**Comment by Chogster** [comment]
Hi @with-heart,

Are there any plans to support this in the near future? As a newbie to Chakra UI, it took me a while to find the workaround mentioned by @tomaszgil.

**Comment by bradley-varol** [comment]
`focusBorderColor` does nothing for me, neither inside `baseStyle` or outside of it...
```
const StyledInput = chakra(Input, {
  baseStyle: {
    width: '100%',
    height: '100%',
    padding: '0 0 0 24px',
    borderWidth: '2px 0 2px 2px',
    borderColor: 'lightGrey',
    borderRadius: { base: '25px 0 0 25px', tablet: '30px 0 0 30px' },
    textStyle: 'baseBodyText',
    textColor: 'darkGrey',
  },
  defaultProps: {
    focusBorderColor: '#820d0d',
  },
})
```

**Comment by pablocubico** [comment]
Hey @with-heart and anyone following, I'm solving it by altering the shadow labeled "outline" (see: https://chakra-ui.com/docs/features/style-props#shadow), for example:

```
const shadows = {
  outline: '0 0 0 3px red',
};

const theme = extendTheme({ config, styles, colors, components, shadows });
```

I think that's all it takes, unless I'm missing something... Maybe it's a bit confusing because "outline" is actually a token for the `box-shadow` property and not for `outline`. 🤔

**Comment by pablocubico** [comment]
> 

I think you can use my example above with CSS variables, for ex:
```
const shadows = {
  outline: '0 0 0 3px var(--chakra-colors-brand-500)',
};
```
