### ISSUE TITLE
Alert background color is invalid in dark mode

### ISSUE THREAD

**Issue by cosformula** [chakra-ui/chakra-ui#6637]
### Description

In dark mode, the background color of the Alert container was set to `211` (should be `rgba(251, 211, 141, 0.16)`), result in a transparent background.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-alert-dark-mode-bg-bug-0gh8t8?file=/src/App.js

### Steps to reproduce

1. Click Toggle Color Mode
2. Showing a transparent background
3. Inspect Alert Container
<img width="322" alt="image" src="https://user-images.githubusercontent.com/18232501/188548871-d5dcf0a2-b9a1-4527-a09d-d7a739c7329b.png">
 

### Chakra UI Version

2.3.1

### Browser

Google Chrome 105.0.5195.102 (Arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by GhostSlayer** [comment]
This also happens to me on the latest version (2.3.1)

![image](https://user-images.githubusercontent.com/51095261/188704190-7a988595-f1d2-4782-9d03-bb32b53da122.png)
![image](https://user-images.githubusercontent.com/51095261/188704210-432af5b6-b8cf-46da-9ca0-9ae3b48d458a.png)

**Comment by victorseara** [comment]
If I understand it correctly, the problem was related to how we were parsing css vars. We were splitting RGB values using commas as a matcher, which explains the computed value @cosformula showed. 

It's working in the example bellow:
[Codesandbox](https://codesandbox.io/s/create-react-app-ts-forked-eju38x?file=/src/App.tsx)

**Comment by segunadebayo** [comment]
Fixed this is a recent PR #6595. I'll release an update soon
