### ISSUE TITLE
Number Input accepts letter e

### ISSUE THREAD

**Issue by ramizqazi** [chakra-ui/chakra-ui#6676]
### Description

Number Input is accepting letter e and when i un foucus from the input it gives me this number -9007199254740991 at the input which is not editable 

### Link to Reproduction

https://chakra-ui.com/docs/components/number-input/usage

### Steps to reproduce

1. Go to chakra Ui number input  example
2. Click on the input and type letter e
3. then un focus on the input by clicking somewhere else 
4. See  error

### Chakra UI Version

2.2.9

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Klaha** [comment]
I'd like to take a look and fix this.

**Comment by anubra266** [comment]
Oh...sorry @Klaha I'm just seeing your comment. 😢

**Comment by Patrick-Ullrich** [comment]
To whoever is fixing this - keep in mind that the html spec `type="number"` supports the letter `e`. 

This is because input type=number accepts a valid floating-point number. See more: https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number.

This could be solved without chakra by handling the case in the `onChange` event. 

Furthermore, + and - are also valid inputs in a number field. 

Now whether the specific `NumberInput` component needs to follow the html spec type="number" is of course a different discussion :)
