### ISSUE TITLE
NumberInput does not allow dots, when pass value as number

### ISSUE THREAD

**Issue by vitaliyirtlach** [chakra-ui/chakra-ui#6701]
### Description

When I create NumberInput and pass number and control number change I can't write dots in input, but when i control string input that's work

### Link to Reproduction

https://codesandbox.io/s/divine-tdd-xdn7tv?file=/src/index.tsx

### Steps to reproduce

1. const [value, setValue] = React.useState(0);
2. value={value}
3. onChange={(_, value) => setValue(value)}4. See error

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by theashishmaurya** [comment]
Well, that is an issue but for now, I found a way you can get around it. You still can't add manually a point but use  `  step={0.1}
`  so that when the user increases the value it increased by 0.1 instead of 1.
@vitaliyirtlach

**Comment by theashishmaurya** [comment]
Can someone assign this issue to me? I would love to work on this.

**Comment by anubra266** [comment]
@vitaliyirtlach It's because you're setting the value as the second parameter. Change 
```js
onChange={(_, value) => {
    setValue(value);
}}
```

to

```js
onChange={(value) => {
    setValue(value);
}}
```

You can't use the `valueAsNumber` to set state because it won't be able to handle floating numbers when while typing.
E.g. User wants to type `12.4`. As at the point where user types `12.` yet to add the 4, if you're handling as number. `12.` can't be a number.

**Comment by anubra266** [comment]
@vitaliyirtlach It's because you're setting the value as the second parameter. Change 
```js
onChange={(_, value) => {
    setValue(value);
}}
```

to

```js
onChange={(value) => {
    setValue(value);
}}
```

You can't use the `valueAsNumber` to set state because it won't be able to handle floating numbers when while typing.
E.g. User wants to type `12.4`. As at the point where user types `12.` yet to add the 4, if you're handling as number. `12.` can't be a number.

**Comment by vitaliyirtlach** [comment]
thanks @anubra266
