### ISSUE TITLE
Stack won't apply spacing and divider when used with Fragment

### ISSUE THREAD

**Issue by la55u** [chakra-ui/chakra-ui#6757]
### Description

I expected `Stack` to apply spacing and divider between all 4 boxes since fragments don't create additional elements in the markup. Instead it only works for direct children.

### Link to Reproduction

https://codesandbox.io/s/loving-bessie-w1wm53?file=/src/index.js

### Steps to reproduce

Try the CodeSandbox link above

### Chakra UI Version

2.3.4

### Browser

any

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Similar issue here: https://github.com/chakra-ui/chakra-ui/issues/228

**Comment by segunadebayo** [comment]
This only happens when you try to use the `divider` prop. If you remove that prop, it'll work as expected.

When the `divider` prop is passed, we use `Children.map` to inject the divider element. Since you use a Fragment, the Stack can't reach into that element. Consider adding the divider manually instead of passing it via prop.
