### ISSUE TITLE
MenuItem: No hover effect

### ISSUE THREAD

**Issue by adventurini** [chakra-ui/chakra-ui#678]
**Describe the bug**
The background of Menu List gets automatically set, but I am not sure which part of the theme is setting it. If you override the background property on the MenuList, you are unable to change the hover background on the MenuItem.

**Suggested solution(s)**
Add a hover effect to the Menu Item

Here is my code:

``` 
<MenuList bg="charcoal.400">
   <MenuItem color="white">
         <Box color="white" as={FiUser} size="16px" mr={2} />
    Profile
    </MenuItem>
</MenuList>
```
<img width="272" alt="Screen Shot 2020-05-05 at 2 10 01 PM" src="https://user-images.githubusercontent.com/12114942/81116434-3156ac80-8eda-11ea-9cff-88c22727d7b4.png">

**Comment by segunadebayo** [comment]
Hey @adventurini,

The MenuItem hover styles are actually "focus styles" because we used a Roving TabIndex approach in our design. This means we set focus on each menu item when you hover on them.

To change the styles, simply pass `_focus` style props and change any part you want.

I mean

```jsx
<MenuList bg="charcoal.400">
   <MenuItem color="white" _focus={ { bg: "charcoal.50" } }>
         <Box color="white" as={FiUser} size="16px" mr={2} />
    Profile
    </MenuItem>
</MenuList>
```

As a reference, check here: https://github.com/chakra-ui/chakra-ui/blob/0ff86ea7b9c2eb9f16ceb95bdc6983c7a0b14603/packages/chakra-ui/src/Menu/styles.js#L45

Hope you find this useful.

**Comment by muratcan23** [comment]
how can I make the menu item shrink on hover? I mean: I want a margin of 1-2 less so the box will be seen smaller from all sides.

**Comment by Wonder0xWeird** [comment]
@muratcan23 not sure if you're still looking for a solution to this, but setting the _hover style as follows will produce the effect you've inquired about:

```
<MenuItem _hover={{ transform: "scale(0.8)" }} >
   <Button>Test</Button>
</MenuItem>
```

**Comment by muratcan23** [comment]
too late I gave up using this item, thx for your return.
