### ISSUE TITLE
Modal footer is not visible on iOS Chrome

### ISSUE THREAD

**Issue by manlorhid98** [chakra-ui/chakra-ui#6798]
### Description

When I use a modal with footer, the iOS footer bar overlaps the modal footer. It happens only on Chrome, not Safari.

### Link to Reproduction

https://codesandbox.io/s/hardcore-mendel-rt50vf?file=/src/index.js

### Chakra UI Version

2.0.0

### Browser

Google Chrome 92.0.4515.90

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by nxtman123** [comment]
I believe this does happen in Safari as well. We've been seeing the same issue with our app on iOS Safari and Chrome, but the problem is only when the browser's URL bar is in view (from scrolling up, or by default when the page loads).

It's because the min-height of the ModalContent is set to "100lvh" via `--chakra-vh` which uses the large viewport height unit. See [Mozilla's docs](https://developer.mozilla.org/en-US/docs/Web/CSS/length#relative_length_units_based_on_viewport) on relative length units based on viewport. There are three new sets of [relative length units](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#relative_length_units) that I didn't know about until yesterday.

So by setting `minH="100dvh"` we can fix this for these iOS browsers. Unfortunately, these units are [not well supported yet](https://caniuse.com/viewport-unit-variants) by other browsers, which means they wouldn't get a full screen modal. So we need to leave the existing min-height (don't replace it) but then CSS override it in another class with `dvh`.

In [this sandbox](https://codesandbox.io/s/confident-danilo-riglwt?file=/src/index.js) I added `sx={{ '&': { minH: '100dvh' } }}` to create that new class that overrides the min-height with new units.

This obviously isn't a permanent fix. Chakra UI needs to switch to dynamic units or something else. I don't know why `--chakra-vh` uses the long units but there's probably some other use case. If someone knows how to overwrite `--chakra-vh` (it's not in the theme as far as I can tell), please let us know how and if it breaks anything else.
