### ISSUE TITLE
New TS version release date?

### ISSUE THREAD

**Issue by akiarostami** [chakra-ui/chakra-ui#681]
Hello the wonderful Chakra team!

Do you have any potential release date for your new version? Even a rough estimate? Knowing it would tremendously help.

Thank you!

**Comment by segunadebayo** [comment]
Hi @akiarostami,

We'll create an issue that addresses this question. A rough estimate is somewhere between May and June. I believe it won't go beyond June.

It's taking some time due to the fact that the core is pretty small and there's so much we can do per time, but we'll smash it and release soon.

Expect the issue over the weekend.
