### ISSUE TITLE
SyntaxError: Unexpected token '=' . Expected an opening '(' before a method's parameter list

### ISSUE THREAD

**Issue by diqye** [chakra-ui/chakra-ui#6828]
### Description

An error appear when Safari in iPhone X visit, because class field syntax code of chakra-ui is not supported. It is in nextjs project

### Link to Reproduction

http://www.diqye.com/music/expert

### Steps to reproduce

1. Visit in safari 

### Chakra UI Version

^2.0.4

### Browser

safari in iPhoneX or same timing's iPad 

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![11665753471_ pic](https://user-images.githubusercontent.com/34941345/195856651-65a769fd-f7a2-44bc-9991-deb6a052cf42.jpg)
<img width="713" alt="image" src="https://user-images.githubusercontent.com/34941345/195856738-e8f9454a-81e8-440c-b54f-4a9abbf8f29d.png">

**Comment by Ngomana** [comment]
I'm also getting the same error

**Comment by latanoel** [comment]
I'm also experiencing same issue in a NextJS project.

**Comment by Ngomana** [comment]
I downgraded to an older version of Chakra ui and it works.

**Comment by latanoel** [comment]
> I downgraded to an older version of Chakra ui and it works.

What version did you downgrade to?

**Comment by Ngomana** [comment]
It's version `1.8.8`

**Comment by Irrelon** [comment]
I can confirm this is an issue with Chakra-UI used with Next.js and iOS 13.7 (some later versions of iOS don't have this issue because they natively support public class properties).

I downloaded iOS 13.7 simulator using XCode to test this when a customer told me their old iPad doesn't work with our site.

I'm using Chakra-UI 2.4.1 and Next.js 13.0.1.

I also tried switching Next.js to using babel via a .babelrc and manually specifying the babel public class properties plugin but this didn't work. I believe it is not compiling modules like Chakra-UI and only attemtping to compile my own project source code.

**Comment by Irrelon** [comment]
Further to this, I pulled down the chakra-ui repo for some testing. The basic typescript sandbox link provided by chakra-ui docs also causes this error, showing that in a barebones application the problem still exists:

![image](https://user-images.githubusercontent.com/492293/203106472-f36c9a53-de30-454b-babe-dc47ab9cf349.png)

Steps to reproduce:

Open XCode and download the iOS 13.7 platform so that you can create a simulator based on that version.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/492293/203107056-918acc77-f7fe-4e28-9f86-17daf1ce9148.png">

Open a simulator with iOS 13.7 and then browse to the sandbox URL https://codesandbox.io/s/chakra-ui-typescript-pomi8

Open Safari Desktop and open a debug session to inspect the simulator for more error detail.

**Comment by dn-la** [comment]
I downgrade to 2.2.4 and it's seems worked.

**Comment by segunadebayo** [comment]
This is most likely related to the tsup config and the target we set currently.

I'll dig into it shortly

**Comment by Irrelon** [comment]
@segunadebayo Thanks Segun. Very kind of you. I tried to dig into this myself and got as far as the tsup config. Reached out to the community on discord for some guidance here https://discord.com/channels/660863154703695893/1020028116934066387/threads/1044317895502598234 but no responses yet.

Happy to help if I can... I'm the author of [Isogenic Game Engine](https://github.com/Irrelon/ige) and [ForerunnerDB](https://github.com/Irrelon/ForerunnerDB) to name a couple so I'm not new to creating and contributing to open source projects. I think the work you've done on Chakra-UI is brilliant and I'm a big fan :)

**Comment by cichien** [comment]
We have this issue to in iOS 13

**Comment by brenopolanski** [comment]
I have similar error:

```
"@chakra-ui/react": "^2.3.5",
"next": "12.3.1",
```

> Tested on iOS 13
![Screenshot from 2022-11-24 15-20-07](https://user-images.githubusercontent.com/1894191/203847945-1829c17f-f7b9-42cc-ac98-726c7ef89e5f.png)

**Comment by brenopolanski** [comment]
> This is most likely related to the tsup config and the target we set currently.
> 
> I'll dig into it shortly

Some refs:

1. https://tsup.egoist.dev/#target-environment
2. https://esbuild.github.io/api/#target
