### ISSUE TITLE
NextJS & SSR Bug: Warning: Prop `className` did not match. Server: "css-1ignaq9" Client: "css-1xh7umy"

### ISSUE THREAD

**Issue by adventurini** [chakra-ui/chakra-ui#684]
**Describe the bug**
Console error on load.
<img width="541" alt="Screen Shot 2020-05-07 at 9 39 56 AM" src="https://user-images.githubusercontent.com/12114942/81320918-c2e32d00-9046-11ea-8019-9ec387b666e2.png">

**Expected Behavior**
No console error on load.

**Comment by benregn** [comment]
@adventurini I think people will have a hard time helping you out unless you provide some more details about this problem and ideally minimal project reproducing the bug.

One question, are you using the `ColorModeProvider`? Server-side might be rendering the light theme and when it's rendered and hydrated on the client, it might change to the dark theme which uses different classes.

**Comment by feross** [comment]
I've also seen this issue when using `ColorModeProvider`. Removing it fixes the issue.

@benregn What's the right way to handle the case where the server sends a light mode page but the client is in dark mode?

**Comment by with-heart** [comment]
I haven't had time to go through and give it the read it deserves, but Josh W. Comeau recently took a deep dive on this exact topic: https://joshwcomeau.com/gatsby/dark-mode/

Might be useful information in there. I'll try to go through it later and report back any relevant findings.

**Comment by benregn** [comment]
Josh's article is great and explains the underlying problems really well. His solution relies on using [CSS Custom Properties (Variables)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) so if you aren't using them or aren't familiar with them, it could take a bit of work to setup. I haven't experimented with his solution yet when using Chakra.

@feross I'm not sure if I can answer what the 'right way' is but the solution Josh presents definitely works and another solution I've seen work is to store the preference in a cookie but that does break static optimization.

**Comment by segunadebayo** [comment]
Hey guys,

We're fixed the issue with the ColorModeProvider in the next release.

It'll be landing soon!

**Comment by feross** [comment]
👏 @segunadebayo

**Comment by javierfuentesm** [comment]
I still have this issue 
![image](https://user-images.githubusercontent.com/19244527/107723646-5406c480-6ca7-11eb-8b38-a557e52a6887.png)

**Comment by PlatonSterh** [comment]
> I still have this issue
> ![image](https://user-images.githubusercontent.com/19244527/107723646-5406c480-6ca7-11eb-8b38-a557e52a6887.png)

same

**Comment by ADParris** [comment]
This issue still persists to this day. I did not add a screen shot as there are plenty of the same already in here. Now, being a studious developer... I don't care AT ALL about the stupid warning. I do, however care about the fact that upon a refresh of the page along with this error the layout basically breaks. I've been researching this for hours now and am coming up empty other than removing all of these css in javascript implementations, because they all have this problem evidently, and sticking with regular old css (which is far from ideal, as I happen to love Chakra). So, for the love of God, could someone point me at the solution to this little issue. Oh and I should also mention that I've done all the _app and _document stuff, infact I'm using the example template, from Next, for Next / Chakra / Typescript. Any help would be appreciated, before I pull my remaining hair out.  ;)

**Comment by niconiahi** [comment]
same happening to me when ussing `useMediaQuery` as so:
```jsx
  const [isLargeDevice] = useMediaQuery('(min-width: 62em)')

  return {
    isLargeDevice,
  }
}
```

then used: (THIS THROWS AN ERROR)
```jsx
   <Text color='white' textStyle={isLargeDevice ? 'body.bold.lg' : 'body.bold.md'}>
       Don't miss out on new proposals
   </Text>
```

used: (THIS DOESN'T)
```jsx
   <Text color='white'>
       Don't miss out on new proposals
   </Text>
```

screenshot here:
![image](https://user-images.githubusercontent.com/8381041/124301037-a1d87800-db35-11eb-990f-ab1cd9d40b1b.png)
