### ISSUE TITLE
toastSpacing prop is not applied in ToastProvider.tsx

### ISSUE THREAD

**Issue by Darmun** [chakra-ui/chakra-ui#6900]
### Description

When I set toastSpacing  in ChakraProvider, it doesn't get applied

### Link to Reproduction

https://codesandbox.io/s/black-leftpad-wb40tj?file=/src/index.tsx

### Steps to reproduce

1. Click on "click me" few times, to create stack of toasts.
2. Notice spacing between toast.
3. Change value of toastSpacing passed to provider.
4. Repeat step 1.
5. See spacing of toast - remains the same, ignoring passed prop value.

### Chakra UI Version

2.3.6

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Pretty much same issue as here, with defaultOptions prop: https://github.com/chakra-ui/chakra-ui/issues/6370 - toastSpacing can be passed to toastProvider, but stays unused.

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. Luckily it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please open a new issue and follow the instructions in the issue template.
