### ISSUE TITLE
Make tabpanels the height of the largest tabpanel

### ISSUE THREAD

**Issue by aldeka** [chakra-ui/chakra-ui#6961]
### Description

It would be nice if tab panels could take up the same height as whichever sibling tabpanel is largest.

### Problem Statement/Justification

Right now, if the contents of your tab panels are different sizes, the layout thrashes in an ugly way when you switch between tabs.

https://user-images.githubusercontent.com/689247/200944740-9a2d072c-c62c-421f-aa4a-f7801b076787.mov

You'd avoid this if tabpanels were all the same size (even if some panels' contents didn't require it). (Obviously this would only work for tab UIs without lazy loading.)

### Proposed Solution or API

Desired behavior:

https://user-images.githubusercontent.com/689247/200945697-887697cc-292d-49e4-a475-aa610a8285fb.mov

(I hard-coded the height into the smaller tab panel for the demo--obviously that isn't a workable implementation.)

Using `visibility: hidden!important;` instead of `display: none!important;` and then using a ref to measure the panels is one possible way to fix this.

### Alternatives

I tried hacking around this myself but because inactive tab panels are `display: none!important;`, they don't have a height that I could use a ref to measure.

**Comment by marek-sed** [comment]
Some non optimal workarounds.

I assume you are using something to center that whole component, and since the height of the Card changes as you tab to next item that moves the position, tab header since you are trying to keep it centered. You can calculate marginTop based on screen/parent to fix the position of tablist.

You can also set maxHeight of parent Card the center element like this although it wont be precisly centered but often good enough.
https://codesandbox.io/s/xenodochial-browser-gr7bgo?file=/src/index.tsx


I always wonder about height, Why do you not consider setting height not to be workable solution?

**Comment by segunadebayo** [comment]
Hi @aldeka,

Thanks for reporting this. My intuition is that this is a custom feature that you may need to implement on your end. 

We can't measure the height of a hidden panel. I'd recommend using a flexbox around the TabPanels element to solve this. From the look of the UI, there should be a max-height set for all tabs to prevent jumpiness.

Using `visibility` isn't a viable approach because it removes the accessibility semantics from that element. It could work but will require some complexity we don't want to add.

Thanks for understanding.

**Comment by dionjwa** [comment]
I would wrap the title and card in a `<VStack/>` and set `justify="flex-start"`. That way, the top of your card won't jump to the center and back, and the card can expand with different content, without the title jumping around.
