### ISSUE TITLE
Radio doesn't work with numeric type values

### ISSUE THREAD

**Issue by ArthurPedroti** [chakra-ui/chakra-ui#6966]
### Description

The component Radio doesn't work when you pass a number in the value property. But at the docs, the property value accepts string and numbers.

It seems the value change when we click on the radios, but the UI doesn't change.

![image](https://user-images.githubusercontent.com/52859409/201180674-cb6b388a-87a6-4bb0-b177-f69f91eb4043.png)

### Link to Reproduction

https://stackblitz.com/github/ArthurPedroti/chakra-radio?file=README.md

### Steps to reproduce

1. Try to select any Radio
2. Open devtools and check the console when we click at the radios

### Chakra UI Version

^2.3.7

### Browser

Edge

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Utkarshn10** [comment]
Hey @ArthurPedroti you are passing the number values as object i.e {} while the values need to be passed through ''. 

Here is the link to the documentation: https://chakra-ui.com/docs/components/radio#usage

**Comment by ArthurPedroti** [comment]
Passing the number through '' make it a string, and the value needs to be a number, not a string.

Also, the own property type accepts a number.

I'm questing this because the radio, checkbox, and select, all have the same behavior, they all accept a number on the value property, but the radio doesn't work properly or doesn't work like the checkbox and select or checkbox.

Like this select e.g. bellow, it works properly, and doesn't seems it's unable like the radio:
```
<Select placeholder='Select option'>
  <option value={1}>Option 1</option>
  <option value={2}>Option 2</option>
  <option value={3}>Option 3</option>
</Select>
```

**Comment by ArthurPedroti** [comment]
I added a console.log at the value of the RadioGroup, and it's seems the value change when we click in the radios, but the UI doesn't change.

**Comment by steventoben** [comment]
The value attribute on a native HTML `<input/>` element must always be a string. Even type="number" and type="date" values will be converted to a string in HTML.

You are passing the value correctly, in JSX value={1} is indeed passing a number value and not an object as mentioned above.

If you look at the RadioGroup onChange signature 
`onChange?(nextValue: string): void`
you'll see that it only takes in a value of type string

If you take a look at the source code for useRadioGroup, it looks like in the internal onChange handler they convert the passed value to a string. 

You could technically pass a number into the defaultValue of the RadioGroup and that will show the Radio with the corresponding number value as checked, but since internally the RadioGroup value is converted to a string, once you try to select another Radio the UI will end up with none of them selected.

Basically, using your example if you select a Radio with a value={2} internally the RadioGroup value will become "2", since your Radio's value is 2 (number), not "2" (string), the RadioGroup thinks none of your Radios are selected because it's looking for "2".

I'm honestly not 100% sure about why value on Radio accepts a number. But that's why your UI isn't updating, the value of RadioGroup has to be converted to a string because in HTML the radio button `<input/>` values will be string, so the types don't match when a Radio has value of type number.

If you really need to use a number then you could make a controlled RadioGroup and converting the value to a number in the onChange handler, like this:

```
const [value, setValue] = React.useState<number>(1);
return(
  <RadioGroup value={value} onChange={(e) => setValue(parseInt(e))}>
    <Radio value={1}>a</Radio>
    <Radio value={2}>b</Radio>
    <Radio value={3}>c</Radio>
  </RadioGroup>
);
```
I'm not sure if that's any helpful, because I'm not exactly sure of the use case for accepting numbers aside from convenience or not having to pass numbers as strings.

**Comment by ArthurPedroti** [comment]
I understand your point of view @steventoben, but I open this discussion because it's strange "convert behavior" that always converts the number to a string, and why the value property has this type "string | number". 

If all will be converted to a string, even if is a radio, checkbox, or select, why the type of value is "string | number"?

**Comment by anubra266** [comment]
@ArthurPedroti Thanks for pointing this out. We only accept strings, so the docs will be updated accordingly

**Comment by ArthurPedroti** [comment]
@anubra266 I created the pr #7026 to fix that, I think it's just a little tweak to the values types in Radio and RadioGroup.

If you see that have any other fix to be made, tell me and I'll adjust.

From what I've seen, the docs of types are generated from the chakra types, so I think this is the only PR necessary.
