### ISSUE TITLE
Modal content seems to be mounted by default

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#7067]
### Description

I expect that if the modal is closed its content would not be mounted.

The reproduction below has been made by @aboveyunhai in this issue: https://github.com/chakra-ui/chakra-ui/issues/7018

### Link to Reproduction

https://codesandbox.io/s/sandpack-project-forked-zncoev?file=/App.tsx

### Steps to reproduce

1. Go to the codesandbox
2. Click on the different buttons
3. Look at the logs

### Chakra UI Version

2.4.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by uvera** [comment]
Should be intended behaviour. Check https://github.com/chakra-ui/chakra-ui/issues/7018#issuecomment-1336216412

**Comment by aboveyunhai** [comment]
@uvera  is right on the parsing point. 

my example does not mean the children component is mounted by default. It just means some of your functions can be executed unexpectedly depending on how you construct your code. 

I guess that's why your raise the issue because some of your functions were running unexpectedly. 
Since `Jsx` was executed like a function, the following will be run lazily, if you insist to keep everything in the same component.

```js
<ModalBody> 
        { () => { 
              your_function(), 
              return (<YourComponent />) 
        }} 
</ModalBody>
```

**Comment by lcswillems** [comment]
It seems indeed this is not an issue with Chakra but rather with JSX. I believe at some point it was mounting the content of the modal without it being open but I don't succeed to reproduce. I am closing for now.
