### ISSUE TITLE
[@chakra-ui/gatsby-plugin] Attempted import error: 'baseTheme' is not exported from './theme'

### ISSUE THREAD

**Issue by zzzkan** [chakra-ui/chakra-ui#7179]
### Description

When customizing a theme with @chakra-ui/gatsby-plugin v3.1.1, the following warning appears.

```sh
warn ./node_modules/@chakra-ui/gatsby-plugin/src/provider.js
Attempted import error: 'baseTheme' is not exported from './theme' (imported as 'baseTheme').
```

theme is the same as described in the [readme](https://github.com/chakra-ui/chakra-ui/tree/main/tooling/gatsby-plugin#customizing-the-theme). 

```js
// src/@chakra-ui/gatsby-plugin/theme.js

import { extendTheme } from "@chakra-ui/react"
const theme = {
  colors: {
    primary: "rebeccapurple",
  },
}

export default extendTheme(theme)
```

### Link to Reproduction

https://github.com/zzzkan/chakra-ui-gatsby-plugin

### Steps to reproduce

1. Clone a reproduction repository : `git clone https://github.com/zzzkan/chakra-ui-gatsby-plugin.git`
2. Install dependencies : `npm install`
3. Start developing : `npm run develop`

### Chakra UI Version

2.4.5

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by zzzkan** [comment]
I needed to export `baseTheme`  because the plugin's theme was updated in #7096.
```diff
import { extendTheme } from "@chakra-ui/react"
const theme = {
  colors: {
    primary: "rebeccapurple",
  },
}

export default extendTheme(theme)

+ export const baseTheme = {}
```

but i think it is strange to need to export unnecessary themes...

**Comment by TylerAPfledderer** [comment]
@segunadebayo I think I got it.

So due to the shadowing approach of `theme.ts` over the gatsby-plugin version when extending the theme, I tried a different approach due to having two default theme objects to decide over whether or not `ChakraBaseProvider` was to be used.

1. Turn `theme.js` in the plugin into a dummy file with essentially `export default {}` in order for the shadowing to still work.
2. Import `theme` and `baseTheme` from Chakra directly into `provider.js`
3. In `provider.js` run check to see if the object from `theme.js` is not empty (if the dev shadowed it with an extended theme), then...
4. Run check where if the object from `theme.js` still comes back empty, supply `theme` or `baseTheme` instead to the provider depending on if the dev wants `ChakraBaseProvider` via `isBaseProvider` config option.

Along with updating `gatsby-ssr.js`, I did tests with the `extendBaseTheme`, `extendTheme`, and not having the shadowing, and it works as expected.

Though because the approach I took required importing the two themes from Chakra to be checked, does that add payload?

Would love the thoughts here! 😅

**Comment by TylerAPfledderer** [comment]
@segunadebayo there appears to be a much more straightforward and simplified solution.

1. Imported `theme` from Charka is not required for the functioning to work with the provider (though the object is need for `gatsby-ssr.js`). Since `theme.js` in the plugin is still needed for shadowing of an extended theme, it can be reduced to a dummy file with `export default {}`.
2. When passing a theme to the provider, it needs to either be _not_ an empty object, or pass `undefined` to the `theme` prop of said provider. So there could just be a check to determine whether or not the object exported from `theme.js` is empty.

Testing this with no extended theme, `extendTheme`, and `extendBaseTheme` (with `isBaseProvider: true` in the gatsby config) all look to be working as intended with no warnings!

**Comment by zzzkan** [comment]
I think one of the solutions is also to revert the "isBaseProvider" option. The difference between `ChakraProvider` and `ChakraBaseProvider` is only the default parameter for `theme`.

https://github.com/chakra-ui/chakra-ui/blob/05c31f4097be0973565532aed4c611bcb0bcdb2e/packages/components/react/src/chakra-provider.tsx#L16-L35

So, it is enough to shadow this plugin’s theme with `baseTheme`. In practice, will customize the theme using `extendBaseTeme`.
```js
// src/@chakra-ui/gatsby-plugin/theme.js

import { extendBaseTheme } from "@chakra-ui/react"
const theme = extendBaseTheme({
  // pass your custom values
})
export default theme
```

**Comment by TylerAPfledderer** [comment]
Thank you for the feedback @zzzkan. 😸 Good point!

Even if a user started with this provider and no extended theme, since there are no default component themes automatically supplied, the user has to either:
1. Style the components in props, or
2. Extend the theme to bring in only the default theming they want, plus adding their own styling

With #2 overriding the provider anyway in it's rendering of `baseTheme`, which at that point wouldn't matter which provider you used, which you pointed out.

**Comment by wryfi** [comment]
I see this in my project too, just an annoyance really but 👍 for either fix.

**Comment by zzzkan** [comment]
Even if you only want to use the `baseTheme` (No. 1),  i think just shadow plugin’s theme instead of isBaseProvider option.

```js
// src/@chakra-ui/gatsby-plugin/theme.js

import { baseTheme } from "@chakra-ui/theme"
export default baseTheme 
```

So, it's simpler to revert the option.  If I had to choose, I prefer the simple one.
