### ISSUE TITLE
AccordionItem final CSS not respecting the source code CSS order.

### ISSUE THREAD

**Issue by ricardo-passos** [chakra-ui/chakra-ui#7195]
### Description

When I set a border color for the `AccordionItem` component, say `red` (it could be any other color), I expect it to be `red`; instead, the generated CSS border color is always `black`.

### Link to Reproduction

https://codesandbox.io/p/sandbox/interesting-feather-1k53cx?selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A24%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A24%7D%5D

### Steps to reproduce

1. Set the accordion component's structure (Accordion, AccordtionItem, AccordionButton, AccordionPanel)
2. Set the AccordionItem `borderColor` CSS attribute to any value other than `black`
3. The border color hasn't changed
4. Compare the generated CSS in the devtools to the source code and you'll see the CSS order isn't being respected.

### Chakra UI Version

2.4.4

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @ricardo-passos,

The order of properties passed to an element is never guaranteed since props are eventually mapped to objects, which doesn't guarantee order.

Besides that, I think you should use `borderWidth` and `borderColor` instead since that's all you want.

`<AccordionItem borderRadius="md" borderWidth="1px" borderColor="red">`

That should work as expected
