### ISSUE TITLE
Toastr breaks on specific position enum values

### ISSUE THREAD

**Issue by intyro** [chakra-ui/chakra-ui#72]
**version:** 0.2.6

**I'm submitting** an issue

**Current behavior:** I do have an issue using the Toastr at a specific position. for example, setting the Toastr position for `bottom-left` works fine. other values break like `top-end`.

**Comment by lee-reinhardt** [comment]
I've noticed this as well, and all the `top` positions have the same issue. I poked around debugging it the other day and it's caused by `.Toaster__message-wrapper` having `transform: translateY(-100%) scale(1)` set.  It pulls the most-recent toast out the top of the viewport.

I didn't come to a solution, but I think there's an animation or something not happening. It should update to `translateY(0%) scale(1)`.
