### ISSUE TITLE
Centered modal with large content breaks overflow

### ISSUE THREAD

**Issue by bertho-zero** [chakra-ui/chakra-ui#7224]
### Description

When I create a modal (centered or not), I expect to be able to see all the contents of it.

As soon as my centered modal is too big, the top disappears. Everything else works normally and the bottom is displayed correctly when I scroll, just the top is cut off.

### Link to Reproduction

https://codesandbox.io/s/thirsty-fermat-gy9oqs?file=/src/index.js

### Steps to reproduce

1. Click on 'Trigger modal'

### Chakra UI Version

2.4.7

### Browser

Brave 1.46.144

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by bertho-zero** [comment]
A `display: grid` instead of `display: flex` on `.chakra-modal__content-container` fix the problem:

[Capture vidéo du 12-01-2023 15:40:33.webm](https://user-images.githubusercontent.com/8525267/212096243-b1890045-4e04-4dea-aa4a-bf9f45142dc5.webm)

**Comment by miedziak** [comment]
happens also on Chrome 112.0.5615.49

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by warrenday** [comment]
This issue still persists for me in the latest version.

It's due to `.chakra-modal__content-container` having `display: flex` and `align-items: center`. Changing `align-items` to baseline or flex-start fixes the issue.

Changing the display to grid caused other issues for me, so this approach may be better.

Thanks for the tip @bertho-zero
