### ISSUE TITLE
Popover CloseOnEsc does not work when trigger is hover

### ISSUE THREAD

**Issue by amyn0602** [chakra-ui/chakra-ui#7229]
### Description

When trigger is set to hover, pressing on Esc does not close the Popover.

### Link to Reproduction

https://codesandbox.io/s/exciting-banzai-izowkg?file=/src/App.js

### Steps to reproduce

1. Hover on Trigger button
2. Observe the Popover is displayed
3. Pressing on Esc key
6. The Popover is not dismissed

### Chakra UI Version

2.4.8

### Browser

Google Chrome 108

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Yes, this is by design. The escape key listener is currently attached to the `PopoverContent`. Changing this to a global key listener will be a breaking change for some applications

**To fix this, you can do one of the following**
- move focus to the popover when it's open (within an effect)
- add a global esc key listener and close the popover
