### ISSUE TITLE
`Highlight` component does not support theming

### ISSUE THREAD

**Issue by GKosheev** [chakra-ui/chakra-ui#7268]
### Description

It would be great to allow theming for the `Highlight` component as the current one does not support it and `mark`, which wraps all the words from `query`, has some problems with `baseStyle` in dark mode.

Unless it's expected behavior, I can make a PR for this issue. 

### Link to Reproduction

-

### Steps to reproduce

-

### Chakra UI Version

latest

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by TylerAPfledderer** [comment]
Hey @GKosheev! Do you have a minimal repro of the dark mode issue you described?

`Highlight` is only a wrapper, but there is an internal component called [Mark](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/layout/src/highlight.tsx#L60-L71) that does accept a style config! You would just have to export with the name "Mark" and not "Highlight". 

Give that a try!

**Comment by GKosheev** [comment]
@TylerAPfledderer, if you toggle color mode in the following example, all the words, except `spotlight`, will change their color according to the mode. 

```tsx
<Highlight query={"spotlight"}>you can spotlight words</Highlight>
```
Is it expected behavior?

I also couldn't find an implementation of theming for the `Mark` component in `theme/src/components/index.ts`. If I could create custom variants within the theme for the `Mark` or `Highlight` components, that would be great.

**Comment by TylerAPfledderer** [comment]
@GKosheev That is expected behavior, because it would be intended to supply a different `bg` color for the marked text, hence the component being called "Highlight".

As to the theme, the lack of a default is also intended, and would need to supply all of your own as needed per the [Single Part Component Styling](https://chakra-ui.com/docs/styled-system/component-style#styling-single-part-components).

A default config does not need to be present in order for you to extend the theming. :)
