### ISSUE TITLE
Switch value not being set by React-Hook-Form

### ISSUE THREAD

**Issue by ThyagoMC** [chakra-ui/chakra-ui#7286]
### Description

When using Chakra UI with react hook form, I am able to control the input fields as expected. However, when using a Switch component, the reset() action is not able to reset the value of the component

The reset only work if isn't passed any value to it and only to uncheck the Switch. 
If a defaultValue is provided for the Switch as checked  it will be shown as expected on the first render but the reset function will only uncheck the Switch.

If some value is passed to the reset function it will not affect any Switch  component.

I wonder if there is a potential to revise the integration of this component?

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-react-hook-form-switch-forked-zizlwy?file=/src/HookForm.js

### Steps to reproduce

1. Go to ['codesandbox'](https://codesandbox.io/s/chakra-ui-react-hook-form-switch-forked-zizlwy?file=/src/HookForm.js)
2. Change the name field to another value
3. Click on switch component to make it deactive
4. Click on reset button.
The name field is reset correctly, but the switch remains unchanged

### Chakra UI Version

2.4.9

### Browser

Chrome, Brave

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by super-sid** [comment]
For using external library components with React Hook Form, its mentioned on RHF's website that we need to use the `<Controller />` component.
https://react-hook-form.com/api/usecontroller/controller

Below is a codesandbox for solving your use case:
[Sandbox Link](https://codesandbox.io/s/chakra-ui-react-hook-form-switch-with-controller-7h8gh5?file=/src/HookForm.js)

I hope this is sufficient to close out this issue.

**Comment by jkerekes-ANT** [comment]
There are issues even if you use the `<Controller />` component.

Here is a demo: https://codesandbox.io/p/sandbox/wizardly-orla-vnzv9c

**Additional info**
 * if you use `ReactDOM` from  `react-dom` instead of `react-dom/client` (React v17 render), the issue is not reproducible.
 * if you call `reset()` on the HTML form element, it works (ex:  JavaScript from browser console, with react useRef doesn't work)
 * I reproduced with setups: `react-scripts` or `vite` using react 18 and 19 versions
