### ISSUE TITLE
Changelog formatting issue

### ISSUE THREAD

**Issue by feross** [chakra-ui/chakra-ui#731]
The changelog at https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/CHANGELOG.md#080-2020-05-16 has some formatting issues that make it hard to read.

Just wanted to flag this for you in case you weren't aware! Thanks for all the great work!

**Comment by segunadebayo** [comment]
Thanks for letting me know @feross.

We'll look into it shortly.

**Comment by with-heart** [comment]
Looks like it's breaking due to unescaped `>` in this line:

`- add iconColor prop to <Select /> ([968ca80](https://github.com/chakra-ui/chakra-ui/commit/968ca80d916f691ed26515a6e80c43d01eb25d9f))`

Replacing `<Select />` with `<Select /\>` makes it render correctly. I wonder if there's a way to auto-escape when generating.

**Comment by segunadebayo** [comment]
Thanks for fixing this @with-heart.

We'll move to changeset after the v1.0 release so we can have more control over how the changelogs are generated.
