### ISSUE TITLE
Checkbox.label `fontSize` cannot be customized from theme settings

### ISSUE THREAD

**Issue by tkc310** [chakra-ui/chakra-ui#7328]
### Description

I tried the following theme settings,
but only `fontSize` did not seem to be reflected in the style.
(fontWeight & color is reflected.)

```
import { extendTheme } from '@chakra-ui/react';

const customTheme = extendTheme({
  components: {
    Checkbox: {
      baseStyle: {
        label: {
          fontSize: '2rem',
          fontWeight: 'bold',
          color: 'red',
        },
      },
    },
  },
});

<ChakraProvider theme={customTheme} />
```

I was able to work around it by directly overriding the class style,
but is there a better solution?

```
:global(.chakra-checkbox__label) {
  font-size: 2rem;
}
```

### Link to Reproduction

https://codesandbox.io/s/friendly-wing-s22jn7?file=/src/theme.ts

### Chakra UI Version

2.4.9

### Browser

Google Chrome 109.0.5414.119

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by GKosheev** [comment]
@tkc310, I've done some research and the reason for such behavior is that `checkboxTheme` has the following default config:
```typescript 
defaultProps: {
    size: "md",
}
```

And `size: "md"` has the following configs: 

```typescript
  md: definePartsStyle({
    control: { w: 4, h: 4 },
    label: { fontSize: "md" },
    icon: { fontSize: "0.625rem" },
  }),
```

As you can see from here, it has predefined `fontSize: "md"` in the `label` part, and that causes your `baseStyle` to be overridden by that.

Since `control` part highly depends on `size`, which is getting defined within each `size` according to it's name size, I suggest a couple of ways to fix that problem: 

1. Remove all declarations of `fontSize` from `sizes` and create default `fontSize` of `label` in the `baseStyle`:

```diff
const baseStyleLabel = defineStyle({
+  fontSize: "md",
...
})

const sizes = {
  sm: definePartsStyle({
-   label: { fontSize: "sm" },
  }),
  md: definePartsStyle({
-   label: { fontSize: "md" },
  }),
  lg: definePartsStyle({
-    label: { fontSize: "lg" },
  }),
}
```

2. Remove all `sizes` with a declaration of the default control, label and icon (let's say medium size would be the default one):

```diff
const baseStyleControl = defineStyle((props) => {
+ [$size.variable]: "sizes.4"
...
}
const baseStyleIcon = defineStyle({
+ fontSize: "2xs" 
...
})
const baseStyleLabel = defineStyle({
+  fontSize: "md",
...
})
- const sizes = { ... };
```

Before making any changes, It'd be great if @segunadebayo could review the proposed solutions and shared his thoughts on that.

**Comment by tkc310** [comment]
@GKosheev 
Thanks for your advice.
I now understand that the label style of the `Checkbox` component depends on `sizes`.
