### ISSUE TITLE
CSS variable 'popper-arrow-shadow-color' being overwritten on dark mode

### ISSUE THREAD

**Issue by pedroscosta** [chakra-ui/chakra-ui#7476]
### Description

When I set the `popper-arrow-shadow-color` css-var using the `extendTheme` function, it gets overwritten by the default value when using dark mode.

![image](https://user-images.githubusercontent.com/5331735/226763289-0f5446f0-85fb-4c76-8d7a-b64ab47c06da.png)

### Link to Reproduction

https://codesandbox.io/s/happy-yalow-bu7ddk

### Steps to reproduce

1. Extend the default theme
2. Set the css var under `Popover` -> `content`
3. Use dark mode
4. See the bug on the arrow shadow color

### Chakra UI Version

2.5.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @pedroscosta,

This is not a bug. It's happening because the default theme set's the dark mode color of the arrow under the `_dark` property. You'll need to go ahead and override that.

You've got two options:

- Set `"red !important"` to increase the priority
- Update the styles to override the `_dark` property

```jsx
content: {
          [cssVar("popper-arrow-bg").variable]: "white",
          _dark: {
              [cssVar("popper-arrow-shadow-color").variable]: "red"
           }
        }
```
