### ISSUE TITLE
Global styles, resetCSS, resetScope and cssVarsRoot - Adding styles outside of my component

### ISSUE THREAD

**Issue by ozzyonfire** [chakra-ui/chakra-ui#7520]
### Description

When I use cssVarsRoot and resetScope, I expect that the Chakra UI styles will only be applied to the selected div. 

### Link to Reproduction

https://codesandbox.io/s/pedantic-farrell-g2q0zk?file=/src/index.tsx

### Steps to reproduce

In the codesandbox I am trying to demonstrate my use case. 

I have a separate component on a page which contains it's own styles. 
I'd like to respect the page styles, but render my component using Chakra-UI styles.

If I use the recently added resetScope feature and target my component, or even a div wrapper around my component. I am still seeing global styles injected into the main page. 

Even if I try extending the base theme and going through that route, these styles still override the body. Notably the two classes that are giving me the most trouble are "gradient" and "chakra-ui-light" that are getting added to the classes of the body element on the page. 

Has anyone been able to get this to work, or is this not possible. It seemed like #7464 was built for this, but I may have misunderstood it's use-case.

### Chakra UI Version

2.5.4

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by posabsolute** [comment]
Same here, I still get leaked CSS, especially around body, HTML fonts and others

**Comment by posabsolute** [comment]
I investigated a bit the issue, for context, in our case we have:

- an old monolith where part of the page are newer react apps
- we also have a micro front-end setup for newer apps, so we load and unload apps without page refresh. 
- One last thing is that it's a white-label platform, with very customized headers per customer, for us Styled component is necessary.

I see 2 main issues right now where Chakra leaks styles outside the Chakra Provider.

1. It adds the styles to the <head>, in a micro front-ends setup this is an issue since we can load and unload apps, and you can get a lot of duplication, Styled components now offer a DOM element target option which dictates where to inject the styles, it be great the Chakra Provider leverage this feature too and provide the same option.

2. Even with the Scoped globals some styling leaks from the scope, this seems mostly related to body/html styles. See Screenshot below

<img width="847" alt="Screenshot 2023-04-04 at 7 19 23 PM" src="https://user-images.githubusercontent.com/114950/230111170-d62fd2b0-434a-42ac-a789-a43c3fc6fd15.png">

**Comment by segunadebayo** [comment]
Good catch @ozzyonfire.

I've added a `disableGlobalStyle` option you can pass to the `ChakraProvider` so you can turn off any global style leaks.

The leak is coming from the internal Chakra global styles defined in the theme.

I'll publish a new version shortly.

**Comment by Andrei-Ist** [comment]
@segunadebayo 
I'm trying to figure out how to use the disableGlobalStyle feature, I'm using the latest release 2.8.0.
I'm not sure it's a bug or I'm not using the feature correctly. 

My use case is injecting a react component styled with Chakra UI into a webpage, with a Chrome Extension. I'm using webpack 5 to create the dist folder to upload the chrome extension. 

In my ChakraProvider I have the following, injecting the content in a new div element in that webpage: 
     root.render(
      <React.StrictMode>
        <ChakraProvider disableGlobalStyle={true}>
          <AnalyzerView emailDataStore={dataStore} />  --> my react component styled with Chakra UI
        </ChakraProvider>
      </React.StrictMode>
      );
  
This is what I get in the <head> section of the webpage where I'm injecting my component. 

<img width="1366" alt="styles injected in header" src="https://github.com/chakra-ui/chakra-ui/assets/79289313/c6d4015c-9011-4777-9c8e-0ba0c54eafde">
      
Also, when I select a button from the website where I'm injecting the component that shouldn't be affected by the Chakra, I see styles applied from Chakra.  See below: 
      
<img width="523" alt="styles injected in an website element" src="https://github.com/chakra-ui/chakra-ui/assets/79289313/23f53108-1c70-44f4-97be-1d060b03f9b0">

I've also tried using resetScope feature with Chakra Provider, and while I still get the styles injected in the header, it seems not to impact the website where I'm injecting the component. Here the problem is that I'm getting my component messed up, one example would be adding padding=0 to all the button elements, but there are others.   

<img width="533" alt="button styles injected in element" src="https://github.com/chakra-ui/chakra-ui/assets/79289313/8e4f5856-e9ed-4873-860a-f8d71339288c">

**Comment by theshadowagent** [comment]
I'm having the same issues as @Andrei-Ist on the same use case for a Chrome extension.

**Comment by williaster** [comment]
Same problem with `^2.8.1`

**Comment by Andrei-Ist** [comment]
Couldn't find a fix, i finally switched to MUI, which worked in this scenario. Took me a week to rewrite the frontend, but it also took me equally to find a solution.
It's a pity, that you don't get good guidance based on the documentation or discord channels, as Chakra is great to work with, until you get into a more complex situation.

**Comment by Weixuanf** [comment]
HI please refer to this link for solution, you can disable CSSReset and host your own CSSReset: https://github.com/chakra-ui/chakra-ui/issues/2802#issuecomment-1186287297
