### ISSUE TITLE
Cannot change the border color of Input

### ISSUE THREAD

**Issue by kaluabentes** [chakra-ui/chakra-ui#7556]
### Description

I'm using  extendTheme to customize the theme and when I use the following code the result is unexpected:

```javascript
import { inputAnatomy } from "@chakra-ui/anatomy"
import { createMultiStyleConfigHelpers } from "@chakra-ui/react"

const { definePartsStyle, defineMultiStyleConfig } =
  createMultiStyleConfigHelpers(inputAnatomy.keys)

const baseStyle = definePartsStyle({
  // define the part you're going to style
  field: {
    borderColor: "gray.200",
  },
})

const Input = defineMultiStyleConfig({ baseStyle })

export default Input
```

The result is a black border color:

![image](https://user-images.githubusercontent.com/6353257/230756030-7a852528-b580-4f8a-a431-df87dec17ed2.png)

Any help will be thankful.

### Link to Reproduction

https://codesandbox.io/s/serverless-morning-yfpgd4?file=/src/index.js

### Steps to reproduce

1. Create a custom theme
2. Set Input field styles

### Chakra UI Version

2.5.5

### Browser

Microsoft Edge 112.0.1722.34

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sblyvwx** [comment]
Changing the default variant works. Although I don't know why you cannot change it in baseStyle, I guess it gets overwritten somewhere.
```ts
const baseStyle = definePartsStyle({
  variants: {
    outline: {
      // define the part you're going to style
      field: {
        borderColor: "gray.200"
      }
    }
  }
});
```

**Comment by mendozagioo** [comment]
Hey @kaluabentes, I hope this could be help you:
Look, the right way to customize a component (in you case `Input` ) using `extendTheme` is using the `variant` attribute, and another thing to keep in mind is "some styles are shared ONLY in the `variant` object" this is because some styles  are applied direcly in the `variant` styles (in the `Input`  case: `border, borderColor, bg, boxShadow, userSelect`), to add another styles in the component you need to use `baseStyle` attribute.

For you specific case try with this:
````jsx
import * as React from "react";
import * as ReactDOMClient from "react-dom/client";
import { Box, ChakraProvider, Input, extendTheme } from "@chakra-ui/react";

const components = {
  Input: {
    baseStyle: {
      field: {
        fontWeight: "bold",
        textTransform: "uppercase",
      }
    },
    variants: {
      outline: {
        field: {
          border: '5px solid',
          borderColor: 'tomato',
          _hover: {
            borderColor: "purple"
          }
        }
      }
    }
  }
}

const theme = extendTheme({ components });

function App() {
  return (
    <Box padding={4}>
      <Input />
    </Box>
  );
}

const rootElement = document.getElementById("root");
const root = ReactDOMClient.createRoot(rootElement);

root.render(
  <React.StrictMode>
    <ChakraProvider theme={theme}>
      <App />
    </ChakraProvider>
  </React.StrictMode>
);
````
As you can see, some extra styles that you might need in the component are handled from `baseStyle` attribute.
Also emember that, styles referent to size are handled in a separate attribute (`sizes` ).

For more information about this topic you can reed this documentation: https://chakra-ui.com/docs/styled-system/component-style#styling-single-part-components

**Comment by kaluabentes** [comment]
> Changing the default variant works. Although I don't know why you cannot change it in baseStyle, I guess it gets overwritten somewhere.
> 
> ```ts
> const baseStyle = definePartsStyle({
>   variants: {
>     outline: {
>       // define the part you're going to style
>       field: {
>         borderColor: "gray.200"
>       }
>     }
>   }
> });
> ```

Thanks you guys, this work for me!

**Comment by letsclode** [comment]
dont forget to add these : boxShadow: 'none'
