### ISSUE TITLE
Unsafe inline style violate Content Security Policy

### ISSUE THREAD

**Issue by yinlam22** [chakra-ui/chakra-ui#7600]
### Description

Unsafe inline style is used in some of the chakra UI components that will violate the Content Security Policy
Example: 
- https://github.com/chakra-ui/chakra-ui/blob/d3fc1fd61dcee50a8916dfee9bd403e645bf6cbb/packages/components/toast/src/toast.provider.tsx#L130
- https://github.com/chakra-ui/chakra-ui/blob/d3fc1fd61dcee50a8916dfee9bd403e645bf6cbb/packages/components/toast/src/toast.utils.ts#:~:text=%3A%20undefined-,return%20%7B,%7D,-%7D
```
  return {
    position: "fixed",
    zIndex: "var(--toast-z-index, 5500)",
    pointerEvents: "none",
    display: "flex",
    flexDirection: "column",
    margin,
    top,
    bottom,
    right,
    left,
  }
```

**Expected behavior**
- A way to add nonce globally to all chakra UI components
- Avoid the use of unsafe inline style

### Link to Reproduction

Not really possible to show this in CodeSandbox

### Steps to reproduce

Add the Content-Security-Policy header on a website with this value:

```
"base-uri; child-src; connect-src 'self' *; default-src; font-src; form-action; frame-ancestors 'self' *; frame-src 'self'; img-src 'self' * data:; manifest-src 'self'; media-src 'self'; object-src 'none'; script-src 'self'; style-src 'self' ;"
```

### Chakra UI Version

2.4.1

### Operating System

- [x] macOS
- [x] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @yinlam22,

The styles used in that component are not unsafe, except I misunderstand what you're saying. Adding styles in the `style` attribute is not an issue with React.

As far as I know, this will only be an issue when style elements are injected into the document.

**Comment by yinlam22** [comment]
Hi @segunadebayo 
Sorry, I should have provided more clarification and shared my finding on this. 

What I meant by unsafe inline style on that chakra UI component is it is blocked by the Content Security Policy when the "**unsafe-inline**" is not added to the Content-Security-Policy: style-src 

if the unsafe-inline source is not specified in the CSP style-src, then it will block the inline style attributes: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles

I reproduced the scenario using codesandbox
https://codesandbox.io/s/chakra-ui-toast-example-ds6lwm?file=/src/App.js

when inspecting the page, we noticed that all the ```<div>``` rendered under ```<div class="chakra-portal">``` has style attribute injected directly to the element and thus it is violating the no unsafe-inline CSP

![image](https://user-images.githubusercontent.com/117242008/234447320-9da98e55-a585-40b0-b849-0aa13aa659e2.png)

**Comment by jacklimwenjie** [comment]
Hey @segunadebayo is it possible to reopen this? I'm having the same issue

**Comment by NoobTW** [comment]
Same here. I think this should be reopen.

**Comment by ptim** [comment]
If using vite, this seems relevant (doesn't require `Content-Security-Policy: style-src 'unsafe-inline';`):

> When [html.cspNonce](https://vitejs.dev/config/shared-options.html#html-cspnonce) is set, Vite adds a nonce attribute with the specified value to any `<script>` and `<style>` tags, as well as <link> tags for stylesheets and module preloading. Additionally, when this option is set, Vite will inject a meta tag (`<meta property="csp-nonce" nonce="PLACEHOLDER" />`).
>
> The nonce value of a meta tag with `property="csp-nonce"` will be used by Vite whenever necessary during both dev and after build.

https://vitejs.dev/guide/features.html#content-security-policy-csp

Would be great to see mention of this in Chakra docs 👍 (I'm not enough of an authority to contribute such, at this stage...)

**Comment by thesnups** [comment]
I'm using Vite and have a working solution that uses the [`html.cspNonce`](https://vite.dev/guide/features.html#content-security-policy-csp) mentioned above by @ptim . Here are a few things that I learned along the way:

1. Choose a placeholder value for the `nonce` and specify it in the Vite config:

    ```js
    import { defineConfig } from 'vite'
    
    export default defineConfig({
      // ...
      html: {
        cspNonce: 'NONCE_PLACEHOLDER',
      },
      // ...
    });
    ```

2. You need per-request server processing to replace the placeholder value with a random cryptographic value. In my project, I am hosting on AWS and leverage a Lambda function to serve the `index.html` file produced by Vite. The Lambda function generates a strong `nonce` value and replaces the placeholder in `index.html` for each request. Here is a snippet of the relevant parts of the Lambda code:

    ```js
    const nonce = crypto.randomBytes(16).toString('base64');
    
    const rawBody = await getObjectFromS3('index.html').Body.transformToString();
    const body = body.replace(/NONCE_PLACEHOLDER/g, nonce);
    
    const headers = {
      'Cache-Control': 'no-cache, no-store', // Instruct CloudFront and user's browser to not cache the file
      'Content-Security-Policy': `default-src 'self'; script-src 'self' 'nonce-${nonce}'; style-src 'self' 'nonce-${nonce}'`,
    };
    
    return {
      statusCode: 200,
      headers,
      body,
    };
    ```

3. In addition to adding the `nonce` to static scripts, styles, and preload links, Vite creates a `meta` tag: `<meta property="csp-nonce" nonce="NONCE_PLACEHOLDER">`. At runtime, this DOM element provides access to the actual, replaced `nonce` value. Your app code must retrieve the value from the element and apply it to dynamically inserted scripts and styles. Note that you cannot use `metaElement.getAttribute('nonce')` because the browser conceals that attribute for security purposes ([source](https://github.com/vitejs/vite/blob/9fc31b6e4d4f2a5bd9711d4f84dcb55061ebead0/packages/vite/src/node/plugins/html.ts#L1155-L1156)). Instead, you must use the `metaElement.nonce` property. Create a utility module to expose the nonce value to the rest of the React app:

    ```ts
    const cspNonceMetaEl = document.head.querySelector('meta[property="csp-nonce"]') as HTMLElement|undefined;
    const retrievedNonce = cspNonceMetaEl?.nonce;
    export default retrievedNonce || 'ERROR_RETRIEVING_CSP_NONCE';
    ```

4. When using Chakra UI, Emotion needs to be made aware of the `nonce` via [`createCache` and `CacheProvider`](https://emotion.sh/docs/@emotion/cache#nonce-string):

    ```ts
    import { ChakraProvider } from '@chakra-ui/react';
    import createCache from '@emotion/cache';
    import { CacheProvider } from '@emotion/react';
    import nonce from './nonce'; // The module described in #3
    import { system } from './theme'; // Chakra v3 theme
    
    const cache = createCache({
      nonce,
      key: 'ui',
    });
    
    export default () => (
      <CacheProvider value={cache}>
        <ChakraProvider value={system}>
          <App/>
        </ChakraProvider>
      </CacheProvider>
    );
    ```

5. When using dark/light color modes in Chakra UI v3, `next-themes` needs to be made aware of the `nonce` via [`ThemeProvider`](https://github.com/pacocoursey/next-themes?tab=readme-ov-file#themeprovider). You need to edit the `ui/color-mode.tsx` file generated by the Chakra snippets CLI:

    ```ts
    import { ThemeProvider } from 'next-themes';
    import type { ThemeProviderProps } from 'next-themes';
    import nonce from './nonce'; // The module described in #3
    
    export type ColorModeProviderProps = ThemeProviderProps;
    
    export function ColorModeProvider(props: ColorModeProviderProps) {
      return (
        <ThemeProvider
          attribute='class'
          nonce={nonce}
          disableTransitionOnChange
          {...props}
        />
      );
    }
    ```

Hope this helps someone!

**Comment by ptim** [comment]
Props for the comprehensive guide @thesnups 🙏
