### ISSUE TITLE
useBreakpointValue and screen resize

### ISSUE THREAD

**Issue by juliancwirko** [chakra-ui/chakra-ui#7609]
### Description

When I use `useBreakpointValue` with ssr false and fallback value when scaling the window up, I see that fallback is always returned before the correct value. Is this the proper behavior for this hook? What is interesting when scaling the window down, it works as I would want it to.

### Link to Reproduction

https://codesandbox.io/s/c3wegk?file=/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/c3wegk?file=/App.tsx
2. Open the console
3. Start resizing the window (iframe)
4. when scaling the window up, the fallback value is always console logged before the correct value. When there is no fallback, undefined is consol logged before the correct value 
5. When scaling the window down, it works as it should

### Chakra UI Version

2.6

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by danielfdsilva** [comment]
Any update on this issue?

If multiple breakpoint hooks are being used at the same time, they do not all return the same breakpoint value.
Code sandbox example: https://codesandbox.io/p/sandbox/gracious-voice-cwf5ct

```js
  const breakpoint = useBreakpointValue({
    base: "base",
    sm: "sm",
    md: "md",
    lg: "lg",
    xl: "xl",
    "2xl": "2xl",
  });

  const columns = useBreakpointValue({
    base: 4,
    md: 8,
    lg: 12,
  });

  console.log("breakpoint", breakpoint);
  console.log("columns", columns);
  console.log("---");
```

When going from `md` to `lg` there are multiple renders with a inconsistent combination of results:
```
breakpoint base
columns 8
---
breakpoint lg
columns 8
---
breakpoint lg
columns 4
---
breakpoint lg
columns 12
---
```

The fact that different hooks think that they are on different breakpoints, breaks a lot of things.

**Comment by danielfdsilva** [comment]
I figured out what is happening here, but this feels more like an architecture problem, rather than a bug...

The problem is with the `useEffect` in the `useMediaQuery` hook.

https://github.com/chakra-ui/chakra-ui/blob/5e1ea4a4c4108c08fc327480c7f73102ea4f568b/packages/components/media-query/src/use-media-query.ts#L39-L77

### Scenario
Let's assume we only have 1 use of `useBreakpointValue`

```js
const breakpoint = useBreakpointValue({
    base: "base",
    sm: "sm",
    md: "md",
    lg: "lg",
    xl: "xl",
    "2xl": "2xl",
  });

  console.log("breakpoint", breakpoint);
  console.log("---");
```
When going from `md` to `lg` you would see:

```
breakpoint base
---
breakpoint lg
---
```
but if you go from `lg` to `md` you still get 2 renders, but correct:

```
breakpoint md
---
breakpoint md
---
```

This happens because 2 media change events are fired. (added by line `63`). The media queries are ordered so the first event to fire is the `md`, and then the `lg`.

Looking at the handler this is the flow when going from `md` to `lg`.
https://github.com/chakra-ui/chakra-ui/blob/5e1ea4a4c4108c08fc327480c7f73102ea4f568b/packages/components/media-query/src/use-media-query.ts#L50-L57

- evt for `md` with match `false` (we moved to `lg`)
- the `prev` array was `[ false, false, true, false, false, false]`
- and now since we're no longer `md` it is `[ false, false, false, false, false, false ]`
- state is set so react renders and we get `breakpoint base`
- then the evt for `lg` fires with `true`
- the `prev` array was `[ false, false, false, false, false, false]` and becomes `[ false, false, false, true, false, false]`
- state is set and react renders with `breakpoint lg`

When going down, since `md` fires first, we get `[ false, false, true, true, false, false ]`, skipping the intermediate state with all `false`.

### Conclusion

For each use of `useBreakpointValue` we get 2 renders (one for the media query being exited and another for the entered). The mismatch becomes worse and worse depending on the number of uses.

The example on the previous comment uses it 2 times so that's 4 renders.

<details><summary>

### Possible approach

</summary>
<p>

A possible way to go about this would be to check the queries every time and force a render on media change, but I don't know what the implications of this would be, performance or otherwise...

```ts
function useMediaQuery(
  query: string | string[],
  options: UseMediaQueryOptions = {},
): boolean[] {
  const { ssr = true, fallback } = options

  const { getWindow } = useEnvironment()

  const queries = Array.isArray(query) ? query : [query]

  let fallbackValues = Array.isArray(fallback) ? fallback : [fallback]
  fallbackValues = fallbackValues.filter((v) => v != null) as boolean[]

  const [, forceUpdate] = useState(0);
  const firstRender = useRef(true);

  useEffect(() => {
    const win = getWindow();
    const mql = queries.map((query) => win.matchMedia(query));

    const handler = () => forceUpdate(Date.now());

    mql.forEach((mql) => {
      if (typeof mql.addListener === "function") {
        mql.addListener(handler);
      } else {
        mql.addEventListener("change", handler);
      }
    });

    handler();

    return () => {
      mql.forEach((mql) => {
        if (typeof mql.removeListener === "function") {
          mql.removeListener(handler);
        } else {
          mql.removeEventListener("change", handler);
        }
      });
    };
  }, [getWindow])

  const returnFallback = firstRender.current && ssr;
  firstRender.current = false;

  return queries.map((query, index) => ({
    media: query,
    matches: returnFallback ? !!fallbackValues[index] : getWindow().matchMedia(query).matches
  })).map((item) => item.matches);
}
```

</p>
</details>

**Comment by segunadebayo** [comment]
Duplicate of #6401

Will address these shortly
