### ISSUE TITLE
Semantic tokens no longer support foundation values

### ISSUE THREAD

**Issue by loreggia** [chakra-ui/chakra-ui#7660]
### Description

Defining a semantic token referencing a foundation value does no longer work in v2.6.0+ (worked in 2.5.5).

Example:

Having the following semantic token in a theme
```typescript
const theme = extendTheme({
  semanticTokens: {
    radii: {
      default: "lg"
    }
  }
});
```
and using it on on a component
```tsx
<Box borderRadius="default">...</Box>
```
will no longer work.

### Link to Reproduction

https://codesandbox.io/s/stupefied-solomon-rdg95e?file=/package.json

### Steps to reproduce

1. See that the border has a radius and an outline shadow.
2. Change the version of the @chakra-ui/react package to 2.6.0 or 2.6.1
3. The border doesn't have a radius nor an outline anymore.

### Chakra UI Version

2.6.0

### Browser

Edge 113.0.1774.35

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by TylerAPfledderer** [comment]
Hey @loreggia!

Now with the ability to nest semantic tokens from `v2.6.0` and on for better organizing, `default` has become a reserve key word to be used in conjunction with the `_light` or `_dark` modifiers or other psuedoProp names you would used in building your semantic tokens.

When flattening these nested token objects, there is a small function that stops the iteration if `default` or any of the pseudoProps are found.

You would need to change the name of this token in your example to `base`, say.

**Comment by TylerAPfledderer** [comment]
@loreggia for convenience in using such a word, this has been brought up with the team to convert the usage, where instead of `default`, it can become `_default`.

To clarify, `default` is a reserve word to be able to assign a default value to a semantic. And then use a modifier like `_dark` to provide an alternate value if dark color mode is toggled.

Changing the naming to an underscore will stay in line with the pseudo props convention and allow you to use `default` as a semantic!

However, this will be a breaking change and is to be considered for Chakra v3. So please stick with the suggestion I provided above. 😄

**Comment by loreggia** [comment]
Hi @TylerAPfledderer, thanks for your response.

It's strange, I could have sworn that other tokens that were not named `default` also didn't work, but I tested it again and like you said, it only happens for the `default` tokens.
Seems this is a breaking change in my case and I will have to change the naming of my tokens if I want to update to v2.6+ then.

It would probably be good to describe this behaviour more explicitly in the docs.

Thanks for your help!
