### ISSUE TITLE
[Popover/Modal] Losing form state inside modal/popovers

### ISSUE THREAD

**Issue by andregoldstein** [chakra-ui/chakra-ui#803]
Hi there!

I'm not sure if this is an issue with popovers/modals being "removed" from the DOM vs hidden using CSS but I have a form inside a popover component and when the popover is closed and reopened, the form state inside is lost.

Apologies if this is something outside the scope here but it would appear that somehow the component is re-rendering and then perhaps losing state.

The Form is using `react-hook-form` in case that is of any relevance.

**Comment by with-heart** [comment]
Hi @andregoldstein! :wave: 

Any way you could reproduce your issue in codesandbox.io? That'd make it a lot easier for us to help :)

**Comment by andregoldstein** [comment]
@with-heart Hello! Thanks, will do!

**Comment by andregoldstein** [comment]
Here is a link to a pared-down version

https://codesandbox.io/s/angry-keller-fl7lz?file=/src/index.js

PS: It could well be that this is normal behaviour!

**Comment by segunadebayo** [comment]
Hi @andregoldstein,

You're right, this is because the Popover gets removed from the DOM. We've fixed this to use the `hidden` attribute so it remains in the DOM. As for the modal, we think it's best to mount/unmount it from the DOM.

The fix is available in the `v1.0.0-next.3` pre-release. We're trying to get `v1` out as fast as possible so you can start using it.

Cheers.

**Comment by andregoldstein** [comment]
Cheers and thanks for all your great work!
