### ISSUE TITLE
Menu no longer scrolls to selected item

### ISSUE THREAD

**Issue by shawn-talin** [chakra-ui/chakra-ui#8075]
### Description

When I open a Menu with many items, and the MenuList has a `maxH` set with items hidden by overflow scroll, I expect the selected item to be scrolled to or brought into focus when I type the first letter of the item label. Instead the item is selected but not scrolled to.

This is working in v2.8.0 but not in v2.8.1. Suspected cause: https://github.com/chakra-ui/chakra-ui/commit/0b2c4049f9ac59554313b3032e8cf9a904141a5b

### Link to Reproduction

https://codesandbox.io/s/determined-cherry-q46ywc?file=/src/index.tsx

### Steps to reproduce

See menu example in codesandbox. v2.8.1 doesn't scroll to item.
Change to v2.8.0 and it scrolls to item. 

### Chakra UI Version

2.8.1

### Browser

Google Chrome 118

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by JenJoyHamborg** [comment]
I'm currently experiencing the exact same issue shown in CodeSandbox above arrow down does scroll additional items into view. I'm using 2.8.2, mac, chrome 121. Downgraded to 2.8.0 and scroll behavior with keyboard is working as expected.

**Comment by evgenii-paikachev-nl** [comment]
For me downgrading `@chakra-ui/react` to 2.8.0 didn't work. 
After some digging i realised this is because i've recently updated all of the chakra packages to latest which prompted an update of peerDependecy called `@chakra-ui/menu`. 
Issue is introduced in 2.2.1 version of that package. 

Solution that worked for me:
Install specific version(<2.2.1) of chakra menu
`yarn add @chakra-ui/menu@2.2.0` 

And then in package.json add
```
  "resolutions": {
    "@chakra-ui/menu": "2.2.0"
  }
```
This forces the use of this package version across all packages, including nested dependencies.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
