### ISSUE TITLE
Question: Why removed the styled system package?

### ISSUE THREAD

**Issue by remorses** [chakra-ui/chakra-ui#809]
I see that the `dev-ts` branch reimplements `styled system` features, is it really necessary?

if you use the `styled system` package there is a lot of code that can be shared with other depencencies and the bundle size reduced,

you lose the benefit of getting improvements and bug fixes made in the upstream package,

probably a lot of inconsistencies and breaking changes will emerge as soon as the package is published

**Comment by segunadebayo** [comment]
Hi @remorses,

To be honest, this was exactly what I thought before we made the decision. I personally prefer not to re-invent the wheel and re-use existing ideas if possible.

What I can tell you is that we tried to use styled-system for the new API structure we have but we needed some custom scenarios not accounted for, and waiting for our PR to get merged in styled-system might take a while.

I don't expect inconsistencies due to this decision because what we wrote is well-tested for compatibility with styled-system. However, if issues occur, it's our responsibility to fix it. That's why this will be released as `beta` first to test it out.

Thanks for your genuine concern about this. Let's launch and then we'll evaluate this.
