### ISSUE TITLE
align abbreviation is not working for ModalContent Component

### ISSUE THREAD

**Issue by ElsevarAsadov** [chakra-ui/chakra-ui#8232]
### Description

You know there are some styling abbreviations makes our life easier such as justify instead of justifyContent.when i wanna use align instead of alignItems it doesnt work. Looks like ModalContent only works for alignItems.i think this issue works for every case no need example code.I faced this issue several times when in different projects.

```js

 <ModalContent alignSelf={'center'}>
      ...
 </ModalContent>
```

### Chakra UI Version

2.8.2

### Browser

Brave

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by thallesyam** [comment]
Hey, good evening. I wanted to know if this issue is still open?

This is my first time contributing to an open-source project, and I followed this approach, but I'm not sure if it's the most appropriate according to the development standards of this library.

![image](https://github.com/chakra-ui/chakra-ui/assets/59545660/869f3375-af8c-41f5-b554-5a91727e0dae)
![image](https://github.com/chakra-ui/chakra-ui/assets/59545660/a220c883-42fd-4333-a97e-7c1e5174f54c)

**Comment by segunadebayo** [comment]
align is just for Stack components; not every component. Please use alignItems instead
