### ISSUE TITLE
Stack default alignItems should be `stretch`

### ISSUE THREAD

**Issue by remorses** [chakra-ui/chakra-ui#828]
This line adds a breaking change, the default should not be `flex-start`

https://github.com/chakra-ui/chakra-ui/blob/5b0986f6f23b64ecc706754aff6b1d36a3a62865/packages/layout/src/stack.tsx#L75-L80

It should be set to either `normal` (the css default, but not very predictable) or `stretch` (behaves as before, has predictable behaviour, makes the items inside 100% large

**Comment by aaronmcadam** [comment]
I think having full-width elements is more surprising behaviour. I end up having to set `flex-start` a lot because sometimes my stack elements are buttons, which I don't want stretching across the width of the container.

**Comment by segunadebayo** [comment]
@remorses, this was intentional and the reason is in line with what @aaronadamsCA mentioned.

We're having a major release, this allows us re-define some components and props.

Thanks for your concern and we'll make sure to add this to our migration guide.

**Comment by remorses** [comment]
This way old projects using chakra ui will be impossible to port to version 1, they will leave chakra or remain to version 0

I use something like 200 instances of stack components on one of my project, do you think I will add an align start to every one of them?

I di t want to be rude, I am giving my opinion

**Comment by with-heart** [comment]
@remorses You'll be able to change the base styles for all components using the new component theming api. https://github.com/chakra-ui/chakra-ui/blob/master/docs/pages/theming/simple.mdx#using-the-themekey

```js
const theme = {
  components: {
    Stack: {
      baseStyle: {
        align: 'stretch'
      }
    }
  }
}
```

**Comment by jsvossen** [comment]
This is an old issue, but I couldn't find any other reference to it. I am setting some default styles using `defineStyleConfig` (as outlined [here](https://chakra-ui.com/docs/styled-system/component-style)), but I noticed it doesn't work for any of the layout components (Stack, Flex, Wrap, Box, etc). Is this intentional? Is there another way to set default styles for those? I really prefer `alignItems="stretch"` for Stack and want to set it as a default. I'm on v2.3.4.
