### ISSUE TITLE
Back button should close the drawer

### ISSUE THREAD

**Issue by aghassemi** [chakra-ui/chakra-ui#9]
Hitting native browser back does not close the drawer.

**Comment by devanshj** [comment]
I think this should be kept userland because this would require pushing a state to history which is not owned by chakra. I agree that if the user wants this feature anyway a `useHistory: true` prop will be nice to have.

Also if someone is using a router this is router specific. Here's an [example how to do it with `react-router`](https://codesandbox.io/s/react-router-location-state-rmmu4). It's just a fork of Ryan's [modal example with the back feature](https://codesandbox.io/s/react-router-location-state-m0qqr).

**Comment by segunadebayo** [comment]
I agree with @devanshj . This isn't controlled by Chakra, users (developers) will have to handle this behavior within their apps.
