### ISSUE TITLE
Passing responsive styles in array syntax causes errors in console from emotion.

### ISSUE THREAD

**Issue by pacxiu** [chakra-ui/chakra-ui#9092]
### Description

On fresh Next 15 repo, adding chakra UI and just copying:
`<Text fontWeight={["medium", undefined, undefined, "bold"]}>Text</Text>`

from docs are causing error logs:
![image](https://github.com/user-attachments/assets/d47ae347-a452-410f-b546-2161c8eb61e4)
![image](https://github.com/user-attachments/assets/d8d59f92-9904-4754-8f78-95dbd42aa565)

Tried with `Box` and `Flex` components and issue also occurs.

### Link to Reproduction

-

### Steps to reproduce

Init fresh Next15 repo, add Chakra UI, copy/paste any component with array syntax for responsive values.

### Chakra UI Version

3.0.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I checked it locally and can't reproduce it.

This issue doesn't contain a reproduction, and it's hard for us to help.

Please create a StackBlitz reproduction, and we'll re-open

**Comment by pacxiu** [comment]
> I checked it locally and can't reproduce it.
> 
> This issue doesn't contain a reproduction, and it's hard for us to help.
> 
> Please create a StackBlitz reproduction, and we'll re-open

Updated with StackBlitz reproduction

**Comment by pacxiu** [comment]
Just repinging @segunadebayo as it is some kind of obstacle for our migration to v3.

**Comment by pacxiu** [comment]
Any update @segunadebayo ?

**Comment by jvnlwn** [comment]
The issue is related to using tokens that do not exist in the system (i.e. `borderRadius={["0", "2xl"]}`, where "2xl" is not defined as a system token).

If you are attempting to use a token provided by Chakra, you must pass the `defaultConfig` to `createSystem()`:

```ts
import { createSystem, defineConfig, defaultConfig } from '@chakra-ui/react';
const customConfig = defineConfig({/*...*/});
const system = createSystem(defaultConfig, customConfig);
```

I ran into this issue when upgrading to v3 (specifically v3.31.0). Might be nice if Chakra caught the issue upstream (before emotion catches it) and provided a helpful error log.
