### ISSUE TITLE
Popover doesn't close on second click when target is a Link & closeOnBlur={true}

### ISSUE THREAD

**Issue by nikhilpatil-git** [chakra-ui/chakra-ui#915]
<img width="1680" alt="popover_issue" src="https://user-images.githubusercontent.com/1549630/85283358-22758a80-b485-11ea-9d9d-bf0286f89ff7.png">

If i put target as a <Link> inside popover and put closeOnBlur={true} than on first click it opens the popup and on second click it closes it and opens again, the expected behavior is that on first click it should open and on second click it should close as it's doing with other target for example with a button.

Please help to explain if this is an issue or if there is any workaround.

thanks
Nikhil

**Comment by nikhilpatil-git** [comment]
@segunadebayo can you please look into this ?

thanks

**Comment by with-heart** [comment]
Hi @nikhilpatil-git, can you reproduce this in codesandbox so we can investigate your issue?

**Comment by segunadebayo** [comment]
@nikhilpatil-git, kindly provide a codesandbox reproduction.

**Comment by nikhilpatil-git** [comment]
This is the codesandbox of the issue, 
[Issue reproduction](https://codesandbox.io/s/issue-915-pop-over-56s8c)

**Comment by segunadebayo** [comment]
Hi @nikhilpatil-git,

The issue is that a `Link` without `href` passed is not focusable so it's really hard for the `Popover` to manage focus correctly.

I also think it's a bit counter-intuitive to use a Link as a PopoverTrigger, the question would be **"is this a link that takes a user to a new page"** or **"is this just a button that looks like a link and opens a popover".**

To make this work, I'd recommend you change `Link` to `Button` with `variant='link'` set so it looks like a link but acts a button and is focusable at all times.

```jsx
<PopoverTrigger>
       <Button variant="link" onClick={open} variantColor="pink">
         <b>Popover Target</b>
       </Button>
</PopoverTrigger>
```

Hope you find this useful. Cheers.

**Comment by segunadebayo** [comment]
https://codesandbox.io/s/issue-915-pop-over-xpirm?file=/src/App.js

**Comment by nikhilpatil-git** [comment]
@segunadebayo thanks very much for the help, you are write i want to open the popover by pressing on a text so i'm putting it inside Link to make it clickable so your solution will solve my problem thanks once again for the help.
