### ISSUE TITLE
defaultConfig always taking priority when merging.

### ISSUE THREAD

**Issue by m4r1vs** [chakra-ui/chakra-ui#9170]
### Description

I am migrating from V2 to V3 and trying to apply my old custom Theme to the new workflow. As I understand it from the guides, I need to define a custom `config` and merge that with the `defaultConfig`. However, I cannot figure out how to overwrite some of the values when merging. It seems like in `mergeConfigs(A,B)` B should overwrite A but it is not always the case as you can observe in the attached stackblitz.

Did I understand the workflow correctly?

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-dxolzy?file=src%2Ftheme.ts

### Steps to reproduce

1. Create custom config with slotRecipe for `Card.Root`
2. Define `border` in the slotRecipe to be something different than the default ("for example `2px solid black`).
3. Define `borderRadius` in the slotRecipe to be something different than the default ("for example `12px`).
4. Notice that the border of cards do not change but the radius does change.
5. Add `!important` to the `border`.
6. Notice that now both Radius and Border is changed as expected.

### Chakra UI Version

3.1.1

### Browser

Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
To override a recipe correctly, you need to examine its design. That's why we include the link to each recipe in the docs.

https://github.com/chakra-ui/chakra-ui/blob/main/packages/react/src/theme/recipes/card.ts

For the Card recipe, you notice that the card recipe has a default variant of outline, which controls the border. That's where you want to override.

```tsx
const cardRecipe = defineSlotRecipe({
  slots: ['root'],
  base: {
    root: {
      borderRadius: '12px',
      boxShadow: '3px 3px 0 black',
    },
  },
  variants: {
    variant: {
      outline: {
        root: { border: '2px solid black' },
      },
    },
  },
});
```

Alternatively, you can create a new variant to house the new styles you have.
