### ISSUE TITLE
Popover closes when clicking on button inside popover in firefox

### ISSUE THREAD

**Issue by rbk84** [chakra-ui/chakra-ui#9222]
### Description

When I click on a button inside a popup, the button's prop loading changes and the popover closes.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-l6o6a7

### Steps to reproduce

1. Go to 'https://stackblitz.com/edit/vitejs-vite-l6o6a7'
2. Click on 'Trigger'
3. Click on 'Click Me'

### Chakra UI Version

2.8.2

### Browser

Firefox 132.0.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Philzen** [comment]
@rbk84 the

**Comment by Philzen** [comment]
@rbk84 The underlying cause is the fact that `isLoading={true}` also disables the button, which in turn resets the focus on the page → popover loses focus and thus closes.

This very behavior also affects a11y which i raised via #7965

In your case, there are two possible workarounds:
1. setting `disabled={false}` on the `Button` (you'll need a newer version than v2.8.2 for that to work)
2. setting `closeOnBlur={false}` on the `Popover` – which of course makes it stay permanent unless explicitly dismissed, which may not be want you want in your UI

**Comment by rbk84** [comment]
@Philzen what version do you suggest upgrading to? The problem persists with version 2.10.4

**Comment by Philzen** [comment]
> The problem persists with version 2.10.4

You need >= 2.9 to be able to use the *first workaround*. 

The issue itself is untackled, as is #7965

**Comment by rbk84** [comment]
@Philzen Thanks, the first suggested workaround worked. It's a shame that the button's behavior in the loading state and with the disabled="false" attribute is incorrect as a result (pressing the button remains available)

**Comment by psychedelicious** [comment]
@segunadebayo 

For example, consider a popover with some content including a button, and clicking the button disables the button. This closes the popover, because it sees the focused button being disabled as a blur.

Same thing happens for `<input />` elements - if a focused input is disabled, the popover is closed.

Maybe `closeOnBlur={false}` is OK for some use cases, but in mine, the popover should still close when the user clicks outside it. For the same reason, a focus trap also does not work for me.

For now, I'm faking disabling the button. Contrived example:
```tsx
<IconButton
  icon={<PiArrowCounterClockwiseBold />}
  aria-label={t('common.reset')}
  onClick={() => {setIsDisabled(true)}}
  opacity={isDisabled ? 0.5 : undefined}
  cursor={isDisabled ? 'not-allowed' : undefined}
  pointerEvents={isDisabled ? 'none' : undefined}
/>
```
